### ISSUE TITLE
Just dosn't work

### ISSUE THREAD

**Issue by Rainbow3D** [File-New-Project/EarTrumpet#1001]
The sound tray dosn't change. I tried uninstalling and re-installing the program multiple times but it just doesn't work (both from microsoft store and other places). I can uninstall it from widows search bar, but if I go in the control panel I don't see it show up with all the other apps (I don't think it's supposed to do so unless under a different name and icon). When I look in task manager it shows as working and is taking around 18.7mb of RAM, but no CPU percentage.

## Meta
* EarTrumpet version: 1.2.3.4
* Windows 10 version: 19042.746
![image](https://user-images.githubusercontent.com/97561516/149028601-2ff91703-da12-4714-aec4-31f1abb1c57b.png)

**Comment by riverar** [comment]
@Rainbow3D Sounds like you may not be clicking the right icon. Did you drag the EarTrumpet icon out of the overflow area? (GIF below)

![Welcome GIF](https://user-images.githubusercontent.com/475132/149028395-8b62440b-b0a6-4d0c-9d38-143812e05eb2.gif)

**Comment by Rainbow3D** [comment]
The Icon is the same one that it shows in the preview yes. But the tray that comes up is still the one from Windows, as if the app wasn't installed at all.

**Comment by riverar** [comment]
@Rainbow3D Can you share a video or screenshot of the area with the overflow area expanded? There should be two icons at first that look identical (confusing I know).

**Comment by Rainbow3D** [comment]
Yes, found it, and it obviuly works, I remembered that it changed how the original icon behavend, not adding another one. Now I feel dumb for making an account just over this. Thanks for your help and sorry fow wasting your time...

**Comment by riverar** [comment]
@Rainbow3D Not a waste and don't feel bad at all. Feel free to reach out if you need anything else my friend. 👍
