### ISSUE TITLE
Windows Shell Experience Host 

### ISSUE THREAD

**Issue by Jswee1** [File-New-Project/EarTrumpet#101]
Windows Shell Experience Host Shows up in my Ear Trumpet i read that is a background process of windows ive end it and restart windows but it still shows up there how can i hide it https://postimg.org/image/t98lv9vi5/

**Comment by Droyk** [comment]
That icon is really important for new notification sound's for example UWP warning sound, Action center notification sound typically any UWP notification depends on Windows Shell Experience Host if you really want to hide that icon you should disable notification sound from sound properties
![](https://cloud.githubusercontent.com/assets/475132/21827473/978bc3fa-d740-11e6-9da6-cb2efed84235.png)

**Comment by riverar** [comment]
Closing this issue as we don't have any plans to hide this session.
