### ISSUE TITLE
Provide an installer

### ISSUE THREAD

**Issue by thany** [File-New-Project/EarTrumpet#1013]
## Description

There is no installer to download. This is a perfectly fine, well-accepted, and vastly common way to install anything on Windows.

You might not like it, but users do. Please make a normal installer. Make it with Microsoft technology (MSI) if you must, but please make a regular ol' downloadable installer.

Winget and chocolatey are not good (to put it lightly). Not even for me as a developer, and certainly not for novice users. The Store doesn't even work everywhere (geographically speaking that is), isn't allowed by company policy, is blocked by a firewall, or is just plain broken. And no, any form of manual override to this is just as horrible as a CLI variety.

## Steps to reproduce

1. Open the homepage
2. Find the installer
3. Download it
4. Execute it
5. Profit

## Meta

EarTrumpet version: none
Windows 10 version: 21H2

Don't lock this thread again. Make an installer already. Locking a bug is counter-productive. Shutting people up is a bad idea.

**Comment by riverar** [comment]
@thany We hear you loud and clear. We have no plans to address this at this time but we'll certainly keep in mind.
