### ISSUE TITLE
Ear Trumpet and Spotify BUG With launching Games!!

### ISSUE THREAD

**Issue by xXShadowMcXx** [File-New-Project/EarTrumpet#1019]
### Summary

Spotify App/Apps in General and Game Launching specifically the New Mass Effect Legendary Edition on X-Box Game Pass

OS; Windows 11  
CPU; AMD RYZEN 5 2600 GPU; 
NVIDIA RTX Motherboard; 
ASUS Prme X$70 Pro
WIFI/Blu-tooth; AX200NGW WiFi 6 Card Bluetooth 5.1 AX3000M PCIe

### Steps to reproduce

I was Listening to Spotify over my Blue-tooth Speaker. I had set Spotify to Play that App through that Blue-tooth Speaker.  A Cortana Invoke Assistant Speaker to be Exact.   I Launched a Game and it Loaded into the game before i could Pause the Music.  So i Pressed Start and was able to Navigate back to Spotify and Pause the Music I then Clicked back into the Game and the Music started to Play from Spotify so i went and Paused the Music again and it did Pause.  But again the Music would Start up whenever the Spotify Window was  not the Window in focus.  Then stop when Spotify was the Window in Focus.  So i then Closed Spotify and checked it wasn't on the Task-bar or  in System-tray. because the Music was STILL PLAYING.  I Believe Ear-trumpet somehow caught up Spotify in the back-ground tasks some how.  pPlease Look into This please I do Enjoy the Product and Wish to See it Improve thank You for the Time.

### EarTrumpet version

2.1.9.0

### Windows version

10.0.22000.434

**Comment by riverar** [comment]
@xXShadowMcXx Thanks for the interesting report. I don't see how EarTrumpet caused this but I'd be interested if you can reproduce this. If you can, try closing EarTrumpet -- does the problem go away?

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.
