### ISSUE TITLE
Trouble installing from the windows store

### ISSUE THREAD

**Issue by Amauril** [File-New-Project/EarTrumpet#102]
The legacy version you have here installed and works just fine, to be sure, but I wanted to get your latest version and I am having trouble installing it.  When I click install, it asks me which drive I'd like to install it on- my operating system drive is not shown despite having more than enough space (I use E: rather than C:). It downloads a small amount, and gives me error 0x80073CF9.  I've done the most common troubleshooting steps for that error you can find, but the error remains the same.  Do you have any advice?

**Comment by riverar** [comment]
Settings > Storage > Change where new content is saved, is your main OS drive listed here?

**Comment by GoldenTao** [comment]
Please reopen this issue if you're still seeing the same problem.
