### ISSUE TITLE
EarTrumpet not working

### ISSUE THREAD

**Issue by AnjanaJK** [File-New-Project/EarTrumpet#1027]
### Summary

So I just installed the application and when I click on the Windows Volume icon, nothing seems to appear. As per the video demonstration, i am not getting the similar output. I have also restarted the pc. I have attached a screenshot below.

 

### Steps to reproduce

![issue1](https://user-images.githubusercontent.com/97173715/149886007-fedde063-ae1e-4fc2-bd37-62eca9b23e1a.png)
![issue2](https://user-images.githubusercontent.com/97173715/149886025-539bc8a7-2888-44c0-9752-96cc2a40fc7b.png)

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19043.1466

**Comment by tomo2403** [comment]
Start the app from start menu and look for the other speaker symbol in tray icons. You can disable the default icon in the settings app.

**Comment by riverar** [comment]
Sounds like you're not clicking the EarTrumpet icon. Make sure it's not hidden away in the overflow area.
![welcome](https://user-images.githubusercontent.com/475132/150079677-f238ad3c-2bb8-4aed-9c21-1981c7b25991.gif)

**Comment by riverar** [comment]
Closing for now, but feel free to continue the discussion and re-open if needed!

**Comment by AnjanaJK** [comment]
I got it! Thanks!
