### ISSUE TITLE
Remember settings

### ISSUE THREAD

**Issue by Jazzmega** [File-New-Project/EarTrumpet#1028]
Hi! EarTrumpet doesn't remember the app settings in my PC with Windows 11.

Standard mixer neither remembers settings.

For instance: 
If I set Chrome at 50% volume. When I close it and open it again, it is set at 100% again.

Any solution? thanks a lot for your work

**Comment by riverar** [comment]
Thanks @Jazzmega for the kind words. We're already tracking this request via https://github.com/File-New-Project/EarTrumpet/discussions/649 so closing this out. Windows unfortunately doesn't do a great job at remembering audio levels.
