### ISSUE TITLE
Scrolling EarTrumpets device with 'ThinkPad Compact Keyboard' kills its scroll function

### ISSUE THREAD

**Issue by M0RT1M4R** [File-New-Project/EarTrumpet#1029]
**what I'm doing**
- open EarTrumpets device list (left click the taskbar symbol)
- expand the device list
- trying to scroll up or down that list with ThinkPad Compact Keyboard
- happens with version 2.1.9.0 as well as dev version 2.1.9.18

**issue**
immediatly with the scrolling a "HScroll Application" window pops up, saying "HScroll Application has stopped working > A problem caused the program to stop working correctly. Please close the program"

HScroll application can be found here:
"C:\Program Files (x86)\Lenovo\ThinkPad Compact Keyboard with TrackPoint driver\HScrollFun.exe"

**workaround**
After executing "HScrollFun.exe" I get my scroll functionality back.
![image](https://user-images.githubusercontent.com/25716937/150037009-8348f543-5957-43d9-ae90-610c9d1adbf0.png)

**Comment by riverar** [comment]
@M0RT1M4R Hi there, interesting issue. Can you confirm this is the device you are using? https://www.lenovo.com/us/en/p/accessories-and-software/keyboards-and-mice/keyboards/0b47190

**Comment by riverar** [comment]
Looks like this is a known issue with Lenovo's app/driver https://forums.lenovo.com/t5/Displays-Options-and-Accessories/ThinkPad-Compact-Bluetooth-Keyboard-with-TrackPoint-Scrolling-stops-working-in-VS2017/m-p/3970470?page=1

But if you can confirm that's the hardware, I'll buy one and try it myself.

**Comment by riverar** [comment]
Purchased hardware, awaiting arrival.

**Comment by riverar** [comment]
Not seeing any issues here on Windows 11 w/ HScrollFun 1.2.0.4. Can you verify this is still a problem with the latest EarTrumpet? Can you provide the version of HScrollFun.exe? (I used the driver package here https://pcsupport.lenovo.com/us/en/accessories/pd026503-thinkpad-compact-keyboard-drivers)

**Comment by riverar** [comment]
Not enough information to continue here. Ping me if you return / have the requested info.
