### ISSUE TITLE
Trying to revert to a Restore Point with EarTrumpet installed results in 0x80070091 HR

### ISSUE THREAD

**Issue by wyfiwyg** [File-New-Project/EarTrumpet#103]
Hi , 

Recently I had to install earTrumpet via the widows store (I never do such thing), and for some reasons I had to use a windows restore point in the next days... . But it was not possible to do it without uninstalling the new earTrumpet before.

I had that message while trying to restore : 
Source : AppxStaging
Destination : %ProgramFiles%\WindowsApps
Undefined error during restoration : 0x80070091

After uninstalling earTrumpet, it was ok to use the restore points dated before the windows Store Installation.

So... my question : is it possible to get installations & updates of earTrumpet without the windows Store stuff ?

**Comment by wyfiwyg** [comment]
Ok. I did it 3 times, and cleaned up the old 1.3.2.0 version & registry infos before, to be sure, because it was still installed after the first 1.4.3.0 installation.

Everytime I install the available version from windows Store 1.4.3.0, then i can't use the windows restore points and get that 0x80070091 error.

I installed another program from windows store, and I had no problems.

Windows 10 - Version 1607 - 14393.693

**Comment by riverar** [comment]
Interesting, let me contact some folks and see if this is a known issue.

**Comment by riverar** [comment]
Microsoft has confirmed the problem, will update when I get more information.

**Comment by riverar** [comment]
This should be fixed, as of Windows 10 April 2018 Update. If you run into this again, please let us know!
