### ISSUE TITLE
Microphone icon in Eartrumpet?

### ISSUE THREAD

**Issue by stressatoo** [File-New-Project/EarTrumpet#1032]
### Summary

There's a microphone icon in Eartrumpet, if you hover the mouse on it's gonna show you the microphone name, I just don't get why it's here since sliding it won't change the volume. I believe what causes it is using once the "playback" option in the windows audio settings, to hear your own voice.

### Steps to reproduce

1. Open EarTrumpet
2. Look for a mic icon

### EarTrumpet version

2.1.9.18

### Windows version

10.0.22000.466

**Comment by stressatoo** [comment]
![image](https://user-images.githubusercontent.com/60473020/150609332-28afb8e0-f05a-4c92-b2ef-6857f99258dd.png)

**Comment by DigitalNXZ** [comment]
I have an older version~
I think it is related to threads like #99 #269 #302 etc

May a Feature (still in work)? would really be happy if its related to those ^^

**Comment by stressatoo** [comment]
Hi, thanks for the reply. That's also what I thought, at first, but lowering it doesn't change the mic volume.

**Comment by riverar** [comment]
This is normal behavior; this is a result of _listening_ to an input device (e.g. microphone, line in, etc.)

![image](https://user-images.githubusercontent.com/475132/188514666-b123d4c0-fabd-409b-80e5-479cbf31d57f.png)

Closing as there's no work to be done here at the moment. Thanks!
