### ISSUE TITLE
EarTrumpet re-enables itself at startup

### ISSUE THREAD

**Issue by Outpizza** [File-New-Project/EarTrumpet#1044]
### Summary

When I turn disable EarTrumpet in the Startup tab in my Task Manager, it re-enables itself the next time the computer is turned on.

### Steps to reproduce

1. Go to the Startup tab in Task Manager
2. Disable EarTrumpet
3. Restart computer

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19044.1466

**Comment by riverar** [comment]
We don't do anything special here, but this area has been pretty buggy in Windows across the past few releases.

You can manually open Registry Editor and navigate to `Computer\HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\EarTrumpet` and set `State` to `1`.

![image](https://user-images.githubusercontent.com/475132/158704879-37ab6956-5135-49e8-854d-b33781e582f5.png)
