### ISSUE TITLE
Project is unbuildable out-of-the-box

### ISSUE THREAD

**Issue by SamusAranX** [File-New-Project/EarTrumpet#105]
See for yourself:
![VS2015's Error List](https://cloud.githubusercontent.com/assets/676069/23178154/a3199bf8-f869-11e6-8471-a1f712a69f58.PNG)

When opening the solution for the first time, VS2015 prompted me to install the UWP SDK, which I did. (I also rebooted after that, just to be sure)
I have no idea why it's still complaining about missing references. 
And due to the name of the component, "Windows", it's effectively un-google-able.
Could you please amend the readme with more information on how to successfully build this?

**Comment by SamusAranX** [comment]
No matter what solution I use, I get the exact same errors.

**Comment by riverar** [comment]
Does `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd` exist?

**Comment by SamusAranX** [comment]
![Windows.winmd](https://cloud.githubusercontent.com/assets/676069/23179312/b4f6455c-f86d-11e6-870b-fb9c2f9334c5.PNG)
It does.

**Comment by riverar** [comment]
Which Windows 10 SDK did you install?

**Comment by SamusAranX** [comment]
Honestly, I have no idea. Visual Studio just went "You need the Universal Windows Platform SDK" and installed it.
It doesn't show up on the Apps & Features list, either.

**Comment by riverar** [comment]
Check Add/Remove programs (or Apps & features in recent builds of Windows 10) for a version number.

**Comment by SamusAranX** [comment]
Looking closer, there were two entries called "Windows Software Development Kit" with version numbers 10.0.14393.795 and 10.0.14393.33.
Is that what you meant?

**Comment by riverar** [comment]
Yup, I'll set up a clean machine and see what's going on. Thanks for the info.

**Comment by riverar** [comment]
Our codebase has changed drastically since this last report. Give it a shot again and let us know if you have any issues.
