### ISSUE TITLE
laggy when clicking on icon

### ISSUE THREAD

**Issue by github-user1112** [File-New-Project/EarTrumpet#1052]
### Summary

not a major issue or anything but when i click on the icon it goes up 90% of the way smoothly and then kind of jumps the rest of they way and its a slight nuisance. 
 

### Steps to reproduce

just click the icon in the tray

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19044.1466

**Comment by FroggyRaven** [comment]
i have this too

**Comment by riverar** [comment]
Thanks, we're currently tracking this via #391. It's a known issue with our combination of Microsoft technology (Acrylic backdrop, WPF host, etc.).
