### ISSUE TITLE
I can't open the volume window even if I press the speaker icon.

### ISSUE THREAD

**Issue by issaac07** [File-New-Project/EarTrumpet#1057]
### Summary

If you click the speaker icon to open the window and press the speaker icon to close the window, the window does not open even if you press the speaker icon after that.

https://user-images.githubusercontent.com/99344868/153229052-4a12d010-6100-4050-94a3-f33b75ae7c4b.mp4

### Steps to reproduce

1. Click on the speaker icon (volume window opens)
2. Click on the speaker icon (volume window closed)
3. Click on the speaker icon (volume window does not open)

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19043.1466

**Comment by Tencryn** [comment]
I noticed this too. It will re-open if you don't click it for a while but this behaviour makes the application feel unresponsive and sluggish.
