### ISSUE TITLE
Changing App audio

### ISSUE THREAD

**Issue by PierogiPL** [File-New-Project/EarTrumpet#1060]
I connected a hdmi cable from my laptop to a samsung tv and i want my browser to output audio and another app to output audio in my laptop speakers but after a long time i havent been able to figure out how to do it

**Comment by riverar** [comment]
@PierogiPL Have you tried right-clicking on the app in EarTrumpet? You can click the double arrows and use the options there to redirect audio where you need it.

![image](https://user-images.githubusercontent.com/475132/158703414-91e6a58f-d1c6-489c-9977-23f98a6aa3ef.png)

Going to close this as it's not an issue in EarTrumpet, but feel free to continue the discussion.
