### ISSUE TITLE
Can't save my settings after software restarted

### ISSUE THREAD

**Issue by Fus-RoDah** [File-New-Project/EarTrumpet#1061]
### Summary

Every time I restart softwares ,the software volume will all back to 100%.
For example:I turned down the Chrome volume to 30%,but after restart Chrome ,the Chrome volume will back to 100%.

### Steps to reproduce

1.Turn down one software volume
2.Restart the software
3.Get 100% volume

### EarTrumpet version

2.1.9.0

### Windows version

Win10 20H2 version:19042.1526

**Comment by riverar** [comment]
This is not currently a EarTrumpet feature/bug; Windows is _supposed_ to do this for you, but it's been broken across several releases with no real fix in sight. We have a few issues in this repository tracking this so I will close this one.

In the meantime, you could try using a developer build (see https://eartrumpet.app), which has EarTrumpet Actions, which will allow you to set up profiles to possibly achieve the same result. Give it a try!

Hope that helps!
