### ISSUE TITLE
error 0xC0EA000A no se puede reinstalar 

### ISSUE THREAD

**Issue by Galamooth** [File-New-Project/EarTrumpet#1062]
### Summary

use mi disco duro en otra pc, cuando volví aquí me salian problemas con el id de la aplicacion por lo que decidi borrarla y reinstalarla pero ya no me dejo. instalar nueva mente me aparece error 0xC0EA000A "hubo un problema de nuestra parte"..  ayuda!!!

### Steps to reproduce

![Captura de pantalla (3)](https://user-images.githubusercontent.com/90434643/153768758-b4dd105c-ff84-4882-add8-8cd8720f8fd2.png)

### EarTrumpet version

sin instalar 

### Windows version

Microsoft Windows [Versión 10.0.19043.1526]

### Additional information

ayuda

**Comment by riverar** [comment]
0xC0EA000A is `ERROR_CLIP_LICENSE_DEVICE_ID_MISMATCH`. I can't reproduce this or help with Microsoft Store issues here, so I will close this / report this to Microsoft. In the meantime, please try using one of the alternate ways to install EarTrumpet (https://github.com/File-New-Project/EarTrumpet#install). Thanks!

Translated:
0xC0EA000A es 'ERROR_CLIP_LICENSE_DEVICE_ID_MISMATCH'. No puedo reproducir esto ni ayudar con los problemas de Microsoft Store aquí, así que cerraré esto / informaré esto a Microsoft. Mientras tanto, intente usar una de las formas alternativas de instalar EarTrumpet (https://github.com/File-New-Project/EarTrumpet#install). ¡Gracias!
