### ISSUE TITLE
Chrome Profiles

### ISSUE THREAD

**Issue by commercial-sample123** [File-New-Project/EarTrumpet#1066]
### Summary

So i was just doing my online classes today on my university's chrome profile and doing some other stuff on my personal chrome profile. I wanted to reduce the volume of my class(which is on gmeet ) but continue to have the same volume on my personal work. So I open eartrumpet and just see 1 chrome icon in eartrumpet  due to which i am not able to control the profile volumes induvidually which is a major inconvinience for me. If I am missing some setting pls do let me know

### Steps to reproduce

well you just gotta open two chrome profiles and try to control them individually via eartrumpet and you guys will understand the point i am trying to make here

### EarTrumpet version

2.1.9.0

### Windows version

Microsoft Windows [Version 10.0.22000.493]

### Additional information

![image](https://user-images.githubusercontent.com/99725814/154041481-e2bbee87-60b0-419b-b27c-ba272d7a9a05.png)

**Comment by riverar** [comment]
Chrome takes the audio from all tabs and emits them all grouped together, sadly. Neither Windows or I can do anything here, without perhaps a Chrome add-in of sorts. A similar enhancement was brought up years ago here #239.

You might be able to utilize [Chrome Site Isolation](https://www.chromium.org/Home/chromium-security/site-isolation/#:~:text=above%20(e.g.%2C-,[--site-per-process](https://www.chromium.org/Home/chromium-security/site-isolation/#:~:text=above%20(e.g.%2C-,--site-per-process,-).%20They%20also%20work),-).%20They%20also%20work) to workaround this. If you try it out, let us know either way!

Will close this for now as there's no work to be done here, but feel free to continue the discussion.
