### ISSUE TITLE
Volume mixer becomes empty within tens of seconds after EarTrumpet is turned on

### ISSUE THREAD

**Issue by STONE-Git** [File-New-Project/EarTrumpet#1072]
### Summary

Volume mixer becomes empty randomly within tens of seconds each time after EarTrumpet is turned on. Only the Volume mixer of EarTrumpet becomes empty. The Volume mixer of the system seems fine. It happens immediately after changing the default device, but also happens without changing the default device.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/63118507/154965626-21989ecf-e867-4903-a5c5-e0dabb407958.png)
![bug](https://user-images.githubusercontent.com/63118507/154967087-b16e09fc-3acc-490e-b894-e5f227247387.gif)

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19044.1566

### Additional information

[tmp9CC0.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/8109665/tmp9CC0.tmp.txt)

**Comment by riverar** [comment]
@STONE-Git Thanks for the bug report. Can you explain how you are switching devices? Is this via an external switch? Unplugging something? Trying to reproduce this here and so far I can't. Thanks!

**Comment by Sebastian-Specjal** [comment]
I have the same issue with Windows 10 Pro 20H2 10.0.19042 Kompilacja 19042.
After restarting the application, I see active sound-broadcasting applications again

![Zrzut ekranu 2022-03-28 100055](https://user-images.githubusercontent.com/102511601/160353252-4fcd18b2-339f-41f6-8c51-dded81bd8de1.png)

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
