### ISSUE TITLE
Auto-hiding taskbar does not remain open

### ISSUE THREAD

**Issue by Tencryn** [File-New-Project/EarTrumpet#1074]
### Summary

The default volume control will keep the taskbar open while open, but EarTrumpet does not keep the taskbar open. I'd like the taskbar to remain open, but I'll accept a setting incase others do not like this behaviour.

### Steps to reproduce

Set your taskbar to auto-hide, and click on EarTrumpet. Taskbar will hide while EarTrumpet remains open.

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19044.1526]

**Comment by riverar** [comment]
There's no API that we're aware of to do this, sadly. It's an internal shell behavior.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. But be aware, I am talking directly to the Microsoft engineer responsible for this. So stay tuned!
