### ISSUE TITLE
eartrumpet stays on screen when you have a full screen app open

### ISSUE THREAD

**Issue by FroggyRaven** [File-New-Project/EarTrumpet#1075]
### Summary

it just stays on the full screen app until you go back to the taskbar and close it

### Steps to reproduce

have a full screen app open, press the windows key, click on the eartrumpet icon and click on the full screen app
![Screenshot_21](https://user-images.githubusercontent.com/85956701/155250873-690c7b87-0ebf-4f14-96a5-243938f7d68f.png)
![Screenshot_22](https://user-images.githubusercontent.com/85956701/155250879-e1f17bd3-1d74-458c-824b-ba63a6c3ee4a.png)
![Screenshot_23](https://user-images.githubusercontent.com/85956701/155250885-1fc2836a-03d1-40ee-b627-d448c630d7be.png)
![Screenshot_24](https://user-images.githubusercontent.com/85956701/155250891-a6816cd5-2530-45b3-b563-f2dae812829d.png)

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19042.1566

**Comment by FroggyRaven** [comment]
and also for some reason when i click it it pops up in very laggy motion

https://user-images.githubusercontent.com/85956701/155251537-730a0c24-e280-4b55-8b81-f4ef7e022c66.mp4

**Comment by riverar** [comment]
Got it. Fullscreen issue is dupe of #311. Laggy flyout is dupe of #391.

**Comment by FroggyRaven** [comment]
#311 <https://github.com/File-New-Project/EarTrumpet/issues/311> was posted
4 years ago and #391
<https://github.com/File-New-Project/EarTrumpet/issues/391> was posted 3
years ago, not to be rude but shouldn't that be fixed by now?
