### ISSUE TITLE
EarTrumpet do not show some applications when old application like Anno 1602 is started

### ISSUE THREAD

**Issue by badaszszsz** [File-New-Project/EarTrumpet#1079]
### Summary

After starting some "old" application I do not see the applications lists.

I will investigate the issue and suggest fix I have.

![image](https://user-images.githubusercontent.com/86535475/155808917-ee8c645f-e648-424c-8e5d-78f263b06856.png)

Windows 11.

### Steps to reproduce

Start Win 11
Start Anno 1602
Minimalize it and see no apps in ET.

### EarTrumpet version

2.1.9.5

### Windows version

10.0.22000.493

**Comment by riverar** [comment]
Hm, I tried the GOG version and it appears. Can you share more details on what version you're using?

![image](https://user-images.githubusercontent.com/475132/158699732-a75a4279-f6d0-471f-8909-8cd4f7c19cf3.png)

**Comment by badaszszsz** [comment]
Hello! Thanks for asking

Btw. I was not able to fix it nor find the reason. But I will try in the moment with English version...

**Q: Which version do you use?
Q: Is there any HD overlay/mod/plugin used by you?**

I think this is 1(.0).0.5 version...
![image](https://user-images.githubusercontent.com/86535475/158811267-f62cff4e-6630-412f-a390-ff8f7474b8ad.png)
![image](https://user-images.githubusercontent.com/86535475/158811186-f0894ffc-6e07-4ab3-a1d2-ceb579bdbaa4.png)

Beta channel: disabled
**lang: polish**
auto-update: enabled
![image](https://user-images.githubusercontent.com/86535475/158811004-0a12e66c-5657-40c6-8021-f8545b5f926a.png)


![image](https://user-images.githubusercontent.com/86535475/158810633-69886698-3df1-4d40-87b8-17dda7f58165.png)
![image](https://user-images.githubusercontent.com/86535475/158810688-fa3de54f-e498-4e76-b4cf-c1daa1cc34d7.png)

In Config dialog exec from here:
![image](https://user-images.githubusercontent.com/86535475/158810871-6d59feed-af1b-45f6-b91c-4f19f73d93f7.png)
I have setup like this:
![image](https://user-images.githubusercontent.com/86535475/158810799-09ff272d-0828-408f-8084-46455481b3b4.png)

**Comment by riverar** [comment]
Hm, still works for me using the Polish executable.

![image](https://user-images.githubusercontent.com/475132/158952658-f4e97de4-cce4-4720-9428-7ab66913cd01.png)

I noticed in your screenshot, you're showing the Digital Output device. Can you click the chevron to expand the flyout and show all devices? Is the game perhaps on another device?

Can you also restart EarTrumpet, start/stop the game, then collect diagnostics (Settings > General > About) and attach the file? Thanks!

**Comment by badaszszsz** [comment]
Hi, I am sorry but cannot reproduce any longer :( Thanks for the protips, support and maintenance of application.
