### ISSUE TITLE
Mouse wheel on icon in systray no longer changes the volume (Windows 11 Insiders)

### ISSUE THREAD

**Issue by lediur** [File-New-Project/EarTrumpet#1090]
### Summary

In the past, I was able to change the global system volume by scrolling the mouse wheel on the systray icon. This functionality seems to have broken in recent Insider builds of Windows 11. 

Unfortunately, I just noticed this today so I'm not sure if the feature was broken this build or in a previous build.

### Steps to reproduce

- Attempt to change volume by using the mouse wheel on the systray icon
- Note that it doesn't work anymore

### EarTrumpet version

2.1.9.0

### Windows version

10.0.22572.100

**Comment by riverar** [comment]
Yeah, Microsoft broke this. I filed a bug here https://aka.ms/AAgahkf so we'll see what happens. Am keeping a **very** close eye on this as you can imagine.

**Comment by lediur** [comment]
Oh word, thanks for the heads up!

**Comment by riverar** [comment]
Fixed in Windows 11 build 22593 https://blogs.windows.com/windows-insider/2022/04/06/announcing-windows-11-insider-preview-build-22593/!

**Comment by riverar** [comment]
I tested this on my machine and it's still broken. Investigating, sigh.

**Comment by riverar** [comment]
OK really fixed this time in 22598 https://blogs.windows.com/windows-insider/2022/04/13/announcing-windows-11-insider-preview-build-22598/
