### ISSUE TITLE
After Windows10 update EarTrumpet won't start D3D9.dll error

### ISSUE THREAD

**Issue by Venkinovec** [File-New-Project/EarTrumpet#1092]
After Windows updated itself overnight, aplication won't start, no error, just loading circle on cursor very briefly.
After that I can find these errors repeating in Event Viewer after trying to open the app.
.NET Runtime Error
`Aplikace: EarTrumpet.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: kód výjimky c0000005, adresa výjimky 667FD093
`
Application Error 
`Název chybující aplikace: EarTrumpet.exe, verze: 2.1.9.0, časové razítko: 0x615b7739
Název chybujícího modulu: d3d9.dll, verze: 10.0.19041.1566, časové razítko: 0x7dc0c380
Kód výjimky: 0xc0000005
Posun chyby: 0x0004d093
ID chybujícího procesu: 0x4148
Čas spuštění chybující aplikace: 0x01d8392fad645c1a
Cesta k chybující aplikaci: C:\ProgramData\chocolatey\lib\eartrumpet\tools\EarTrumpet\EarTrumpet.exe
Cesta k chybujícímu modulu: C:\WINDOWS\SYSTEM32\d3d9.dll
ID zprávy: e1f66826-7ee4-4e57-b699-e419ce98d691
Úplný název chybujícího balíčku: 
ID aplikace související s chybujícím balíčkem: `
Apologies for different language, don't know if it's possible to export the messages to english.

Aplication installed through chocolatey
### Windows version:
Windows 10 Pro
21H2
Build 19044.1586
Windows Feature Experience Pack 120.2212.4170.0

### EarTrumpet version: 
2.1.9.0

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/158713346-eb42d09e-b911-49c0-9b07-896932109fe1.png)

Hi @Venkinovec! Not seeing any issues here. Sounds like you maybe have an app that's hooking our app -- maybe some customization utilities? Or you may need to update your display drivers? (They tend to have applications that hook apps and do lots of strange things.)

**Comment by riverar** [comment]
Oops, just realized you're on **21H2**. Let me re-test.

**Comment by riverar** [comment]
(Note: 19043.1586 and 19044.1586 are the same. Just an OS quirk.)

**Comment by Venkinovec** [comment]
Are there some other logs I can find besides those I sent ?

**Comment by riverar** [comment]
@Venkinovec Do you use MSI Afterburner? (https://github.com/File-New-Project/EarTrumpet/issues/268) Or Rivatuner? (https://github.com/File-New-Project/EarTrumpet/issues/536)

If not, please do the following:

1. Open Regedit, navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`
2. Create a REG_DWORD value named `DumpType` and give it a value of 2
3. Reproduce the crash
4. Find the EarTrumpet.exe.dmp in %LOCALAPPDATA%\CrashDumps, zip it up and upload it to OneDrive/send a copy to team@eartrumpet.app. (Do not attach it here!)
5. Repeat step 1 above then delete `DumpType` to clean up

Thanks!

**Comment by Venkinovec** [comment]
Actually.. both. You're definitely good at troubleshooting. Did not think myself that these could pose a problem.

**Comment by riverar** [comment]
You don't need to remove them but I think just update them to the latest versions. 👍

**Comment by Venkinovec** [comment]
Yeah, I'll update them and do investigation on behaviour of those three apps. I'll keep you posted in this issue.

**Comment by Venkinovec** [comment]
@riverar  After making investigation I've come up with this conclusion.
For this behaviour is responsible update of windows which is same as #536 
Update RivaTuner fixed this issue, but if someone needs for a reason older version (like me) it's possible (and easy) to disable hooking on EarTrumpet. 

Just add new profile for application, locate eartrumpet.exe and set detection level to NONE.
That's it. Hope this helps someone. 👌 
![image](https://user-images.githubusercontent.com/25304952/158804292-579a1ad7-124c-41cf-9430-f60c76da14f1.png)
![image](https://user-images.githubusercontent.com/25304952/158804689-25f72d16-ff4b-46a4-ba70-9ea80cb2bfe1.png)
