### ISSUE TITLE
Your Phone doesn't support audio output redirection

### ISSUE THREAD

**Issue by ParanormalBanana** [File-New-Project/EarTrumpet#1096]
### Summary

I am trying to switch the output of Your Phone app, because it's using the default audio output instead of the default communications output. 

But eartrumpet can't change it, when I try to, it flickers in place and stays where it is, without getting reassigned.

### Steps to reproduce

start a call using Your Phone app
open eartrumper volume mixer
right click on your phone
click the double arrow
select correct output

### EarTrumpet version

2.1.9.18

### Windows version

10.0.22000.556

**Comment by riverar** [comment]
That's lame. Can you file this feedback (put a link to this issue in there) in Feedback Hub (WinKey + F)? Do so under the category **Apps > Your Phone**. After you're done, paste a link to your issue here and I'll also send it to the Your Phone team. Thanks!

**Comment by ParanormalBanana** [comment]
Hi, 

https://aka.ms/AAgd9kg

here you go !

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
