### ISSUE TITLE
[Visual Bug] Volume bar doubles as the volume is raised and lowered in mixer

### ISSUE THREAD

**Issue by migmarquez** [File-New-Project/EarTrumpet#1099]
### Summary

When we increase or decrease the volume in the mixer, the bar showing the volume percentage is duplicated on top of each other

### Steps to reproduce

Steep 1: Click on EarTrumpet icon located in taskbar
Steep 2: Turn up or down volume of any application

### EarTrumpet version

2.1.9.0

### Windows version

11

### Additional information

![image](https://user-images.githubusercontent.com/101899691/159256144-e4eb3021-d2cd-43a9-b42e-bcefafb03dbb.png)

**Comment by riverar** [comment]
Not sure I understand. Can you maybe circle what you mean?

**Comment by riverar** [comment]
That's our [peak meter](https://docs.microsoft.com/en-us/windows/win32/coreaudio/peak-meters) feature, it's showing audio output on left and right channels. The top most set of bars represents audio output from all apps.

Make sense?

**Comment by migmarquez** [comment]
> Esa es nuestra función de [medidor máximo](https://docs.microsoft.com/en-us/windows/win32/coreaudio/peak-meters), muestra la salida de audio en los canales izquierdo y derecho. El par de barras en la parte superior representa la salida de audio de todas las aplicaciones, mientras que el par inferior es específicamente para esa aplicación.`A`
> 
> ¿Entender?

o great is a feature then. it would be good to divide them a little more because this way it looks like a visual error.
maybe separating a little bit their distance or differentiating them with a little bit more faint color, by the way i have seen that they solved the audiolog error in the new version good work

**Comment by riverar** [comment]
We haven't made any changes for audiodg yet.

**Comment by mrchanshares** [comment]
So the left and right channels already designed and built-in?

**Comment by riverar** [comment]
Closing as there's no work to do here, looks like there was some confusion around our peak metering feature.
