### ISSUE TITLE
Seemingly random unable to use it. 

### ISSUE THREAD

**Issue by gizmo179** [File-New-Project/EarTrumpet#110]
I see no pattern in error encounter. Sometimes it just give the error below and I need to restart the pc to use Ear Trumpet again.
Sorry the error message is in Danish!

Se slutningen af denne meddelelse, hvis du vil have detaljer om,
hvordan du starter JIT-fejlfinding i stedet for denne dialogboks.

************** Undtagelsestekst **************
System.ArgumentException: -2147484008 er ikke en gyldig værdi for denne egenskab. Gyldige værdier er fra Int32.MinValue til og med Int32.MaxValue.
   ved System.Windows.Window.ValidateTopLeft(Double length)
   ved System.Windows.Window.CoerceLeft(DependencyObject d, Object value)
   ved System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
   ved System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   ved System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   ved System.Windows.Window.set_Left(Double value)
   ved EarTrumpet.MainWindow.UpdateWindowPosition()
   ved EarTrumpet.MainWindow.TrayIcon_Invoked()
   ved System.Action.Invoke()
   ved EarTrumpet.TrayIcon.TrayIcon_MouseClick(Object sender, MouseEventArgs e)
   ved System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
   ved System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   ved System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   ved System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Indlæste assemblies **************
mscorlib
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
EarTrumpet
    Assemblyversion: 1.4.4.0
    Win32-version: 1.4.4.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/40459File-New-Project.EarTrumpet_1.4.4.0_x86__1sdd7yawvg6ne/EarTrumpet.exe
----------------------------------------
PresentationFramework
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1638.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1638.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1638.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1638.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1638.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PresentationFramework.Aero2
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
System.Windows.Forms
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PresentationCore.resources
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_da_31bf3856ad364e35/PresentationCore.resources.dll
----------------------------------------
UIAutomationTypes
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
PresentationFramework.resources
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_da_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_da_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_da_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Accessibility
    Assemblyversion: 4.0.0.0
    Win32-version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT-fejlfinding **************
Hvis du vil aktivere JIT-fejlfinding, skal værdien jitDebugging indstilles
i afsnittet system.windows.forms i konfigurationsfilen
for programmet eller computeren.
Programmet skal desuden kompileres med fejlfinding
aktiveret.

Eksempel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Når JIT-fejlfinding er aktiveret, bliver alle ikke-afviklede
undtagelser sendt til den JIT-fejlfindingsfunktion, der er registreret på computeren, i stedet for
at blive afviklet af denne dialogboks.

**Comment by riverar** [comment]
Are you using any utilities that may be touching the Windows Taskbar? Or is it configured oddly, like perhaps moved to a different side of the screen?

**Comment by gizmo179** [comment]
I don't think so at least. I'm using f.lux and Reddit Enhancement Suit.

**Comment by GoldenTao** [comment]
If this one is still happen, please reopen this issue.
