### ISSUE TITLE
It is not possible to interact with EarTrumpet UI using an Xbox controller

### ISSUE THREAD

**Issue by gus33000** [File-New-Project/EarTrumpet#1102]
### Summary

When using an Xbox controller (or any Xinput device), it is not possible to navigate throughout EarTrumpet flyout, or EarTrumpet settings page, nor to change anything. This is however possible with the Windows native flyout and used to be working fine in old EarTrumpet versions.

### Steps to reproduce

- Connect an Xbox controller or any Xinput controller
- Open EarTrumpet flyout
- Try to navigate around the ui, notice it doesn't work
- Now press tab on your keyboard, notice it does work.

### EarTrumpet version

2.1.9.26

### Windows version

10.0.22579.1.ni_release.220315-1501

### Additional information

Previously reported on telegram to @riverar, filing this in the repo so it can be kept track of.

**Comment by BuggingYou** [comment]
If this ever gets implemented please make it optional, because it conflicts with "JoyToKey" type of software and unfortunately Microsoft many years ago promised a way to disable Xinput on uwp apps and never actually provided it.

**Comment by riverar** [comment]
@BuggingYou Thanks great to know, thanks!

**Comment by riverar** [comment]
Closing for now as there's no tangible interest in this feature. You're welcome to keep bugging me privately of course. That usually yields good results. 🙃
