### ISSUE TITLE
Windows Store Version, Gives this app licenses error

### ISSUE THREAD

**Issue by georgiouc** [File-New-Project/EarTrumpet#1110]
### Summary

I have been using this app for a few months, works wonders, even replaced windows volume control.
Recently it refuses to boot, showing this error message

![whateve](https://user-images.githubusercontent.com/103134222/162025609-09970a2f-531d-47c0-ad03-4369e4149e0d.jpg)

I tried reinstalling, issue still occur

### Steps to reproduce

Simple boot/startup causes this

### EarTrumpet version

2.1.10.0

### Windows version

21H2

### Additional information

OS Build: 19044.1586
Version: 21H2
Win 10 Pro

I have never raised an issue on github before, I don't know if this is the right place to do it. I haven't found any other way to contact the creators. I am simply reching out for help, as I want to keep using this amazing app! Thanks!

**Comment by georgiouc** [comment]
I can now confirm that this issue has resovled itself. I have not done anything

**Comment by riverar** [comment]
Closing for now as there's no work to do here; it's sadly a windows bug. If you keep hitting this, please do let us know.
