### ISSUE TITLE
volume settings for yandex.music is not saving

### ISSUE THREAD

**Issue by TheBeautyLlama** [File-New-Project/EarTrumpet#1115]
### Summary

before reboot
![изображение](https://user-images.githubusercontent.com/84794955/162576450-a4fa82b9-1946-46a5-80a0-e7c7440d19a2.png)
after
![изображение](https://user-images.githubusercontent.com/84794955/162576463-eb92d268-0352-4859-8c1f-d2ea685183ea.png)

### Steps to reproduce

launch yandex.music
reduce volume
close yandex.music
laucn yandex.music
volume settings will reset

### EarTrumpet version

2.1.10.0

### Windows version

10.0.22000.556

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. (Windows is in charge of remembering audio levels. That said, you can work around this using EarTrumpet Actions.) Feel free to keep the discussion going. Thanks!

**Comment by Serg-labo** [comment]
Нет EarTrumpet, так же не запоминает ничего.
