### ISSUE TITLE
Blurred icon bug after using a game in fullscreen with different resolution.

### ISSUE THREAD

**Issue by niiiksh** [File-New-Project/EarTrumpet#112]
There is a bug when you open a game with different resolution lower than native in fullscreen mode next time you look at the EarTrumpet icon it will be blurred like very bad quality icon. I'm using Surface Pro 4 (and it uses scaling 200% to show Windows UI in acceptable size) but this bug may be on any Windows PC, I guess.

**Comment by riverar** [comment]
It's a bug in Windows 10. Please upvote https://aka.ms/cxblbb

**Comment by GoldenTao** [comment]
This one should be fixed in the latest version of EarTrumpet (2.1.2.0). Please reopen if you're still having an issue.
