### ISSUE TITLE
VolumeMixer Draws out of screen

### ISSUE THREAD

**Issue by Aryetis** [File-New-Project/EarTrumpet#1121]
### Summary

Once deployed the volume mixer expands itself out of screen. Making it impossible to grab the top audio device entry and thus minimize it.

![image](https://user-images.githubusercontent.com/4246001/163624776-b5ecb2fa-03b4-45f9-9416-2ed98935e87c.png)

### Steps to reproduce

1/ Get a load of audio devices
2/ Set the taskbar to "hide automatically" 
3/ Expand the volume mixer 

Top option should now be out of reach.

### EarTrumpet version

2.1.10.0

### Windows version

10.0.22000.556

### Additional information

I'm also using startisback to replace the default/system audio icon in my taskbar with earTrumpet. I don't think it should interfere with it though.

**Comment by riverar** [comment]
Ouch, will get that fixed. Thanks for reporting.

**Comment by hichemfantar** [comment]
Was about to make an issue about this, definitely an annoying bug.

**Comment by riverar** [comment]
EarTrumpet 2.2.0.0 resolves this issue and is now available via the Store (and soon other sources).

**Comment by Aryetis** [comment]
Ok so this fix resolved the issue for the basic case.
But in some (edge) case the issue still occur.

Basically my setup is made of three screens : 
- The main one, in paysage mode (1080p, display scaling 100%)
- The second one, in portrait mode (1080p, display scaling 100%)
- The third one, in paysage mode (1080p, projector, display scaling 125%)

And I can switch between two configurations by the push of a button on a hdmi switcher : 
- main + second screen (in extend mode)
- main + third screen (in "only second monitor" <=> only the projector mode)

At first I thought it was due to the display scaling but nope : 

After switching my secondary monitor with Display Scaling at 125% from
![image](https://user-images.githubusercontent.com/4246001/169687943-5f64a4b0-bdc9-43d2-89d2-320ac0cca5c1.png)
(with Display Scaling 100%)
![image](https://user-images.githubusercontent.com/4246001/169688079-c9f9c86d-d5dd-4ac8-bb42-3f23266706e7.png)
