### ISSUE TITLE
Virus detection from Kaspersky

### ISSUE THREAD

**Issue by TheRealKiake** [File-New-Project/EarTrumpet#1123]
### Summary

When i press a certain combination of keys it makes false-flag detection on kaspersky. Kaspersky automatically provides a block for the application so you can't re-use it unless you reinstall the program.

The type of virus that kaspersky use to label on eartrumpet is "worm".

### Steps to reproduce

Use any version of Kaspersky and press in order:
Shift+ctrl+windows+alt+f4 on your desktop.

### EarTrumpet version

2.1.10.0

### Windows version

10.0.19044.1586

### Additional information

Image of Kaspersky detection
![image](https://user-images.githubusercontent.com/51777805/163654770-68e22e3f-24d3-401c-9ae7-c5a37280c223.png)

This is an image of me trying to reopen eartrumpet after the reproduction of the combination:
![image](https://user-images.githubusercontent.com/51777805/163654656-64c824d8-4bc3-4c88-a03a-64f1b7a69e40.png)

**Comment by riverar** [comment]
Thanks for the report. This is a false positive. I'll figure out how to get it whitelisted.

**Comment by riverar** [comment]
@TheRealKiake Can you try these steps? https://support.kaspersky.com/viruses/answers/1870

**Comment by riverar** [comment]
Closing for now, re-open if you need further help.
