### ISSUE TITLE
Missing options when the Spatial Sound option is changed.

### ISSUE THREAD

**Issue by EfeKamil** [File-New-Project/EarTrumpet#1127]
### Summary

The audio options disappear when you switch Spatial Sound settings. Just like Default --> DTS, DTS --> Default and such.

### Steps to reproduce

Just switch to Windows Sonic Audio in sound settings.

### EarTrumpet version

2.1.10.0

### Windows version

10.0.19044.1645

**Comment by riverar** [comment]
Closing as dupe of #587 #1049 etc.
