### ISSUE TITLE
after use remote desktop client (ipad) to control pc :thinner size

### ISSUE THREAD

**Issue by ylcz2014** [File-New-Project/EarTrumpet#1128]
### Summary

after use remote desktop client(ipad) to control pc :thinner size

### Steps to reproduce

before use remote desktop client(ipad) to control pc :normal size
![image](https://user-images.githubusercontent.com/13727499/164971858-06be2650-b3fc-4a6e-9444-3a406626a884.png)

after use remote desktop client(ipad) to control pc :thinner size
![image](https://user-images.githubusercontent.com/13727499/164971848-90e466d3-6516-4420-9dc4-6eed4b1e87f4.png)

### EarTrumpet version

2.1.9.0

### Windows version

10.0.19042.746

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1304, thanks!
