### ISSUE TITLE
Icon looks weird in windows 11 light theme

### ISSUE THREAD

**Issue by Bramgus12** [File-New-Project/EarTrumpet#1129]
### Summary

As much as you might hate light mode user, I am one of them. The Icon just looks out right weird and pixelated on the light mode task bar.

### Steps to reproduce

I do not really have steps to reproduce this. Just install the app and observe in light mode.

### EarTrumpet version

2.1.9.26

### Windows version

10.0.22598.100

### Additional information

![image](https://user-images.githubusercontent.com/42220620/165084774-e1e8730a-576a-486f-b3b0-5aaa2e113708.png)

**Comment by riverar** [comment]
@Bramgus12 This Insider Preview build is broken. Can you try the newest?

**Comment by Bramgus12** [comment]
I updated to windows 11 version 10.0.22610.1 and updated to the ear trumpet version in the dev channel. This didn't change a thing for me. It is still broken.

**Comment by Bramgus12** [comment]
I do not use remote desktop. The icon looks like this from when I start the machine.

**Comment by riverar** [comment]
@Bramgus12 Interesting, thanks. Can you right-click EarTrumpet, click EarTrumpet Settings > Collect troubleshooting data, then send that data to `team@eartrumpet.app` or if you're comfortable, put that in this issue?

**Comment by Bramgus12** [comment]
I sent the log file to that email address.

**Comment by Bramgus12** [comment]
Also, I've seen issues here also referencing an icon that looks weird. There it is mentioned that people use fractional scaling on their display. I just want to mention that I have a 1440p monitor and that I use 100% scaling in windows 11.

**Comment by riverar** [comment]
Thanks, this continues to be an Windows Insider Build issue, thanks for your patience! Will report this upstream.

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/167032004-ee901c2c-2039-4862-93e1-2585f7135efa.png)

Looks like Microsoft gave up on their new system tray for now and reverted all changes in 22616 (flighted today). EarTrumpet icon looks good now.

Can you verify?

**Comment by riverar** [comment]
Closing for now but feel free to continue the discussion.

**Comment by Bramgus12** [comment]
problem seems to be solved in the latest preview build of win 11.
