### ISSUE TITLE
Ear Trumpet

### ISSUE THREAD

**Issue by Muthaliza** [File-New-Project/EarTrumpet#113]
I cannot get ET to work. It appears to be installed...
 ![image](https://cloud.githubusercontent.com/assets/16308624/24587321/acbe54f4-17b4-11e7-9e82-c43ea710cd9c.png)
...but despite rebooting I get the useless Win 10 slider just the same...
![image](https://cloud.githubusercontent.com/assets/16308624/24587338/185fecc2-17b5-11e7-8e54-a99540728dbb.png)
What good is that? One slider for all apps? Stoopid is what it is and no improvement over the Window 7 volume control which is why there is a need for Ear Trumpet in the first place.
Windows 10 is still in beta although released 1+ yrs ago as RTM, hence all the third-party apps to remedy this or that shortcoming.

**Comment by GoldenTao** [comment]
Ear Trumpet does not replace the Windows volume control. If you left-click the Ear Trumpet icon you should get our volume window.

Also it looks like you've installed the old version from Github releases, you can get the latest version and any future updates from the Windows Store. [https://www.microsoft.com/store/apps/9nblggh516xp](https://www.microsoft.com/store/apps/9nblggh516xp)

**Comment by Muthaliza** [comment]
Thank you Golden. But I did download it via the Windows Store just to make sure I got the current version and did everything 'by the book'. 

When I left-click the Ear Trumpet icon, I get this 
![image](https://cloud.githubusercontent.com/assets/16308624/24587889/a6d1dd40-17be-11e7-9f37-af8192f9aeb8.png)
"irregardless" of what I 'should' get. And when I click the speaker icon, the same ol'-same ol'
![image](https://cloud.githubusercontent.com/assets/16308624/24587906/09030dc2-17bf-11e7-957a-ec9702b369cb.png)
I'd be very grateful to instead get this, as it looks good and is functional

![image](https://cloud.githubusercontent.com/assets/16308624/24587941/81567520-17bf-11e7-8090-8035656ce13e.png)

so if you can help me achieve that, I'd be grateful.

**Comment by GoldenTao** [comment]
Not sure if your mouse is setup for left-click as primary action, but if it is, you should see the bottom screenshot when left-clicking the EarTrumpet icon. Using right-click or secondary action will show the menu you are seeing.

It looks like the version from the store isn't running if you're still seeing version 1.3.2.0.  The current version is 1.4.4.0.  Make sure you exit the old version, uninstall it and run the new version once you have installed it from the store.

**Comment by Muthaliza** [comment]
_'Not sure if your mouse is setup for left-click as primary action...'_ well, neither am I. I just recently 'upgraded' to 10. Perhaps this primary/secondary thingy is something unique to Windows 10? It sure didn't used to be an issue in 7.
How, then, do I setup the mouse for left-click as primary action?

**Comment by Muthaliza** [comment]
Yes I get it. I left-clicked on the icon and got EarTrumpet, but it was of course not there next time I clicked the volume icon.
Is there then no replacement for the sorry one-slider Win 10 volume control?

**Comment by GoldenTao** [comment]
You will only see EarTrumpet when you click the EarTrumpet icon. I think the issue you're seeing is that the EarTrumpet icon is in the hidden tray area, you an drag it into the main tray area.

**Comment by Muthaliza** [comment]
GoldenTao: I did that just now and of course it works. Meanwhile, waiting for your reply, I went the registry tweak route, adding subkey HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\MTCUVC and setting it to 0.

So, now I have the best of both worlds...thx for bearing with me!

**Comment by riverar** [comment]
I think you're confused. EarTrumpet only works when left-clicking the EarTrumpet icon. Marking bug as invalid.

**Comment by Muthaliza** [comment]
Excuse me? I never 'marked bug' as you put it. Besides, David Golden has
explained things to me in a calm, patient way.

Where do you come in all of a sudden?

Go away! And never darken my inbox again.


​

**Comment by riverar** [comment]
Again, you're confused. Maybe there's a language barrier here.
Closing bug.
