### ISSUE TITLE
Applications disappear from flyout after switching users

### ISSUE THREAD

**Issue by aragubas** [File-New-Project/EarTrumpet#1131]
### Summary

Applications disappear from ear trumpet when logging out and logging back

I have two users on my pc, one has ear trumped and the other doesn't
If i log out from the user that has ear trumpet, and log in into the user that doesn't have it installed and log in again, all apps will be missing in ear trumpet window (even the system sounds slider)

### Steps to reproduce

Open ear trumpet, open some apps that reproduce audio (like spotify or chrome)
Log out and log in into another user that doesn't have ear trumpet installed
Log in back into the user that has ear trumpet installed, and all apps that plays audio will not appear in ear trumpet (even system sounds)

### EarTrumpet version

2.1.10.0

### Windows version

10.0.19044.1645

### Additional information

![image](https://user-images.githubusercontent.com/47148297/165397276-d929b6a3-d7a8-4583-8c50-7aad45125725.png)

**Comment by riverar** [comment]
@aragubas I tried to repro this but can't. Can you provide a step by step on what you do/click on/etc.? Would appreciate it greatly.

**Comment by aragubas** [comment]
> @aragubas I tried to repro this but can't. Can you provide a step by step on what you do/click on/etc.? Would appreciate it greatly.

You will need two users: User A who doesn't have EarTrumpet installed and User B who have EarTrumpet installed.
First, you log in into User B, open some applications that reproduce audio and the applications will appear on ear trumpet as normal. Now you log off User B and login in into User A, and now you log off User A and go back to User B and all applications on EarTrumpet window will be gone.

Btw, I forgot to mention but I use VoiceMeeter as well

**Comment by aragubas** [comment]
Sorry its not exactly logging off but switching users

**Comment by riverar** [comment]
@aragubas Thanks! I can reproduce this.

**Comment by ChronoInferna** [comment]
I am also having this issue; a quick restart fixes it I think but it is pretty annoying to have to restart it every time.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
