### ISSUE TITLE
The animations opened by this software in Win10 have dropped frames.

### ISSUE THREAD

**Issue by 13695024379** [File-New-Project/EarTrumpet#1139]
### Summary

Hello, I am a Chinese user. This software is excellent and provides a lot of convenience. However, in Windows 10 21H2, the animation displayed by clicking on the software on the taskbar has dropped frames. Please fix it, thank you!

### Steps to reproduce

None

### EarTrumpet version

2.1.10.0

### Windows version

Windows 10 21H2

**Comment by riverar** [comment]
Hi @13695024379, we're aware of this (see https://github.com/File-New-Project/EarTrumpet/issues/391). It's a tough issue related to our use of acrylic, WPF, etc. Closing as duplicate.
