### ISSUE TITLE
A remote procedure call (RPC) protocol error occurred.

### ISSUE THREAD

**Issue by Forecaster** [File-New-Project/EarTrumpet#114]
This error happens occasionally during startup. I wouldn't mind much if it didn't suspend the startup of everything until the popup window is closed.

http://imgur.com/a/zNegN

If this is something that is logged anywhere I can provide the logs if you tell me where they are.

**Comment by riverar** [comment]
Yikes. Sounds like a Microsoft Desktop Bridge (Centennial) bug, I'll ask them if there's anything we can find/provide them.

**Comment by riverar** [comment]
What locale is this system running? en-us? zh-*? Interested in the weird characters at the top of the window.

**Comment by riverar** [comment]
Can you also provide OS version information? (winver)

**Comment by Forecaster** [comment]
System: http://i.imgur.com/8YCExeQ.png

System language is `English (United States)`

**Comment by Forecaster** [comment]
If by "weird characters" you mean the icons in the top right covering part of the window title they're buttons from DisplayFusion, they're not characters

**Comment by riverar** [comment]
Thanks! I also sent a copy of this information to Microsoft. I suspect DisplayFusion has a hook that's not behaving here, but will investigate.

**Comment by Forecaster** [comment]
I'm not sure what you mean, the buttons are put on every window, they're for manipulating windows, moving them between monitors and pinning them and such. They're supposed to be there.

**Comment by riverar** [comment]
Right, I'm just saying DisplayFusion may be interfering with Windows. Or it may not, will investigate. Thanks!

**Comment by Forecaster** [comment]
Ah I see, yes it might be. Thanks!

**Comment by riverar** [comment]
ℹ️ Microsoft has confirmed this is a bug in Windows, awaiting fix.

**Comment by riverar** [comment]
Closing this bug as the fix made its way into Windows a long time ago (oops!).
