### ISSUE TITLE
Add an Option to open a window

### ISSUE THREAD

**Issue by Wachert** [File-New-Project/EarTrumpet#115]
Please build in an Option to open the volume Manager as an own window like the original Windows one.

This way you can, if you have multiple Screen and on the main Screen a full Resolution window mode game started, still Change the volume of different apps without opening the taskbar on the main Screen.

I mean the tool in the green boxes on the left part of the following Screen.

![snip_20170411185500](https://cloud.githubusercontent.com/assets/16701558/24920828/f7551d46-1ee8-11e7-82b8-5f7a8e6903ec.png)

**Comment by riverar** [comment]
This poses interesting challenges, like refreshing the window (live? polling?) without impacting the experience (pause when focused, perhaps?).

**Comment by Wachert** [comment]
What do you mean exactly? it just needs to be an own window, moveable that i can fast take my mouse in it, change a volume of one app and go back to my other fullscreen window in the centered screen.

it dont need to update "live" or background polling.

it would be enough when the mixer "view" updates when the window of the mixer get focused.
Normally nothing changes till i use the mixer.

ok, its possible the volume of an app changes when i use another mixer, like the windows own one, or an app gets closed... but the mixer window of trump dont needs to get updated in the background with a polling or something like this.

It should be enough when it gets updated when the window is focused.

**Comment by riverar** [comment]
Bam! Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
