### ISSUE TITLE
Audio Routing Issue

### ISSUE THREAD

**Issue by WalkingWithNero** [File-New-Project/EarTrumpet#1150]
### Summary

Dark Souls: Remastered launched from Steam got once recognized and after restarting the Machine it didn't work anymore.

### Steps to reproduce

As described in the summary 

### EarTrumpet version

2.1.10.0

### Windows version

10.0.19044.1682

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/168171714-1e67450d-13a3-46d7-9925-a6753b5f82e9.png)

**Comment by riverar** [comment]
@WalkingWithNero Can you right-click EarTrumpet, click EarTrumpet Settings > Collect troubleshooting data, then send that data to `team@eartrumpet.app` (or provide it here). Thanks!

Also, can you check if the game shows up in Windows Settings > System > Sound > Volume mixer?

**Comment by riverar** [comment]
Closing for now, but please do re-open if you continue to have this issue.
