### ISSUE TITLE
Multiple EarTrumpet.exe appear in the taskbar settings - Win 11

### ISSUE THREAD

**Issue by michaelwrenn** [File-New-Project/EarTrumpet#1166]
### Summary

Running Windows 11 Pro, Version	10.0.22000 Build 22000
In Settings -> Personalization -> Taskbar -> Taskbar Corner Overflow

There are multiple "EarTrumpet.exe" items listed.
![Screenshot 2022-05-24 090720](https://user-images.githubusercontent.com/4238761/170055560-2d6ed0a0-da7c-478d-861f-6df58e43a196.png)

### Steps to reproduce

It is unknown what is causing multiple instances to be shown

### EarTrumpet version

2.2.0.2

### Windows version

10.0.22000 Build 22000

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. (Windows has rebuilt the system tray and this settings area in subsequent versions of Windows 11.) Feel free to keep the discussion going. Thanks!
