### ISSUE TITLE
EarTrumpet crashes PC

### ISSUE THREAD

**Issue by aronooo** [File-New-Project/EarTrumpet#1184]
### Summary

I've been having a problem for 2-3 months but it has become increasingly annoying and I've not found a fix anywhere so I'm hoping someone can help me here. Sometimes (I really don't know what's causing it, it really seems to be at random), when I click on the eartrumpet icon in the taskbar my whole PC freezes and I cant see my cursor move or anything of the sort. Ctrl + alt + delete doesnt work, it becomes completely unresponsive. Only thing I've noticed is that if this happens while I'm talking to someone on discord, they can still hear me, but thats the full extent of what I can do. Only a restart fixes it and then it inevitably happens again. 

a small thing that might help is that most of the time I notice this issue is when I alt-tab out of sometinhg (most of the time Valorant) and then I click the icon is when this crash occurs. this might not help at all but its the only common thing about most (not all I think) of the incidents.

### Steps to reproduce

I'm afraid i cant help here. if a crash report would be helpful somehow I'd be happy to send one but I'm not sure where that's located, so please respond if you're able to help with that.

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19043.1766

**Comment by riverar** [comment]
Hi @aronooo, sorry to hear about your machine freezing. EarTrumpet isn't directly responsible for that, but perhaps there's an audio driver/hardware issue here? Best advice I can give is to double-check you're using the latest drivers. Also consider restoring clock speeds if you're overclocked at all. You may also want to consider upgrading Windows to the latest release.

Closing this for now as there's nothing actionable here. But feel free to continue the discussion.
