### ISSUE TITLE
Bug? Cannot control Discord sounds and screen sharing separately to discord voice calls whilst old windows mixer can.

### ISSUE THREAD

**Issue by Cypherthegreat** [File-New-Project/EarTrumpet#1187]
### Summary

Amazing App however I would like to request a feature/bug fix
I use discord a lot, personally I love that on the classic windows mixer you can control the sound of the users in call separately to the sound of the discord app, i.e. if someone is screen sharing or joins a call you can lower that sound, whilst keeping the volume of the presenter high. In Eartrumpet there is only one volume control for discord for some reason. Would be amazing if there was an update to address this as it may happen with other apps also.

I have tested with Base discord and Discord Canary as well as shown by the images below 
![image](https://user-images.githubusercontent.com/29981993/176676332-16b70578-d195-4024-9354-d843d525c8df.png)
![image](https://user-images.githubusercontent.com/29981993/176676528-af16df75-6513-4d6c-aa77-395c8686d225.png)

### Steps to reproduce

Install discord 
have at least 2 people in the call
open classic volume mixer
when a user joins the call or rings the 2nd discord out put should make the sound effect sounds, whilst the first carries the call audio channel
eartrumpet will only show a single audio channel

### EarTrumpet version

2.2.0.0

### Windows version

19044.1766

**Comment by ryantheleach** [comment]
@Cypherthegreat right click the discord icon, and it will fold out showing both instances.

![image](https://user-images.githubusercontent.com/141554/181284428-5461a015-e025-45b2-ab0b-69360df7f6cf.png)

**Comment by riverar** [comment]
Badging on our icons sounds like a good idea!
