### ISSUE TITLE
It would be amazing if this app could allow me to select 2 or more output channels.

### ISSUE THREAD

**Issue by skyaddict** [File-New-Project/EarTrumpet#119]
Scenario is I want to be able to share bluetooth audio on my slate with my wife and son while on a flight.

**Comment by davuxcom** [comment]
This is likely out of scope for EarTrumpet, if this became available in the platform we may change but until now I personally recommend you try VoiceMeeter.  

You configure your programs to output into VoiceMeeter, then under A1 and A2 you can select two existing output devices and you will get no-latency dual streaming.
