### ISSUE TITLE
EarTrumpet 2.2.0.0

### ISSUE THREAD

**Issue by asasd5152** [File-New-Project/EarTrumpet#1191]
### Summary

![177561643-1f6b0345-575a-41fb-b37b-3f5dfc83f0af](https://user-images.githubusercontent.com/38377367/177993840-d6e155df-3201-4b42-b4f2-97541b34b615.png)

### Steps to reproduce

open 

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19044.1766

### Additional information

[tmpCD52.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/9072132/tmpCD52.tmp.txt)

**Comment by riverar** [comment]
Closing as there's not enough information to indicate an EarTrumpet issue here. Looks like there's a severe issue with Windows.Storage.ApplicationData.dll on this system.

```
System.TypeInitializationException:
'EarTrumpet.DataModel.Storage.Internal.WindowsStorageSettingsBag'
的類型初始設定式發生例外狀況。 ---> 
System.BadImageFormatException:  不是有效的 Win32 應用程式。 
(Exception from HRESULT: 0x800700C1)
```
