### ISSUE TITLE
Crashing entire PC when playing Valorant

### ISSUE THREAD

**Issue by binkr-pix** [File-New-Project/EarTrumpet#1192]
I'm not sure why this happens but whenever I try to open Eartrumpet when playing Valorant my entire PC crashes, not just crashes regularly, I have to hard reboot the entire system

**Comment by adan-ea** [comment]
Valorant is known to have some trouble with a lot of computers, what makes you think that EarTrumpet is the reason here ?

**Comment by riverar** [comment]
Sorry to hear about your machine crashing. EarTrumpet isn't directly responsible for that, but perhaps there's an audio driver/hardware issue here? Best advice I can give is to double-check you're using the latest drivers. Also consider restoring clock speeds if you're overclocked at all. If you have a crash dump (`\Windows\memory.dmp`), feel free to zip it up and send us a copy/link (team@eartrumpet.app). Do not attach dumps to GitHub as they may contain private information.

Closing this for now as there's nothing actionable here thus far. But feel free to continue the discussion.

**Comment by rowancy** [comment]
having the exact same problem, never hapenned before, formatted windows and downloaded latest version from win store and started to happen, im gonna remove the overclock on my gpu to see if that helps!

**Comment by Gwydion5** [comment]
same problem here /:

**Comment by riverar** [comment]
@Gwydion5 Sorry for the trouble. Was it also Valorant? They must be doing something really wrong over there :(
