### ISSUE TITLE
"ERROR 0x80070422"

### ISSUE THREAD

**Issue by RAPTORSK** [File-New-Project/EarTrumpet#1193]
### Summary

Desde hace 2 días tengo el problema que el EarTrumpet no me funciona me comuniqué con MICROSOFT y me dijeron que el error no es de mi equipo, la aplicacion al parecer cuenta con un fallo al abrirse o instalarse ya que me sale este error: Mensaje de error en la instalación de la aplicación: Appinstaller operation failed with error code 0x80070422. Detail: No se puede iniciar el servicio, porque está deshabilitado o porque no tiene dispositivos habilitados asociados a él. (0x80070422).

### Steps to reproduce

Restablecí mi maquina y despés de instalar me funcionó noemal, no sé en que momento empezo a dejar de funcionar busque todas las maneras y es soporte de MICROSOFT me dijo que el erro lo contenía la misma aplicación.

### EarTrumpet version

2.2.0.3

### Windows version

10.0.19044.1806

### Additional information

![Captura 1](https://user-images.githubusercontent.com/109047980/178168207-545e07c2-eba3-400d-8433-491ddfc47c02.PNG)

**Comment by riverar** [comment]
0x80070422 maps to `ERROR_SERVICE_DISABLED`. Sounds like the Windows Update service might be disabled?

Closing this issue as there's nothing actionable here, but feel free to keep the discussion going.
