### ISSUE TITLE
Ear Trumpet Issue

### ISSUE THREAD

**Issue by Chowtown** [File-New-Project/EarTrumpet#1197]
With the ear trumpet app, whenever I click on the speaker icon, it still looks the same as default and there aren't multiple sliders I can mess around with.

**Comment by riverar** [comment]
Sounds like you're not clicking the right audio icon.

![Welcome animation](https://user-images.githubusercontent.com/475132/181989913-d8574d7b-1c35-47e0-9b5b-ebacd32c0a2d.gif)
