### ISSUE TITLE
It might be worth mentioning what versions of Windows this supports (e.g. not Windows 7) :-(

### ISSUE THREAD

**Issue by scunliffe** [File-New-Project/EarTrumpet#12]
I saw this on Twitter and it looked really cool, but I didn't realize the windows version constraints.

**Comment by riverar** [comment]
Related to #7

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/41

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/4

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/190
