### ISSUE TITLE
Volume flyout is offscreen when using many audio devices

### ISSUE THREAD

**Issue by RaulFury** [File-New-Project/EarTrumpet#1206]
### Summary

Greetings, 
When many audio devices are present on the system, it seems the Volume flyout will disappear off screen towards the top and this hides the top portion of the volume screen.

### Steps to reproduce

This is a constant issue, the only way to resolve this at the moment is to disable audio devices.

### EarTrumpet version

2.2.0.0

### Windows version

10.0.22000.856

### Additional information

![image](https://user-images.githubusercontent.com/68669170/185187345-c14dccc5-e465-43f2-bdba-c945c47b6f46.png)

**Comment by riverar** [comment]
@RaulFury Can you collect troubleshooting data via Settings and provide the top 20 or so lines? Just interested in the DPI, OS build, etc.

**Comment by riverar** [comment]
@RaulFury Also, is this with taskbar auto-hide enabled?

**Comment by RaulFury** [comment]
Hi Riverar, 
Thanks for the reply and a great app!
I just tested and you are correct, this seems to occur only with the auto-hide taskbar enabled.
Here is the top 20 lines of the log:
version: 2.2.0.0
runtimeMinutes: 460
gdiObjects: 94
userObjects: 42
globalGdiObjects: 5397
globalUserObjects: 5397
handleCount: 769
releaseStage: production
osVersionBuild: 22000.1.amd64fre.co_release.210604-1628
osArchitecture: 64 bit
processorCount: 12 core(s)
IsLightTheme: False
IsSystemLightTheme: False
IsRTL: False
IsTransparencyEnabled: True
UseAccentColor: False
AnimationsEnabled: True
IsHighContrast: False
HasIdentity: True
IsShuttingDown: False

**Comment by riverar** [comment]
@RaulFury Thanks, fixed in [3d819a9](https://github.com/File-New-Project/EarTrumpet/commit/3d819a968a4c2eff8bc5acfbb971db89be68c302).

Do you mind trying a dev build to verify it's fixed? https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

**Comment by RaulFury** [comment]
I can confirm the Dev build fixes the issue!
Let me know if you need something else, thanks!

**Comment by di00ib** [comment]
> @RaulFury Thanks, fixed in [3d819a9](https://github.com/File-New-Project/EarTrumpet/commit/3d819a968a4c2eff8bc5acfbb971db89be68c302).
> 
> Do you mind trying a dev build to verify it's fixed? https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

used the dev build and was JUST BARELY able to see and click on the drop down arrow
also tried to replicate the problem to see if I could use the fix to go back to normal
it worked as it should
thank you very much riverar
