### ISSUE TITLE
Trackbar change does not play a beep sound on Windows Server 2022

### ISSUE THREAD

**Issue by xmha97** [File-New-Project/EarTrumpet#1210]
### Summary

Trackbar change does not play a beep sound on Windows Server 2022

### Steps to reproduce

1. Open the main pane from the system tray
2. Slide the "System Sounds" trackbar

### EarTrumpet version

2.2.0.3 (from Chocolatey)

### Windows version

10.0.20348.887 (Windows Server 2022)

### Additional information

You can use this code:
```
new System.Media.SoundPlayer(@"C:\Windows\Media\Windows Foreground.wav").Play();
```

**Comment by riverar** [comment]
How strange, I can reproduce this. Appears to be an OS bug?

**Comment by riverar** [comment]
`System.SystemSounds.Beep.Play()` is not functioning on 20348.261 for me. Investigating.

**Comment by riverar** [comment]
Closing this OS issue in favor of the linked dotnet issue.
