### ISSUE TITLE
add autostart option for the volume mixer window

### ISSUE THREAD

**Issue by D4n2021** [File-New-Project/EarTrumpet#1213]
So that we don't have to right-click -> EarTrumpet volume mixer leftclick every single time we log into windows. thank you

**Comment by riverar** [comment]
Hey @D4n2021, sounds like a good idea. We're currently tracking feature requests over at https://github.com/File-New-Project/EarTrumpet/discussions. I'll close this one. Thanks!

**Comment by riverar** [comment]
Work is already done and in `dev`.

![image](https://github.com/user-attachments/assets/7b93b203-071c-4799-b145-ac08aaf18477)
