### ISSUE TITLE
Show Mute Icon When Sound is Completely Off

### ISSUE THREAD

**Issue by DanJ210** [File-New-Project/EarTrumpet#122]
Hello. I searched for this and didn't find anything. I gave this app 5 stars btw because it is of that quality.

This is more of a feature request but I would like to use this app icon to replace the native audio icon baked into windows. The one thing I like is when I have my sound completely off there is an X on the native audio icon. I don't see the icon for this app changing when sound is completely down or off. 

Would this be something I could request?

Thanks for the hard work and the great app.

**Comment by riverar** [comment]
Hey Dan, thanks. We actually got this done, it's just sitting in our dev branch at the moment I believe. Should show up sometime soon.

**Comment by riverar** [comment]
Done; 1.5 update in the store.
