### ISSUE TITLE
Windows subsystem for android icon doesn't show up

### ISSUE THREAD

**Issue by rp1231** [File-New-Project/EarTrumpet#1223]
### Summary

![EarTrumpet_XHOLjtZjqA](https://user-images.githubusercontent.com/47380919/189326811-f6f906b4-b184-40de-874f-5ffcac6eb39f.png)

Windows subsystem for android icon doesn't show up

### Steps to reproduce

Run Windows subsystem for android 

### EarTrumpet version

v2.2.0.0

### Windows version

10.0.22000.918

**Comment by riverar** [comment]
Thanks @rp1231, does it show up in the native mixer? (e.g. sndvol.exe)

**Comment by riverar** [comment]
Great thanks, will get this fixed.

**Comment by riverar** [comment]
@rp1231 Can you confirm this is working as intended in a dev build? (https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller) Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/475132/192048902-aa048790-8668-4b08-90ac-a2c9137fd69e.png)

**Comment by riverar** [comment]
I'm guessing this will go away after a reboot. We have several reports of the OS ShellItemImageFactory implementation being quirky... :(

**Comment by riverar** [comment]
@rp1231 Hm, shouldn't matter but can you send me the steps you used so I can reproduce it here?
