### ISSUE TITLE
Random order of output devices in volume mixer window

### ISSUE THREAD

**Issue by MikeyMike22** [File-New-Project/EarTrumpet#1226]
### Summary

audio out output devices appear next to each other in random order instead of sorted by alphabet.

### Steps to reproduce

Have 3 audio output devices and name them after this scheme ("ABC" example name):
1 - ABC
2 - DEF
3 - GHI

Sometimes, the order is 3 -1 - 2 instead of 1 - 2 - 3, as can be seen in screenshot below.

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19044.1949

### Additional information

![grafik](https://user-images.githubusercontent.com/40214892/190650661-c586f7b7-a07a-467c-85e7-d40c38393cdf.png)

**Comment by riverar** [comment]
Done, this is in dev branch. Should be in retail channels soon!
