### ISSUE TITLE
UI bug in light mode

### ISSUE THREAD

**Issue by xmha97** [File-New-Project/EarTrumpet#1228]
### Summary

https://user-images.githubusercontent.com/23485114/191291190-2ec42038-1250-40a3-b563-546d37fca5cc.mp4

### Steps to reproduce

1. Hover mouse on title label

### EarTrumpet version

2.2.0.3 (from Chocolatey)

### Windows version

10.0.20348.1006 (Windows Server 2022)

**Comment by riverar** [comment]
What are you expecting to see here?

**Comment by xmha97** [comment]
The color of the text should not be light:
![image](https://user-images.githubusercontent.com/23485114/192765248-886161df-a95e-4f0b-8dcf-4f2885d18feb.png)

**Comment by riverar** [comment]
Thanks for your patience. Update 2.2.1.0 is now available via multiple channels. Closing.
