### ISSUE TITLE
Volume Control doesn't get update when its open and is changed by another device

### ISSUE THREAD

**Issue by timtoeruem** [File-New-Project/EarTrumpet#123]
When i open the Volume Control of EarTrumpet and use the wheel on my headset to change the volume the Volume Control doesn't get update. Not a big deal because reopening fixes the not updated GUI but could be an enhancement.

**Comment by riverar** [comment]
Yup, I believe this ties into some backlog items we have for live UI (e.g. audio peaks).

**Comment by riverar** [comment]
Done; 1.5 update in the store.
