### ISSUE TITLE
No applicable app licenses found.

### ISSUE THREAD

**Issue by melonboops** [File-New-Project/EarTrumpet#1230]
I've been using Ear Trumpet for a while now and never had an issue until I booted up my laptop to see this message. I've reinstalled Ear Trumpet and continue to see this message. I'm not sure if it's just me receiving this or if others are also having the same issue.

![image](https://user-images.githubusercontent.com/66756292/191373593-cc47d27e-95e5-4c6a-b4c4-db484a4a30a4.png)

**Comment by riverar** [comment]
Hey @melonboops, this is a bug in Windows--not EarTrumpet--that comes to haunt users from time to time. (See also https://github.com/File-New-Project/EarTrumpet/issues/887.) I don't have much in the way of advice, other than perhaps installing EarTrumpet through non-Store sources (e.g. Chocolatey).

Closing for now as there's no work for us to do here.
