### ISSUE TITLE
Cannot distinguish between multiple Microsoft Edge SKUs

### ISSUE THREAD

**Issue by AisinGioroKiIoi** [File-New-Project/EarTrumpet#1238]
### Summary

![image](https://user-images.githubusercontent.com/52952040/193437142-38b456cb-0724-42c6-a822-37dde6f75d1b.png)
如图所示，不同版本的浏览器，图示图标一样，不便分辨。希望能像浏览器自身那样，带上CAN、BETA、DEV的标识。

### Steps to reproduce

无

### EarTrumpet version

2.2.0.0

### Windows version

版本	Windows 11 專業工作站版 Insider Preview 版本	22H2 安裝於	‎2022/‎9/‎30 OS 組建	25211.1001 體驗	Windows Feature Experience Pack 1000.25211.1001.0

**Comment by AisinGioroKiIoi** [comment]
浏览器自身标识如图：
![image](https://user-images.githubusercontent.com/52952040/193437202-4d568801-3578-4d0c-88af-8a5c3c83cf2e.png)

**Comment by riverar** [comment]
We use the icon from the executable. We can't pull icons from random shortcut on the desktop as the application may be started from other locations.

![image](https://user-images.githubusercontent.com/475132/193438963-08311d51-f66a-4870-8edb-627351142bf4.png)

**Comment by AisinGioroKiIoi** [comment]
您可能误解我的意思了，我不是说从桌面获取图标。我只是从桌面图标举了个例子。无论是Edge还是chrome，它四个版本，无论在桌面还是任务栏上，都是不同的图标。Edge瀏覽器分别是无标识，带着CAN、BETA、DEV的标识的。谷歌浏览则是，无表示，带着B、D的标识的，无标示黄色图标的。而咱的软件中，四个版本都是相同的标识，不便区分。

**Comment by AisinGioroKiIoi** [comment]
您可能误解我的意思了，我不是说从桌面获取图标。我只是从桌面图标举了个例子。无论是Edge还是chrome，它四个版本，无论在桌面还是任务栏上，都是不同的图标。Edge瀏覽器分别是无标识，带着CAN、BETA、DEV的标识的。谷歌浏览则是，无标识，带着B、D的标识的，无标识黄色图标的。而咱的软件中，四个版本都是相同的标识，不便区分。

**Comment by riverar** [comment]
Windows has the same problem distinguishing between apps. Will investigate further.

![image](https://user-images.githubusercontent.com/475132/193439836-920bec53-2114-4a6a-9b51-680bf837e96a.png)
![image](https://user-images.githubusercontent.com/475132/193439842-cba2973c-066c-49fe-b036-f7edd0cf4acd.png)

**Comment by AisinGioroKiIoi** [comment]
好的吧，非常感谢。如果可以的话，也希望咱的软件能解决这个问题。毕竟对于部分用户来说，选择咱的软件，也是因为Windows原生应用功能比较弱一点。

**Comment by riverar** [comment]
@AisinGioroKiIoi I've reached out to the Microsoft Edge team to see what they think as well!

**Comment by richeney** [comment]
@riverar It would be great to find out if they could support feeding through Microsoft Edge apps separately as well with their own icons. 

If using web version of Teams as an app, or YouTube, Radio X player, BBC iPlayer, Netflix etc. then the apps show on the taskbar with their own icon. Having those separated within EarTrumpet would be amazing. At the moment EarTrumpet just shows a single Edge logo source (as expected).

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here right now so am closing this issue for now. (I haven't heard anything from the Edge folks.) Feel free to keep the discussion going. Thanks!
