### ISSUE TITLE
Can not remember CSGO's volume

### ISSUE THREAD

**Issue by MJSummer** [File-New-Project/EarTrumpet#1239]
### Summary

if i restart my laptop, ET will set CSGO's volume to 100%, which is not my setting:50%

### Steps to reproduce

if i restart my laptop, ET will set CSGO's volume to 100%, which is not my setting:50%

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19044.1826

**Comment by riverar** [comment]
Hi @MJSummer. EarTrumpet doesn't remember any volumes, this is an OS function. Windows is supposed to do this, but as you're noticing it does so poorly. If you want, you can try EarTrumpet Actions in the developer builds and create an _action_ to automatically set the volume of CSGO to 50% on start.

Closing this for now as there's no work to be done here. But feel free to keep the discussion going.
