### ISSUE TITLE
Request - Allow "Line-In" to show in list of application audio sliders

### ISSUE THREAD

**Issue by YoYo-Pete** [File-New-Project/EarTrumpet#124]
I run a Line-In for external audio, and it would be really nice if that line-in would show up in the list of windows apps so I could adjust it via slider just like it was an app.

I have consoles connected to my multiheaded PC gaming setup.   When I run a console, I connect it via HDMI to my center monitor and run the line-out to the line-in on my PC, this allows the game sound to go out my selected speakers (headset or speakers).   

However when I do this, the 'line-in' I see on the windows 'volume mixer' is not really available in EarTrumpet.    Windows is sending the line-in direct to my default selected audio outbound.

Would it be possible to have that line-in be a slider just like the windows 10 applications?  This would allow people using this for external audio (maybe phone or MP3 player) to be able to control the audio via the app's sliders instead of trying to adjust audio on the playing device (in my case a monitor that makes audio adjustment very difficult).

That's my suggestion/request.  Even if it doesnt make it in there, I really enjoy your application and it's a MUST HAVE for anyone on win10. <3

**Comment by riverar** [comment]
Line-In is a separate device, it should show up when you right-click EarTrumpet. But I understand you want to manage its volume *without* switching the default audio device. Managing multiple devices at once is on our backlog.

**Comment by davuxcom** [comment]
Hi Pete - are you using the 'Listen' checkbox in the device properties (Recording Devices -> Line In -> Listen)?  I've added fixes for this in 336564d2d6c5d13c3e38e208018699d943dc4394
