### ISSUE TITLE
Changing active playback / audio device unmutes muted apps

### ISSUE THREAD

**Issue by Magnificus36** [File-New-Project/EarTrumpet#125]
When I switch the active playback device apps that where muted are no longer muted.
Both when switching using the default Windows volume control and when using EarTrumpet to switch.

**Comment by riverar** [comment]
Can't reproduce this. Can you provide more info on OS/app? The app might have an auto-play feature.

**Comment by Magnificus36** [comment]
Currently I also using EarTrumpet 1.4.4.0 and I can still reproduce this with Groove and Edge (playing a YouTube video).

My exact use case was: I had a live YouTube stream, of a all day event, open at the side while working. I had the video muted because there was a better separate audio stream (without commercials) plus I did want the video open at the side all the time but not always the audio. And the reason I had Edge muted instead of the YouTube video itself was because so other YouTube videos would not start muted.

Sorry it took a while to find the time to reproduce this my self and to come back to this.

**Comment by riverar** [comment]
We reproduced this too during development of EarTrumpet 2.0. Give the update a shot, should resolve your issue (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp). If not, re-open this please.
