### ISSUE TITLE
Crashed in valorant

### ISSUE THREAD

**Issue by flaredomon** [File-New-Project/EarTrumpet#1250]
### Summary

When I open the volume control of the software while playing VALORANT, the PC screen freezes.
Therefore, I have to go to reboot to fix it.

### Steps to reproduce

1:VALORANT PLAYING 
2:START VOLUME CONTROL IN EarTrumpet
3:PC FREEZES

### EarTrumpet version

2.2.0.0

### Windows version

latest

**Comment by riverar** [comment]
Not likely an EarTrumpet issue. Suspect audio drivers or hardware related issues. Re-open if you have more information to share!
