### ISSUE TITLE
Flyout animation doesn't respect the correct OS performance option

### ISSUE THREAD

**Issue by cgytrus** [File-New-Project/EarTrumpet#1251]
### Summary

The built-in volume slider's flyout animation is toggled when the "Animate windows when minimizing and maximizing" option is toggled, but in EarTrumpet it's toggled when the "Fade or slide menus into view" option is toggled

### Steps to reproduce

1. Go into the Windows performance options
2. Toggle "Animate windows when minimizing and maximizing" off and "Fade or slide menus into view" on
3. You will see that the built-in volume slider doesn't have an animation but EarTrumpet does
4. Toggle "Animate windows when minimizing and maximizing" on and "Fade or slide menus into view" off
5. You will see that the built-in volume slider *does* have an animation now but EarTrumpet *doesn't*

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19044.2130

### Additional information

https://user-images.githubusercontent.com/30120687/196951156-7990af1b-9bb8-4a69-9b17-3ad3adf439c6.mp4

**Comment by riverar** [comment]
Adding to confusion, Windows 11 does not respect any of the older SPIs and instead looks at the Accessibility > Visual Effects > Animation effects setting as a discrete on/off. [facepalm]

**Comment by riverar** [comment]
Fixed in a207c648, thanks for your patience. Will push out in next update.

**Comment by riverar** [comment]
Thanks for your patience. Update 2.2.1.0 is now available via multiple channels. Closing.
