### ISSUE TITLE
Volume Mixer missing all other program volumes except Master volume

### ISSUE THREAD

**Issue by DecafChan** [File-New-Project/EarTrumpet#1252]
### Summary

When clicking on the EarTrumpet icon in my tray area to pull up the Volume Mixer, it won't show programs that are currently open(Discord, for example) and will only display the master volume. I have to close and reopen the program to have it appear in the EarTrumpet Volume Mixer.

### Steps to reproduce

Seems to happen at random, but if I figure out the cause, I'll update.

### EarTrumpet version

2.2.0.0

### Windows version

Windows 11 - 10.0.22000 Build 22000

**Comment by q1k** [comment]
How do I make it so it only shows the Master volume?

I don't want to see hundreds of programs when I open the volume slider.


Also, how do I make it open the classic Volume Mixer by default, instead of having to open a submenu for that?

**Comment by riverar** [comment]
> How do I make it so it only shows the Master volume?
> 
> I don't want to see hundreds of programs when I open the volume slider.
> 
> Also, how do I make it open the classic Volume Mixer by default, instead of having to open a submenu for that?

None of these are supported today, sorry.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
