### ISSUE TITLE
Main volume slider is at the wrong place (should be at the bottom)

### ISSUE THREAD

**Issue by ppvnf** [File-New-Project/EarTrumpet#1254]
### Summary

There's a [discussion](https://github.com/File-New-Project/EarTrumpet/discussions/689) about this, but I believe this is a bug instead of feature request. 

The correct position of the main volume slide in the sound menu is at the bottom (system icon):

![Captura de tela 2022-10-27 125029](https://user-images.githubusercontent.com/73800734/198339614-3d646b2c-10b1-4591-95e9-8c0971c4a948.png)

EarTrumpet moves it to the top somehow:

![Captura de tela 2022-10-27 125046](https://user-images.githubusercontent.com/73800734/198339761-673cfdfa-d21e-4042-8751-a9e2fe258024.png)

IMO the main volume slide should be near the taskbar like in the default Windows sound menu:

![Captura de tela 2022-10-27 125046 2](https://user-images.githubusercontent.com/73800734/198339860-ee97e0fe-8c93-4765-af26-ef0e45f21e48.png)

### Steps to reproduce

Click EarTrumpet icon

### EarTrumpet version

2.2

### Windows version

10.0.19044.2130

**Comment by riverar** [comment]
This is not a bug; we designed it this way. I appreciate that some folks want it flipped though (#689).
