### ISSUE TITLE
Discord Crash?

### ISSUE THREAD

**Issue by theardentgold** [File-New-Project/EarTrumpet#1256]
### Summary

The app launches normally when I start up windows(screenshot 1) but it seems to have an issue with discord because when I open it, it resets and looks like this instead (screenshot 2). I also believe it has something to do with audiodg.exe because it shows up briefly before it cuts out, is there a way to like reset it or something?

### Steps to reproduce

Start-Up windows and simply open Discord.

### EarTrumpet version

2.2.0.0

### Windows version

Version 10.0.22621.674

### Additional information

![uh](https://user-images.githubusercontent.com/106575199/198824600-ed306054-3033-41e5-bee8-c7c3aeddb7f8.png)

![unknown (1)](https://user-images.githubusercontent.com/106575199/198824605-769d5b93-7438-45a6-be31-7a62df5234fc.png)

**Comment by riverar** [comment]
Does restarting EarTrumpet resolve this?

**Comment by theardentgold** [comment]
it only seems to be happening when I restart my pc, but restarting eartrumpet does seem to fix it,  it is kind of annoying restarting it all the time. I do use voicemeeter banana for switching audio from following this video https://youtube.com/watch?v=E_agZx1c_u0&feature=share&utm_source=EKLEiJECCKjOmKnC5IiRIQ but I can only get this to happen from the discord app. I think there is some kind of overflow because audiodg.exe shows up in my currently selected audio device then discord shows up in all of my audio devices, then it closes and just looks empty and I can't control the volumes.

**Comment by riverar** [comment]
Yeah we're overdue for an overhaul of some of our internals. The Windows Core Audio API has a [particular recovery model](https://learn.microsoft.com/windows/win32/coreaudio/recovering-from-an-invalid-device-error) we need to adapt (on error, basically _start over_).

**Comment by riverar** [comment]
Will close this for now as there's no Discord-specific work here, but the overhaul working is on-going.
