### ISSUE TITLE
"Search" appears as an app in EarTrumpet's list 

### ISSUE THREAD

**Issue by bolololololo** [File-New-Project/EarTrumpet#1259]
### Summary
I don't know if it's a bug but when I open EarTrumpet's panel it shows Search as one of the programs running. It might be related to Windows Feature Experience Pack that appears in the legacy mixer as shown below.

### Steps to reproduce
Step 1: Click on EarTrump icon in taskbar.

### EarTrumpet version
2.2.0.0

### Windows version
11 22H2

### Additional information
![gf](https://user-images.githubusercontent.com/80776140/199220712-1e9644ea-6f0d-43be-8370-50e6ef1f52eb.png)
![gf1](https://user-images.githubusercontent.com/80776140/199221063-da000434-5d74-451c-b095-bcc7ba6267b4.png)

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/216499567-e173d37b-9511-4083-ac1b-c6a54b66c1d3.png)

Shows up as Windows Feature Experience Pack in sndvol 🥴

**Comment by bolololololo** [comment]
I believe it's not an issue with EarTrumpet but something buggy with Windows 11 that treats search as a program that outputs audio. Anyway the developers could just filter out this entry in future versions, as I believe no one really adjusts the volume for this.

**Comment by riverar** [comment]
Added a workaround. It should now show the _slightly_ less terrible CBS asset on Windows 10 and Windows 11.

![image](https://user-images.githubusercontent.com/475132/222657139-299d601e-0b92-4e05-83e0-e2d8da384c6c.png)
