### ISSUE TITLE
Audio coming out of devices simultaneously, no longer working

### ISSUE THREAD

**Issue by earthtoamelia** [File-New-Project/EarTrumpet#1267]
### Summary

I use ear trumpet to allow system sounds to come from my speakers when my headphones are plugged in. This way I never miss a notification sound if my headphones are plugged in but not being worn. This worked for about a day. Soon after, the issues started. In the Ear Trumpet mixer, I have the volume up for both audio devices that are connected to the computer. Yet sound will only come out of one of them. I've determined that right-clicking Ear Trumpet in the task bar allows me to click to "check" one device or the other. I want sound to come out of both devices simultaneously, with the ability to turn down the master volume of one or another as needed. This feature was working when I first downloaded the app. Please help! I need to stop missing notifications coming through my headphones when they aren't being worn. 

### Steps to reproduce

Click ear trumpet in the task bar
Set Speaker master volume to 100
Set Headphones master volume to 100

### EarTrumpet version

2.2.1.0

### Windows version

10.0.19043.2251

### Additional information

![Screenshot 2022-11-11 125417](https://user-images.githubusercontent.com/118012002/201400290-8606176d-0fe0-4cfc-b215-549f4d10799d.png)
Shows sound mixer with volume for both devices on, yet no sound is coming out of whichever one is not checked when I right-click the ear trumpet icon in the task bar.

![image](https://user-images.githubusercontent.com/118012002/201400336-31abf9cc-4ef1-414f-8435-fafe4b4259dc.png)
As you can see, I can only have one or the other "checked" in the ear trumpet app. This makes no sense because I was able to produce sound from two different devices simultaneously when I first downloaded the app less than a month ago. I have already uninstalled and reinstalled the app, so I have the latest version. The issue is still occurring.

**Comment by riverar** [comment]
Hi @earthtoamelia! Simultaneous audio output is not something Windows or EarTrumpet supports.

Maybe your audio device manufacturer has a Stereo Mix or similar? (see screenshot)
![image](https://user-images.githubusercontent.com/475132/204044694-e6a52d6b-d562-4873-8567-e998deed15aa.png)

You can access the above window by right-clicking EarTrumpet's tray icon > Windows Legacy > Recording devices.

Will close this for now, but feel free to keep the discussion going.
