### ISSUE TITLE
Feature request: Implement same UI for selecting audio source as in Windows

### ISSUE THREAD

**Issue by niiiksh** [File-New-Project/EarTrumpet#127]
![image](https://cloud.githubusercontent.com/assets/16052532/25826191/88c2fe72-344e-11e7-8b74-c5ecf6a7c24e.png)
I'd like to see the same UI in Ear Trumpet.

**Comment by riverar** [comment]
We have a similar feature in EarTrumpet 2.0. Give that a shot and let us know what you think. (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
