### ISSUE TITLE
Japanese .resx updates have stopped

### ISSUE THREAD

**Issue by maboroshin** [File-New-Project/EarTrumpet#1274]
### Summary

Resources.en-JP.resx is no longer being updated from Crowdin. However, only two places are in the English original on this App.

### Steps to reproduce

See Resources.ja-JP.resx on GitHub

### EarTrumpet version

2.2.1.0

### Windows version

10

**Comment by riverar** [comment]
Looking into this now.

**Comment by riverar** [comment]
Not sure I understand. We have a Japanese resource file here https://github.com/File-New-Project/EarTrumpet/blob/master/EarTrumpet/Properties/Resources.ja-JP.resx and it's 97% complete (same on Crowdin). Am I missing something? (en-JP is not valid.)

**Comment by maboroshin** [comment]
I didn't explain myself well enough.

I can see below string finished in Crowdin  6 months ago: `Increase volume for all devices` (And `Decrease volume`)
![image](https://user-images.githubusercontent.com/41102508/204061584-400df46a-d228-4e1e-b211-15092b04a6c7.png)

In CHANGELOG.md, it became ver 2.2.1.0 a month ago. The above strings remain in English in this version 2.2.1.0.
![image](https://user-images.githubusercontent.com/41102508/204062333-2f697e8e-038e-476e-a50d-f0029f784f98.png)

The Japanese file on GitHub was updated 1 year and 9 months ago. In [Resources.ja-JP.resx
](https://github.com/File-New-Project/EarTrumpet/blob/master/EarTrumpet/Properties/Resources.ja-JP.resx), Does not contain the corresponding key: `SettingsAbsoluteVolumeUpText` 

On the other hand, other language files have this key:  ["SettingsAbsoluteVolumeUpText"](https://github.com/File-New-Project/EarTrumpet/search?q=SettingsAbsoluteVolumeUpText) (GitHub Search)

**Comment by riverar** [comment]
Thanks, I see that now! Let me kick Crowdin a few times.

**Comment by riverar** [comment]
Good news! This has been fixed and is available in EarTrumpet 2.2.2.0 (now live). Closing as fixed, thanks again for the report.
