### ISSUE TITLE
Add the app volume and device preferences menu to Ear Trumpet

### ISSUE THREAD

**Issue by megamanzerobasslink** [File-New-Project/EarTrumpet#1277]
![image](https://user-images.githubusercontent.com/52249142/204962997-6c8a8d9b-cf3e-4b25-9917-303b877c80b1.png)

**Comment by riverar** [comment]
Added in [98ebcb8](https://github.com/File-New-Project/EarTrumpet/commit/98ebcb894834b15ad315b9cd9f784c61dd5648c4). This will make its way into a future update soon thanks!

**Comment by megamanzerobasslink** [comment]
Thank you, very based kind sir!
