### ISSUE TITLE
Not smooth animation when you change the volume

### ISSUE THREAD

**Issue by SoulNaturalist** [File-New-Project/EarTrumpet#1278]
### Summary

I have to reload the application to fix this problem.
Also, when you increase the volume, it breaks select.

### Steps to reproduce

When working for a long time, it occurs.
It may be my local windows problem.

### EarTrumpet version

2.2.1.0

### Windows version

10.0.19045. 0

**Comment by SoulNaturalist** [comment]
I would even say the application window, as if lagging

**Comment by riverar** [comment]
Closing this for now, I leave EarTrumpet running for weeks and not seeing anything like that here. Might be a Bluetooth device which I have seen to have high latency. If anyone has more info, a video, etc. please drop it in here.
