### ISSUE TITLE
At install, app doesn't work, got "Unhandled exception" window

### ISSUE THREAD

**Issue by sanjayananda** [File-New-Project/EarTrumpet#128]
I downloaded the app from Windows Store and tried running it. The first thing that popped up was this error window:

> **Microsoft .NET Framwork**
> Unhandled exception has occurred in a component in your application. If you click Continue, the application will ignore this error and attempt to continue.
> 
> '-2147484008' is not a valid value for this property. Valid values are from Int32.MinValue through Int32.MaxValue.
> 
> **Details:**
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentException: '-2147484008' is not a valid value for this property. Valid values are from Int32.MinValue through Int32.MaxValue.
>    at System.Windows.Window.ValidateTopLeft(Double length)
>    at System.Windows.Window.CoerceLeft(DependencyObject d, Object value)
>    at System.Windows.DependencyObject.ProcessCoerceValue(DependencyProperty dp, PropertyMetadata metadata, EntryIndex& entryIndex, Int32& targetIndex, EffectiveValueEntry& newEntry, EffectiveValueEntry& oldEntry, Object& oldValue, Object baseValue, Object controlValue, CoerceValueCallback coerceValueCallback, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, Boolean skipBaseValueChecks)
>    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
>    at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
>    at System.Windows.Window.set_Left(Double value)
>    at EarTrumpet.MainWindow.UpdateWindowPosition()
>    at EarTrumpet.MainWindow.TrayIcon_Invoked()
>    at System.Action.Invoke()
>    at EarTrumpet.TrayIcon.TrayIcon_MouseClick(Object sender, MouseEventArgs e)
>    at System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
>    at System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
>    at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
>    at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1648.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> EarTrumpet
>     Assembly Version: 1.4.4.0
>     Win32 Version: 1.4.4.0
>     CodeBase: file:///C:/Program%20Files/WindowsApps/40459File-New-Project.EarTrumpet_1.4.4.0_x86__1sdd7yawvg6ne/EarTrumpet.exe
> ----------------------------------------
> PresentationFramework
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1647.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
> ----------------------------------------
> WindowsBase
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> PresentationCore
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
> ----------------------------------------
> System.Xaml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> PresentationFramework.Aero2
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> UIAutomationTypes
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1586.0 built by: NETFXREL2
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by riverar** [comment]
Where is the Taskbar docked on your screen? What is your DPI scale factor set to? (Under Scale and layout in Display settings)

**Comment by psynex** [comment]
I had the same problem just installing it for the first time today.  Taskbar docked on bottome and DPI set to 100% (recommended)

**Comment by riverar** [comment]
Are you using any apps modifying the desktop/shell, like WindowBlinds?

**Comment by GoldenTao** [comment]
If this is still an issue, please reopen.
