### ISSUE TITLE
Applications not showing when new output is connected

### ISSUE THREAD

**Issue by X512B11** [File-New-Project/EarTrumpet#1281]
### Summary

When switching between built in speakers to my AirPods, EarTrumpet will not show active sound applications in the list. Sometimes it works, other times it does not. 

Some times the applications will show but the applications listed, the volume slider will not adjust the volume. It will slide, but volume will remain the same. 

When the problem occurs, if I quit EarTrumpet and then re-launch it, the applications will show and act as normal.

Windows 10 there was no problem of this, Windows 11 (current system) there seems to be issues.... please keep in mind that when I switch to the Bluetooth headphones (AirPods), there is a bit of delay/problems from when the computer says the headphones are connected to the sound actually being herd from the headphones. Some times the whole computer freezes for a min or two. Sometimes I need to switch Bluetooth off and on again to get any sound from the Bluetooth headphones. (I'm guessing this is not EarTrumpet fault but more Intel or Microsoft issue but thought it might be relevant) 

### Steps to reproduce

Use Bluetooth headphones on a Windows 11 machine running 22H2. (Windows sound settings; I have the microphone portion of the AirPods disable to keep sounds quality decent. I use the internal microphone of the laptop always) 

### EarTrumpet version

2.2.1.0

### Windows version

10.0.22621.900

### Additional information

Use the same settings/configuration on Windows 10 without any problems.

**Comment by Beet4** [comment]
I have the exact same issue when switching between headphones and speakers in Sound Blaster Command. After switching between devices programs/games does not show up in the EarTrumpet list until I either restart the program/game or restart EarTrumpet.

![image](https://user-images.githubusercontent.com/38279393/208115750-0d075615-82fc-44cd-898b-a68652edac9b.png)

**Comment by X512B11** [comment]
@Beet4 - Quick question, are you on Windows 11 using Bluetooth headphone?

**Comment by RealAct** [comment]
I also have this problem on Windows 11 latest public release. I was going to make a new post about it, but I guess since the author already saw this, I will also add myself to this list. 

The only solution I have found is to relaunch the application, and sometimes that doesn't work either.

I really hope this gets fixed, as I absolutely love this app.

**Comment by X512B11** [comment]
Paid topic (not sponsor but cost more doh!), but for anyone using AirPods (2nd Gen), I ended up buying AirFly by TwleveSouth (Bluetooth to 3.5mm) and switching between internal speakers and 3.5mm, the issue does not seem to persist. 

Windows 11 in general with AirPods (2nd Gen) seem to have lots of issues on my device.... computer sometimes freezes, no audio, ect... the adaptor used helps avoids these issues. (EarTrumpet is still a pretty awesome program/tweak!)

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
