### ISSUE TITLE
Logitech G Hub Audio Setting Not Retained

### ISSUE THREAD

**Issue by SamBoasman** [File-New-Project/EarTrumpet#1284]
### Summary

In Logitech G Hub I can attach sound samples/effects to key binds, however every time Ear Trumpet or Logitech G Hub restarts it loses the sound limit setting for Logitech G Hub and goes back to 100%. This also happens in windows volume mixer.

### Steps to reproduce

 - Launch both Ear Trumpet and logitech G. 
 - If Ear Trumpet does not detect Logitech G immediately, play a sound from logitech G.
 - Set the volume of logitech G to a custom value
 - Exit and relaunch application (either Logitech G Hub or Ear Trumpet will do)

### EarTrumpet version

2.2.1.0

### Windows version

10.0.22621.819

**Comment by riverar** [comment]
This isn't a feature of EarTrumpet (although EarTrumpet Actions, [in dev builds](https://eartrumpet.app), may help). This is _supposed_ to be handled by Windows.

Please follow the steps here (change the template as needed) https://github.com/File-New-Project/EarTrumpet/issues/512#issuecomment-683485012 to get Microsoft feedback with log data.

Closing this for now as there's nothing to fix/do here but I will keep this on top of mind. Thanks!
