### ISSUE TITLE
Anki not registered as an application correctly.

### ISSUE THREAD

**Issue by Apocalypse612** [File-New-Project/EarTrumpet#1292]
### Summary

Anki is not appearing as an application in EarTrumpet. It's misrepresented as the media player used to play audio, assuming you have audio in your flash cards.

### Steps to reproduce

Boot it up and try to play audio, then check EarTrumpet.

### EarTrumpet version

2.2.1.5

### Windows version

10.0.19042.985

### Additional information

![image](https://user-images.githubusercontent.com/6374154/210852782-9e178403-6e75-4a0d-bfae-e88eac27080b.png)

**Comment by riverar** [comment]
Hi @Apocalypse612!

Anki is using a separate program (mpv) to play audio. Windows reports the same, so sadly there's not much we can do here. You may want to file an issue on Anki at https://github.com/ankitects/anki.

![image](https://user-images.githubusercontent.com/475132/211211220-c76ab81c-4ea8-48fc-a02f-106ea19f5af6.png)

As a workaround, Anki could perhaps:
* Modify the bundled mpv.exe, replacing its icon with the Anki icon
* Start mpv.exe with `title=` parameter to set a more appropriate title during playback

**Comment by Apocalypse612** [comment]
Thanks!
