### ISSUE TITLE
MEmu does not fully support audio stream re-routing

### ISSUE THREAD

**Issue by Tenzzai** [File-New-Project/EarTrumpet#1297]
### Summary

Just installed Windows 10 on a brand new pc and with it eartrumpet from microsoft store.
When I change the output device for a specific program, I have to change the default output device between my speakers (secondary) and headset (main) for the change to take effect...
And if I restart the program I have to do it again.

### Steps to reproduce

1. right click a program to change output device
2. Chose the desired output device for that program(This case to " Realtek USB Audio"
![Screenshot_1](https://user-images.githubusercontent.com/122692985/212488665-b627bcfe-0852-46dd-abcf-5b0d5d760653.png)

3. does not disappear from "logitech" field and sound still on headset
![Screenshot_2](https://user-images.githubusercontent.com/122692985/212488678-edd961ef-ee4b-4f35-b213-647c2a342046.png)

4. using Eartrumpet "Windows legacy and Playback devices" to change the "Default device" back and forth once
![Screenshot_3](https://user-images.githubusercontent.com/122692985/212488704-7763cf4e-bc1c-4dea-aa7e-af28579a32d0.png)
![Screenshot_4](https://user-images.githubusercontent.com/122692985/212488717-bfe31640-5345-4806-95d6-f465fbd0dfd4.png)

5. and the sound finally changes completely 
![Screenshot_5](https://user-images.githubusercontent.com/122692985/212488719-d1f7048b-9a7e-4ce8-b335-a0eb2d73b5db.png)

### EarTrumpet version

2.2.1.0

### Windows version

10.0.19045.2486

**Comment by riverar** [comment]
I'll take a look but I'm guessing MEmu uses MMDeviceAPI or WASAPI directly. So when we try to re-route the audio stream, things don't go as planned. (https://learn.microsoft.com/windows/win32/coreaudio/stream-routing).

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1307, thanks!
