### ISSUE TITLE
The volume percentage text is not changing in real time in EartTumpet when scrolling the mouse wheel over the EartTumpet icon.

### ISSUE THREAD

**Issue by bigplayer-ai** [File-New-Project/EarTrumpet#1298]
### Summary

The volume percentage text is not changing in real time in EartTumpet when scrolling the mouse wheel over the EartTumpet icon.

### Steps to reproduce

1) move mouse pointer to eartrumpet tray icon
2) scroll to change volume
3) see the overlay text not changing its volume percentage (as shown in the image below)
in the image I changed the volume from muted to maximum level.
![changed volume to maximum, notification says it is muted](https://user-images.githubusercontent.com/119108387/212519971-d15c86e3-b30d-4e92-80a8-dd820ed0896b.png)

### EarTrumpet version

2.2.1.0

### Windows version

Microsoft Windows [Version 10.0.22621.1105]

### Additional information

Windows 11 22H2

**Comment by riverar** [comment]
@bigplayer-ai Hi there. Can you right-click EarTrumpet, click EarTrumpet Settings > Collect troubleshooting data, and attach that here (or send it to us via email `team@eartrumpet.app`.) Thanks!

**Comment by riverar** [comment]
Closing this for now but if it keeps happening let me know.

**Comment by bigplayer-ai** [comment]
Yes it's still happening

**Comment by riverar** [comment]
@bigplayer-ai Can you retry this with the latest Windows 11 update? That features a new system tray and new tooltips!

**Comment by riverar** [comment]
@bigplayer-ai Thanks, have you upgraded to EarTrumpet 2.2.2.0? That has some scroll improvements too.

**Comment by bigplayer-ai** [comment]
Can we have an option without the scroll hook? Or have an option to turn off this feature?On 3 Mar 2023, at 11:19, Rafael Rivera ***@***.***> wrote:﻿
@bigplayer-ai Thanks, have you upgraded to EarTrumpet 2.2.2.0? That has some scroll improvements too.

**Comment by riverar** [comment]
Can reproduce with Windows 10 22H2 19045.2728

**Comment by riverar** [comment]
Verified this is already working in EarTrumpet dev builds. Should go out to public soon. (Heads up @aniave)
