### ISSUE TITLE
Clicking the "toggle mute" button crashes the program

### ISSUE THREAD

**Issue by duradara** [File-New-Project/EarTrumpet#1299]
### Summary

When you click the "toggle mute" button to mute everything the program crashes 

This button:
![Screenshot 2023-01-17 184728](https://user-images.githubusercontent.com/50158352/213019829-3dc17542-bbce-4b5e-9653-be84afcd90ef.png)

### Steps to reproduce

Open the program a click the "toggle mute" button

### EarTrumpet version

2.2.1.0

### Windows version

10.0.19044.2251

**Comment by riverar** [comment]
Hi @duradara can you perform the steps listed here? https://github.com/File-New-Project/EarTrumpet/issues/823#issuecomment-840719173

Also be aware your Windows version (19044) is end of life, might want to upgrade soon to something supported by Microsoft.

**Comment by duradara** [comment]
I just sended the file to team@eartrumpet.app

**Comment by riverar** [comment]
@duradara Thanks. I installed 19044.2251 and can't seem to reproduce this issue.

Any chance you could install the latest updates from Windows Update?

**Comment by duradara** [comment]
I just uninstalled and installed again the program and its fixed

**Comment by riverar** [comment]
Thanks @duradara. Very strange behavior, will keep an eye on it / our crash metrics.
