### ISSUE TITLE
SkyGo opens new Output for every video/stream

### ISSUE THREAD

**Issue by Grimeton** [File-New-Project/EarTrumpet#130]
Hi,

the SkyGo app from German pay-tv provider Sky opens a new audio output for every stream or video you watch on the platform. So over time you end up with 10 or 20 entries in the list. 

The thing is only one audio output is active all other are more or less abandoned. When you close the app all the outputs go away.

Seems a lot like the Skype problem to me.

Let me know if you need some kind of debugging information or whatever and I'll make sure you get it.

KR,

G.

**Comment by Grimeton** [comment]
Update:

It seems that the audio channels go away after a certain timespan. Seems like 5 minutes or so and you're left with the one that's actually used.

Cu

**Comment by riverar** [comment]
We made a bunch of changes to grouping behavior in EarTrumpet 2.0. Give that a try. You can grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
