### ISSUE TITLE
After installing EarTrump the 'volume ducking/ during Teams/Discord/WhatsApp calls is no longer working.

### ISSUE THREAD

**Issue by MMitsialis** [File-New-Project/EarTrumpet#1302]
### Summary

After installing EarTrumpet I have noticed that during voice calls using Teams, Discord and WhatsApp volume ducking of other background does not happen. this forces me to manually pause or mute the background app audio the call then enable again after  the cal.

### Steps to reproduce

1. Install EarTrumpet and enable.
2. Join a Teams/WhatsApp/Discord session  with background audio playing/
3. The background audio continues playing a the original volume is not attenuated during the active call. 

### EarTrumpet version

2.2.1.0

### Windows version

10.0.19045.2364

**Comment by riverar** [comment]
We don't do anything with ducking, so this is unlikely a EarTrumpet issue. Instead, right-click the EarTrumpet icon then go to Windows Legacy > Sounds > Communications tab and ensure ducking is set as you desire.

![image](https://user-images.githubusercontent.com/475132/214774132-194c7536-2a90-4b50-83bf-0827b057c267.png)

Will close this as there's nothing actionable here but feel free to keep the discussion going / re-open.
