### ISSUE TITLE
Disney+ App reverts to "Default" audio device every time an episode ends a new one begins

### ISSUE THREAD

**Issue by SpyderZT** [File-New-Project/EarTrumpet#1306]
### Summary

When you've set the Disney+ App (From the MS Store) to a secondary audio destination, it reverts back to the "Default" destination every time an episode of a show ends, even though it still shows as assigned to the new source in the task tray menu. A second instance of the app where the audio shows up as active appears when you look at that menu. Weirder, "Right Clicking" that new instance Still shows the app properly assigned, and you have to click the same location it's already assigned to so that you can move it over again.

### Steps to reproduce

1) Assign the Disney+ Application to any audio destination beyond the Default destination while the app is running.
2) Wait for an episode of a series (Or a Movie, or etc.) to end, and when the next episode begins, observe that the audio has reverted to the "Default" destination as a duplicate entry.
3) When Right Clicking that entry to see its assignment, note that it Still shows as assigned to that secondary destination.
4) Click the same entry it shows as assigned to and note that the audio is again transferred to the secondary destination.

### EarTrumpet version

2.2.1.0

### Windows version

10.0.19045.2546

### Additional information

https://user-images.githubusercontent.com/14990202/214964823-45539bca-3619-4ea5-8108-d1cd649bab2a.mp4

**Comment by riverar** [comment]
Interesting, thanks for the excellent report. Will try this out!

**Comment by riverar** [comment]
Looks like there's an issue with the audio stream routing UX in Windows and the handling within the Disney Plus app.

Please file an issue in Feedback Hub under `Devices and Drivers` > `Audio and sound`. Use the `Recreate my problem` feature to gather a trace of you repeating the steps in the video. These critical logs will land right on the audio team's desks; I know an engineer there actively looking at this stuff! Be sure to also include a link to here so they know this is blocking an EarTrumpet user.

Thanks again; closing as it's not directly actionable by us but will be keeping an eye out here. Feel free to continue the discussion as well.

**Comment by SpyderZT** [comment]
By coming back here, I realized I hadn't sent that trace. ;? Done now.
