### ISSUE TITLE
Latest DEV Build 2.2.2.12

### ISSUE THREAD

**Issue by jh30uk** [File-New-Project/EarTrumpet#1308]
### Summary

Cannot update from or even clean install due to "The Parameter Is Incorrect" msg

### Steps to reproduce

Try to install for yourself.

### EarTrumpet version

DEV 2.2.2.12

### Windows version

11 Dev

### Additional information

![2023-01-28](https://user-images.githubusercontent.com/109413574/215250558-38836a11-9de6-4ad2-b4c1-b614bf837650.png)

**Comment by riverar** [comment]
@jh30uk Can you click that (i) in the corner? Also what build of Windows 11?

**Comment by riverar** [comment]
So far, am seeing

1.19.10173.0 on Windows 10 w/ 19044.2486
1.19.3132.0 on Windows 11 w/ 25281

![image](https://user-images.githubusercontent.com/475132/215254835-a419cc4c-94a9-4218-9180-b363ee61436b.png)

**Comment by riverar** [comment]
Oh this happens after clicking install/update.

![image](https://user-images.githubusercontent.com/475132/215254944-aa44340f-a0a4-4697-a3f1-ffd2624dd7da.png)

**Comment by riverar** [comment]
@jh30uk Hi there, this is a known issue with AppInstaller. I changed the server-side manifest recently and forgot. A reboot is required to clear a cache somewhere. Can you confirm rebooting fixes the issue?

I filed another bug on Microsoft about this. https://github.com/microsoft/WindowsAppSDK/issues/3378

**Comment by jh30uk** [comment]
No, I obviously tried a reboot as would expect that at times.

I do have the Master installed but disabled, I may try uninstalling that then rebooting and try dev again.

**Comment by riverar** [comment]
@jh30uk Did you try rebooting when I posted that message? Any reboots prior to that message (Jan 28 1:48AM PST) don't count because I edited that file several times. If at any point you downloaded the `.appinstaller` and ran it, AppInstaller cached it and subsequent install attempts would fail. (It's lame, I know.)

I'm still getting the error too because I haven't rebooted my main box, ha! But my other machines did seem to clear up.

**Comment by jh30uk** [comment]
Yes, I have rebooted Mutiple time and right now typing this MSG I cannot install it opening the link even after clearing browser cache.

**Comment by riverar** [comment]
Very strange, let me see what else I can find out. Thanks for your patience.

**Comment by riverar** [comment]
Looks like AppInstaller is very broken in at least 25281+, I'm having the same issue locally with all AppInstaller apps. Let's keep an eye on the bug I filed in the WinAppSDK repo. Closing this issue as there doesn't appear to be any work to be done.

**Comment by jh30uk** [comment]
All works now on Latest Win 11 Dev 25290 (1st Feb Build) and ET Dev 2.2.2.22

**Comment by riverar** [comment]
Thanks for following up, will upgrade my machine tomorrow. Frustrating that Microsoft never officially documented this.
