### ISSUE TITLE
audiodg memory leak windows 10

### ISSUE THREAD

**Issue by hrvn** [File-New-Project/EarTrumpet#131]
Hello, 
I have been using the app for a couple of days, mostly for muting MS Edge. I noticed that when the app is running, audiodg uses about 8.8GB of my 16GB RAM. Is this normal?

**Comment by riverar** [comment]
What sound chipset are you using? This is likely a leak in a 3rd party sound driver, unrelated to EarTrumpet.

**Comment by riverar** [comment]
If you see this again, let us know. But closing this issue for now.
