### ISSUE TITLE
Clicking the "toggle mute" button crashes the program + now the "master volume" slider doesn't work

### ISSUE THREAD

**Issue by duradara** [File-New-Project/EarTrumpet#1314]
### Summary

A few weeks ago I made this post #1299 and the problem solved itself after I uninstalled and installed again. Now I have the same problem again but also the "master volume" slider (The volume bar at the top I dont know if what's it actual name) doesn't change the volume, the programs sliders at the bottom work well only the top one doesn't work.  
Sorry if my english is bad.

![1](https://user-images.githubusercontent.com/50158352/216477059-a4d9df34-59c3-430d-9607-3f0b69384338.png)
![2](https://user-images.githubusercontent.com/50158352/216477065-0ba96539-f8d7-4656-9254-6396e3ef5234.png)

### Steps to reproduce

-Open the program a click the "toggle mute" button and it crashes

-Moving the top volume slider does nothing.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.19044.2251

**Comment by duradara** [comment]
Okey I just tried to change the audio source from my speakers to my monitor audio and now the top slider works and clicking the mute bottom doesn't crash.  So I guess the problem is my speaker??? Does anyone have a possible solution for this?

**Comment by riverar** [comment]
Hey @duradara, can you provide the log from Settings? Just curious what device this is. I suspect a driver issue.

**Comment by duradara** [comment]
> Hey @duradara, can you provide the log from Settings? Just curious what device this is. I suspect a driver issue.

I just sed it to [team@eartrumpet.app](mailto:team@eartrumpet.app)

**Comment by riverar** [comment]
@duradara Thanks, the OS is returning `ERROR_INVALID_HANDLE` when calling `IAudioEndpointVolume.SetMute`. Does restarting EarTrumpet fix the issue? Or does it remain?

**Comment by duradara** [comment]
> @duradara Thanks, the OS is returning `ERROR_INVALID_HANDLE` when calling `IAudioEndpointVolume.SetMute`. Does restarting EarTrumpet fix the issue? Or does it remain?

Manually closing and reopening EarTrumpet seems to fix the issue somehow???

**Comment by duradara** [comment]
Nevermind the issue is back and then I restarted my PC and the issue is gone, so I guess I will have to live with this now, lol

**Comment by riverar** [comment]
Let's tie this to #1305. We need to add better error recovery, thanks for your patience!
