### ISSUE TITLE
Firefox multiple sound control when enabled multiprocesswindow

### ISSUE THREAD

**Issue by Garry050** [File-New-Project/EarTrumpet#132]
<img src=https://i.ppn.pw/cc/645ca6c4/w3d9e3a14.png>
pls fix it.

Windows 10 Creators Update x64 + Firefox 54.0.1(64bit)

**Comment by riverar** [comment]
Does this happen all the time? Can't reproduce with 54.0.1 (64-bit) on Windows 10 rs3 16237. If you could provide a bit more info (e.g. sites open, are those open instances, what does it show when you hover over them) that would be great.

**Comment by Onepamopa** [comment]
This happens all the time with Firefox 56 64bit. To reproduce you need more open tabs in order to utilize multi process properly.

**Comment by Onepamopa** [comment]
Also, sometimes volume resets to 100% on one or more firefox "threads".

**Comment by riverar** [comment]
We made a bunch of changes to grouping behavior in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
