### ISSUE TITLE
DEV 2.2.2.24 Freezes at times.

### ISSUE THREAD

**Issue by jh30uk** [File-New-Project/EarTrumpet#1320]
### Summary

EarTrumpet icon cannot be selected be it right/left clicked, it does nothing and sometime closes when you do so, once relaunched it is runs fine for a while.

### Steps to reproduce

It is random, take a while to happen.

### EarTrumpet version

DEV 2.2.2.24

### Windows version

Win 11 Dev 25295.1000

**Comment by jh30uk** [comment]
It seems to be using the most CPU during music playback over other processes, hitting Moderate Power Usage of 5-6%.

**Comment by riverar** [comment]
When you say _power usage_, what are you referring to? If you see high CPU usage in Task Manager, try to right-click EarTrumpet.exe and select Create memory dump.

**Comment by jh30uk** [comment]
I have reinstalled it and will keep an eye on it, remember this is the first build to update/install after the build that would not be that MS to blame or not, I am sure you remember as we spoke of this.

**Comment by riverar** [comment]
Yep, I remember. Thanks again. Will close this for now just to keep the issues list limited to actionable items but if it happens again and you get that dump, please do let me know asap.
