### ISSUE TITLE
If Output Device name changes, on the next restart the apps that were on that device won't show in EarTrumpet

### ISSUE THREAD

**Issue by kanjieater** [File-New-Project/EarTrumpet#1329]
### Summary

For some reason my steinberg ur-44c updated it's name from 2- Steinberg UR44C to 3- Steinberg UR44C
![image](https://user-images.githubusercontent.com/32607317/222002822-ea08b04f-b4ba-4bd2-90fd-d08b50c3eebf.png)

The apps I had on 2- UR44C no longer show in EarTrumpet. They are muted and I cannot hear them. I tried going to System -> Sound -> Volume Mixer and resetting apps & device volumes, but that did not restore it. 

Other apps are still showing 
![image](https://user-images.githubusercontent.com/32607317/222003066-9204c836-b15b-4830-977e-845b5ceb9147.png)
But the one I'm playing right now, does not show up (and is not muted)
![image](https://user-images.githubusercontent.com/32607317/222003135-45ef6c50-3065-468c-83d3-35b0bfdac100.png)

### Steps to reproduce

Change the output device of an app.
Change the driver name for the device, or remove the device when shutting down.
You won't have access to that app on your default playback device anymore

### EarTrumpet version

2.2.2.24

### Windows version

10.0.22621 build 22621

### Additional information

If I rename the app, I can see the app showing again.

**Comment by riverar** [comment]
And restarting EarTrumpet fixes it, I presume?

**Comment by riverar** [comment]
Can you start the app, verify it's missing, then collect diagnostics (in EarTrumpet settings) and provide that here? (You can also email it to team@eartrumpet.app if you have any privacy concerns.)

**Comment by riverar** [comment]
Can't reproduce this directly but I associated it with master issue https://github.com/File-New-Project/EarTrumpet/issues/1305. If you get some time to look into this, I'd be curious to see:
* the requested logs 
* whether or not the app shows up in the Windows mixers
