### ISSUE TITLE
(Volume)Mixer too large horizontally and vertically

### ISSUE THREAD

**Issue by speldenaar** [File-New-Project/EarTrumpet#1335]
### Summary

When using 7 devices with some outputs connected (see scrshots 1, 1920x1080) the vertical mixer does not display all devices,
instead you need to SCROLL to get to the upper device.
Issue: when scrolling, you change sound volumes.

Also the volumemixer is too large horizontally.
It crosses multiple displays. (scrshot2)
The devices are horizontally alligned. (scrshot3)

Please fix with adaptive or make smaller

### Steps to reproduce

1920x1080 PC res

More devices than the (volume)mixer can show horizontally and vertically

### EarTrumpet version

2.2.2.0

### Windows version

10.0.19045.2728

### Additional information

![EarTrumpet3](https://user-images.githubusercontent.com/17081465/226381229-50646b84-3220-40d4-800e-4eb914ad0ba2.png)
![EarTrumpet2](https://user-images.githubusercontent.com/17081465/226381233-a5dd7939-7187-4433-b86f-04e8f8811416.png)
![EarTrumpet1](https://user-images.githubusercontent.com/17081465/226381246-5f75d8be-beb3-4e22-ba34-25c6f330636f.png)

**Comment by riverar** [comment]
Do you use all of those devices?

**Comment by riverar** [comment]
Closing this as I'm not seeing an issue here. That said, we have other feature requests/issues tracking improvements such as being able to filter the device list. Feel free to keep the discussion going.
