### ISSUE TITLE
PotPlayer overrides Eartrumpet settings

### ISSUE THREAD

**Issue by andre-holivia** [File-New-Project/EarTrumpet#1338]
### Summary

PotPlayer - Media Player: https://potplayer.daum.net/
EarTrumpet is set to play sound from PotPlayer at 50%

Changing sound in all other software. Sound levels retained except for PotPlayer. 
Changing sound level in PotPlayer OVERRIDES the EarTrumpet settings

### Steps to reproduce

To reproduce: 
* Go to PotPlayer
* Play content
* Change the sound setting. 

This change overrides the EarTrumpet orchestration

### EarTrumpet version

 10.0.23419.1000

### Windows version

Windows 22H2

### Additional information

Happens on all versions of Windows - Both Release track and Insider track

**Comment by riverar** [comment]
Not sure what we can do here, PotPlayer is not interacting with Windows audio in the correct manner. You may want to file a bug with them (if possible). I'll close this for now, but feel free to share any other suggestions here.
