### ISSUE TITLE
EarTrumpet changes audio devices on its own

### ISSUE THREAD

**Issue by KapperBear** [File-New-Project/EarTrumpet#1339]
### Summary

I have three audio devices on this Windows 10 PC. Speakers, wireless headset and a VB-Audio Virtual Cable I use to stream music to another location. For years EarTrumpet has worked perfectly for this, but this week it has already twice changed the device from the virtual cable to speakers when music was playing.

### Steps to reproduce

1. I start music playback, for example with Winamp, Tidal, or whatever, and then use EarTrumpet to switch that app to the virtual cable for streaming.
2. Everything works fine for some time, but then EarTrumpet decides to switch the music app output from virtual cable to speakers without me doing anything.
3. I have only been able to fix this by restarting EarTrumpet, the music app, and my stream setup. Simply changing the device back in EarTrumpet does nothing - the audio still comes out of this PC's speakers. And it seemed like the app was showing up twice in EarTrumpet, but one of the entries was doing nothing.

I only noticed the issue this week.

A curious extra detail: both times it happened was when the same song started playing in Tidal. I can't see how that would affect anything, but it was quite a coincidence on such a large playlist.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.19045.2728

**Comment by riverar** [comment]
Be aware Tidal is known broken and could be the culprit here. https://github.com/File-New-Project/EarTrumpet/issues/313 (Nothing has changed recently in EarTrumpet on this front.)

**Comment by riverar** [comment]
Closing this issue as it's not directly actionable, but I associated it with master issue https://github.com/File-New-Project/EarTrumpet/issues/1305 as the unexpected behavior here is related.
