### ISSUE TITLE
foobar2000 appears to have multiple audio sessions but only one is active

### ISSUE THREAD

**Issue by roughnecks** [File-New-Project/EarTrumpet#134]
Title.

Thanks, app is really good.

**Comment by riverar** [comment]
Thanks, does it happen all the time? Playing any type of media? I'll download it now and try to reproduce.

**Comment by roughnecks** [comment]
It happens all the time for me with MP3 and I'm using the desktop App.
Also, if I mute the fake session and restart foobar, it goes back to 100%.

**Comment by roughnecks** [comment]
I just noticed that foobar has got double session in Windows Mixer too... Maybe it's not EarTrumpet's fault, afterall. https://www.dropbox.com/s/lc3udsnqy69qs6j/eartrumpet_vs_winmixer.gif?dl=0
