### ISSUE TITLE
Ear Trumpet Not recognizing Google Chrome.

### ISSUE THREAD

**Issue by xJayByrd** [File-New-Project/EarTrumpet#1346]
### Summary

I cannot use the audio from Chrome because ear trumpet is recognizing it and it is not showing up ear Trumpet open applications sounds list. 

### Steps to reproduce

I don't know

### EarTrumpet version

EarTrumpet 2.2.2.0

### Windows version

10

**Comment by riverar** [comment]
I got a similar report from another Chrome user on Windows 11. @xJayByrd can you verify the app is missing from the official Windows mixer too?

**Comment by IISAKNIFE** [comment]
I am having this issue on firefox developer right now

**Comment by riverar** [comment]
@IISAKNIFE and is it also missing from the windows mixer too?

**Comment by Redsawss** [comment]
> 

I am having the exact same issue with Chrome, this happened shortly after I installed eartrumpet.

**Comment by TheRogue31** [comment]
Same here. I uninstalled it, and now my chrome audio still doesn't work... any ideas?
