### ISSUE TITLE
MS teams reverts to 100% volume at the start of each call despite being set to desired volume. 

### ISSUE THREAD

**Issue by trandall50** [File-New-Project/EarTrumpet#1348]
### Summary

MS teams reverts to 100% volume at the start of each call despite being set to desired volume. Moving the slider during a call is the workaround. 

### Steps to reproduce

Have the slider set to desired volume, start call, notice its 100% despite being set as desired, move slider during call as workaround.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1555

### Additional information

![image](https://user-images.githubusercontent.com/11558845/231838633-794b07c4-5e4b-40fe-a74e-a69b50280b87.png)
![image](https://user-images.githubusercontent.com/11558845/231838664-44d8cbee-2fae-4613-98b1-63b91798d35c.png)
![image](https://user-images.githubusercontent.com/11558845/231838687-e2f27dec-7d9d-44b3-a30a-9bf27084b62b.png)

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/233893282-fae88519-21bd-4e95-9bbe-48739a92233e.png)

Can confirm here with default sound mixer and EarTrumpet. Teams is not respecting the OS values and is overriding them with in-app settings. You'll have to set your desired volume in-app.

Closing as there's nothing to do here but I recommend you file feedback from the Teams app. Be sure to link them to this GitHub issue! `https://github.com/File-New-Project/EarTrumpet/issues/1348`

![image](https://user-images.githubusercontent.com/475132/233893487-35e0b7ed-57c2-4981-a5ab-6e7b05dccec0.png)
