### ISSUE TITLE
EarTrumpet icon not visible when Windows starts

### ISSUE THREAD

**Issue by cbouju** [File-New-Project/EarTrumpet#1353]
When Windows (10) starts, the EarTrumpet icon does not appear in the notification bar.
To make it appear, I have to launch the application from the start menu.

Also, the native Windows sound management icon remains visible all the time :  when Windows starts, and when I launch EarTrumpet from the start menu.

This problem occurs for both the standard and dev versions of EaarTrumpet.

_Originally posted by @cbouju in https://github.com/File-New-Project/EarTrumpet/issues/1086#issuecomment-1514964535_

**Comment by riverar** [comment]
Closing, there's nothing actionable here. (Please fill out the [bug report template](https://github.com/File-New-Project/EarTrumpet/issues/new?assignees=&labels=&template=bug_report.yml) when filing issues!)

Sounds like this is the typical Windows startup tasks bug, please follow these steps: https://github.com/File-New-Project/EarTrumpet/issues/417#issuecomment-566869108.

**Comment by cbouju** [comment]
For information:

After seeing the steps at #417, the EarTrumpet state at Startup remains enabled in the Task Manager, and my registry values are correct.

The only way I found to fix the problem is to create a shortcut in the windows start menu:
`C:\Users\xxxxxxxxx\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)`
with the command line for EarTrumpet:
`explorer.exe Shell:AppsFolder\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne!EarTrumpet`

I don't know if this is the best way, but it works.

**Comment by riverar** [comment]
@cbouju I'm curious, can you try https://github.com/File-New-Project/EarTrumpet/issues/417#issuecomment-537760757

**Comment by cbouju** [comment]
![2023-04-24_075610](https://user-images.githubusercontent.com/13716801/233911253-af925872-949d-43d5-a66e-a2bea432dcaa.jpg)

**Comment by riverar** [comment]
Does it change when you manipulate it via Task Manager?

**Comment by cbouju** [comment]
If I deactivate with Task Manager, then State is changed to 1, UserEnableStartupOne stays at 1.
If I activate with Task Manager, then State change to 2, UserEnableStartupOne stays at 1.

**Comment by riverar** [comment]
Strange, everything seems to be working correctly. Are you sure the app isn't just hiding in the overflow flyout? Does eartrumpet.exe show up in Task Manager?

![](https://user-images.githubusercontent.com/475132/234479212-8ed3e66a-0921-420d-abd0-8a5343425ad0.gif)

**Comment by cbouju** [comment]
Yes, I'm sure the application isn't hiding in the overflow pane.
And eartrumpet.exe does not appear in the task manager.

Although it is present in the startup list: 

![2023-04-26_081054](https://user-images.githubusercontent.com/13716801/234485167-948a21ff-5aea-4c48-b2a9-3ed14e084c3f.jpg)
