### ISSUE TITLE
Groggy Audio

### ISSUE THREAD

**Issue by Zu770** [File-New-Project/EarTrumpet#1354]
### Summary

My friend told me about this hoping it would help with stream audio and I wasnt satisfied with it so I uninstalled it and after I did that all of my audio is now groggy when I open up my streamlabs and frankly it is starting to annoy me because I cant fix it.

### Steps to reproduce

I tired reinstalling it to hopefully fix it and then delete it after I fixed it but i cant seem to figure it out.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1555

**Comment by riverar** [comment]
Hi @Zu770, we don't apply audio effects or anything like that. Try this: Open the Settings app, then go to System > Sound > Volume Mixer. At the bottom, click the Reset button.

Will close this as there's nothing to do here for us. But feel free to keep the discussion going.

**Comment by Zu770** [comment]
I have tried it but right as I open streamlabs it switches to groggy or
muffled like audio, I didnt have this problem till I downloaded the program

**Comment by riverar** [comment]
@Zu770 EarTrumpet only manipulates volume levels using Windows APIs, once it's uninstalled and you hit that reset button, anything EarTrumpet related is gone. Try uninstalling/reinstalling Streamlabs? Or that NVIDIA streaming app? Sounds like an audio sound effect or something.

**Comment by Zu770** [comment]
I have
