### ISSUE TITLE
Levels changing when changing app focus

### ISSUE THREAD

**Issue by tdg063** [File-New-Project/EarTrumpet#1355]
### Summary

If I am listening to music in a browser (Brave) and I change tabs or alt+tab to another app the levels change. When the browser tab playing the sound is focused (active) sound is proper level. Change to another tab level drops. Changing to another app level drops more.

Expected behavior: levels remain unchanged.

### Steps to reproduce

Browser volume level set to 8, speaker level set to 20. Brave Browser version 1.150.121 Chromium version 112.0.5615.138 (Official Build) 64-bit

### EarTrumpet version

2.2.2.0

### Windows version

Win11 OS Build 22000.1817

### Additional information

![image](https://user-images.githubusercontent.com/131539941/233791820-5b59be2a-0a2e-479e-8f61-c511e3ef0bd2.png)

**Comment by riverar** [comment]
Hm, can't reproduce this. Here's what I'm doing:

1. Open Brave 1.50.121
2. Navigate to `https://www.youtube.com/watch?v=MVPTGNGiI-4`
3. Set volume to 8 via EarTrumpet
4. Alt-Tab around the OS/apps (e.g. Spotify, File Explorer, Edge browser, etc.)
5. Observe volume doesn't change

Can you maybe provide a desktop recording with a mixer (Windows or EarTrumpet) open? Or fix my steps above?

**Comment by tdg063** [comment]
I'm surprised you can't reproduce. In further testing I uninstalled Ear Trumpet rebooted and the problem persists.
  

  
I then tested other browsers and discovered this is only happening with Brave and is not an issue with Ear Trumpet.
  

  
Sorry for the false alarm. It seems I need to contact the Brave team.
  

  
Tim
  

  

  

  
  
  
  
  
>

**Comment by riverar** [comment]
Interesting, if you figure out what's causing it let us know. Will close for now but feel free to keep replying.

cc: @jonathansampson for awareness
