### ISSUE TITLE
Legacy mixer by default

### ISSUE THREAD

**Issue by q1k** [File-New-Project/EarTrumpet#1359]
Add an option to use the legacy mixer (legacy components) by default. I would like to save time by not having to click many times to get to it.
And before anyone says that I can just use the other volume mixer I'd like to point out that that design also suffers from the same problem I mentioned in https://github.com/File-New-Project/EarTrumpet/issues/1358. It's basically unusable.

**Comment by riverar** [comment]
Thanks! Feature requests go here https://github.com/File-New-Project/EarTrumpet/discussions/new?category=ideas. Closing this as it's not an issue.
