### ISSUE TITLE
Required Localization for 1.4.5.0

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#136]
We need to translate a What's New block of text for EarTrumpet users prior to releasing 1.4.5.0.

## Text to translate
What's new in EarTrumpet version 1.4.5.0
* The icon in the Notification Area icon has changed and now looks like the one built into Windows 10
* We updated the Notification Area icon for high DPI users
* We improved text rendering on the main window
* Fixed a problem with changes from Windows Volume Mixer not showing in EarTrumpet (e.g. mute)
* Added supported for Simplified and Traditional Chinese (thanks Yue Yin)

[Close]

## Required Languages
- [x] Simplified Chinese
- [x] Traditional Chinese
- [x] German
- [x] French
- [x] Norwegian Bokmål
- [ ] Norwegian Nynorsk
- [x] Russian

**Comment by riverar** [comment]
Adding @yinyue200 @dAr2q @jonstodle @actionthomas for potential help, would be very appreciated!

**Comment by adescre** [comment]
## Text to translate
Changements dans EarTrumpet pour la version 1.4.5.0

- L'icone de la zone de notifications a changée, et ressemble maintenant à celle pré-intégrée dans Windows 10
- Nous avons mis à jour l’icone de la zone de notifications pour les utilisateurs d’écran à haut DPI
- Nous avons amélioré le rendu du texte sur la fenêtre principale
- Nous avons réglé un problème où les changements dans le Gestionnaire de Volume Windows ne se reflétaient pas dans EarTrumpet (exemple : muet)
- Nous avons ajouté le support du Chinois Simplifié et Traditionnel (merci Yue Yin)

**Comment by yinyue200** [comment]
## Text to translate

EarTrumpet 1.4.5 更新内容

* 通知区域的图标现在更加具有 Windows 10 风格
* 我们为高 DPI 的用户更新了通知区域的图标
* 我们改进了本应用主窗口的文本渲染
* 修复 Windows 音量混合器的变化不在 EarTrumpet 中呈现的问题（例如 静音）
* 增加了对简体中文和繁体中文的支持（感谢殷越）

**Comment by riverar** [comment]
@yinyue200 Does this cover both Chinese versions? Or which one?

**Comment by yinyue200** [comment]
@riverar Sorry , I forgot to translate a Traditional Chinese version. Wait a minute.

**Comment by yinyue200** [comment]
## Traditional Chinese

EarTrumpet 1.4.5 更新內容

* 通知區域的圖標現在更加具有 Windows 10 風格
* 我們爲高 DPI 的用戶更新了通知區域的圖標
* 我們改進了本應用主窗口的文本渲染
* 修復 Windows 音量混合器的變化不在 EarTrumpet 中呈現的問題（例如 靜音）
* 增加了對簡體中文和繁體中文的支持（感謝殷越）

## Simplified Chinese

EarTrumpet 1.4.5 更新内容

* 通知区域的图标现在更加具有 Windows 10 风格
* 我们为高 DPI 的用户更新了通知区域的图标
* 我们改进了本应用主窗口的文本渲染
* 修复 Windows 音量混合器的变化不在 EarTrumpet 中呈现的问题（例如 静音）
* 增加了对简体中文和繁体中文的支持（感谢殷越）

**Comment by vzczc** [comment]
Hva er nytt i EarTrumpet versjon 1.4.5.0
Meldingsikonet er endret og ser nå ut som det som er innebygget i Windows 10.
Vi har oppdatert meldingsikonet for brukere med høy DPI.
Vi har forbedret rendering av tekst i hovedvinduet.
Fikset et problem med endringer in Windows volum mikser som ikke ble vist i EarTrumpet (f.eks mute)
La til støtte for Simplified/Traditional kinesisk (takk Yue Yin)

**Comment by swisszeni** [comment]
# German
Was ist neu in EarTrumpet Version 1.4.5.0
- Das Symbol im Infobereich hat geändert und sieht nun aus wie das in Windows 10 eingebaute
- Wir haben das Infobereichsymbol für Nutzer mit hoher DPI aktualisiert
- Wir haben die Textdarstellung im Hauptfenster verbessert
- Beheben eines Problems durch welches Änderungen im Windows Lautstärkemixer nicht in EarTrumpet angezeigt wurden (z.B. stummschalten)
- Unterstützung für vereinfachtes und traditionelles Chinesisch (danke Yue Yin)

**Comment by cH40z-Lord** [comment]
@swisszeni (https://github.com/File-New-Project/EarTrumpet/issues/136#issuecomment-321500448)
> Das Symbol im Infobereich hat geändert und sieht nun aus wie das in Windows 10 eingebaute

You're missing a `sich`:  „Das Symbol im Infobereich hat sich geändert und sieht nun aus wie das in Windows 10 eingebaute”.
An alternative translation would be: „Das Symbol im Infobereich wurde aktualisiert und sieht nun aus wie das von Windows 10”

I personally would prefer the latter as it sounds more natural and not like a direct translation.

Included with the rest of it:

* Das Symbol im Infobereich wurde aktualisiert und sieht nun aus wie das von Windows 10
* Das Symbol im Infobereich erhielt ebenfalls Unterstützung für Monitore mit einer hohe DPI
* Die Textdarstellung im Hauptfenster wurde verbessert
* Ein Problem wurde behoben bei dem Änderungen vom Windows Lautstärkemixer nicht in EarTrumpet angezeigt wurden, z.B. Stummschalten
* Unterstützung für vereinfachtes und traditionelles Chinesisch (danke Yue Yin)

**Comment by swisszeni** [comment]
@cH40z-Lord you're right. Changed it to a easier to read version. As for the rest: I tried prevent diverging too much from the original phrasing.

Oh and you got a typo in 'Das Symbol im Infobereich erhielt ebenfalls Unterstützung für Monitore mit einer hohe DPI'. It should be 'hohen'.

**Comment by moraks** [comment]
I can translate into Russian. Please, add russian lang to 1.4.5.0
____ 
Что нового в EarTrumpet версии 1.4.5.0

Значок в значке области уведомлений изменился и теперь выглядит как стандартный в Windows 10
Обновлен значок области уведомлений для экранов с высоким DPI
Улучшен рендеринг текста в главном окне
Исправлена проблема, из-за которой изменения в микшере громкости Windows  не отображались в EarTrumpet (например, отключение звука)
Добавлена поддержка упрощенного и традиционного китайского языка (спасибо Юэ Инь)

**Comment by riverar** [comment]
@moraks Awesome, thank you very much. Will add that in.

**Comment by riverar** [comment]
Hey guys, need your help again! Would appreciate it! https://github.com/File-New-Project/EarTrumpet/issues/166
