### ISSUE TITLE
app UI need some improvements 

### ISSUE THREAD

**Issue by mehraanakbarii** [File-New-Project/EarTrumpet#1366]
### Summary

1.please replace sliders with new windows 11 look sliders

![image](https://github.com/File-New-Project/EarTrumpet/assets/120687618/888cd2bc-7c27-4402-bd84-779df91bbd8c)

2.please add missing options to windows legacy context menu

![image](https://github.com/File-New-Project/EarTrumpet/assets/120687618/3041d6e7-cd1a-4374-be3f-e86892270745)

3.please change the silent icon position

![image](https://github.com/File-New-Project/EarTrumpet/assets/120687618/97acc765-233f-4f61-b784-bfa7339c047c)

### Steps to reproduce

https://github.com/File-New-Project/EarTrumpet/discussions/1365

### EarTrumpet version

Latest

### Windows version

Latest Windows 10 22H2

**Comment by riverar** [comment]
1. Yep, very aware and am reminded daily. 😔 Microsoft is working on some Windows 11 brushes and styles for WPF so we're currently waiting for that. https://github.com/dotnet/wpf/blob/main/roadmap.md#modernizing-wpf. Alternatively, we may have to rewrite the entire UI stack.

2. The spatial sound request is being tracked via https://github.com/File-New-Project/EarTrumpet/discussions/660; troubleshooters are EOL and will be removed from the OS soon so we bother with that

3. We don't think showing the mute state/icon for every row as a particularly good change, so won't be making this change.

Going to close this for now, but feel free to keep the discussion going. Thanks!

**Comment by mehraanakbarii** [comment]
thank you very much

**Comment by mehraanakbarii** [comment]
a project called volumey using same freamwork (WPF) here is the link of the repo maybe you can find a way to change slider style by help of this repo :
[Volumey](https://github.com/G-Stas/Volumey)

**Comment by mehraanakbarii** [comment]
thanks for your response.
there is a same volume mixer project called volumey that based on same freamwork (WPF) and it has windows 11 style sliders , here is the link of the repo maybe you can find a way to change slider style by help of this :
[Volumey](https://github.com/G-Stas/Volumey)
