### ISSUE TITLE
Some information about Updating UI stuff

### ISSUE THREAD

**Issue by mehraanakbarii** [File-New-Project/EarTrumpet#1368]
### Summary

there is a same volume mixer project called volumey that based on same freamwork (WPF) and it has windows 11 style sliders , here is the link of the repo maybe you can find a way to change slider style by help of this :
[Volumey](https://github.com/G-Stas/Volumey)

![Desktop Screenshot 2023 05 11 - 22 40 12 22](https://github.com/File-New-Project/EarTrumpet/assets/120687618/0a29b478-c46e-4efc-b752-67de834a2a52)

### Steps to reproduce

good luck 

### EarTrumpet version

Latest

### Windows version

Latest Windows 10 22H2

**Comment by riverar** [comment]
Thanks @mehraanakbarii. I think this is using ModernWpf. It's certainly something we can consider. (I haven't tried it yet.) Closing for now as there's no work to track here but feel free to keep the discussion going.
