### ISSUE TITLE
Support for Windows 10 LTSB?

### ISSUE THREAD

**Issue by ookic** [File-New-Project/EarTrumpet#137]
LTSB users have no access to the Windows Store or its apps. Can I create an exe file from the source code still being uploaded here? How can I get updated versions of Eartrumpet on my LTSB machine?

**Comment by riverar** [comment]
You should be able to check out the EarTrumpet repository and compile. May need to unload/remove the AppX and BackgroundTask projects. Let us know how you go!

**Comment by dbap127** [comment]
As a person who has very little compiling experience, how do you do that?

**Comment by ookic** [comment]
+1.
With all my blind effort, I have tried to build Eartrumpet.vs15.sln 1.4.4.0 on VisualStudio 2017, unloading appx and backgroundtask. It's given me countless errors, through blind tweaking this is the closest (or more likely, farthest) i have gotten: 
https://i.imgur.com/5uki0qw.png

This is what it looks like with the default settings of VS17.
http://i.imgur.com/fKkjHqp.png

**Comment by riverar** [comment]
@ookic Looks like you're trying to compile this against a Windows 8.1 SDK, which isn't supported. Must be Windows 10. Are you using Windows 10 to compile this as well?

**Comment by ookic** [comment]
Sorry, that was just me experimenting. This is what it looks like compiled under windows 10:

http://i.imgur.com/laAGwtS.png

**Comment by ookic** [comment]
Okay, I've opened it on Windows SDK 10.0.15063.0 and platform v141
I'm trying to build "EarTrumpet", is this the correct task? 
https://i.imgur.com/wCqhP4t.png
Trying to "release" just brings me to an empty debugging screen.

Honestly I have no idea what I'm doing.

**Comment by riverar** [comment]
@ookic You compiled it successfully, just like the output says. Congrats. 👍

**Comment by riverar** [comment]
The key attribute for Windows 10 LTSB is that features or functionality never change. This is why it doesn't support the Windows Store or any apps delivered via that channel. Therefore, we cannot support that platform.

But you're free to download the code and compile it.
