### ISSUE TITLE
Browser constantly being mutted

### ISSUE THREAD

**Issue by snowbound** [File-New-Project/EarTrumpet#1373]
### Summary

It does not matter whether the web browser is Firefox or Brave but I am constantly having to go in and increase the volume for the browser from 0 to say 45. It will reset itself back to 0 if the browser has to be updated and restarted.

### Steps to reproduce

1.set a volume level for the browser
2. wait till the browser receives an update 
3. restart browser
4. level has been reset back to 0

### EarTrumpet version

2.2.2.0

### Windows version

10.0.19845.2965

**Comment by riverar** [comment]
Very strange. What does sndvol.exe show? Or Start > Settings > System > Sound > Volume mixer? (Windows 11)

**Comment by snowbound** [comment]
It happened again but this time without Brave browser getting an update. Sndvol.exe showed 0 in sndvol.exe. I moved it up to 50 aka halfway and tried playing a YouTube video. No Audio. Checked Ear Trumpet and it was at 1. Moved ear trumpet to 40 and audio was fine. Let me monitor the sndvol.exe the next time this happens and will report back.

**Comment by riverar** [comment]
If it happens in sndvol.exe then this may be something unrelated to EarTrumpet. Unless maybe you're using EarTrumpet Actions (dev builds) by any chance w/ an action run amok? Am looking forward to hearing more!

**Comment by riverar** [comment]
Closing this for now but please feel free to continue the discussion / ping me if we need to revisit.
