### ISSUE TITLE
Sound sources not showing up

### ISSUE THREAD

**Issue by DrPhreek** [File-New-Project/EarTrumpet#138]
Ear trumpet doesn't seem to be picking up sound sources any better than the default windows mixer any more. Using 1.4.4.0, skype doesn't show up, nor does chrome.

**Comment by riverar** [comment]
Are those apps making sound when you check? Quiet apps won't have an active sound session. Also, what OS build/version?

**Comment by DrPhreek** [comment]
Oh, yes, they were making sound--that's why I went to go change their levels! I am running Windows 10 Pro 64-bit, version 1703, build 15063.540.

I just checked again and noticed that chrome shows up now that I have switched the system sound output from Realtek HD Audio 2nd output--which is a usb headphone set--back to the regular back panel output for the speaker system (Realtek High Definition Audio).  This switch is made by clicking on the default windows taskbar sound icon and selecting the playback device from the top of the popup. I can't check skype now, as 1) I am no longer in a call, and 2) I need to use the headset for calls.

**Comment by riverar** [comment]
Ah yes. This is the frustrating "app is using the wrong device" problem. We don't currently support forcing apps to a new audio device, so sometimes they can be stuck on another. If you change the default (right-click EarTrumpet) you will probably see your apps on the other device(s).

**Comment by DrPhreek** [comment]
You are absolutely right! My skype was showing up under a THIRD sound device (necessary for the microphone on the headset, but the speakers for which are on the 2nd sound device). Thank you. At least now I know the volumes will show up somewhere--I will just need to look around when one disappears. Much appreciated!
