### ISSUE TITLE
Sometimes main window will get stuck and not hide when clicking outside of it.

### ISSUE THREAD

**Issue by DCaedus** [File-New-Project/EarTrumpet#1381]
### Summary

Sometimes main window will get stuck and not hide when clicking outside of it.

### Steps to reproduce

Open a game in borderless fullscreen mode.
Open Win Start menu to show the taskbar.
Click on EarTrumpet icon to open it's menu.
Then Click back on open game.
EarTrumpet main window should remain open on top of the game, and even showing the Windows taskbar again and clicking on it won't make EarTrumpet go away.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1702

**Comment by riverar** [comment]
Duplicate/related: https://github.com/File-New-Project/EarTrumpet/issues/311

I have this issue too, personally, with the Grounded game. I'll take another look but last I checked, it's a Windows issue.

**Comment by riverar** [comment]
Steps to reproduce with mostly any non-native notification area icon/context menu:

1. Type the Windows key to open Start
2. While Start is open, right-click a non-native notification area icon (that supports showing a context menu)
3. Click the desktop
4. Observe context menu is "stuck" open

There's nothing we can do here right now. When in this state, EarTrumpet does not have focus (the Shell does). To raise awareness (and priority) please use the Feedback Hub to file an issue. Choose the category `Desktop Environment` and sub-category `Taskbar`. Ensure you include a link to this issue!
