### ISSUE TITLE
RANDOM FREEZE

### ISSUE THREAD

**Issue by FoshunX** [File-New-Project/EarTrumpet#1386]
### Summary

Sometime, out of random. It will freeze my screen when I click it. Often when I am gaming especially with fps game such as VALORANT, it will freeze my screen if I click on it to adjust my volume. It worked fine last year but not this time.

### Steps to reproduce

what?

### EarTrumpet version

2.2.2.0

### Windows version

10.0.19045.3031

### Additional information

got no screenshot.

**Comment by riverar** [comment]
We've had similar reports in the past. There appears to be something seriously wrong with Valorant. If it happens again, please follow the steps here https://github.com/File-New-Project/EarTrumpet/issues/1192#issuecomment-1194163444

https://github.com/File-New-Project/EarTrumpet/issues/1250
https://github.com/File-New-Project/EarTrumpet/issues/1192
https://github.com/File-New-Project/EarTrumpet/issues/1184

Closing for now as there's no work to be completed, but please do keep us informed!
