### ISSUE TITLE
Ear trumpet doesnt stay in its designated area after newest windows update

### ISSUE THREAD

**Issue by precelYT** [File-New-Project/EarTrumpet#1392]
### Summary

Ear trumpet doesnt stay in its designated area after newest windows update . It started doing it after newest windows update

### Steps to reproduce

![image](https://github.com/File-New-Project/EarTrumpet/assets/136735112/1ae2882f-e2ad-424e-aaa4-15add6d89a5c)

### EarTrumpet version

2.2.2.0

### Windows version

21h2

### Additional information

![image](https://github.com/File-New-Project/EarTrumpet/assets/136735112/8b55942c-c57d-477a-9e04-e1172496db6f)

**Comment by precelYT** [comment]
When i open it it only shows half of the window

**Comment by riverar** [comment]
Ah, thanks. We're tracking similar issues via https://github.com/File-New-Project/EarTrumpet/issues/1304

Was this from a machine that just woke up from sleep?

**Comment by precelYT** [comment]
sorry english is not my first language and is there a fix for this issue?

**Comment by riverar** [comment]
@precelYT Not yet. Are you using a laptop?

**Comment by precelYT** [comment]
no im using a pc

**Comment by precelYT** [comment]
nvw it fixed it self after pc reboot

**Comment by riverar** [comment]
@precelYT Thanks we'll fix this as part of #1304
