### ISSUE TITLE
Not all audio application found

### ISSUE THREAD

**Issue by finn-freitag** [File-New-Project/EarTrumpet#1394]
### Summary

Eartrumpet can't find the audio playing applications for my headset, but Windows Sound Mixer can.

### Steps to reproduce

Connect a Headset (JBL Quantum 610 wireless) to the computer via 2.4GHz dongle and play audio. Probably there are other ways to reproduce this bug.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1702

### Additional information

![image](https://github.com/File-New-Project/EarTrumpet/assets/126865059/36439ae8-6525-4d63-bba9-d300c2b038cd)

**Comment by riverar** [comment]
@finn-freitag Which app is missing here?

**Comment by finn-freitag** [comment]
@riverar In Eartrumpet under "Lautsprecher (JBL Quantum 610 Wireless* Game)" (the last speaker) are all application missing that are listed in the Windows Sound Mixer (Systemsound, Firefox, StreamWriter, Spotify, MS Teams, JBL QuantumENGINE). The audio from these apps comes out of this speaker, even if they are not listed there.

**Comment by riverar** [comment]
@finn-freitag Ah I see, thanks. Do you have an APO/special effect enabled? Perhaps Windows Sonic? Dolby? etc?

**Comment by finn-freitag** [comment]
@riverar Thanks for this hint, Windows Sonic was enabled. I disabled and re-enabled it a few times and now it works!

**Comment by riverar** [comment]
@finn-freitag This is ultimately related to a bug we're tracking here https://github.com/File-New-Project/EarTrumpet/issues/1305. When APOs are turned/off, the device or various sessions get invalidated and we don't quite recover properly from that. We'll get that patched up at some point.
