### ISSUE TITLE
NVIDIA GPUs Clocks stuck

### ISSUE THREAD

**Issue by BiRaitBec** [File-New-Project/EarTrumpet#1398]
### Summary

Hello there, here cause i have been using your program for a while and it works greatly for what it is supposed to do.

However i find a major problem  with it and my nvidia gpu.

When i don't use it, the gpu clock are normal at idle, like around 210 MHz on gpu clock and 405 MHz at memory clock on 4070 FE.

As soon as i enable eartrumpeth the gpu clock are stuck at 2475 MHz and 10501 MHz respectively. It seems like eartrumpeth is considered a constant running heavy gpu application, while instead is just an hidden button waiting to be opened once in a day or every 2 days. 

Like even browsers do go to those clocks when opening a new page, but then go back to around idle all the time you stay in it, say twitch or youtube streams and videos.

Is there any way you can fix that or is it on nvidia side to do?

### Steps to reproduce

Checking gpu and gpu memory clocks at idle without eartrumpet in the taskbar, and then with it to see if there is any stuck clocks not considered idle.

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1413

**Comment by riverar** [comment]
Hey @BiRaitBec, this should be fixed as of https://github.com/File-New-Project/EarTrumpet/issues/771. Can you try EarTrumpet ([dev](https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller)) and verify? I'll push out a retail update soon.

**Comment by BiRaitBec** [comment]
I tested your suggested release and indeed fixed the problem, thank you so much, can't wait for the retail update.
