### ISSUE TITLE
Auto focus master volume 

### ISSUE THREAD

**Issue by LennyPenny** [File-New-Project/EarTrumpet#140]
The default windows tray audio control automatically focuses the master volume - this enables you to, for example, use the scroll wheel to control your volume as soon as you click the tray icon. 

Currently with EarTrumped you need to move your mouse over the master volume bar to focus it after you clicked the tray icon to be able to use, for example, the scroll wheel to adjust volume

**Comment by riverar** [comment]
Yep, definitely want to add this in.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

**Comment by stil** [comment]
Was there a regression, because I believe it doesn't work on 2.0.7.0.
I still need to hover mouse over master volume to use mouse scroll.
I'm very used to just clicking volume tray icon and scrolling anywhere to change volume, it would be great to have EarTrumpet work the same way.

**Comment by Petah** [comment]
Yea this doesn't work the same way as the windows one. On the windows one, you can use the mouse wheel when not hovering the menu/icon (i.e. over another window). But EarTrumpet you have to either hover the menu or icon.

**Comment by krasa** [comment]
This is super annoying. Win 10. 

@riverar please reopen
