### ISSUE TITLE
UI Closes on First Click

### ISSUE THREAD

**Issue by mixm1xmix** [File-New-Project/EarTrumpet#1402]
### Summary

When I open EarTrumpet from the tray icon, when I click on a volume slider to adjust it, the UI disappears. I then need to click on the tray icon again, and clicking any slider works as intended.

### Steps to reproduce

Reproducible by clicking into another application, then clicking the tray icon again. This occurred on Windows 10, then on a new PC running Windows 11, even after an app re-install.
![06-28-23-New_Issue_·_File-New-ProjectEarTrumpet_—_Mozilla_F-u9K9D](https://github.com/File-New-Project/EarTrumpet/assets/71462112/2e97a515-f126-4f07-b139-62e66030b6d4)

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1848

**Comment by riverar** [comment]
Strange, can you collect troubleshooting data (in Settings > General > About)? Any other apps customizing windows or dealing with the mouse perhaps?

**Comment by mixm1xmix** [comment]
[tmpC6A5.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/11906562/tmpC6A5.tmp.txt)

log uploaded. the only related apps I use are:
- StartAllBack for Start Menu customization
- SoundSwitch for easy toggle between my stereo speakers and headphones
- SoundLock to limit the maximum volume apps can produce (avoid going deaf from games)

I will try toggling these off for a bit to troubleshoot.

**Comment by mixm1xmix** [comment]
this appears to be 100% due to soundlock.
https://www.3appes.com/sound-lock/

**Comment by riverar** [comment]
@mixm1xmix Interesting! I'll try that out here too.

**Comment by riverar** [comment]
Can confirm its limiter is causing the flyout to close. Will investigate why and see if there's something we can do here.
