### ISSUE TITLE
If you disconect all the playback devices the apps stop showing until a EarTrumpet restart

### ISSUE THREAD

**Issue by xsm2** [File-New-Project/EarTrumpet#1407]
### Summary

If you disconect all the playback devices the programs stop showing until a EarTrumpet restart. Ex:

Headphones connected:
![imagen](https://github.com/File-New-Project/EarTrumpet/assets/32161135/c2039031-7b17-493a-b463-47d54030786c)

Headphones disconected:
![imagen](https://github.com/File-New-Project/EarTrumpet/assets/32161135/cef3b045-80fc-4eeb-afe5-4a7b21a750e4)

Headphones reconected:
![imagen](https://github.com/File-New-Project/EarTrumpet/assets/32161135/2a5a7379-d19d-4b9e-940a-aaf5f415a1f3)

When you restar EarTrumpet the programs show again. 

It's probably related to https://github.com/File-New-Project/EarTrumpet/issues/1400.

### Steps to reproduce

1. Disconect all your playback devices 
2. Reconect any of them

### EarTrumpet version

2.2.2.0

### Windows version

10.0.22621.1848

**Comment by riverar** [comment]
Thanks, yup, we're tracking that via https://github.com/File-New-Project/EarTrumpet/issues/1305.
