### ISSUE TITLE
Forza Horizon 3 suddenly missing.

### ISSUE THREAD

**Issue by dustojnikhummer** [File-New-Project/EarTrumpet#141]
FH3 stopped appearing in EarTrumpet Menu (other UWP apps do) but game volume is still very low (just like I set it last time it was working). Also I just noticed when I enter Spotify (UWP version),it is in ET. But when I alt tab,it vanishes until I exit it and reopen it again.
https://imgur.com/a/Ci0Lo

**Comment by riverar** [comment]
This can happen when the app latches onto the wrong audio device. If you right-click EarTrumpet and change default devices, do you see the app there?

**Comment by riverar** [comment]
I can reproduce this on RS4 17025.

**Comment by riverar** [comment]
Fixed in fd5ef2e, standby for release.

**Comment by riverar** [comment]
Done; 1.5 update in the store.
