### ISSUE TITLE
When opened EarTrumpet won't change volume slider

### ISSUE THREAD

**Issue by niiiksh** [File-New-Project/EarTrumpet#142]
If I change volume other way than with EarTrumpet and it is already opened it won't change volume level and slider won't move. For example I can change volume with multimedia keys on my keyboard or with touchpad gesture but it won't affect indicator on EarTrumpet until I close it and open again. Standard Windows volume control does it right.

**Comment by riverar** [comment]
Yup repeat of #123

**Comment by timtoeruem** [comment]
#123 is done, this can also be closed :)

**Comment by GoldenTao** [comment]
Fixed in 1.5.0.0
