### ISSUE TITLE
Tooltip doesn't update immediately if scroll wheel [...] setting is off

### ISSUE THREAD

**Issue by bachig26** [File-New-Project/EarTrumpet#1427]
### Summary

I'm using the experimental/nightly build version (https://install.eartrumpet.app/dev/EarTrumpet.Package_2.2.2.46_x86.appxbundle) and while using this feature (**Use the scroll wheel to change volume while hovering over the EarTrumpet icon**), I find the function doesn't work properly as expected.

Experienced issues:
1. While scrolling to change volume, the volume level doesn't go below 24%, and I also tried to change by opening the flyout but also can't change it.
2. also while scrolling volume, when the volume is scrolled to say at 76%, and after I move mouse out of the icon and hover over the icon, it automatically changed to 74%.

Note: this bug happened to persistent today, as past 2 days since I have installed this version, it only happened now.

### Steps to reproduce

1. enable the "Use the scroll wheel to change volume while hovering over the EarTrumpet icon".

2. and try to scroll to change the volume by hovering over the icon, and i can experience the issue.

### EarTrumpet version

2.2.2.46

### Windows version

Win 10 22H2 (19045.2364)

**Comment by Tester798** [comment]
I think 2nd bug should be fixed in #1426.
Not sure about the 1st bug, it sounds strange.

**Comment by redactedscribe** [comment]
Using 2.3.0.0 I have unchecked both mouse settings so that the scrollwheel should not affect any volume sliders, but scrolling still adjusts them, even after restarting EarTrumpet.

**Comment by riverar** [comment]
@redactedscribe That's not what this feature is for, see also https://github.com/File-New-Project/EarTrumpet/issues/1431. Sorry for the confusion.

**Comment by riverar** [comment]
Thanks @bachig26, this is queued up for the next update. You should see this go out to dev builds in a few minutes.

**Comment by bachig26** [comment]
> @bachig26 This is typically due to a misbehaving application (probably MPC in this case).

no, it's not just MPC as show in the clip, the tray icon clip was with the Vivaldi browser that i use.

> Try this:
> 
> 1. Restart EarTrumpet
> 2. Reproduce the 24-28% issue
> 3. Collect diagnostics via Settings > General > About
> 4. Attach that here (you may have to zip it up)

and I just removed and re-installed app again with clearing the registry, I'm not seeing this issue now. don't know why and how.
Probably, I'll send you the diagnostics data once I see this issue again.
That's really weird, I should have saved a diagnostics copy before re-installing the app.

**Comment by riverar** [comment]
@bachig26 Ah, thanks for the correction. Weird indeed, feel free to ping me again if it comes up and we'll try to get to the bottom of it.

**Comment by riverar** [comment]
Closing for now, but please ping us again if this occurs again.
