### ISSUE TITLE
Stopped Japanese translation again

### ISSUE THREAD

**Issue by maboroshin** [File-New-Project/EarTrumpet#1429]
### Summary

This issue is recurrent. 2.3.0.0 remains in English. translation has been completed by Crowdin. The pull request is not working again.

![image](https://github.com/File-New-Project/EarTrumpet/assets/41102508/89ea76a5-f1a1-40e4-a07d-bb5cbed9bf2d)

### Steps to reproduce

Open settings in Japanese environment

### EarTrumpet version

2.3.0.0

### Windows version

10

### Additional information

Same problem before: https://github.com/File-New-Project/EarTrumpet/issues/1274

**Comment by riverar** [comment]
Investigating. CrowdIn is showing the following:

![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/b1c4bf6b-fa5c-4007-8962-026eb1328941)
![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/46d170b4-eeb8-475e-903d-72a81f07b942)

I believe sync only occurs if it hits 100%, checking.

**Comment by riverar** [comment]
Fixed in `dev`, will get this out soon. I need to first stabilize the notification area icon, then we can push out updates much faster.

**Comment by maboroshin** [comment]
@riverar : I didn't actually see that string, so it remained untranslated.
I fixed your machine translation. Please approve my translation.
