### ISSUE TITLE
Scroll wheel flyout volume change not being disabled when off

### ISSUE THREAD

**Issue by ctrlcmdshft** [File-New-Project/EarTrumpet#1431]
### Summary

Version 2.3.0.0 the option to "Use the scroll wheel to change volume while the flyout is open" isnt working 

when off and i scroll through the list of items in the flyout it changes volume if using scroll wheel to scroll through the list 

### Steps to reproduce

turn setting off or on and same thing happens when trying to scroll through list it changes volumes 

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22621.2134

**Comment by riverar** [comment]
Hi @ctrlcmdshft, this feature turns on/off the ability to change the master volume using the wheel anywhere on the desktop. It's not designed to prevent scrolling of individual sliders when interacting with the flyout. Hope that helps clarify!

**Comment by redactedscribe** [comment]
> Hi @ctrlcmdshft, this feature turns on/off the ability to change the master volume using the wheel anywhere on the desktop. It's not designed to prevent scrolling of individual app sliders when interacting with the flyout. Hope that helps clarify!

@ctrlcmdshft I was really hoping that this feature _was_ for that because scrolling in the Taskbar Flyout often accidentally changes the volumes of random devices/apps. Never used the desktop feature or even noticed it myself.

**Comment by riverar** [comment]
Fair. Will think about adding an option to ignore the mouse wheel when the flyout is open.
