### ISSUE TITLE
windows 11使用异常情况反馈

### ISSUE THREAD

**Issue by tabkey9** [File-New-Project/EarTrumpet#1437]
### Summary

安装 EarTrumpet  之后，它让我的 Windows 11 失去了某些基本常用的功能。

### Steps to reproduce

【安装 EarTrumpet 之前】
Windows 11系统下，桌面任务栏右下角有三个图标（分别是：WIFI、音量、电池），当鼠标经过时，它们看上去是一个整体，
经过WiFi时会显示我的网络连接情况，鼠标点击时，弹出窗体（其他WiFi信号等信息）
经过音量时，会显示当前音量，鼠标点击时，弹出窗体（调节音量）
经过电池时，会显示当前电量情况，鼠标点击时，弹出窗体（电池相关设置）

【安装 EarTrumpet 之后】
我从微软应用商城安装EarTrumpet之后，（版本2.3.0.0）鼠标点击那三个图标已经没有了反馈。
经过WiFi时会显示我的网络连接情况，鼠标点击时，无响应；
经过音量时，会显示当前音量，鼠标点击时，无响应；
经过电池时，会显示当前电量情况，鼠标点击时，无响应；

### EarTrumpet version

版本2.3.0.0

### Windows version

Windows 11 专业版 22H2 -  Microsoft Windows [版本 10.0.22621.2134]

### Additional information

Sorry, I am from China and I am using Simplified Chinese to provide you with feedback on my usage.

**Comment by riverar** [comment]
Hi @tabkey9,

耳喇叭不会替换控制中心中的图标。它应该显示为一个单独的图标，如下面的屏幕截图所示。
EarTrumpet doesn't replace the icons in the Control Center. It should appear as a separate icon like the screenshot below.

如果您仍然遇到问题，可以录制视频剪辑吗？
If you're still having an issue, can you record a video clip?

谢谢！
Thanks!

![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/c170b551-3ea8-465b-bf7c-ccec32a38a7d)

**Comment by tabkey9** [comment]
谢谢！我上面提到的异常问题可能只会出现在当我第一次安装"EarTrumpet "软件的时候，可能是安装"EarTrumpet "需要重启Windows系统吧！我的Windows系统已经恢复正常了。

Thanks! The abnormal issue I mentioned above may only occur when I first install the "EarTrumpet" software. It may be that installing "EarTrumpet" requires restarting the Windows system! My Windows system has returned to normal.
