### ISSUE TITLE
Quick access to sound control panel

### ISSUE THREAD

**Issue by geotay** [File-New-Project/EarTrumpet#144]
I think adding Sound control panel to the right click context menu for Ear Trumpet would be very useful. Possibly even attaching direct access to the playback properties for each device, I'm primarily looking for quicker/easier option to toggle spatial sound.

**Comment by DGX-Development** [comment]
This would be a great enhancement and very useful.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

**Comment by riverar** [comment]
We looked into Spatial Sound and that's a very quirky one. Let me know if you still want that and we'll re-open and re-target this bug.
