### ISSUE TITLE
The Sandboxie programs clones are taken as one. 

### ISSUE THREAD

**Issue by Ivanoshechka** [File-New-Project/EarTrumpet#1446]
### Summary

A program that has been cloned (or duplicate idk) in Sandboxie counts as one program in EarTrumpet.

![image](https://github.com/File-New-Project/EarTrumpet/assets/88715280/b8b50f5e-e986-4842-b628-5d60445ccaef)

https://github.com/File-New-Project/EarTrumpet/assets/88715280/dcf378af-e755-4e7f-a37b-ae684bbe56e9

### Steps to reproduce

Get [Sandboxie](https://sandboxie-plus.com/).
Run any program.
Open a windows default mixer.
Start turn up or down and see the bug(?).

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19045.3324

### Additional information

Is this a bug at all? Maybe it's just impossible to divide a two program in menu.

**Comment by riverar** [comment]
Hi @Ivanoshechka, we group applications that request to be grouped. Right-click the app/row to show individual apps.

**Comment by riverar** [comment]
Closing as there doesn't appear to be an issue here, but feel free to keep the discussion going.

**Comment by Ivanoshechka** [comment]
Alr, thanks, didn't know. ^^
