### ISSUE TITLE
EarTrumpet is out of sync with Windows mixer volume

### ISSUE THREAD

**Issue by SAWARATSUKI** [File-New-Project/EarTrumpet#1452]
### Summary

The volume set in EarTrumpet is not synchronized with the Windows mixer volume.

If you move the volume bar in EarTrumpet, the volume bar in the Windows mixer will move only about 1/10 of the amount you move.
This means that even if the volume is set to 100% in EarTrumpet, the Windows mixer will show 10%.

For reference, see the bar in Google Chrome.
The volume is different between EarTrumpet and Windows mixer.

This makes the volume heard from the speakers seem lower than usual.

I am having trouble because the sound is quieter than usual.

EarTrumpetで設定した音量はWindowsミキサーの音量と同期しません。

EarTrumpetで音量バーを動かすとWindowsミキサーの音量バーは動かした1/10程度しか動きません。
これによりEarTrumpetで音量を100%にしてもWindowsミキサーでは10%を示します。

参考に、Google Chromeのバーを見てください。
EarTrumpetとWindowsミキサーでは音量が異なります。

これによりスピーカーから聞こえる音量が普段より小さく感じてしまいます。
思っていた以上に音が出ないので困ってしまいます。

![image](https://github.com/File-New-Project/EarTrumpet/assets/64746703/9b74d0c3-f78b-4b98-bf6d-9ee0a8721814)

![image](https://github.com/File-New-Project/EarTrumpet/assets/64746703/328c5871-9d1c-4834-bac9-5d8f1bae0e42)

### Steps to reproduce

1. Open Windows Mixer and EarTrumpet.

2. Move the EarTrumpet bar.

3. The Windows mixer bar will move slightly.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19045.3324

**Comment by riverar** [comment]
Hi @SAWARATSUKI, do you have `Use logarithmic volume scale` turned on perhaps?

![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/415f1c24-d2ef-4a22-82bf-6726db65ba71)

**Comment by SAWARATSUKI** [comment]
> Hi @SAWARATSUKI, do you have `Use logarithmic volume scale` turned on perhaps?
> 
> ![image](https://user-images.githubusercontent.com/475132/265512900-24b16f72-8e5a-49f3-a1dd-520fe21b3e66.png)

Your comment reminded me of the existence of that feature!
It was turned off, but after turning it on and then off again, it now syncs correctly!

Thank you very much!
