### ISSUE TITLE
When I change songs on SoundCloud Windows app the volume goes back to 100

### ISSUE THREAD

**Issue by Cryptikz** [File-New-Project/EarTrumpet#146]
Not sure if this is an easy bug to fix, or if it's just the soundcloud app

**Comment by riverar** [comment]
What version/build of Windows are you running?

**Comment by Cryptikz** [comment]
Windows 10

**Comment by cafehaine** [comment]
run winver.exe (type this in the start menu or in the run dialog using windows + R ) and write the version number that you get from here
![image](https://user-images.githubusercontent.com/11913365/32135038-8fbfd4a2-bbf8-11e7-89ff-80486f7bf908.png)

**Comment by riverar** [comment]
I can reproduce this. Appears to be a Windows bug, will report it up the chain.

**Comment by riverar** [comment]
Filed a bug at SoundCloud on 10/30, ref id: `[SoundCloud] Re: SoundCloud resets volume on next song play`

**Comment by GoldenTao** [comment]
The latest version of the Soundcloud app appears to work correctly, please reopen this ticket if you're still having issues.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue doesn't have any work to be completed so am closing it. Thanks!
