### ISSUE TITLE
wont start, wont start as administrator, no feedback on failure to start

### ISSUE THREAD

**Issue by mrbi11** [File-New-Project/EarTrumpet#147]
new windows 10 laptop, Dell inspiron, macafee anti-virus
If you want more diagnostics email me.
As its free I will answer what i can.
Saw at least one other rating with same issue.

**Comment by GoldenTao** [comment]
Ear Trumpet doesn't have any UI when it starts. Did the icon not show up in the tray area? (or possibly the tray overflow area)

**Comment by riverar** [comment]
@mrbi11 Any follow up on this?
