### ISSUE TITLE
Tooltip off by 2% after scrolling to change volume

### ISSUE THREAD

**Issue by NinelieZ** [File-New-Project/EarTrumpet#1483]
### Summary

After changed volume by scrolling wheel on icon, volume shown is always a 2% mismatch. For example, if you scroll to turn up volume to 20% displayed, and hover mouse on icon again it will show 22%. And turn down to 20% it will be 18%.

### Steps to reproduce

1. Hover mouse on the tray icon.
2. Scroll wheel to 20%.
3. Hover mouse again and check volume.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19044.3693

### Additional information

https://github.com/File-New-Project/EarTrumpet/assets/44182970/ed76eed4-8b50-41ba-aced-9cba0d5624a7

**Comment by riverar** [comment]
Good catch! We'll get that fixed up.

**Comment by riverar** [comment]
Hm, think this is already fixed in `dev`, can you try a dev build @NinelieZ? 
https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

**Comment by NinelieZ** [comment]
There is no issuse with this version. It works perfect now. 🥰
