### ISSUE TITLE
Randomly will not show all Apps

### ISSUE THREAD

**Issue by nickcappy** [File-New-Project/EarTrumpet#1487]
### Summary

Occasionally all apps under a speaker will disappear and I have to restart the application to show them again (ex: when I want to change where my browser is sending the sound to and its not there, I have to restart EarTrumpet to move it). 

### Steps to reproduce

Honestly, have no idea. It seems to be at random. I attached 2 photos: one is prior restarting, the other is after restarting)

![Screenshot 11_25_2023 1_15_17 PM](https://github.com/File-New-Project/EarTrumpet/assets/62626744/57deed20-8e22-421f-81d4-bff94459ee12)
![Screenshot 11_25_2023 1_16_05 PM](https://github.com/File-New-Project/EarTrumpet/assets/62626744/899b860b-d0b2-4189-9a5b-6dadf643f7fd)

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22621.2715

**Comment by riverar** [comment]
This can happen for a number of reasons, like switching users in Windows. We're tracking the work needed to fix the core cause of this via #1305. 

Will close this for now but if you nail down when it happens, let us know here so we can ensure we cover that use case.

Thanks for reporting!
