### ISSUE TITLE
Add ability to see inactive (but present) audio sessions

### ISSUE THREAD

**Issue by Onepamopa** [File-New-Project/EarTrumpet#149]
Hello,

If possible make the application able to display the inactive (but still running) applications so we can adjust volume on them.

Some times for example Metro apps volume or Mozilla Thunderbird volume can be adjusted when initially the applications make sound, but the icons hide after a while.

"Show all" mode on/off should be added.

**Comment by riverar** [comment]
Not sure Windows gives us this information, will take a look.

**Comment by riverar** [comment]
Try this in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp).
