### ISSUE TITLE
AudioDeviceManager.GetDefaultDevice does not use eRole Parameter

### ISSUE THREAD

**Issue by mdovey** [File-New-Project/EarTrumpet#1494]
### Summary

There appears to be a typo in the AudioDeviceManager.GetDefaultDevice code. Whilst the method has a parameter to pass the role of default device returned, this parameter is ignored and the method is hardcoded to always return the eMultimedia role:

    public IAudioDevice GetDefaultDevice(ERole eRole = ERole.eMultimedia)
        {
            try
            {
                var rawDevice = _enumerator.GetDefaultAudioEndpoint(Flow, ERole.eMultimedia);
                TryFind(rawDevice.GetId(), out var device);

I assume that the first line in the try cause was meant to use the parameter rather than a constant, i.e. should be:

                var rawDevice = _enumerator.GetDefaultAudioEndpoint(Flow, eRole);

### Steps to reproduce

N/A

### EarTrumpet version

Current master branch

### Windows version

N/A

**Comment by riverar** [comment]
Hm, I'll have to do some testing, but I believe we did this on purpose. We don't want to retrieve a default audio device that falls into different categories such as eCommunications.

**Comment by mdovey** [comment]
It doesn't make much sense (to me) to have a parameter to GetDefaultDevice which isn't then used in the function. And eRole defaults to eMultimedia so GetDefaultDevice() would always return the eMultimedia device, and to get the eCommunications device you'd have to explicitly call GetDefaultDevice(ERole.eCommunications).

For comparison, its mirror SetDefaultDevice does use the eRole parameter:

        public void SetDefaultDevice(IAudioDevice device, ERole role = ERole.eMultimedia)
        {

   ...snip...

            // Racing with the system, the device may not be valid anymore.
            try
            {
                s_PolicyConfigClient.SetDefaultEndpoint(device.Id, role);

For EarTrumpet, this is somewhat academic as (afaict) the only place GetDefaultDevice is called is in AudioDeviceManager.QueryDefaultDevice:

        private void QueryDefaultDevice()
        {
            TraceLine("QueryDefaultDevice");
            var currentDeviceId = _default?.Id;
            _default = GetDefaultDevice();

which would return the eMultimedia device with or without the proposed change.

However, I'm using EarTrumpet in a StreamDeck+ plugin (https://github.com/ceridwen-com/CeridwenAudioTools) where I do want to get the eCommunications device. Although, it might not be the most efficient way - given I'm importing a lot of EarTrumpet code I don't use - I'd prefer to use the EarTrumpet code directly rather than a fork, given you've already done all the heavy lifting for the (I think still undocumented) required Windows function call. It might be lazy, but it would make it easier for me to incorporate any changes should you need to modify EarTrumpet due to Microsoft breaking something in a future Windows version!

**Comment by riverar** [comment]
That's fair. Let's get that fixed up 👍

**Comment by riverar** [comment]
Fixed in https://github.com/File-New-Project/EarTrumpet/commit/2178d3d94e70349391bd143e6b78250561499933
