### ISSUE TITLE
Acronis software crashes Windows 10 Fall Creators Update when using EarTrumpet

### ISSUE THREAD

**Issue by Grimeton** [File-New-Project/EarTrumpet#150]
Hi,

when running certain Apps like Netflix, Plex or SkyGo, or running certain games from the steam store, going back to the desktop and clicking on the eartrumpet icon in the taskbar, gives me this:

![img_4544](https://user-images.githubusercontent.com/2773919/32133908-8302441e-bbe1-11e7-8fa5-dfd987f4bbbf.JPG)
![img_4563](https://user-images.githubusercontent.com/2773919/32133909-86ee8452-bbe1-11e7-93ea-48e7ea1df9d6.JPG)

It's strange. It's a single click on the icon in the taskbar to get the list of apps and the volume controls. 

Interestingly it happens since I upgraded to 1709 (RS3) of Windows 10 Enterprise X64 N

KR,

G.

**Comment by riverar** [comment]
`virtual_file.sys` isn't a Windows component. Looks like you have a piece of broken Acronis software installed.

**Comment by Grimeton** [comment]
Yeah I googled that too. The problem here is that Eartrumpet is the only piece of software that is able to trigger the bug... So I wonder what causes it....

**Comment by riverar** [comment]
Can you provide the name of the Acronis software you're using and its version? Have you opened an Acronis bug yet?

**Comment by Grimeton** [comment]
It's Acronis True Image 2017 latest build. I already opened a bug with Acronis but haven't got anything back.

I'd debug it, but the machine crashes and goes into blue-screen-mode so no debugging here. 

Another thing is that certain things need to come together to trigger the bug. I think the virtual_file.sys driver is only one of many layered drivers here that is shown. 

Going to verify this tomorrow and will let you know.

**Comment by riverar** [comment]
Great, thanks. Will try to reproduce too.

**Comment by Grimeton** [comment]
@riverar Hi, sorry for the late reply. After removing the virtual_file.sys from the driver stack, everything is back to normal. Acronis couldn't really help so I just removed it. Whatever caused, I don't know.

**Comment by GoldenTao** [comment]
Glad it's working again. We'll make a note in case anyone else hits a similar issue with Acronis.
