### ISSUE TITLE
Some applications show blank white page icon in mixer

### ISSUE THREAD

**Issue by Kazserah** [File-New-Project/EarTrumpet#1503]
### Summary

The program showing a blank icon is foobar2000 v2.0

the normal windows volume mixer shows the icon just fine, it's just a problem with EarTrumpet. 

When this happened in the past with a different program (WebCord), uninstalling/reinstalling EarTrumpet fixed it. But no longer.

### Steps to reproduce

Self explanatory 

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19044.2604

### Additional information

![Screenshot_1](https://github.com/File-New-Project/EarTrumpet/assets/99200664/67ca9ea9-3c50-408e-b6c5-02548c67a26f)

**Comment by zhengyang-lu** [comment]
I also had this issue with foobar2000. I fixed it by updating to the latest version of foobar2000 (2.1.2 as of this comment).

**Comment by riverar** [comment]
Working here with 2.1.2 as well. Will close this for now, but if it happens again, please let us know!

![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/d537242c-b3be-4044-9127-a44ada2173ac)

**Comment by zhengyang-lu** [comment]
The issue reappeared for me. Reinstalling foobar2000 didn't help and it also changed foobar's taskbar icon to the generic white file icon.

I did a little more digging, and came across this guide on clearing Windows' icon cache: https://www.elevenforum.com/t/rebuild-icon-cache-in-windows-11.2049/

I followed option three (along with restarting restarting explorer.exe) and it fixed it for me.
