### ISSUE TITLE
When I adjust the volume of the PotPlayer, EarTrumpt suddenly gets bigger

### ISSUE THREAD

**Issue by tp01-gogogo** [File-New-Project/EarTrumpet#1505]
### Summary

When I adjust the volume of the PotPlayer, EarTrumpt suddenly gets bigger.

### Steps to reproduce

![vokoscreenNG-2024-01-17_13-39-43](https://github.com/File-New-Project/EarTrumpet/assets/111100869/97d9e413-4db1-4d30-bff5-73596f980d4a)

### EarTrumpet version

2.3.0.0

### Windows version

win10 22H2 19045.3930 & win10 LTSC

**Comment by riverar** [comment]
Hey @tp01-gogogo, thanks for the report. We had a similar report here https://github.com/File-New-Project/EarTrumpet/issues/1338. You may want to reach out to PotPlayer for support. Feel free to have them contact us if they need more information / assistance.
