### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Onepamopa** [File-New-Project/EarTrumpet#151]
Hello,

Would it be possible to add "Settings" to EarTrumpet, in which to enable/disable default device switch on right mouse click, and instead only "switch" the applications for the selected output ?

I'm asking because I'm using an audio routing software that requires one device to always be default output and various applications are routed through the external output from that application.

So right now if I want to adjust volume using EarTrumpet, it actually switches the selected output as default prior to displaying the applications volume controls, which breaks the audio routing...

**Comment by riverar** [comment]
I see. You want the ability to control volumes for multiple devices, without setting the default. Got it.

**Comment by riverar** [comment]
You can now redirect apps to other devices with EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp) and let us know how it goes.
