### ISSUE TITLE
Spontaneous crash 0xe0434352

### ISSUE THREAD

**Issue by SorabayashiStudios** [File-New-Project/EarTrumpet#1514]
### Summary

Appears to be encountering a critical exception causing the software to crash and close. In event viewer, I captured the following:

> Faulting application name: EarTrumpet.exe, version: 2.3.0.0, time stamp: 0x64cfe711
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.3693, time stamp: 0x64ee7a9c
> Exception code: 0xe0434352
> Fault offset: 0x0013f932
> Faulting process id: 0x5808
> Faulting application start time: 0x01da4dee09e0de66
> Faulting application path: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.3.0.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 1c03ff26-5321-4607-84c5-33771878fdb1
> Faulting package full name: 40459File-New-Project.EarTrumpet_2.3.0.0_x86__1sdd7yawvg6ne
> Faulting package-relative application ID: EarTrumpet

### Steps to reproduce

I have a handful of applications open, including multiple browser windows and a game. I alt-tabbed to EarTrumpet, and it promptly vanished. I checked the taskbar, and when I moused over EarTrumpet, the icon then suddenly disappeared.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19045.3693

**Comment by riverar** [comment]
@SorabayashiStudios Thanks for the report, not seeing anything in Bugsnag (our error reporting backend). Can you share which game you had open? If you can reproduce it, please let me know and we'll re-open this. Thanks!

**Comment by SorabayashiStudios** [comment]
Ouch, I was hoping the internal bug reporting system would have caught and sent something. That singular item in Event Viewer was the only information I could get about the crash. Unfortunately, I don't think this will be anything remotely plausible to trace or reproduce without more data than just what the Event Viewer has given me.

I had roughly a half dozen firefox windows open, averaging 10 tabs each. Some were simple webpages, others were cloud/live-syncing pages like Google Sheets. The game I had open was Honkai Star Rail, and I had alt-tabbed to Ear Trumpet to lower the game's volume, at which point Ear Trumpet just vanished.

**Comment by riverar** [comment]
Interesting I'll do some testing with the game, thanks. Yeah, looks like Bugsnag has started cutting back on the open source plan and is now throwing my events on the floor.
