### ISSUE TITLE
EarTrumpet Crashing after open any media

### ISSUE THREAD

**Issue by mfrls** [File-New-Project/EarTrumpet#1522]
### Summary

My app is crashing after open any type of media in any app. I have repaired and restore data, uninstall and install again. Probably is windows. I don't know.

### Steps to reproduce

EarTrumpet start with Windows, after open any app of media like Youtube, Spotify, it crashes.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22631.3235

**Comment by riverar** [comment]
Can you find any EarTrumpet events in Event Viewer > Windows Logs > Application?

**Comment by mfrls** [comment]
@riverar 
Hey, i don't know what i am doing, but i have found this files and some of them i cant open.
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/e199af5e-0e3e-4491-9ebc-519f9cbe86bc)
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/068f3157-f882-4c8d-8c3f-dcc73720e428)
[WER.fe47e1fc-0415-4097-9684-b13cd30222c7.tmp.WERInternalMetadata.txt](https://github.com/File-New-Project/EarTrumpet/files/14578985/WER.fe47e1fc-0415-4097-9684-b13cd30222c7.tmp.WERInternalMetadata.txt)
thub.com/File-New-Project/EarTrumpet/assets/163205146/91ac824c-452c-439a-bc9d-dc02100e85e2)

**Comment by mfrls** [comment]
<WERReportMetadata>
<OSVersionInformation>
<WindowsNTVersion>10.0</WindowsNTVersion>
<Build>22631</Build>
<Product>(0x30): Windows 10 Pro</Product>
<Edition>Professional</Edition>
<BuildString>22621.3235.amd64fre.ni_release.220506-1250</BuildString>
<Revision>3235</Revision>
<Flavor>Multiprocessor Free</Flavor>
<Architecture>X64</Architecture>
<LCID>1046</LCID>
<BuildLayers>
<BuildLayer LayerName="22621.1.amd64fre.ni_release.220506-1250" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22631" QfeNumber="3235" IsTopLevel="1" IsChecked="0" BuildStamp="220506-1250" BuildBranch="ni_release" BuildArch="amd64" BuildLab="22621.ni_release.220506-1250" BuildLabEx="22621.1.amd64fre.ni_release.220506-1250"/>
<BuildLayer LayerName="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="3235" IsTopLevel="0" IsChecked="0" BuildStamp="240225-1138" BuildBranch="ni_release_svc_prod3" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod3.240225-1138" BuildLabEx="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138"/>
<BuildLayer LayerName="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="3235" IsTopLevel="0" IsChecked="0" BuildStamp="240225-1138" BuildBranch="ni_release_svc_prod3" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod3.240225-1138" BuildLabEx="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138"/>
</BuildLayers>
</OSVersionInformation>
<ProblemSignatures>
<EventType>MoAppCrash</EventType>
<Parameter0>40459File-New-Project.EarTrumpet_2.3.0.0_x86__1sdd7yawvg6ne</Parameter0>
<Parameter1>praid:EarTrumpet</Parameter1>
<Parameter2>2.3.0.0</Parameter2>
<Parameter3>64cfe711</Parameter3>
<Parameter4>appresolver.dll</Parameter4>
<Parameter5>10.0.22621.3235</Parameter5>
<Parameter6>a42db59d</Parameter6>
<Parameter7>c0000005</Parameter7>
<Parameter8>000173c4</Parameter8>
</ProblemSignatures>
<DynamicSignatures>
<Parameter1>10.0.22631.2.0.0.256.48</Parameter1>
<Parameter2>1046</Parameter2>
<Parameter22>e2a5</Parameter22>
<Parameter23>e2a5934c14e66921972cbe137a4819ff</Parameter23>
<Parameter24>d304</Parameter24>
<Parameter25>d304dbb8eb8f73dfb197b8a0d2dd6102</Parameter25>
</DynamicSignatures>
<SystemInformation>
<MID>4CFBAD81-27B1-4EEF-A78F-07FEDDF3A2C5</MID>
<SystemManufacturer>ASUS</SystemManufacturer>
<SystemProductName>System Product Name</SystemProductName>
<BIOSVersion>1603</BIOSVersion>
<OSInstallDate>1687916189</OSInstallDate>
<OSInstallTime>1601-01-02T23:29:11Z</OSInstallTime>
<TimeZoneBias>03:00</TimeZoneBias>
</SystemInformation>
<SecureBootState>
<UEFISecureBootEnabled>1</UEFISecureBootEnabled>
<PolicyPublisher>{77fa9abd-0359-4d32-bd60-28f4e78f784b}</PolicyPublisher>
</SecureBootState>
<ReportInformation>
<Guid>0309e81a-66e9-4b5e-b0e7-c72c8261192c</Guid>
<CreationTime>2024-03-12T21:38:11Z</CreationTime>
</ReportInformation>
</WERReportMetadata>

**Comment by mfrls** [comment]
[WER.fe47e1fc-0415-4097-9684-b13cd30222c7.tmp.WERInternalMetadata.txt](https://github.com/File-New-Project/EarTrumpet/files/14579008/WER.fe47e1fc-0415-4097-9684-b13cd30222c7.tmp.WERInternalMetadata.txt)

**Comment by mfrls** [comment]
`<WERReportMetadata>
<OSVersionInformation>
<WindowsNTVersion>10.0</WindowsNTVersion>
<Build>22631</Build>
<Product>(0x30): Windows 10 Pro</Product>
<Edition>Professional</Edition>
<BuildString>22621.3235.amd64fre.ni_release.220506-1250</BuildString>
<Revision>3235</Revision>
<Flavor>Multiprocessor Free</Flavor>
<Architecture>X64</Architecture>
<LCID>1046</LCID>
<BuildLayers>
<BuildLayer LayerName="22621.1.amd64fre.ni_release.220506-1250" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22631" QfeNumber="3235" IsTopLevel="1" IsChecked="0" BuildStamp="220506-1250" BuildBranch="ni_release" BuildArch="amd64" BuildLab="22621.ni_release.220506-1250" BuildLabEx="22621.1.amd64fre.ni_release.220506-1250"/>
<BuildLayer LayerName="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="3235" IsTopLevel="0" IsChecked="0" BuildStamp="240225-1138" BuildBranch="ni_release_svc_prod3" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod3.240225-1138" BuildLabEx="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138"/>
<BuildLayer LayerName="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="3235" IsTopLevel="0" IsChecked="0" BuildStamp="240225-1138" BuildBranch="ni_release_svc_prod3" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod3.240225-1138" BuildLabEx="22621.3235.amd64fre.ni_release_svc_prod3.240225-1138"/>
</BuildLayers>
</OSVersionInformation>
<ProblemSignatures>
<EventType>MoAppCrash</EventType>
<Parameter0>40459File-New-Project.EarTrumpet_2.3.0.0_x86__1sdd7yawvg6ne</Parameter0>
<Parameter1>praid:EarTrumpet</Parameter1>
<Parameter2>2.3.0.0</Parameter2>
<Parameter3>64cfe711</Parameter3>
<Parameter4>appresolver.dll</Parameter4>
<Parameter5>10.0.22621.3235</Parameter5>
<Parameter6>a42db59d</Parameter6>
<Parameter7>c0000005</Parameter7>
<Parameter8>000173c4</Parameter8>
</ProblemSignatures>
<DynamicSignatures>
<Parameter1>10.0.22631.2.0.0.256.48</Parameter1>
<Parameter2>1046</Parameter2>
<Parameter22>e2a5</Parameter22>
<Parameter23>e2a5934c14e66921972cbe137a4819ff</Parameter23>
<Parameter24>d304</Parameter24>
<Parameter25>d304dbb8eb8f73dfb197b8a0d2dd6102</Parameter25>
</DynamicSignatures>
<SystemInformation>
<MID>4CFBAD81-27B1-4EEF-A78F-07FEDDF3A2C5</MID>
<SystemManufacturer>ASUS</SystemManufacturer>
<SystemProductName>System Product Name</SystemProductName>
<BIOSVersion>1603</BIOSVersion>
<OSInstallDate>1687916189</OSInstallDate>
<OSInstallTime>1601-01-02T23:29:11Z</OSInstallTime>
<TimeZoneBias>03:00</TimeZoneBias>
</SystemInformation>
<SecureBootState>
<UEFISecureBootEnabled>1</UEFISecureBootEnabled>
<PolicyPublisher>{77fa9abd-0359-4d32-bd60-28f4e78f784b}</PolicyPublisher>
</SecureBootState>
<ReportInformation>
<Guid>0309e81a-66e9-4b5e-b0e7-c72c8261192c</Guid>
<CreationTime>2024-03-12T21:38:11Z</CreationTime>
</ReportInformation>
</WERReportMetadata>`

**Comment by mfrls** [comment]
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/cd0fc180-118e-4026-9ddf-a8ccc9de7207)
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/de16760b-8790-41bb-a984-90d0e0797419)

**Comment by riverar** [comment]
This one is interesting, thanks.

```
Aplicativo: EarTrumpet.exe
Versao do Framework: v4.0.30319
Descricao: O processo foi terminado devido a uma excecao sem tratamento.
Informacoes da Excecao: System.AccessViolationException
em EarTrumpet.Interop.Shell32.SHCreateltemInKnownFolder(System.Guid, Ulnt32, System.String, System.Guid)
em EarTrumpet.DataModel.AppInformation.Internal.DesktopAppInfo .. ctor(Int32, Boolean)
em EarTrumpet.DataModel.AppInformation.AppInformationFactory.CreateForProcess(Int32, Boolean)
em EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSession .. ctor(EarTrumpet.DataModel.Audio.lAudioDevice, EarTrumpet.Interop.MMDeviceAPI.IAudioSessionControl,
System.Windows.Threading.Dispatcher)
em EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSessionCollection.CreateAndAddSession(EarTrumpet.Interop.MMDeviceAPI.IAudioSessionControl)
em EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSessionCollection.EarTrumpet.Interop.MMDeviceAPI.IAudioSessionNotification.OnSessionCreated
(EarTrumpet.Interop.MMDeviceAPI.IAudioSessionControl)
```

If you open File Explorer and type `shell:appsfolder` and ENTER, what happens? Does it show a list of all your applications on the machine?

![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/f4ea7197-7003-4c81-b8af-56ffbee2ea49)
![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/c643e62e-cb4f-4802-b206-7cffdb73d214)

**Comment by mfrls** [comment]
@riverar Yes it open

**Comment by mfrls** [comment]
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/4e241e82-cfe4-4f67-930e-2c829d66a6b3)

**Comment by mfrls** [comment]
sorry for the system in Portuguese

**Comment by riverar** [comment]
@mfrls That's okay. 

1. Remove EarTrumpet
2. Install a development build https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller
3. Let me know if that crashes and we'll add some code to figure this out
4. Thank you for your help!

**Comment by mfrls** [comment]
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/068ade73-9ed8-42cd-aa10-f075bc054e5d)
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/85146a0f-1f59-4187-9c7c-fcd786518977)
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/a134dea0-823a-4ebb-b0bc-30db19c4f064)
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/09b292a4-2eca-41b7-a4ef-61a83ef3561b)
![image](https://github.com/File-New-Project/EarTrumpet/assets/163205146/22731d98-1a79-4011-8dde-3c96c137f5f9)

**Comment by mfrls** [comment]
I don't understand, but i read something about software protection. Windows defender is blocking the app?

**Comment by riverar** [comment]
@mfrls So it crashed again with the development version? That's good. 

I pushed some code to development for you to try.

1. Click here https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller
2. Upgrade to 2.3.0.18, do not launch when ready.
3. Close/Kill EarTrumpet completely if it opened automatically
4. Hold the **LEFT ALT** key on your keyboard and launch EarTrumpet. You can let go of the key when you see the EarTrumpet icon or after about 5 seconds.
5. In File Explorer, type `%temp%` and press **ENTER**.
6. Verify you have a file `EarTrumpetTrace.log`. If not, try steps 3-5 again.
7. Start the media that crashes EarTrumpet.
8. Drag/drop the `EarTrumpetTrace.log` into this GitHub issue.

Thank you!

**Comment by mfrls** [comment]
[EarTrumpetTrace.log](https://github.com/File-New-Project/EarTrumpet/files/14579678/EarTrumpetTrace.log)

**Comment by mfrls** [comment]
`AudioDeviceManager-(Playback) Create
AudioDeviceManager-(Playback) Create Exit
TaskbarIconSource Changed: kind=NoDevice dpi=96 isSysLight=False isLegacy=False
AudioDeviceManager-(Playback) OnDeviceAdded {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}
AudioDevice Create {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}
IconHelper LoadIconForTaskbar C:\WINDOWS\System32\SndVolSSO.dll,125 16x16
AudioDeviceSession Create *SystemSounds {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
FlyoutViewModel ChangeState Hidden
AudioDeviceManager-(Playback) OnDeviceAdded {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}
AudioDevice Create {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}
AudioDeviceSession Create *SystemSounds {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
AudioDeviceManager-(Playback) QueryDefaultDevice
TaskbarIconSource Changed: kind=SpeakerTwoBars dpi=96 isSysLight=False isLegacy=False
IconHelper LoadIconForTaskbar C:\WINDOWS\System32\SndVolSSO.dll,123 16x16
AddonResolver Load
AudioDeviceManager-(Recording) Create
AudioDeviceManager-(Recording) Create Exit
AudioDeviceManager-(Recording) OnDeviceAdded {0.0.1.00000000}.{385d783d-d7d4-4a3b-9cc8-07d86c7d25db}
AudioDevice Create {0.0.1.00000000}.{385d783d-d7d4-4a3b-9cc8-07d86c7d25db}
ProcessWatcher Clear
AudioDeviceSession Create *SystemSounds {0.0.1.00000000}.{385d783d-d7d4-4a3b-9cc8-07d86c7d25db}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
ShellNotifyIcon IsVisible True
App DisplayFirstRunExperience Showing welcome dialog
DialogWindow .ctor
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
AudioDeviceManager-(Recording) QueryDefaultDevice
AudioDeviceSessionCollection AddSession *SystemSounds {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
AudioDeviceSessionCollection AddSession *SystemSounds {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
ImageEx LoadImage 24x24 C:\WINDOWS\sysnative\audiosrv.dll,203
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
DialogWindow Closed
AudioDeviceSessionCollection OnSessionCreated
AudioDeviceSessionCollection OnSessionCreated
DesktopAppInfo Attempting AppID resolve for pid 13040
DesktopAppInfo Attempting AppID resolve for pid 13040
AudioDeviceSessionCollection OnSessionCreated
DesktopAppInfo Attempting AppID resolve for pid 13040
DesktopAppInfo Attempting display name read for AppID Valve.Steam.Client
DesktopAppInfo Attempting display name read for AppID Valve.Steam.Client
DesktopAppInfo Attempting display name read for AppID Valve.Steam.Client
`

**Comment by mfrls** [comment]
I try open steam and crash, but it crash with other apps to

**Comment by mfrls** [comment]
`AudioDeviceManager-(Playback) Create
AudioDeviceManager-(Playback) Create Exit
TaskbarIconSource Changed: kind=NoDevice dpi=96 isSysLight=False isLegacy=False
AudioDeviceManager-(Playback) OnDeviceAdded {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}
IconHelper LoadIconForTaskbar C:\WINDOWS\System32\SndVolSSO.dll,125 16x16
AudioDevice Create {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}
AudioDeviceSession Create *SystemSounds {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
FlyoutViewModel ChangeState Hidden
AudioDeviceManager-(Playback) OnDeviceAdded {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}
AudioDevice Create {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}
AudioDeviceSession Create *SystemSounds {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
AudioDeviceManager-(Playback) QueryDefaultDevice
TaskbarIconSource Changed: kind=SpeakerTwoBars dpi=96 isSysLight=False isLegacy=False
IconHelper LoadIconForTaskbar C:\WINDOWS\System32\SndVolSSO.dll,123 16x16
AddonResolver Load
AudioDeviceManager-(Recording) Create
AudioDeviceManager-(Recording) Create Exit
AudioDeviceManager-(Recording) OnDeviceAdded {0.0.1.00000000}.{385d783d-d7d4-4a3b-9cc8-07d86c7d25db}
AudioDevice Create {0.0.1.00000000}.{385d783d-d7d4-4a3b-9cc8-07d86c7d25db}
ProcessWatcher Clear
AudioDeviceSession Create *SystemSounds {0.0.1.00000000}.{385d783d-d7d4-4a3b-9cc8-07d86c7d25db}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
ShellNotifyIcon IsVisible True
AudioDeviceManager-(Recording) QueryDefaultDevice
AudioDeviceSessionCollection AddSession *SystemSounds {0.0.0.00000000}.{2fd2a16d-4b1e-4d02-b9e4-508b4cb81ea7}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
AudioDeviceSessionCollection AddSession *SystemSounds {0.0.0.00000000}.{ab758034-d6fe-49dc-b0a6-e81babb08b38}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|16%b#
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
ImageEx LoadImage 24x24 C:\WINDOWS\sysnative\audiosrv.dll,203
## BrushValueParser Parse FAILED ## 'ControlLightBackgroundRest/0.5' System.Windows.Controls.Primitives.RepeatButton
FlyoutViewModel ChangeState Opening
WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=65832, Size=[Left=0,Top=1032,Right=1920,Bottom=1080], Monitor=Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1032} Primary=True DeviceName=\\.\DISPLAY1
FlyoutViewModel ChangeState Open
FlyoutViewModel ChangeState Closing_Stage1
FlyoutViewModel ChangeState Closing_Stage2
FlyoutViewModel ChangeState Hidden
FlyoutViewModel ChangeState Opening
WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=65832, Size=[Left=0,Top=1032,Right=1920,Bottom=1080], Monitor=Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1032} Primary=True DeviceName=\\.\DISPLAY1
FlyoutViewModel ChangeState Open
FlyoutViewModel ChangeState Closing_Stage1
FlyoutViewModel ChangeState Closing_Stage2
FlyoutViewModel ChangeState Hidden
AudioDeviceSessionCollection OnSessionCreated
DesktopAppInfo Attempting AppID resolve for pid 11748
DesktopAppInfo Attempting display name read for AppID MSEdge`

**Comment by mfrls** [comment]
it something wrong with my pc?

**Comment by riverar** [comment]
The EarTrumpetTrace log is missing for some reason. Can you email it to `team@eartrumpet.app`? Something might be wrong with GitHub.

**Comment by riverar** [comment]
Perfect, got your logs. Very interesting problem, almost seems like an OS issue. Standby.

**Comment by mfrls** [comment]
Any fix?

**Comment by riverar** [comment]
Sorry for the long delay @mfrls, I just finished a major port to .NET 8+. If you don't mind trying again, I've added additional code to our [dev builds](https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller).

If you could repeat the steps here, that'd be great! https://github.com/File-New-Project/EarTrumpet/issues/1522#issuecomment-1992703859
