### ISSUE TITLE
Does not work with the new Windows Media Player

### ISSUE THREAD

**Issue by Lark8037** [File-New-Project/EarTrumpet#1523]
### Summary

I can set the volume freely while the new Windows Media Player is running, but when I quit the new windows media player and start it again, the volume I set is not recorded and returns to 100%.

### Steps to reproduce

Restart Windows Media Player.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22631.3296

### Additional information

Windows Media Player version 11.2401.2.0

**Comment by riverar** [comment]
Hey there @Lark8037. EarTrumpet does not _save_ volume levels at this time. Windows is supposed to handle this, but it's been broken for years and Microsoft has been unresponsive to my reports. We are tracking this already with https://github.com/File-New-Project/EarTrumpet/issues/1495 so I'll close this one, but thank you for the additional report. Feel free to keep the discussion going here if desired.

You can also try a EarTrumpet dev build (https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller) and set the volume at app startup with EarTrumpet Actions.
