### ISSUE TITLE
Action's App ID uses Install Location which breaks after app upgrades

### ISSUE THREAD

**Issue by GR8Dane604** [File-New-Project/EarTrumpet#1524]
### Summary

Hi. Thanks for this amazing product!

Having trouble with actions frequently breaking for application like MSTeams which are updated often. EarTrumpet is storing the Package InstallLocation which includes the version instead of using something like PackageFamilyName which is persistent from version to version. 

This action works correctly until an update to MSTeams takes place:

        <Actions>
            <BaseAction xsi:type="SetAppVolumeAction">
                <Device>
                    <Kind>Playback</Kind>
                </Device>
                <App>
                    <Id>C:\Program Files\WindowsApps\MSTeams_24033.811.2738.2546_x64__8wekyb3d8bbwe</Id>
                </App>
                <Option>Decrement</Option>
                <Volume>5</Volume>
            </BaseAction>
        </Actions>

New version of MSTeams is released and the action must be updated to work:

        <Actions>
            <BaseAction xsi:type="SetAppVolumeAction">
                <Device>
                    <Kind>Playback</Kind>
                </Device>
                <App>
                    <Id>C:\Program Files\WindowsApps\MSTeams_24046.2809.2757.3796_x64__8wekyb3d8bbwe</Id>
                </App>
                <Option>Decrement</Option>
                <Volume>5</Volume>
            </BaseAction>
        </Actions>

I'm not sure where the App ID is populated from when selected from the list, but if it's from the Package Manager then ideally it should use PackageFamilyName instead of the InstallLocation, (see [Package Family Name is often referred to as a 'version-less Package Full Name'](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/package-identity-overview#package-family-name)). PackageFamilyName for MSTeams is `MSTeams_8wekyb3d8bbwe`

Alternatively a wildcard match would also work if this solution conflicts with other capabilities. App ID could be `C:\Program Files\WindowsApps\MSTeams` and would still work correctly.

Any workarounds for the current version would be great if there is a hidden feature I'm missing.

Thanks!

### Steps to reproduce

1. Create new Action
2. Add a Do Action for an app (Mute/Un-Mute or Set Volume)
3. Save Action
4. Upgrade or downgrade target app version impacting the installation path
5. Action no longer functions.

### EarTrumpet version

2.3.0.16

### Windows version

10..0.22635.3209

**Comment by riverar** [comment]
Yup, that's an oversight on our part, good catch. We just need to do a little more planning work to correct this without breaking older actions, standby!

**Comment by riverar** [comment]
Fixed in a3a0587.

@GR8Dane604 I pushed some changes to the dev branch. You'll probably have to edit that action and re-select Teams but afterwards you should be good to go. Thanks for reporting!

Upgrade: https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

**Comment by riverar** [comment]
Fixed in https://github.com/File-New-Project/EarTrumpet/commit/a3a05877dadcc876e4703db42f6cd52fc9dbecb3.

@GR8Dane604 I pushed some changes to the dev branch. You'll probably have to edit that action and re-select Teams but afterwards you should be good to go. Thanks for reporting!

Upgrade: https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller
