### ISSUE TITLE
chrome not recognized by eartrumpet

### ISSUE THREAD

**Issue by willythestinky** [File-New-Project/EarTrumpet#1525]
### Summary

chrome isnt being recognized by eartrumpet so now for some reason i cant hear chrome at all

### Steps to reproduce

i dont know what this section is for

### EarTrumpet version

2,3,0,0

### Windows version

10.0.22631.3296

### Additional information

![eartrumpet problem](https://github.com/File-New-Project/EarTrumpet/assets/164062225/52c61d07-c73f-45bf-908e-4a9f0724b9af)

**Comment by riverar** [comment]
Hey @willythestinky that's odd, can you right-click EarTrumpet, click EarTrumpet Settings > Collect troubleshooting data, then send that data to `team@eartrumpet.app` (or attach it here). Thanks!

Try also expanding the list, does Chrome appear anywhere else?

**Comment by riverar** [comment]
Just for my notes, not seeing this on 26100.1

![image](https://github.com/File-New-Project/EarTrumpet/assets/475132/b591e265-a118-421d-9304-dafae4cfb3ed)

**Comment by willythestinky** [comment]
Nvm i fixad it

lör 20 apr. 2024 kl. 19:34 skrev Rafael Rivera ***@***.***>:

**Comment by riverar** [comment]
@willythestinky Nice. What did you do?

**Comment by willythestinky** [comment]
i went to the settings > system > sound > volume mixer > reset sound
devices and volumes for all apps to the recommended defaults. And it was
fixed
