### ISSUE TITLE
Ummm unplugged headphones and went on a trip, then couldn't hear sound in game while I was gone. 

### ISSUE THREAD

**Issue by zderp** [File-New-Project/EarTrumpet#1527]
### Summary

So I suspect this might be an ear trumpet issue. I use headphones with my laptop and set up valorant to play sound through my headphones only. I went on a trip and didn't take my headphones, and wasn't able to get the game to play sound through my speakers despite doing my best looking at the sound options and changing things. Now that I'm back I plug in my headphones and sound works through my headphones. I tried uninstalling ear trumpet while I was gone and just using windows sound controls with no luck 

### Steps to reproduce

ugh FML 

### EarTrumpet version

I had the beta, and installed it recently but not sure now because uninstalled it. 

### Windows version

10.0.19045.4170]

**Comment by riverar** [comment]
@zderp Likely a core Windows issue. Try this: Open the Settings app, then go to System > Sound > Volume Mixer. (On Windows 10, this may be Advanced sound options > App volume and device preferences.) Find and click the Reset button.

**Comment by zderp** [comment]
That fixed it. Thanks
