### ISSUE TITLE
Feature request: Pick audio output per application

### ISSUE THREAD

**Issue by tobbi007** [File-New-Project/EarTrumpet#153]
Today many programs are web based. Google Music, Amazon Music etc. There is still no proper way to route my audio from chrome to my av-receiver without changing the default audio device.

I recently found this:
https://github.com/audiorouterdev/audio-router

It is able to route chrome audio to another audio device, however the UI is really bad.

Are you planning a similar feature for EarTrumpet?

**Comment by Onepamopa** [comment]
I'm using CheVolume, the UI is a bit better, but overall - the app is still buggy. Support is non-existent (I have ticket open for 15 days without answer). I actually regret purchasing the app...

If EarTrumpet provides routing functionality I'm willing to pay to use it.

**Comment by GoldenTao** [comment]
We've been discussing this one. So far we don't plan on doing it, but it's still on our list to re-discuss again later.

**Comment by Onepamopa** [comment]
I hope you decide to implement routing, it'd be awesome !

**Comment by somefriggnidiot** [comment]
+1 for imitating the functionality of AudioRouter.

**Comment by MrBagginsTV** [comment]
Yeah that feature really would be awesome. Also it would for example help (Twitch etc.) streamers who also use Voicemeter Banana so they can set up their sounds even better.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
