### ISSUE TITLE
Programs do not appear when bluethot speakers/headphones are connected

### ISSUE THREAD

**Issue by JozefBarquero** [File-New-Project/EarTrumpet#1533]
### Summary

When I connect my headphones via Bluethot the Ear Trumpet mixer comes out empty, by this I mean that none of the programs that are playing audio are shown.
Every time this happens to me I have to exit and restart Ear Trumpet.
I am currently using it together with the FxSound program and at the beginning I thought it was a problem of incompatibility between the two programs, but even though I uninstalled FxSound it still happens to me.

### Steps to reproduce

- Connect bluetoht headphones or any new audio device 

### EarTrumpet version

2.3.0.0

### Windows version

 10.0.19045 N/D Compilación 19045

**Comment by riverar** [comment]
Hey @JozefBarquero, yup. Aware of this one, sorry about that. Tracking it via master issue https://github.com/File-New-Project/EarTrumpet/issues/1305. Will close this one and prioritize fixing, thanks for the report!
