### ISSUE TITLE
Devices list gets shifted up if taskbar is set to hide...

### ISSUE THREAD

**Issue by serv01** [File-New-Project/EarTrumpet#1534]
### Summary

If Windows start taskbar is set to automatically hide, EarTrumpet list (if larger then screen resolution height) just shifts up and can not see the top device. If taskbar is always shown, list list is shown normally.

### Steps to reproduce

Automatically hide or always shown start taskbar from taskbar settings.

### EarTrumpet version

2.2.0.0

### Windows version

10.0.19045.4170

### Additional information

Taskbar auto hide: ![RDUYk1fsAc](https://github.com/File-New-Project/EarTrumpet/assets/552451/eb538bcd-7e40-46e4-8745-dbebd99f0f08)
Taskbar always visible: ![ALeCbLcw1a](https://github.com/File-New-Project/EarTrumpet/assets/552451/011b9925-9308-4270-b84e-7575c4018ea6)

**Comment by serv01** [comment]
It seems with new 2.3.0.0 version it works normally, when I posted this post no new version was detected over winget.

**Comment by riverar** [comment]
Strange, we posted 2.3 to winget 8 months ago https://github.com/microsoft/winget-pkgs/tree/master/manifests/f/File-New-Project/EarTrumpet/2.3.0.0

**Comment by serv01** [comment]
With 2.3 version it works normally but neither winget or chocolatey would
not find update for some reason untill yesterday 🤔.

Anyway sorry for taking your time, have an amazing day 😁, byee.
