### ISSUE TITLE
shows this after reboot or startup

### ISSUE THREAD

**Issue by User3254548** [File-New-Project/EarTrumpet#1537]
### Summary

idk look at the screenshot

### Steps to reproduce

restart windows???

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19045.4291

### Additional information

![Screenshot 2024-04-12 202550](https://github.com/File-New-Project/EarTrumpet/assets/118598934/bfbb366d-a3c7-48af-b4a1-ddb28cb5fe31)

**Comment by riverar** [comment]
Hi @User3254548, this is a Windows issue sadly. It appears to show up when application _licenses_ from the Store expire or the machine doesn't have internet access for a while. (See also: https://github.com/File-New-Project/EarTrumpet/issues/1063)

If you continue to have this issue, maybe try installing via Chocolatey or another method (https://github.com/File-New-Project/EarTrumpet?tab=readme-ov-file#install).

Closing for now as there's nothing else we can do here. But feel free to keep the discussion going.
