### ISSUE TITLE
电脑关机后，重新起动其他软件，EarTrumpet 2.3.0.0未能记录之前调节其他软件音量大小，而是直接以音量100%出现，需要手动调节，希望作者能够添加记录之前软件音量。

### ISSUE THREAD

**Issue by zgwsww** [File-New-Project/EarTrumpet#1539]
### Summary

电脑关机后，重新起动其他软件，EarTrumpet 2.3.0.0未能记录之前调节其他软件音量大小，而是直接以音量100%出现，需要手动调节，希望作者能够添加记录之前软件音量。

### Steps to reproduce

电脑关机后，重新起动其他软件，EarTrumpet 2.3.0.0未能记录之前调节其他软件音量大小，而是直接以音量100%出现，需要手动调节，希望作者能够添加记录之前软件音量。

### EarTrumpet version

EarTrumpet 2.3.0.0

### Windows version

 10.0.22000.2538

**Comment by riverar** [comment]
EarTrumpet 不保存音量级别。 Windows 应该可以处理这个问题，但它已经被破坏了很多年，而且微软对我的报告没有回应。我将关闭这个问题； 我们已经通过#1495 跟踪了这一点。 谢谢你！

---

EarTrumpet does not save volume levels. Windows is supposed to handle this, but it's been broken for years and Microsoft has been unresponsive to my reports.

I will close this issue; we are tracking this already with #1495. Thank you!

**Comment by riverar** [comment]
您还可以尝试 EarTrumpet Actions (https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller) 并在启动时设置音量。

---

You can also try EarTrumpet Actions (https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller) and set the volume at startup.
