### ISSUE TITLE
Multiple Windows shell experience host 

### ISSUE THREAD

**Issue by tntxdirtnasty** [File-New-Project/EarTrumpet#154]
in my ear trumpet list. there is 20 of these, Windows shell experience host icons. I'm on windows 10 home, version 1709 build 16299.19
![image](https://user-images.githubusercontent.com/33791159/32984360-eb274168-cc6a-11e7-8d24-16ed44ee126f.png)
![image](https://user-images.githubusercontent.com/33791159/32984362-fd8d2430-cc6a-11e7-8c4c-cfbc2b97a82f.png)
![image](https://user-images.githubusercontent.com/33791159/32984367-084f0e74-cc6b-11e7-9d26-6f3eb539a1db.png)

**Comment by riverar** [comment]
Yikes, that's terrible.

**Comment by GoldenTao** [comment]
Any idea on how we can try to reproduce this one? Was there something happening on your PC at the time?

**Comment by tntxdirtnasty** [comment]
Not sure, seems like every time i get a different notification on my pc another one comes up. still happens now also have multiple sliders for apps one that does nothing and one that controls volume

**Comment by GoldenTao** [comment]
Thanks for the extra detail. We have some changes coming in a future version that might help with this, on our test pc's that notification app doesn't duplicate, but hopefully the new version will sort it.

**Comment by tntxdirtnasty** [comment]
Hey goldenTao just letting you know that sense the previous update to eartrumpet that this bug is still occurring on my pc not sure if anyone else is getting it but i still have multiple of those when i get new notifications on my pc. 
![image](https://user-images.githubusercontent.com/33791159/34453143-b220ac48-ed11-11e7-9beb-fee376d3ef44.png)

**Comment by GoldenTao** [comment]
Thanks for letting us know, we'll keep looking into it.

**Comment by riverar** [comment]
We made a bunch of grouping behavior changes in EarTrumpet 2.0, try it out. You can grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
