### ISSUE TITLE
Main volume slider delay

### ISSUE THREAD

**Issue by Hulayki** [File-New-Project/EarTrumpet#1547]
### Summary

When I open the EarTrumpet volume slider, it always starts with a delay. It comes back after about 5-10 seconds, but only for the main volume slider. I didn't have this problem with the Windows base slider, but as I noticed, all the volume controls from the third party were delayed. I don't think it's the fault of the program, I'd just like some advice on how to fix it, if it can be fixed.

### Steps to reproduce

- I open the EarTrumpet volume control panel
- (Just) the main volume slider responds to the volume controlling with a delay

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22631.3527

### Additional information

https://github.com/File-New-Project/EarTrumpet/assets/97475801/1ca5c268-cfdd-408e-8927-e7d4fcafda73

**Comment by riverar** [comment]
Interesting, please right-click EarTrumpet > EarTrumpet Settings > Collect troubleshooting data, then provide that here or email it to `team@eartrumpet.app`. Thanks!

**Comment by Hulayki** [comment]
Here is the temp file: 
[tmp47EC.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/15160227/tmp47EC.tmp.txt)

I found out that if there is always a sound source from the background, it works fine and this is the result: 
[tmpB54C.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/15160229/tmpB54C.tmp.txt)

It must be some kind of Windows bug, because it also happens with the Windows default volume control, only when using Ctrl + scroll on the taskbar to change the volume.
