### ISSUE TITLE
not showing correct volume on icon hover

### ISSUE THREAD

**Issue by Bazixv13** [File-New-Project/EarTrumpet#1552]
### Summary

the volume is not shown correctly while hovering over the ear trumpet icon with in the system tray

### Steps to reproduce

When you hover over the Ear Trumpet icon in the system tray and increase the volume using the scrollbar (twice), the on-hover text displays an incorrect volume level—it's either two steps too quiet or two steps too loud than the actual volume

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19045.4291

### Additional information

![image](https://github.com/File-New-Project/EarTrumpet/assets/83003002/f41d8d4d-b87e-4e89-816e-0c4a072dc9e5)

**Comment by riverar** [comment]
Think we fixed this already in `dev` builds (https://github.com/File-New-Project/EarTrumpet/issues/1483), can you verify that for us?

You can download a dev build via https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller.

Thanks!
