### ISSUE TITLE
EarTrumpet not responding, potential PotPlayer issue

### ISSUE THREAD

**Issue by vertigo220** [File-New-Project/EarTrumpet#1555]
### Summary

Just had an app that's normally turned down by ET make a loud noise, so checked on ET and clicking on the tray icon didn't show the pop-up/flyout. Right-clicking also did nothing. Totally unresponsive. Killed and relaunched it multiple times, each time the same thing. Refuses to do anything.

### Steps to reproduce

Not sure. It just randomly stopped working.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.19045.4291

**Comment by vertigo220** [comment]
~2 hours later and I came back to my computer after being off of it for 15-20 minutes to find ET's flyout showing, and it's fully responsive now, which allowed me to grab troubleshooting info and email it.

**Comment by vertigo220** [comment]
And it became unresponsive again, this time with the flyout showing but it stopped responding then turned white. I ended the task when it asked, then relaunched it, and now it's doing what it was doing earlier, with the tray icon not responding at all.

**Comment by riverar** [comment]
Hm, initial indications seem to point to PotPlayer changing their audio session from inactive/active every **100 milliseconds** or so, which is a little nuts.

We've had other reports of PotPlayer generally misbehaving:
https://github.com/File-New-Project/EarTrumpet/issues/1338
https://github.com/File-New-Project/EarTrumpet/issues/1505

I'll see if there's anything we can do on our end to improve the situation.

**Comment by riverar** [comment]
I emailed the PotPlayer team. For now, will close this one.
