### ISSUE TITLE
Sound settings appear on the wrong monitor

### ISSUE THREAD

**Issue by LordLioath** [File-New-Project/EarTrumpet#1559]
### Summary

When clicking on the speaker icon in the taskbar, the flowout window will appear and then move to another window and clip off the screen.

### Steps to reproduce

Click Speaker for Ear Trumpet

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22631.3672

**Comment by riverar** [comment]
@LordLioath That's not good. Is this from a system that was restored from sleep (e.g. laptop) by any chance?

**Comment by riverar** [comment]
Closing as duplicate of #1304.
