### ISSUE TITLE
Please add volume mixer and device settings in right-click menu

### ISSUE THREAD

**Issue by duk6046** [File-New-Project/EarTrumpet#157]
After 1.5.0.0 update, icon is became same as default mixer. So I hope to add those(device, sound, etc..) thanks

**Comment by brendonlamb** [comment]
yeah, def the only thing from stopping me using EarTrumpet exclusively is the missing "plackback/recording device" menu option.

Excellent work otherwise, this is light years ahead of the stock windows mixer/icon

**Comment by kleinbub** [comment]
Even better would be having directly a device selector within the eartrumpet panel.
In my activity I need to switch often between different devices, and having to open the playback/recording tabs every time is really a hassle. Having everything on the same panel would be a killer feature.
Thank you so much for your exciting work!

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

**Comment by brendonlamb** [comment]
Installed, awesome.

**Comment by duk6046** [comment]
Big update! thanks
