### ISSUE TITLE
Windows cannot access the specified device... - After December Cumulative Update win10

### ISSUE THREAD

**Issue by SilentPrayeCG** [File-New-Project/EarTrumpet#159]
![image](https://user-images.githubusercontent.com/17825684/33607108-aeb8b818-d9e1-11e7-9c23-ce16ff3c1953.png)
After December Cumulative updates...

It's can be something with permissions, because MSI installers start complaining too
(as example LibreOffice installer says he can't create shortcuts, i changed permissions for start menu folder, and it installer stop give me error about it)
I guess it starts after december patch.

In ear trumpet case i don't know with which folder i should messing around.

**Comment by GoldenTao** [comment]
It sounds like you have a bigger issue with your PC. You can try reinstalling EarTrumpet, but I doubt that will fix the issue. You have plenty of free hard drive space?

**Comment by SilentPrayeCG** [comment]
Not very plenty. You want to suggest me recreate my windows account?)
I know something wrong, and i can't find any reason for it except latest patch.

**Comment by GoldenTao** [comment]
Not entirely sure. You could give a new user account a go, possibly rolling back that update if you definitely know that was the cause?

**Comment by SilentPrayeCG** [comment]
I can try to uninstall update, but when i last time tried do this, my OS just stop working at all.
I better will not try it again...

But i try recreate account i think, i made backup of files already, anyway.

**Comment by SilentPrayeCG** [comment]
I deleted my account, and created it again. Now works fine, only confusing that is icon is same as from default windows mixer... And general volume slider is glitchy.
