### ISSUE TITLE
Windows 11 Quick Settings Flyout Volume Slider is not Synced Properly with EarTrumpet's Volume Sliders.

### ISSUE THREAD

**Issue by AngusAranda** [File-New-Project/EarTrumpet#1596]
### Summary

In Windows 11, when I use the Microsoft built in Quick Settings (Windows Key + A) System Volume Settings, where when you click on the Speaker icon in the Taskbar Notification Area and you get a little overview of a bunch of Windows Settings like Brightness, BlueTooth, Wifi, Airplane Mode, Night Light, etc.; that Volume Slider is not Synced with what EarTrumpet's Volume Sliders display.

I would actually like to see if I can fix this myself.

I have an introductory level of knowledge about programming and code & a very broad fundamental understanding of how it works across a handful of languages and if I can get pointed into the right direction: I can look at the source, build, test, and then make a pull request if / when I get it.

I'm trying to learn even more about coding, and from what Thor (@PirateSoftware) & @ThePrimeagen always say is: Don't read the Manual of how to program. Just start a project and learn what code you need to make the program work. In the process of learning how to make that project work: you will learn how to code.

### Steps to reproduce

1.) Install Windows 11.
2.) Install EarTrumpet from the Microsoft Store.
3.) In the lower right hand corner of your Windows 11 installation, click on the Speakers icon that shows you the Windows Quick Settings, or hold the Windows Key and then press A to bring up the Flyout Floating Panel.
4.) Adjust the Volume Slider, usually the very bottom Slider
5.) Click on EarTrumpet's Speaker icon in the Windows Taskbar Notification Area
6.) Notice how the 2 Volume Sliders are not properly Synced.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.27686.1000

**Comment by riverar** [comment]
Both features use the same APIs, so I'm a bit suspicious of the cause here--this is likely an OS bug. Can you maybe record a video demonstrating the issue? Is this a Bluetooth device by any chance?

**Comment by AngusAranda** [comment]
https://github.com/user-attachments/assets/fdc7d3f4-70ef-4392-9d3e-0e139f7063cc

It looks like using the Community Setting: Logarithmic Volume Scale was causing the issue.

However, I had tried disabling that option and re-enabling it, testing it to see if maybe that was causing the issue and before I made this post I was still having that out of sync issue.

At least it works without it checked, but I guess when it is checked, it can still cause out of sync issues or that setting just might need some attention :D

**Comment by riverar** [comment]
Enabling the Use Logarithmic Volume option will result in mismatching sliders, because Windows doesn't support showing logarithmic values. More context and an interesting article about all this can be found here: https://github.com/File-New-Project/EarTrumpet/pull/228#issuecomment-1505791859

So with this off, is everything behaving as expected now?

**Comment by AngusAranda** [comment]
Sorry for the delay, yes: right now it's working, even though in previous tests it wasn't working.

I'll keep logarithmic volume disabled.

I guess this can be closed.
