### ISSUE TITLE
The audio from certain apps is not audible, while others are distorted.

### ISSUE THREAD

**Issue by joytekko** [File-New-Project/EarTrumpet#1605]
### Summary

when i open any type of game the game audio is heard with a terrible quality and distorted, while, apps like spotify the audio is not heard and, if i try to change the spotify output it comes back to being heard but with an incredibly terrible quality and distorted. i tried to reset the audio settings from windows but nothing, i tried to delete eartrumpet, but nothing. i don't know how to fix it, help me because i'm losing patience <3. anyway i use jbl bluetooth headphones

### Steps to reproduce

I simply downloaded the app, opened a game and accidentally put it in another audio setting and immediately after put it back in the default one, where it sounded fine at first, and then the problem arrived.

### EarTrumpet version

2.3.0.0

### Windows version

19045.4894

**Comment by joytekko** [comment]
the default is (jbl tune 720bt stereo) ,  the second where the audio is distorted is " cuffia auricolare jbl tunes 720bt Hands-free ag audio"

**Comment by joytekko** [comment]
I'm joking hahaha, now that I opened discord I can't hear any application, but if I put them in the other setting I can hear the apps again but in a distorted way and with a bad audio. IM losing patience. how can I reset all the settings!. it doesn't work uninstall the app

**Comment by riverar** [comment]
Hey @joytekko, sounds like a Bluetooth audio device? Or an audio device that has multiple outputs? This area is undergoing some changes in Windows and is wonky.

If you ever find yourself in a weird state, open the Settings app, then go to System > Sound > Volume Mixer. At the bottom, click the Reset button.

**Comment by joytekko** [comment]
I did It already 7 times, doesn't work. And there's another problem, when I
use discord I can't hear any other apps

Il sab 14 set 2024, 19:14 Rafael Rivera ***@***.***> ha
scritto:

**Comment by joytekko** [comment]
I'm losing patient, because I did NOTHING and I deserve this for this f***
app. You have to repair this.

Il dom 15 set 2024, 18:34 Fran ***@***.***> ha scritto:

**Comment by joytekko** [comment]
ear trumpet put all the audio from the microphone of my headphones,
detecting my microphone as the audio output (jbl earphones), not allowing
the audio to reach my headphones (jbl stereo). I find it impossible to
solve the detection problem and remove my microphone from the output
settings, also because if I try to move the audio to JBL stereo the audio
cannot be heard, it is detected but I don't hear anything. help

Il dom 15 set 2024, 19:00 Fran ***@***.***> ha scritto:

**Comment by riverar** [comment]
If you already went to Settings > System > Sound > Volume Mixer and clicked the Reset button, then I'm afraid this is not an EarTrumpet issue but rather an OS issue. (You can verify this by uninstalling EarTrumpet.)

Closing this for now but feel free to keep the discussion going.
