### ISSUE TITLE
Left clicking the tray icon, will open the volume mixer in an independent floating window, not as a flyout/pop up directly above the tray icon.

### ISSUE THREAD

**Issue by DCaedus** [File-New-Project/EarTrumpet#1610]
### Summary

At times, when left clicking on EarTrumpet's tray icon, the volume mixer will open in an independent window, floating on it's own away from the tray and windows task bar, not as a flyout directly above EarTrumpet's tray icon.
I am unsure if there are other factors affecting this, seems to happen at random.
I tried to replicate the bug by left clicking the tray icon again and again but was unsuccessful, it occurs to me perhaps the bug only occurs when EarTrumpet is left alone and not used in a while, or the first time using it after Windows has suspended or turned on.

### Steps to reproduce

Left click on EarTrumpet's tray icon.
Left clicking the tray icon a second time will close the floating window and left clicking it again will open the volume mixer as a pop up as intended.
I tried to replicate the bug by left clicking the tray icon again and again but was unsuccessful, it occurs to me perhaps the bug only occurs when EarTrumpet is left alone and not used in a while, or the first time using it after Windows has suspended or turned on.

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22631.4169

**Comment by riverar** [comment]
Hi @DCaedus, are you using any other shell enhancement apps that could be interfering with the system tray? Maybe an app that provides an alternate taskbar or puts the tray on multiple displays?

**Comment by DCaedus** [comment]
I am using StartAllBack.

**Comment by riverar** [comment]
Ah yeah, it's likely a SAB bug. I can take a peek in October when I'm free but you may want to file a bug on the SAB side as well. Happy to work with their developers if needed.

**Comment by DCaedus** [comment]
Ah gotcha, I will try to send a bug report to them definitely, I don't see any option to do so in their website.. So I suppose I will have to dig around a bit.
I appreciate your commitment, but EarTrumpet and SAB are 2 apps I love and can't live without :)

**Comment by DCaedus** [comment]
This is what happens in case anyone else gets this bug
![Snipaste_2024-09-29_02-51-24](https://github.com/user-attachments/assets/26e31a37-bc3a-4a46-b5a3-26cde71d3bc3)

**Comment by DCaedus** [comment]
It happened again yesterday, even tho I disabled StartAllBack.
![Snipaste_2024-10-01_12-23-22](https://github.com/user-attachments/assets/eaa1d487-fd4f-4c83-a377-b2d56259b2e8)

**Comment by riverar** [comment]
Closing as we're tracking with the master issue, feel free to keep the discussion going.
