### ISSUE TITLE
EarTrumpet won't open

### ISSUE THREAD

**Issue by Jonfer999** [File-New-Project/EarTrumpet#1616]
### Summary

The app's simply not opening, I already tried reinstalling it multiple times (uninstall with windows configurations, microsoft store and revo uninstaller; install with microsoft store, winget and dev version), but nothing changed. When I try opening the app, it creates a proccess in the "details" tab on task manager that stays for ~3 seconds and then vanishes, and I already checked that the app is enabled on startup via task manager 

### Steps to reproduce

Opening the app

### EarTrumpet version

Latest, can't check

### Windows version

10.0.19045.5011

**Comment by riverar** [comment]
Can you find any EarTrumpet events in Event Viewer > Windows Logs > Application?

**Comment by Jonfer999** [comment]
Yes, I opened the event viewer and tried opening the app, which netted me 2 errors and 1 information logs. I'm attaching them on this answer (I wanted to attach it as .evtx, but github doesn't support it so i compressed and did it with a .zip)
[EarTrumpet Events.zip](https://github.com/user-attachments/files/17452366/EarTrumpet.Events.zip)

**Comment by riverar** [comment]
I see.

```
Informações da Exceção: System.TypeInitializationException
   em EarTrumpet.App.set_HasIdentity(Boolean)
   em EarTrumpet.App.OnAppStartup(System.Object, System.Windows.StartupEventArgs)
   em System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
[...]
```
Some sort of Windows (AppModel) bug is surfacing up; sounds like your Microsoft Store or Store apps are not healthy. Anything unusual happening on this machine? Or any customization software installed?

Alternatively, you can try alternate installation methods listed here to rule out the Microsoft Store https://github.com/File-New-Project/EarTrumpet?tab=readme-ov-file#install

Let me know how it goes!

**Comment by Jonfer999** [comment]
Nothing really exceptionally weird happening. I had some lag with the Xbox app yesterday and had to reinstall LoL the day before, but no issues with those apps today.
I tried resetting the Microsoft Store with both cmd and wsreset.exe, and with powershell(admin)

Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

And

Get-appxpackage -all *shellexperience* -packagetype bundle |% {add-appxpackage -register -disabledevelopmentmode ($_.installlocation + “C:\Program Files\WindowsApps\Microsoft.Windows.ShellExperienceHost_1.0.0.2_neutral_ShellExperienceHost.laac0539cc_8wekyb3d8bbwe\AppxManifest.xml”)}


The app’s still not opening. I already tried sideloading with winget, but I don’t really know how to do it with chocolatey to test it that way

**Comment by riverar** [comment]
Try downloading https://packages.chocolatey.org/eartrumpet.2.3.0.nupkg, rename to .zip, and just extract it into a folder somewhere on disk. Run EarTrumpet.exe. I presume that works great.

**Comment by Jonfer999** [comment]
Managed to solve the issue by (re)installing .NET Framework via microsoft's site, since the windows update couldn't catch the need for an update (but did one after the installation)

**Comment by riverar** [comment]
Thanks for following up @Jonfer999!
