### ISSUE TITLE
Windows Subsystem for Android

### ISSUE THREAD

**Issue by TheMeq** [File-New-Project/EarTrumpet#1618]
### Summary

EarTrumpet does not split the audio for multiple Windows Subsystem for Android windows being open with different apps. They are treated as one app and the volume is adjusted for all of them rather then on a window basis. 

### Steps to reproduce

Using Windows Subsystem for Android, launch an Android app. Then, launch another Android app alongside it. Instead of EarTrumpet displaying individual volume controls for each Android app, only one appears that controls the volume for both apps. 

### EarTrumpet version

2.3.0.0

### Windows version

10.0.22631.4317

**Comment by riverar** [comment]
Windows doesn't split the streams either, so I don't think this is possible without a lot of WSA integration work. And WSA is on the way out (end of life) so that's not likely to happen.

Closing for now as there's no work to be done here, but please keep the discussion going!

**Comment by Leggyweggy** [comment]
can confirm this! WSA only gives one volume slider in the regular windows settings sound mixer.
