### ISSUE TITLE
Keep the new icon

### ISSUE THREAD

**Issue by eagleeyez** [File-New-Project/EarTrumpet#162]
Hi,

Great app, just please continue to improve it by adding the options on the default volume icon so we can hide it and keep EarTrumpet only...

**Comment by evlsmurf** [comment]
Give us the option to choose the old or new icon. I go into the sound setting too much to have both of the icons looking the same.

**Comment by FreeER** [comment]
Just updated for me (first restart in awhile, bsod lol) and the first thing I'm doing is trying to figure out how tf I'm supposed to know which is which without testing the d* thing every time, especially when windows doesn't seem to let you hide the "real" sound icon. ffs.

**Comment by paulcee** [comment]
If you change the icon so that it's no longer actually an ear trumpet, perhaps you should rename the app too. It would be strange if the "Notepad" app icon was a quill pen, for example, or if "folders" in Explorer were shown as filing cabinets. Metaphor usage should be consistent to help the user.

**Comment by GoldenTao** [comment]
We'll definitely be keeping the new icon by default as it adds missing tray icon functionality if you have turned off your default volume icon.

The latest version in the store has an option to change back to the original EarTrumpet icon if someone needs to do that.
