### ISSUE TITLE
When I use Redmi Buds 4(Wireless headphones), Mixer don't work

### ISSUE THREAD

**Issue by Deykii** [File-New-Project/EarTrumpet#1624]
### Summary

For some reason its not showing up, but when I use wires headphones, it works
![image](https://github.com/user-attachments/assets/5d701128-f10a-479a-94cd-c2a0f27b0309)
Here's the Windows' mixer
![image](https://github.com/user-attachments/assets/f61ecc18-7d73-4016-8f04-08d9eb29c1a8)

### Steps to reproduce

I just use wireles headphones

### EarTrumpet version

2.3.0.0

### Windows version

Edition: Windows 11 Home; Version: 24H2; OS build: 26100.2161; Experience: Windows Feature Experience Pack 1000.26100.32.0

**Comment by riverar** [comment]
Does restarting EarTrumpet after the buds are connected fix the issue? Might be related to another issue.

**Comment by Deykii** [comment]
> Does restarting EarTrumpet after the buds are connected fix the issue? Might be related to another issue.

Yeah, it helpped, thank you!!!
