### ISSUE TITLE
Speaker Icon inside EarTrumpet doesn't update with the sound volume

### ISSUE THREAD

**Issue by ElvenSpellmaker** [File-New-Project/EarTrumpet#163]
Hey,

Firstly thanks for this programme, it's excellent. =)

One thing I've found is that the speaker icon within the Ear Trumpet menu doesn't update with the sound volume like the notification icon now does:
![image](https://user-images.githubusercontent.com/2286713/33741382-f9295c02-db9b-11e7-8bc0-5829feb3bbc7.png)

As you can see the sound is on 8 but the icon shows a full speaker. The default mixer does this:
![image](https://user-images.githubusercontent.com/2286713/33741411-293a2908-db9c-11e7-9ce0-8828b95bd8c8.png)

**Comment by riverar** [comment]
Now fixed in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
