### ISSUE TITLE
Icon Tooltips are 'root' exe names (Inconsistency)

### ISSUE THREAD

**Issue by ElvenSpellmaker** [File-New-Project/EarTrumpet#164]
Hey,

This is an inconsistency between the names of the programmes in the tooltips and what's shown in the Default Mixer.

For example Skype For Business is shown as `lync.exe` in EarTrumpet:
![image](https://user-images.githubusercontent.com/2286713/33741624-0bb4d922-db9d-11e7-8e4d-f4cf11b4c2d0.png)

But it's shown as `Skype For Business` in the Windows Default Volume Mixer:
![image](https://user-images.githubusercontent.com/2286713/33741643-1fb6ecc6-db9d-11e7-8390-6976250e4478.png)

I'm not sure how I feel because sometimes it's nice to know the root exe that's causing the sound!

(An idea would be to have something like `Skype For Business (lync.exe)`)

**Comment by riverar** [comment]
@ElvenSpellmaker Can you re-test this in 2.0? Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

**Comment by riverar** [comment]
Feel free to re-open this issue if it's still wrong.
