### ISSUE TITLE
[EarTrumpet & 2.3.0.0] - Unable to type with the letters that are set as shortcuts.

### ISSUE THREAD

**Issue by Michellehdr** [File-New-Project/EarTrumpet#1640]
### Summary

[EarTrumpet & 2.3.0.0] - Unable to type with the letters that are set as shortcuts.

### Steps to reproduce

1. Deploy the latest build and update it.
2. Update Microsoft Store.
3. Install EarTrumpet. 
4. Launch the app.
5. Click on Settings
6. General - Shortcuts
7. Set come keyboard shortcuts with letters, eg. q, a, z.
8. Open any text editor, eg. Notepad.
9. Type any general text and observe.

Unable to type with the letters that are set as shortcuts.

### EarTrumpet version

2.3.0.0

### Windows version

1.10.26120.2494

**Comment by riverar** [comment]
Hey @Michellehdr,

Thanks for filing a bug. I can't reproduce this on 27754.rs_prerelease.2411115-1409 (canary). Can you send me an ISO or MSU for 26120.2494 to test against? Are you using normal mouse/keyboard input? Can you provide a video? I'm on the Redmond campus if you'd like to show me in person as well.

Email: `rafael@withinwindows.com`

https://github.com/user-attachments/assets/92d86455-861f-4d7f-9eb6-3bd08a38ec98

**Comment by Michellehdr** [comment]
@riverar from the video you attached, seems like not all Repro steps are performed. It only shows the shortcut keys are set in the app settings. To reproduce the issue you may need to continue with the Repro steps: open text editor, eg. Notepad, type text and observe the issue. Could you please try with it?

**Comment by riverar** [comment]
Oh, that's expected. These are system-wide shortcuts. If the user sets a shortcut key to `Z`, they will not be able to type `Z` into Notepad without invoking EarTrumpet.

Thanks for reaching out.

**Comment by Michellehdr** [comment]
Got it. Thanks for your quick response
