### ISSUE TITLE
Localization Needed for 1.5.2.0

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#166]
We need help translating some text for our context menu item that will allow users to fallback to using the old EarTrumpet icon an upcoming release.

## Text to translate
- Use EarTrumpet Icon

## Required Languages
- [x] Simplified Chinese
- [x] Traditional Chinese
- [x] German
- [x] French
- [x] Norwegian Bokmål
- [ ] Norwegian Nynorsk
- [x] Russian
- [x] Italian

Thank you for the help!

**Comment by adescre** [comment]
* Utiliser l'icône EarTrumpet

**Comment by haefele** [comment]
German: EarTrumpet Icon verwenden

**Comment by Craftuser5000** [comment]
Russian: Использовать иконку EarTrumpet

**Comment by pablojim99** [comment]
Isn't Spanish needed? Just in case: "Utilizar el icono de EarTrumpet"

**Comment by vzczc** [comment]
Norwegian Bokmål: Bruk EarTrumpet ikonet

**Comment by yinyue200** [comment]
Simplified Chinese：使用 EarTrumpet 图标
Traditional Chinese：使用 EarTrumpet 圖標

**Comment by Simizfo** [comment]
Italian: "Usare l'icona di EarTrumpet"

**Comment by GoldenTao** [comment]
Thanks all, this version is now in the store!

**Comment by riverar** [comment]
@Simizfo @yinyue200 @vzczc @pablojimpas @Craftuser5000 @haefele @adescre Could definitely use your help for EarTrumpet 2.0. This time we're trying a collaborative editing platform https://osqwaxf.oneskyapp.com/admin/project/dashboard/project/146899

**Comment by vzczc** [comment]
There is no entry for Norwegian bokmål (the mail language in Norway), I will not venture into translating Norwegian Nynorsk, but you could safely just use Norwegian Bokmål and then someone with more intimate knowledge of NN could correct that.

Let me know when you have added NB and I can provide that.

Øystein
