### ISSUE TITLE
latest microsoft store version is broken, no longer starts

### ISSUE THREAD

**Issue by mailinglists35** [File-New-Project/EarTrumpet#168]

**Comment by mailinglists35** [comment]
i see the process version 1.5.1.0 in task manager but i see no systray icon

**Comment by riverar** [comment]
Are you still seeing this issue? What build of Windows are you on?

**Comment by mailinglists35** [comment]
heh. you changed the icon to match native windows icon. so confusing! it actually works, but it's kind of confusing to see two identical volume icons (and I want to see ALL icons so I cannot hide the windows native icon)

**Comment by riverar** [comment]
Fair enough. We're adding the ability to restore the old icon shortly. Stay tuned.
