### ISSUE TITLE
System Sounds sometimes going down to 0% (and Discord and other apps rarely resetting to 100%)

### ISSUE THREAD

**Issue by ShadowySchemer** [File-New-Project/EarTrumpet#171]
I don't really know how or when this happens, seems to happen at random. I have noticed however that the System Sounds reset more often when I activate a PS4 controller plugged into my computer (I have a separate program to make it work on PC). I can't really make out why this happens. My PC defaults all sounds to my headphones, although I'm not sure that matters.

**Comment by moraks** [comment]
@ShadowySchemer Reset sound Volume Level for " Windows Shell Experience Host" and some other UWP app to 100% is main bug of EarTrumpet. Although, it should be noted that the source of this problem in Windows imperfections... When you  plugged PS4 controller into computer -  " Windows Shell Experience Host" is activated for notify and resets sound settings.

**Comment by ShadowySchemer** [comment]
Ah, I see. I'd still like to notify that I have my controller plugged in all the time, in which case it'd be the program that I use along the controller that's likely at fault.

**Comment by riverar** [comment]
Hey @ShadowySchemer @moraks are you still seeing this issue? Can you provide repro steps? Do I just need to lower the Shell Experience Host volume and plug in a PS4 controller?

**Comment by ShadowySchemer** [comment]
It seems to happen at random, although I haven't seen it happen lately, which adds to the randomness, as I haven't unplugged my PS4 controller or added or removed any programs lately.

**Comment by riverar** [comment]
Closing this bug because it's stale. We released EarTrumpet 2.0 which may have resolved this issue for good. Give it a try (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp).
