### ISSUE TITLE
AMD drivers attempt to load incorrect image in EarTrumpet process

### ISSUE THREAD

**Issue by equin0x80** [File-New-Project/EarTrumpet#173]
I am using Win 10 Pro 64-bit. Windows Update recently changed my ATI graphics driver and messed up my display (black margins at sides of monitor). I was able to fix it by reverting to an older driver; however, I am now getting this error from Ear Trumpet, even before I log in. (After clicking OK to the same error several times, Ear Trumpet then works fine; but same errors occur on next boot.) No other app is giving errors.

"EarTrumpet.exe - Bad Image. c:\windows\system32\aticfx32.dll is either not designed to be run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f."

**Comment by riverar** [comment]
Can you zip up/attach that file here? (drag/drop) Looks like ATI's driver is hooking into our app and trying to load a bad dll. Have you tried installing the latest drivers from AMD? http://support.amd.com/en-us/download

**Comment by equin0x80** [comment]
[aticfx64.zip](https://github.com/File-New-Project/EarTrumpet/files/1557518/aticfx64.zip)
Here's the file. (Maybe delete it later; copyrights...) Installing the latest drivers causes problems with my display, as I mentioned above; so I'm having to stick with the old one.

**Comment by riverar** [comment]
Got it and removed, thanks.

**Comment by riverar** [comment]
This is an AMD/ATI issue; their drivers are trying to load a 64-bit library into our process. You need to upgrade to the latest drivers, sadly.

**Comment by equin0x80** [comment]
Thanks. Is there any chance that reinstalling Ear Trumpet afresh would sort this out (since I had E.T. installed prior to the driver changes that caused the problem)?

**Comment by riverar** [comment]
Sadly, no. This seems to be widely reported and affects all apps/games, not just us. You might be able to turn off AMD's ReLive feature -- or anything similar that allows for app recording or provides an "overlay". 

Perhaps create an AMD issue too: http://www.amdsurveys.com/se.ashx?s=5A1E27D23A3DE979
