### ISSUE TITLE
EarTrumpet Crashes apon screen saver close

### ISSUE THREAD

**Issue by Sn34k** [File-New-Project/EarTrumpet#174]
My app constantly crashes after i wake the pc from screensaver, 

It functions normal during usual usage but once screensaver activates the app crashes and give a error window that it must close. Anyone have this issue.

Next time it does crash, ill post a screen shot. 

Also i'm on Win10 Pro x64

**Comment by Sn34k** [comment]
![earclose](https://user-images.githubusercontent.com/32299517/34031160-68d5fa3e-e1b3-11e7-821e-e6e83c812327.JPG)

**Comment by riverar** [comment]
Which screensaver? What version of EarTrumpet are you on? (right-click the icon in the notification area)

**Comment by Sn34k** [comment]
1.5.1.0

**Comment by riverar** [comment]
@Sn34k Is this still happening?

**Comment by Sn34k** [comment]
Ah sorry i forgot all about this, no its not happening anymore. But only issue i've noted was that when i'm adjusting volumes for the progs. The sliders move in a odd rate. Meaning when i slide them higher or lower the slider moves at its own rate as i adjust the volume. Then finally stops at the desired volume. Not sure if this is caused by this program or another conflicting program. i'll keep you posted for further updates.

**Comment by riverar** [comment]
Yep, aware of that one. Tracking via https://github.com/File-New-Project/EarTrumpet/issues/187, thanks for following up! I'll close this one.
