### ISSUE TITLE
Add Chinese Store Description

### ISSUE THREAD

**Issue by yinyue200** [File-New-Project/EarTrumpet#177]
Store Description for Simplified Chinese:
```
EarTrumpet 是一个用于传统和 Windows 应用商店应用的音量控制应用。
```
Store Description for Traditional Chinese:
```
EarTrumpet 是一個用於傳統和 Windows 應用商店應用的音量控制應用。
```

Thanks

**Comment by riverar** [comment]
@yinyue200 Our text has changed, if you could update the description, that'd be great!

**Comment by yinyue200** [comment]
Simplified Chinese: EarTrumpet 是一款功能强大的 Windows 音量控制软件

Traditional Chinese: EarTrumpet是一款功能強大的Windows音量控制應用程序
