### ISSUE TITLE
Changing Soundcloud volume doesn't work

### ISSUE THREAD

**Issue by ChristoferMinestar** [File-New-Project/EarTrumpet#178]
Since SoundCloud uses a weird system for playing music (has 2 sliders in EarTrumpet that only change bass and treble not volume) it doesn't work with SoundCloud, but it *might* a SoundCloud bug because SoundCloud for Windows 10 is in beta.

**Comment by riverar** [comment]
Can you still reproduce this @ChristoferMinestar ?

**Comment by riverar** [comment]
![soundcloud](https://user-images.githubusercontent.com/475132/39224831-03e18e98-47fe-11e8-8e92-59c79c210024.gif)

This is insane. Reaching out to SoundCloud.

**Comment by riverar** [comment]
SoundCloud refuses to communicate with me, and this bug *still* exists.

**Comment by ChristoferMinestar** [comment]
Still known bug... Have they tried fixing this or even responded yet? I switched to a JS wrapper over the website just to use it individually, and they app is great.

**Comment by riverar** [comment]
SoundCloud hasn't responded at all. I don't know how to reach anyone there.

**Comment by GoldenTao** [comment]
Duplicate of #146
