### ISSUE TITLE
Skip, pause and back skip don't work after launching EarTrumpet.

### ISSUE THREAD

**Issue by ChristoferMinestar** [File-New-Project/EarTrumpet#179]
Skip, pause and back skip don't work after launching EarTrumpet on a Dell XPS 15 9550. They don't work again until after a cold boot.

**Comment by riverar** [comment]
Can you confirm those controls work if you disable EarTrumpet startup? We don't do anything that would cause this, so am a little suspicious.

**Comment by riverar** [comment]
Closing this bug because we can't reproduce this. But give EarTrumpet 2.0 a try, it may have fixed your issue. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
