### ISSUE TITLE
Multiple instances of Firefox appear in EarTrumpet

### ISSUE THREAD

**Issue by PM0792** [File-New-Project/EarTrumpet#180]
Hi there,

EarTrumpet creates multiple instances of Firefox.

Upon starting up Firefox, three instances are created.

![firefox1](https://user-images.githubusercontent.com/20652141/34703287-42bd9112-f546-11e7-8b6a-201144abaa24.png)

For each new tab, an additional instance is created.

![firefox2](https://user-images.githubusercontent.com/20652141/34703288-42f26ebe-f546-11e7-8bc5-64ed92db67b4.png)

Windows 10 Home
Version 1709
OS Build 16299.125

Firefox 57.0.4 (64-bit)

Thanks.

**Comment by ChristoferMinestar** [comment]
Firefox has separate processes per tab, I believe.

**Comment by Rictusempra** [comment]
same for problem on 58.0b16.

>Firefox has separate processes per tab, I believe.

Yes, in about:preferences#general, scroll to `Performance`, uncheck `Use recommended performance settings`. Now you can set content process limit, just like this
![image](https://user-images.githubusercontent.com/16912240/34901523-666a9350-f846-11e7-8755-a407f39d33b5.png)

**Comment by adavier** [comment]
This is a Firefox issue that also occurs in the default windows volume mixer. 
It is summarised in bug id [1358372](https://bugzilla.mozilla.org/show_bug.cgi?id=1358372) I believe.

**Comment by riverar** [comment]
Fixed in future Firefox 60 release https://bugzilla.mozilla.org/show_bug.cgi?id=1358372#c45 currently scheduled for March 13 beta, May 9 release. Feel free to re-open if this issue reoccurs no sooner than March 13.
