### ISSUE TITLE
Unhandled exception when Shell_TrayWnd is not an AppBar

### ISSUE THREAD

**Issue by dremin** [File-New-Project/EarTrumpet#181]
When the EarTrumpet notification area icon is clicked, the application has an unhandled exception if Shell_TrayWnd is not an AppBar. When this is the case, the AppBarData returns a rect with all sides 0, so size calculations in MainWindow.UpdateWindowPosition() attempt to place the window in an invalid position.

Ideally the fallback would be for the window position to be calculated based on the mouse pointer position passed to the window procedure when the icon is clicked.

This issue is exposed by running alternative shells such as Cairo Shell (which creates a Shell_TrayWnd window that is not an AppBar). For more context and the exception output [please see this issue](https://github.com/cairoshell/cairoshell/issues/77).

**Comment by riverar** [comment]
This is a Cairo appcompat bug, marking it as an enhancement request. It's insane to write specialty code for a third-party... shell.

**Comment by dremin** [comment]
While I agree, this is possible to run into without third party shells. For example, if Explorer is not running or has lost its appbar.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
