### ISSUE TITLE
Change volume with scroll on tray icon

### ISSUE THREAD

**Issue by FeBe95** [File-New-Project/EarTrumpet#184]
Would it be possible to add an option to be able to change the master volume while hovering the tray icon and scrolling up and down? Or maybe an option to position the master volume always at the lowest position, so it is easier to locate it every time and without having to move the mouse cursor all the way up to the top of the list. Or maybe I am just lazy ;)

**Comment by Silver2410** [comment]
We're all lazy after all; moving the cursor a bit doesn't take all that effort but I'm crossing my fingers to have this feature available since some time by now :3

**Comment by madefordeveloping** [comment]
+1
Master volume should be selected by default.

**Comment by riverar** [comment]
We support opening EarTrumpet with a hotkey and scroll-to-change wherever the mouse is when the fly-out is open. Give that a shot! Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

**Comment by madefordeveloping** [comment]
Congratulations with the update.
Thank you for listening to user feedback/suggestions.
It works great now. Thank you.
