### ISSUE TITLE
Enhancement: Audio Routing Capability

### ISSUE THREAD

**Issue by BearTM** [File-New-Project/EarTrumpet#188]
Fantastic per-app control of volume!

EarTrumpet would would be doubly amazing if the audio output could also be (dynamically) routed on a per-app basis. This is especially useful for apps like Groove Player which do not allow you to specify the "desired" audio device and/or to easily switch devices on the fly (i.e. switching to headphones from speakers, etc.). If the last specified route per application can also be retained, then specific applications could automatically be routed to the correct audio output on startup.

An example project which implements this type of functionality is AudioRouter:
https://github.com/audiorouterdev/audio-router

If this audio routing capability can be integrated into EarTrumpet (i.e. right-click on the app icon to select the desired output device, and optionally set a "use device as default"), that would be incredible!

**Comment by do-bo** [comment]
I came here to recommend this enhancement :) Although it would probably about double the complexity of this project, EarTrumpet would become an all-in-one application for sound control on Windows.

**Comment by dmwyatt** [comment]
Unless I'm misunderstanding the request, this is built in to  Windows 10 now.

https://www.hanselman.com/blog/AutomaticallyChangeYourAudioInputOutputAndVolumePerApplicationInWindows10.aspx

(Not that eartrumpet couldn't improve on it, I'm sure)

**Comment by riverar** [comment]
And is in EarTrumpet 2.0, to be released soon.

**Comment by BearTM** [comment]
Seriously? That was fast!!! Much appreciated, and I'm looking forward to the update/upgrade.

And with the shout out from Hanselman today about the merits of EarTrumpet ... your announcement and adding of this (missing) functionality will force him to rewrite his 1-day old blog post. Maybe you should let him know his wishes have already been answered?

**Comment by riverar** [comment]
I reached out to Scott, he's on board the 2.0 beta train now 🎉

**Comment by do-bo** [comment]
This is great news! I was happy to see that this will be a new functionality in the April update, but MS made it into a cumbersome experience buried in the Settings app, so I'm sure EarTrumpet will improve upon this :) Thanks!

**Comment by riverar** [comment]
If you would like to put audio redirection through its paces, email me your Microsoft Account (`rafael@withinwindows.com`) and I'll put you in the beta. We could definitely use more eyeballs on that area.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
