### ISSUE TITLE
EarTrumpet raises timer resolution in background

### ISSUE THREAD

**Issue by Wuestengecko** [File-New-Project/EarTrumpet#189]
# Observed behaviour

EarTrumpet requests a timer resolution of 1ms, even when it is just sitting in the background and not showing anything (except, of course, the tray icon).

# Expected behaviour

While sitting idle, the platform timer resolution should not be changed at all.

# How to reproduce

1. Start EarTrumpet. Let it sit in the system tray, and don't open the widget.
2. Open a command line (cmd.exe) as Administrator
3. Run `powercfg -energy duration 5`. This will analyze your system's energy efficiency for 5 seconds, and then generate an HTML report in the current directory.
4. Open the generated report in a browser and see that, under the "Warnings" category, there is EarTrumpet listed as requesting a higher platform timer resolution.

# Platform

Windows 10 Pro, Version 10.0.16299.309
EarTrumpet 1.5.1.0 (installed from Windows Store)

# Additional information

Increasing the timer resolution leads to an increased rate of timer interrupts on the CPU, waking it up from sleep states more often. As EarTrumpet is usually running in the background all the time, this can dramatically increase the power consumption, "which reduces the battery run time on mobile systems by as much as 25 percent", according to Microsoft. You can find their paper called ["Timers, Timer Resolution, and Development of Efficient Code" here][1]. Also see [this Random ASCII blog post][2] for more information.

[1]: https://docs.microsoft.com/en-us/previous-versions/windows/hardware/download/dn550976(v=vs.85)
[2]: https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/

**Comment by riverar** [comment]
Thanks for the report. I'm not aware of any explicit timers we set up so this might be something in WPF. Looking into it.

**Comment by Wuestengecko** [comment]
[Energy Report](https://github.com/File-New-Project/EarTrumpet/files/1894566/energy-report.zip) (Github doesn't like HTML and wanted me to zip it first)

In the Information section you can see this stack of modules listed for EarTrumpet:

```
\Device\HarddiskVolume4\Windows\SysWOW64\ntdll.dll
\Device\HarddiskVolume4\Windows\SysWOW64\kernel32.dll
\Device\HarddiskVolume4\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_95d88c9d04436846\nvd3dum.dll
\Device\HarddiskVolume4\Windows\SysWOW64\d3d9.dll
\Device\HarddiskVolume4\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll
```

The Random ASCII blog post I linked above lists WPF as a known problem, referencing [this Microsoft forum post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d39edd26-5db3-4803-a536-6d39bb16c50c/on-app-launch-wpfgfxv0300dll-is-calling-timebeginperiod1).
Sadly it doesn't look like MS cares about this at all, as the linked blog post is from 2013, the forum post even further back from 2009, and still there's apparently no solution. Also, you can see in my energy report that LockApp.exe requests 1ms ticks even after unlocking the screen, and I also once saw Calculator.exe (the Win10 calculator app) in this report even when the window was closed...

**Comment by riverar** [comment]
Update: There is no update.

I filed a bug on WPF (now fully open source) to rattle some cages.
