### ISSUE TITLE
Windows 10 Universal C Runtime

### ISSUE THREAD

**Issue by svnpenn** [File-New-Project/EarTrumpet#190]
It looks like installing this would allow EarTrumpet to work with other Windows
versions:

> The Windows 10 Universal C Runtime (CRT) is a Windows operating system
> component. The Windows Update package on this page allows Windows desktop
> applications that depend on the Windows 10 Universal CRT release to run on
> Windows Vista SP2, Windows 7 SP1, Windows 8, and Windows 8.1 S14.

http://microsoft.com/download/details.aspx?id=50410

If that is the case, the readme should be updated.

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/12

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/4

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/41

**Comment by riverar** [comment]
Nope.

**Comment by svnpenn** [comment]
why not

**Comment by riverar** [comment]
EarTrumpet was built to control modern (windows 10) applications. These apps don't exist on other platforms. Upgrade your OS to something modern.

**Comment by svnpenn** [comment]
dont tell me what to do.
