### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by padfut** [File-New-Project/EarTrumpet#193]
1. Names!
How about adding a button to toggle "Icon only" vs "Icon+Name"?

2. Shortcut button for Sound setting
EarTrmpet can change device but more settings are needed sometimes.

**Comment by rikkimax** [comment]
For sound setting, do you mean the sound management dialog?

If so, I've hunted down what to execute ``C:\Windows\System32\mmsys.cpl`` and I'd like it too as a notification tray menu item.

**Comment by riverar** [comment]
We already have item 2 implemented in a future release. 👍

**Comment by rikkimax** [comment]
Is there an estimate of when the next release will land? Because that last update of Windows makes item 2 a bit important.

**Comment by riverar** [comment]
Currently in our feature/2.0 branch if you want to be on the bleeding experimental edge. But we're working every night, inching closer and closer. My guess is next month?

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
