### ISSUE TITLE
EarTrumpet sometimes steals focus from fullscreen apps

### ISSUE THREAD

**Issue by shinji257** [File-New-Project/EarTrumpet#200]
I found this issue while playing GTA IV as I had an issue with the game minimizing to allow another app to take focus.

At random times while playing that game EarTrumpet takes focus for unknown reasons.  I am not interacting with the app in any way (that I'm aware of).  I used a focus logger to find out what was taking focus and looked at the last entry after the game went away.

Here is the logger that I used: http://www.happydroid.com/focus

![image](https://user-images.githubusercontent.com/261005/41196056-6d53cfae-6c06-11e8-92a4-77cc2e550aea.png)

**Comment by GoldenTao** [comment]
Can you check in EarTrumpet settings, if you have a Keyboard shortcut setup. Is it possible you're hitting that combination while playing GTA IV?

**Comment by shinji257** [comment]
There is one set but that isn't it.  Even then this is the default key combo.  This is happening immediately after game launch.  It comes up and 6 seconds later is pulled down as EarTrumpet grabs focus.  My hands are not even on the keyboard at this point.

I'll add that I found that the issue does not happen if the game is running in Windowed mode.

**Comment by riverar** [comment]
Does this happen with any other game? Just curious. Will try to repro with GTA IV.

**Comment by riverar** [comment]
Can repro with GTA IV. Investigating.

**Comment by shinji257** [comment]
I'll go ahead and add that I have not noticed this issue with other full screen apps.  Only with GTA IV.  Glad you were able to reproduce it.  I was slightly worried it was just my computer somehow.

**Comment by riverar** [comment]
Thanks @shinji257, all fixed up. Will be in the next update (after 2.0 rolls out in a few days).
