### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by rampofox** [File-New-Project/EarTrumpet#201]
I downloded the app from Windows store and the files provided here.
But I didn't mange to install it the way I see it in the gifs.
Can someone please explain to me what should I do?

**Comment by riverar** [comment]
Hi @rampofox good eye. We're waiting for the Store version to update to 2.0. It's not quite there yet (should be a day or so).

**Comment by rampofox** [comment]
@riverar that means I can't use any feature already listed in the main screen until then? (i want to use Move Apps Between Playback Devices feature).

**Comment by riverar** [comment]
@rampofox 2.0 is available in the store now!

**Comment by Spiralis** [comment]
Weird...
It says 2.0 on the store page, but when it is installed it shows 1.5.3.0.

**Comment by riverar** [comment]
Are you on the latest update for Windows 10?

**Comment by Spiralis** [comment]
I don't think so. I am on 1709. Is this only available after the update to 1803?
