### ISSUE TITLE
Interesting functionalities?

### ISSUE THREAD

**Issue by jclaessens97** [File-New-Project/EarTrumpet#203]
Hey,

I was planning to make a volumemixer with more functionalities than the default (mostly functionalities I would personally use), but then I came across your project which is awesome. It has already some functionalities implemented I was looking for, so I forked it and I'm planning to implement some of the functionalities I was looking for like:

- Quick way to reset all channels to maximum (I've already implemented it in my fork on dev, I'm thinking to add a shortcut for it as well)
- Some sort of 'profile' system that automatically sets the volumes according to a predifined profile (need to investigate how though, with hotkeys and/or if possible, automatically launch when a certain app launches).

Are you interested in these type of functionalities? Or am I the only one that's gonna use it (thus keeping it for myself)? ;)

Very nice work on the project btw!

**Comment by GoldenTao** [comment]
Interesting ideas, for the moment we've had a bit of a mantra to not keep any state about sessions, we do what Windows does.  Since Windows now has the ability to route sessions to another device (though the UI is buried in settings) so we brought that feature across. That same settings window does look like it has the ability to set a default volume for the app as well, but we're still investigating if we can bring that to EarTrumpet.  

That way Windows holds the state of where an app should play and at what volume, so even if you stop using EarTrumpet everything is persisted.

**Comment by jclaessens97** [comment]
I'm not only talking about persisting the volume levels, but setting profiles like #211 mentioned.
In my case when playing games I get 'earraped' and sometimes on another game I can't hear anything of the game when I'm on discord. So my idea was to make it possible to create profiles and load them when another app launches, or at least start with hotkeys, because atm I'm changing the volumelevels manually all the time. Not sure if that fits in your roadmap of EarTrumpet? If you're looking for help I'm always willing to do that!

For the other small feature (max/reset every channel), is that something you would like?

**Comment by Johaine** [comment]
Hi,
I found EarTrumpet while searching for a tool that provides profiles and wanted to ask if there is any chance that this feature gets integrated in the near future. 
When switching between working, surfing the web privately or gaming I always have to change loudness in different applications.
In the evening loudness generally lower than during the day, when nobody cares.
Solo-Gaming: Music loudness down, different games need differen loudness
Gaming with Discord/skype: Music needs even lower loudness, sometimes the voice app can be louder than the game, sometimes it has to be quieter.
When working voice chat may need to be louder than when gaming, etc. pp.

Being able to configure the main volume and the applications volumes to different levels, saving that setting and being able to load such profiles on demand (e.g. dropdown menu) would be great.

**Comment by GoldenTao** [comment]
Yep this one is related to #51, we're working on an add-on for EarTrumpet that will let you setup this kind functionality. We'll update that thread once this goes out!
