### ISSUE TITLE
Chocolatey Package

### ISSUE THREAD

**Issue by stevehipwell** [File-New-Project/EarTrumpet#204]
It would be really useful if there was a Chocolatey package for EarTrumpet; especially on machines where the Windows Store is disabled.

**Comment by riverar** [comment]
Will investigate this. I'm curious, why is the Store disabled?

**Comment by riverar** [comment]
But they let you download and install random programs from the Internet via Chocolately? 😆 (We'll look into it regardless.)

**Comment by stevehipwell** [comment]
Company wide group policy, user based local admin rights.

**Comment by skoshy** [comment]
Same issue applies to me; company wide group policy, but I have local admin rights to install whatever I want (as long as it's not through the Microsoft Store). Would love to see this or at least a regular installable executable!

**Comment by mmitchell816** [comment]
Also if your using the Enterprise version of Windows 10 you can have the store removed.

**Comment by blubbsy** [comment]
same here... company does not allow windows store downloads, but local admin rights...

**Comment by fireglow** [comment]
I'd like another source of a binary install package, too,
since Windows 10 LTSB doesn't have the windows store.

**Comment by riverar** [comment]
Just an update: We're working on this. There's some legal tape we have to clear before we can build these packages, bear with us.

**Comment by justapoorboy** [comment]
> Just an update: We're working on this. There's some legal tape we have to clear before we can build these packages, bear with us.

Any update on this? I love this app but also don't have access to the Windows Store anymore due to recently installing Win 10 LTSB

**Comment by Nonononoki** [comment]
> Any update on this? I love this app but also don't have access to the Windows Store anymore due to recently installing Win 10 LTSB

https://github.com/File-New-Project/EarTrumpet/issues/253#issuecomment-494669438

**Comment by GoldenTao** [comment]
Please see #374.  We have no plans to create a Chocolatey package, but we are in the process of getting a side load package ready.
