### ISSUE TITLE
Double click to mute everything

### ISSUE THREAD

**Issue by moontear** [File-New-Project/EarTrumpet#206]
Simple request / enhancement:

Double click on the tray icon mutes everything. Double-click again and the previous state is restored.

**Comment by do-bo** [comment]
In v2.0 you can middle-click to do this. 

Double-clicking leads to worse feel of the app - it either has to delay showing the volume flyout a bit to see if you meant to double-click or show the flyout immediately and hide it after split second. This blinking looks bad and buggy (see how it works on OneDrive taskbar icon).

**Comment by moontear** [comment]
Middle-click it is. Don't care about double-click or middle click. Great option!
