### ISSUE TITLE
Crash on right-click

### ISSUE THREAD

**Issue by sabonev** [File-New-Project/EarTrumpet#207]
cannot see the option to move apps between different sound devices, on right click app crashes.

**Comment by AmazingMrX** [comment]
I can verify that right clicking anywhere in the interface causes a crash or an unintended exit of some kind.

**Comment by Droyk** [comment]
I was having the same issue 2hrs before but it's working perfectly.
hmm see if restarting your computer works or reinstalling the app again.

**Comment by AmazingMrX** [comment]
So far there's no change on my end, after a reboot or a reinstall. _Curious_.

**Comment by riverar** [comment]
Can you open EarTrumpet settings and click Collect Troubeshooting Data and mail it to me? (rafael@withinwindows.com)

**Comment by AmazingMrX** [comment]
Sent. Hope it helps. Email me back if you need anything else.

**Comment by GoldenTao** [comment]
We think we've tracked this one down, related to having your taskbar auto hide turned on. Let us know if any of you don't have that turned on.

New version should be out in the next few days once it goes through the store process.

**Comment by alessio-cpt** [comment]
Same bug here, using autohide. Disabling it solves the issue. About that, is there anyway to avoid the taskbar from hiding while interacting with eartrumpet? It is kind of annoying that the bar disappears while I am setting the volumes. Thanks for the quick fix though!

**Comment by riverar** [comment]
EarTrumpet 2.0.1.0 update is in the Store now, check for updates! https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp?rtc=1
