### ISSUE TITLE
Separate volume sliders based on window title, not executable name.

### ISSUE THREAD

**Issue by slidedrum** [File-New-Project/EarTrumpet#210]
Currently in the EarTrumpet Volume Mixer if I have multiple instances of the same application open, it changes the volume of all instances at once.   Could you please add an option to separate each instance of an executable by window title.  Like the default windows mixer does.  An option to show the window name without hovering over would be nice too.

Screenshot examples:  
https://i.imgur.com/euqSUMW.png (Default Volume Mixer showing separate instances)
https://i.imgur.com/qG7O0H4.png (EarTrumpet Volume Mixer combining all instances)

Once this option is added, this program will be an invaluable tool for me to view and change volume levels of all devices on one screen!  Thank you.

**Comment by GoldenTao** [comment]
We discussed the grouping we use quite a bit before deciding on grouping by app executable path.  

We found that while Windows has a group id that we can use, and it mostly worked there were enough instances of apps that didn't work correctly (Skype, Minesweeper etc) that it made EarTrumpet much easier to understand and use to group them all together.  This does mean apps like Firefox will have all their windows grouped.  

If you need to access their individual sessions right-click on the app with multiple sessions and you should see a popup that includes all the sub-items.

**Comment by davuxcom** [comment]
We fixed this in 2.0, you can now right-click to get at all the sessions but normally it is grouped into one. We show all session data that window gives us, so that can't be further split.
