### ISSUE TITLE
suggestion: scroll over tray icon for volume adjustment

### ISSUE THREAD

**Issue by Armin2208** [File-New-Project/EarTrumpet#214]
Hello,

some Linux Distros allows users to adjust the volume in this way: You just go with the mouse cursor over the tray icon and when scroll. You don't need to click. This would be a really cool feature for eartrumpet!

Thank you.

**Comment by GoldenTao** [comment]
We did look at doing that in 2.0 but decided that was a bit too "taking control" plus Windows isn't the best at letting us know where our icon is (because of the overflow tray area)

**Comment by vertigo220** [comment]
I'd suggest you check out 7++ Taskbar Tweaker, which has the option to adjust the volume when scrolling over the notification area or the entire taskbar, as well as many other very useful features that should be built in to Windows.

**Comment by Armin2208** [comment]
eartrump has this feature now, so I close this issue lol
