### ISSUE TITLE
app store: installed 1.5.3.0 but the page claims 2.0.1.0

### ISSUE THREAD

**Issue by doktorstick** [File-New-Project/EarTrumpet#215]
Howdy.

I installed the app today--2018/06/14 around 17:10 CST. The Microsoft store page has the Changelog for 2.0.1.0. 

I am not able to view dynamic levels nor could I right-click to assign the audio device.  It's at this point I noticed that the right-click EarTrumpet icon shows "About EarTrumpet 1.5.3.0..."

**Comment by gitanO0** [comment]
+1

**Comment by riverar** [comment]
Are either of you on Windows 10 April 2018 update? 1803 / 17146? Can you paste a screenshot of the Microsoft Store app store page?

**Comment by doktorstick** [comment]
In reverse order:
![image](https://user-images.githubusercontent.com/1571413/41443167-e4dfb148-7000-11e8-8029-3ec3c38c03c5.png)

**Comment by doktorstick** [comment]
![image](https://user-images.githubusercontent.com/1571413/41443198-0f0d7248-7001-11e8-91d0-8bf75545eaae.png)

**Comment by riverar** [comment]
Thanks for that. EarTrumpet 2.0 is available to users running Windows 10 17134+ because of some new APIs in that release. You'll have to upgrade Windows. I'll work with the Store team to make this less confusing to users.

**Comment by limited660** [comment]
I've done every update possible and still can't get to that build.

https://i.imgur.com/n8DB4At.png

**Comment by doktorstick** [comment]
You probably had settings like mine, @limited660. Under your Settings | Windows Update there's a section called "Update settings". Click on the "Advanced options" link there. Now, you should see a section called "Choose when updates are installed" with a drop-down box. Select it to the "Semi-Annual Channel (Targeted)". Return to the previous page and click "Check for updates". You should find that it'll install version 1803.

**Comment by doktorstick** [comment]
Okay, once Windows completed the update *and* I went back to the app store, EarTrumpet updated to 2.0.1.0. Cheers.

**Comment by gitanO0** [comment]
Same for me.  All good.

**Comment by limited660** [comment]
Fixed it for me as well, thanks.
