### ISSUE TITLE
Version 1.5.3.0 Installed

### ISSUE THREAD

**Issue by zk-jlr** [File-New-Project/EarTrumpet#216]
I need some advice please.  I have a fully patch version of Windows 10 but the Microsoft Shop keeps delivering the older version (according to About).  I have reinstalled as couple of times with no luck.

SiSoftware Sandra
General Information
Windows System : Microsoft Windows 10 Personal 10.00.16299
Platform Compliance : x64
Full Name : Windows 10 Home 6.3.1709.16299
Kernel Type : 16299.rs3_release_svc_escrow.180502-1908
Description : 16299.431.amd64fre.rs3_release_svc_escrow.180502-1908

Any help appreciated.
Thanks

**Comment by DDubbleDD** [comment]
You have to have Windows 10 1803(17134), or higher. @riverar addressed that in another issue.

**Comment by zk-jlr** [comment]
Sorry - my bad.  I assumed that my system would have been automatically updated. It's now done and running the latest version of ET.
Rgds
