### ISSUE TITLE
Not starting at boot

### ISSUE THREAD

**Issue by albertopasqualetto** [File-New-Project/EarTrumpet#217]
EarTrumpet seems not starting with windows unless it is activated in task manager.

**Comment by GoldenTao** [comment]
Is EarTrumpet hiding in your tray area overflow popup? (Click the up arrow in the tray area)

**Comment by riverar** [comment]
Could also be related to https://github.com/File-New-Project/EarTrumpet/issues/227

**Comment by albertopasqualetto** [comment]
Sorry, no, it isn't hidden in the tray.
I meant that the app is configured to be started at boot (from the task manager) but when I turn on the pc, it isn't started so there also isn't its process in task manager.
If I open manually EarTrumpet it starts.
This function was working until the last update.

**Comment by GoldenTao** [comment]
Is this still happening even with the newer versions of EarTrumpet?

**Comment by albertopasqualetto** [comment]
> Is this still happening even with the newer versions of EarTrumpet?

No, now it is working well. Thanks
