### ISSUE TITLE
"No playback devices..." when default device state changes

### ISSUE THREAD

**Issue by onebeard1975** [File-New-Project/EarTrumpet#218]
Hi.

If I switch from a secondary monitor attached via HDMI cable, to PC only, EarTrumpet states I don't, "...have any playback devices."  This can be corrected if I quit/restart EarTrumpet.  I've attached a diagnostic run by EarTrumpet while this issue occurs.

[EarTrumpet Diagnostic.txt](https://github.com/File-New-Project/EarTrumpet/files/2106958/EarTrumpet.Diagnostic.txt)

**Comment by riverar** [comment]
Duping this to #233 (even though it's newer) to centralize activity.
