### ISSUE TITLE
Sea of Thieves not showing in EarTrumpet

### ISSUE THREAD

**Issue by AbrahamArmasCordero** [File-New-Project/EarTrumpet#223]
![image](https://user-images.githubusercontent.com/36243865/41497078-4bebbff0-714e-11e8-92c1-2cd57f61078f.png)

**Comment by GoldenTao** [comment]
Can you grab your diagnostic information from the Settings/About window and email it through to us?  I'll send you an email via your profile so you have a return address.

You can paste the troubleshooting data in here, but it might contain personal information.
