### ISSUE TITLE
Downloading version 1.5.3 instead of 2 why?

### ISSUE THREAD

**Issue by biustech** [File-New-Project/EarTrumpet#225]
I'm on win 10 x64 1709
every time i try to download via windows store it gives only the 1.5.3 version 
anyone knows why?

**Comment by Alex229Qc** [comment]
On the store page it says that you need Windows 10 17134.0 which is Windows 10 1803.

**Comment by biustech** [comment]
![screenshot 4](https://user-images.githubusercontent.com/40319261/41502209-6231a0e4-71a4-11e8-81a0-c8dd84be94f2.jpg)

**Comment by biustech** [comment]
maybe the version 2.0 requires the 1803. i was avoiding the upgrade, but now i have one good reason to do it.

**Comment by Alex229Qc** [comment]
![image](https://user-images.githubusercontent.com/40055694/41502221-3a693a66-7183-11e8-9b4a-888468c9feaa.png)

On my side it needs 17134, sorry it's in french.

**Comment by pkillboredom** [comment]
Okay, this is the Windows Store not indicating that there is a newer version available for later builds. Forgot I paused updates on this PC. Visual Studio also bears no indication that the reason it will not build is because of this. MS's fault :)

**Comment by GoldenTao** [comment]
Yeah this is something we're looking into with the Store team, ideally if you haven't upgraded you should only see the profile for 1.5.3.0, but the store doesn't seem to support that properly.

2.x versions of EarTrumpet require Windows 10 1803 (17134) and higher.
