### ISSUE TITLE
Enhancement request: Mute audio when machine goes idle

### ISSUE THREAD

**Issue by quthla** [File-New-Project/EarTrumpet#226]
It would be nice if the App had an option to mute all audio after a user defined time interval of inactivity. 

My laptop is running 24/7 but I don't want it to make any noise when I'm not using it. 

I think I'd probably not be the only one benefiting from that feature.

**Comment by jclaessens97** [comment]
If this is an 'approved' functionality, I can & want to take a look at this? @riverar

**Comment by riverar** [comment]
@jclaessens97 Not yet, we're still talking about how we handle all these new PRs coming in. We are looking into an add-on model that could accommodate functionality that doesn't make it into the core product.

**Comment by quthla** [comment]
@riverar are you still talking about it?
