### ISSUE TITLE
Error: "Windows cannot access the specified device, path, or file"

### ISSUE THREAD

**Issue by KhakiMan** [File-New-Project/EarTrumpet#227]
EarTrumpet worked fine for a few days, but today after a reboot I received an error (see screenshot). "Windows cannot find the specified device...". No known changes made to cause this.

Great app otherwise!

![eartrumpet_error 2](https://user-images.githubusercontent.com/40345664/41513598-b5023ee6-7253-11e8-8bfb-5e124ed0b1f7.png)

**Comment by riverar** [comment]
This is a known issue with Windows (bug 17560321) sadly; should be fixed via Windows Update soon. Will provide more info as I get it.

Does the app start up when manually invoked via Start?

**Comment by riverar** [comment]
If you continue to hit this, please do the following:

1. Open Feedback Hub and navigate to the Feedback pivot
2. Click Add new feedback
3. Create a feedback item with the following attributes:
    - Type: `Problem`
    - Summary: `EarTrumpet launch issue (17560321)`
    - Category: `Install and Update`
    - Subcategory: `App installation and launch issues`
4. Submit your issue.
5. (Optional) Provide a link to the feedback in this issue.

**Comment by nikgtasa** [comment]
Same problem, winstore.
![sihost_sj1o59jbWk](https://user-images.githubusercontent.com/38408810/93273460-955e7b00-f7c0-11ea-9c5c-d6700b0bc090.png)
OS Name	Microsoft Windows 10 Pro	
Version	10.0.19041 Build 19041

**Comment by Taeleus** [comment]
Happening again. Same error. launched windows 11 today and all of a sudden eartrumpet cant be launched and cannot access windowsapps folder

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Thanks!
