### ISSUE TITLE
Suggestion: Drag & Drop in EarTrumpet Volume Mixer

### ISSUE THREAD

**Issue by dvdstelt** [File-New-Project/EarTrumpet#229]
I freaking love the fact that you can select different applications for different output devices. However, if you've set this up at some point and you quickly want to change it for multiple applications, this can be kind of cumbersome. Right-clicking every single application, etc.

A solution would be to add drag & drop in the EarTrumpet Volume Mixer so I can quickly drag applications from one output device to the other.

**Comment by mmitchell816** [comment]
This is one of those intuitive features you think should work. Adding this would help so much with moving sources.

**Comment by stephenju** [comment]
Right click on the app icon should bring up the output device menu directly. The only thing in the panel currently shows is the button that brings up the device menu anyway. Instead of right-click, click, then click again to switch device, it should be just right-click and click.

**Comment by zanmoskotevc** [comment]
This is seriously how it should work - it just makes so much sense. Grab it and drag it
