### ISSUE TITLE
Is it possible to have two sources of audio output to different speakers.

### ISSUE THREAD

**Issue by sajjadjaved01** [File-New-Project/EarTrumpet#230]
I have a Bluetooth speaker that I’d like to stream my YouTube music to while at the same time having my Plural-sight video from Chrome output sound to my monitor speaker. Is this possible.

[Something like this](https://github.com/audiorouterdev/audio-router)

**Comment by YWI** [comment]
It is possible since the new update happened.

I attached a GIF link explaining to you the process. 
https://ywi.cloud/i/ZTRhM.gif

**Comment by riverar** [comment]
@sajjadjaved01 Yep! As @YWI pointed out, this is a new feature in 2.0. Just right-click the application you want to redirect and send it to another device.
