### ISSUE TITLE
Downloaded from microsoft store but its an older version???

### ISSUE THREAD

**Issue by wintrfrost** [File-New-Project/EarTrumpet#232]
hi so i downloaded eartrumpet from microsoft store and its version said 2.0.0 but upon installing my eartrumpet is on version 1.5.3.0 meaning i can not right click to route my audio.
what can be done to fix this????

![capture](https://user-images.githubusercontent.com/40417335/41637919-ea948d96-7499-11e8-87ba-c7ba98e310f7.PNG)

**Comment by GoldenTao** [comment]
Please update your Windows to 1803.
