### ISSUE TITLE
Audio Sources Showing on All Devices

### ISSUE THREAD

**Issue by cheuer** [File-New-Project/EarTrumpet#235]
There are certain audio sources (System Sounds and Steam notably) that apparently like to show on every single audio device, even though they only output to the default. Can these be excluded from all of the non-default audio devices so the list doesn't get like this?

![image](https://user-images.githubusercontent.com/1103172/41692250-6503d632-74bc-11e8-821f-2836f19242b4.png)

Edited to add: I'm on Windows 10 Version 1803 (OS Build 17134.112)

**Comment by riverar** [comment]
Hm we'll talk about this with the group and get back to you.

Few questions:
* What is that S app at the bottom? Just curious if there are icon retrieval improvements we can make.
* Are you really actively using that many devices? (You can disable them in Windows if not.)
* Would you expect to still see the device in this expanded view, just with no apps? Or would you expect us to hide it?

**Comment by cheuer** [comment]
The S is related, it's the output from [VB-Audio virtual cable](https://www.vb-audio.com/Cable/index.htm) B. Not sure why, but it changes to a C when I right-click it:

![image](https://user-images.githubusercontent.com/1103172/41741149-82d860e2-7557-11e8-8477-793c8771360f.png)

Here's the icon that shows in the Legacy volume mixer:

![image](https://user-images.githubusercontent.com/1103172/41741064-401693aa-7557-11e8-8a57-91b4437d0b01.png)

I don't use them every day (so normally I leave this collapsed) but I do use them to separate/mix audio sources when streaming.

I could live with either way, it's useless when there's nothing playing on it, but if it just showed the header and some blank space it wouldn't be bad either.

**Comment by drgruney** [comment]
I would like to second this. I am currently using a LOT of sound devices. I'm working on disabling in Windows the ones I never use, but System Sounds being on everything is a bit much.

![image](https://user-images.githubusercontent.com/24481663/82158969-e1b89f00-9850-11ea-9aba-ea76728b41f3.png)
