### ISSUE TITLE
Welcome to EarTrumpet screen appears at each launch

### ISSUE THREAD

**Issue by Coros** [File-New-Project/EarTrumpet#243]
Every time I start my computer I have to close this unnecessary window.  Please do not show it after first launch or allow us to disable it.

**Comment by GoldenTao** [comment]
Does your PC have low/no hard drive space? If this Window pops up each time you start your computer, we haven't been able to write to settings to say we've already shown you that window. It should normally only appear once.

**Comment by Coros** [comment]
I have 84GB available on my C drive.  Where is the setting file located?  I might need to remove it and start from scratch.

**Comment by GoldenTao** [comment]
It might be easier to try uninstall/reinstall.

We use the UWP/WinRT Windows settings to store that setting. Those are stored in C:\Users\[username]\AppData\Local\Packages\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne though I wouldn't recommend deleting them as it will likely cause EarTrumpet to stop working correctly.

**Comment by Coros** [comment]
A reinstall did fix it.  Thanks!
