### ISSUE TITLE
Windows shows multiple EarTrumpet instances in Taskbar Notification Area settings

### ISSUE THREAD

**Issue by yinyue200** [File-New-Project/EarTrumpet#244]
![applicationframehost_2018-06-23_19-41-38](https://user-images.githubusercontent.com/13848771/41811185-6fcb3398-773d-11e8-85ab-cb6e8ba5a1cb.jpg)

**Comment by riverar** [comment]
I'm seeing the same thing, looks like a Windows bug. Will verify.
![image](https://user-images.githubusercontent.com/475132/41812371-7bf6f128-76d6-11e8-8000-1810beb6942d.png)

**Comment by GoldenTao** [comment]
This looks to be fixed in 1809, please reopen if you're still seeing the same issue.
