### ISSUE TITLE
Creates lag relating to window moving, in the area where Ear Trumpet would show.

### ISSUE THREAD

**Issue by Socialery** [File-New-Project/EarTrumpet#25]
To reproduce:

1. Run ET
2. open its window
3. move any other window over the spot where ear trumpet appeared
4. Shuddering occurs
5. Close ET
6. move window over the spot where ET appeared
7. observe that, since ET's closure, shuddering has ceased.

I don't know wether this is isolated to my computer or not, however I have noticed the link at least.

**Comment by riverar** [comment]
How do you keep EarTrumpet open and move the window over it? Can you use screentogif or something similar to record a clip?

**Comment by Socialery** [comment]
the ear trumpet window closes itself, I'll try recording a video, I don't know how practical it will be however

**Comment by riverar** [comment]
Can't reproduce this, probably GPU related? Is this happening on a secondary monitor?

**Comment by Socialery** [comment]
main display

I have two cards (inbuilt intel, does left and right monitor) and nvidia (does center monitor), the issue occurs on all monitors

windows build is 10240, nvidia driver is at 353.82

**Comment by Socialery** [comment]
Really really late update

So, with another program that also uses Glass, and also sits over other applications, I'm having the same issue (goes at like, 30fps instead of 60fps), so its obviously my computer in some way or another.

Its still weird that, where the ear trumpet window *was*, there was still lag, so, I'm guessing that the window was not destroyed or whatever the term is, when it was hidden (and as a result, the glass was still re-rendering each time a window changed underneath it, even with it being not visible)
