### ISSUE TITLE
[UI Issue] Broken UI when having multiple (more than 5 playback devices

### ISSUE THREAD

**Issue by Aaronlonin** [File-New-Project/EarTrumpet#250]
In my case I have multiple Playback devices (most of them are virtual: steam stream and so). When I expand the devices selection it gets out of my display bounds. Then I cannot collapse it back unless I reboot Eartrumpet.

![2018-06-26 08_14_43-](https://user-images.githubusercontent.com/13785056/41922323-ad7ad54e-7919-11e8-87a1-2873b43d13e2.png)

**Comment by riverar** [comment]
Thanks for the report. Do you use all those devices? Can you disable a few you don't need?

**Comment by davuxcom** [comment]
Fixed in feeecdc6828301148a66ff3853e0df6306dc01c3 - (occurs on DPI greater than 100%)
