### ISSUE TITLE
High contrast issues

### ISSUE THREAD

**Issue by jernejs** [File-New-Project/EarTrumpet#251]
I noticed a few problems with EarTrumpet in High Contrast mode:
- the window is a bit too translucent, making it hard to see the controls :
![EarTrumpet](https://user-images.githubusercontent.com/1800143/41929929-e8a5102a-7979-11e8-8371-2c292599d63c.png)
- right-click menu is nearly unreadable (it also uses completely different colours than any other menu on the system):
![Menu](https://user-images.githubusercontent.com/1800143/41929959-fee51cd6-7979-11e8-8209-16f75d4e4c82.png)

**Comment by riverar** [comment]
Yikes, thanks for the report. We'll get this fixed.

**Comment by jernejs** [comment]
Note that the only reason I use High Contrast is because that's the only way to get light text on dark background working on current Windows versions.

**Comment by davuxcom** [comment]
Themes updated in 0045ea47c9bb128c210b2e18c95336b6edfdb619 to a working state, now only a few hover states should be missing. Thanks for the report!
