### ISSUE TITLE
Provide install executable without using Windows Store (10 LTSB)

### ISSUE THREAD

**Issue by odysseyo** [File-New-Project/EarTrumpet#253]
I am on Windows 10 LTBS [Version 10.0.14393]. It does not have support for the Windows Store. Can the developers provide a more current install outside of the Store?

**Comment by gate1975mlm** [comment]
I agree with this while I personally don't mind installing from the Windows store I also would like to be able to download a standalone installer for EarTrumpet that I could also save to my hard drive.

**Comment by Glenta** [comment]
Yes please, my windows store doesn't work and installer would be very nice

**Comment by parithon** [comment]
I reinstall my computer regularly while testing different version of OS' and I would also like a standalone installer in order to install via chocolatey.

**Comment by thaurane** [comment]
Please continue releasing installers without the need for the windows store. Not everyone has access to it.

**Comment by godey4me** [comment]
Same here. i'd like a standalone installer since my my work Windows 10 LTBS does not have Microsoft store.

**Comment by bastienlemaitre** [comment]
Chocolatey !

**Comment by Smileyxo** [comment]
yes please, I also have a broekn insider preview OS / MS Store, please release an updated executable :)

**Comment by ThomasDebnt** [comment]
I validate this request! The Windows Store is a blight! I much prefer to do my installation as before with a small executable or a portable version... Especially when you're on LTSB version!

**Comment by BobVul** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/204#issuecomment-411184411

**Comment by henriquedesousa** [comment]
My laptop is managed vua Group Policies and the Store is completely disabled, so I'm on a dead end. Thanks !

**Comment by ookic** [comment]
Please! This is a must-have for any windows user, but us LTSB and LTSC users are lost without it!

**Comment by riverar** [comment]
We're working on it, will see if there's a short-term solution we can put in place.

**Comment by Skoddd** [comment]
Please make this happen.

**Comment by VelvetShadows** [comment]
Another vote for it

**Comment by neosignal** [comment]
A portable version that works on LTSC 2019 would be awesome.

**Comment by LiveChief** [comment]
same here

**Comment by MyFilippo94** [comment]
Here's another vote, I also just switched to a LTSB version of windows, and really miss this crucial application.

**Comment by raphidae** [comment]
Please give us an option to install it on Windows LTSC! It could be as simple as a link to the appx and powershell instructions on how to install it, like with the Windows Subsystem for Linux. That's something that's in the store, but can be installed on LTSC.

Have mercy, you're dangling a steak in front of an emaciated person but don't provide the means to get to it ;D

**Comment by henriquedesousa** [comment]
I have 3 kids and a wife and for the love of God cannot find time to install VStudio and compile this myself. Is it possible for someone to share a build, if not against the rules ? danke/thanks

**Comment by Nonononoki** [comment]
> I have 3 kids and a wife and for the love of God cannot find time to install VStudio and compile this myself. Is it possible for someone to share a build, if not against the rules ? danke/thanks

I've forked this project and created a binary executable file - it's the portable version though (can't figure out how to package the installer), so you have to put a shortcut into the startup folder yourself

**Comment by ookic** [comment]
Thank you noki it's working beautifully!!!

**Comment by GoldenTao** [comment]
Please see #374.  We're working on a side loading package that would allow everyone to keep getting updates. @Nonononoki Thanks for your fork, but we don't want anyone to get stuck on an older version.

**Comment by rivman** [comment]
One image, thousand words...

[](https://imgshare.io/image/applicationframehost-qsljthgttk.2fdPX)

**Comment by stephen-hill** [comment]
If you just want to download the binaries:

- Download the nupkg file from https://chocolatey.org/packages/eartrumpet (Download Button)
- Open downloaded .nupkg file with a zip archive manager
- Navigate to tools and open Release.zip
- Extract Release.zip to a folder on your computer
- Execute EarTrumpet.exe
