### ISSUE TITLE
[Feature Request]Add balance control 

### ISSUE THREAD

**Issue by audunn** [File-New-Project/EarTrumpet#254]
Add controls that allow you to control balance as well as volume.
Some times external factors limit speaker placement, in some cases this means you need to adjust balance depending on listening position. Balance controls in windows are buried  quite deep in audio settings and are a pain to readjust when windows resets the balance. This can happen after restarts etc.
Adding a convenient balance control easily accessible with the volume controls would be beneficial in those and similar situations.

**Comment by S0und** [comment]
I would give an other use case. If we could set the volume balance per app base, you could listen to two audio source at the same time, without interfering with each other on the same channel. 

So the application A could be:

- L - 25%
- R - 0%

application B:

L - 0%
R - 100%

You could focus on the youtube video, but still not deattached from listening to music or a stream.

**Comment by ajmilner85** [comment]
Have been scouring the internet tonight looking for a way to do this (volume balance on a per application basis). Can't believe there's nothing available. Hopefully it's a feature that can be added to Ear Trumpet in the future!

**Comment by khag7** [comment]
This would be nice. Not a programmer, can't contribute, but if it gets done I'd gladly donate.

**Comment by WillMoreland** [comment]
Yes! I would love to have a tool that does this. I am a software engineer, possibly able to contribute

**Comment by JohnLoveDA** [comment]
This is not a question of possibility, it's absolutely possible.  There are audio libraries out there that already achieve this, just not in the context of what EarTrumpet offers.

**Comment by maturz** [comment]
If this is implemented it might also be worth a look at implementing not only LR but also 3D ([binaural audio](https://www.youtube.com/watch?v=IUDTlvagjJA)/[3D sound](https://en.wikipedia.org/wiki/3D_sound_synthesis)). It's great being able to adjust the audio source like that so that you can easily focus on many things at once (it's like being able to put a virtual radio in the corner of your room). The LR feature could also be useful for hearing impaired.

**Comment by WolfganP** [comment]
100% supporting this. Adding balance control to individual apps will be a wonderful addition to Ear Trumpet.

**Comment by WillMoreland** [comment]
Is there anything we can do to get this prioritised? I think it would be a killer feature and I'd use it every day.

**Comment by theiwaz** [comment]
+1
