### ISSUE TITLE
Install EarTrumpet without using Microsoft Store

### ISSUE THREAD

**Issue by Glenta** [File-New-Project/EarTrumpet#255]
Is there a possible way to install EarTrumpet without using Microsoft Store?

**Comment by LVmonkey** [comment]
I would also like this.

MS Store will not work with any other browser apart from Edge.

I uninstalled MS Edge when I installed win10 on my machine, not realizing that it was the only browser that would allow usage of the Microsoft Store... 
...and there was no way to reinstall Edge without a full reinstall of Win10.
