### ISSUE TITLE
what are the files in 40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\LocalCache\Local?

### ISSUE THREAD

**Issue by magiclu** [File-New-Project/EarTrumpet#257]
C:\Users\*****\AppData\Local\Packages\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\LocalCache\Local

![image](https://user-images.githubusercontent.com/3338197/42199444-0e36433a-7ec1-11e8-9c31-1d066e6bfbd4.png)
![image](https://user-images.githubusercontent.com/3338197/42199658-46629c08-7ec2-11e8-9c37-9d1cc49d472c.png)

and somehow EarTrumpet conflict with vivaldi browser's update,i can't update this brower if EarTrumpet is open.Are you spying on me,or it is just a bug?

**Comment by riverar** [comment]
Hey @magiclu, can assure you there's no spying. (The code is open for you to review.) I have this too, not sure what's going on. I'll find out.

![image](https://user-images.githubusercontent.com/475132/42199738-ee55fa14-7e44-11e8-9522-e34b77884230.png)

**Comment by magiclu** [comment]
@riverar 
i think maybe this issue is windows 1803 related,when i try to maximise vivaldi and discord ,half the time there is some space on top,can't fully maximise,both app are on the folder.

this maximise issue is definitely a windows 1803 issue,i notices that soon after the update
but i am sure EarTrumpet is somehow using vivaldi.exe even after i closed the brower.the updater says it is being used
after i updated vivaldi,i deleted vivaldi.exe in 40459File-New-Project.EarTrumpet_1sdd7yawvg6ne folder
after an hour ,i checked again it is there again,i did a checksum using 7zip(seems the same file size and date as the updated real file)
![image](https://user-images.githubusercontent.com/3338197/42209153-885c5a18-7ee0-11e8-8ba7-d9d11ff8e3ac.png)

i know you are not spying,because i have been using EarTrumpet for a long time and trust you guys
if it is syping,that is too obvious.and it should be a bug
now,i think maybe i can blame microsoft

**Comment by riverar** [comment]
I sent an urgent email to Microsoft; will update you soon!

**Comment by riverar** [comment]
This was fixed in Windows 10 1903, closing.
