### ISSUE TITLE
Custom DPI scaling results in poor icon quality

### ISSUE THREAD

**Issue by SonicGold** [File-New-Project/EarTrumpet#259]
Please see for yourself in the screenshot below : DPI scaling at 120% here, the icon marked by the arrow is the one from EarTrumpet, the other one (on the right), is the system one.

![2018-07-04_01-17-23](https://user-images.githubusercontent.com/4278079/42248960-b9390788-7f28-11e8-84de-f62b07627c6d.png)

**Comment by DragoCubed** [comment]
The icon on my laptop is way worse. Fingers crossed this gets fixed

**Comment by davuxcom** [comment]
Added a fix in 4d486d16b9923c3e46d551144c11c608f35bc431 to get down-scaling behavior instead of up-scaling behavior. The bug is most apparent when using per-monitor DPI scaling.
