### ISSUE TITLE
IHeartRadio doesn't appear

### ISSUE THREAD

**Issue by rockfordlhotka** [File-New-Project/EarTrumpet#26]
The newly released IHeartRadio app doesn't show up even when actively playing music.

**Comment by riverar** [comment]
Ultimately a bug in ET when dealing with UWP apps that use a background audio task via windows.media.backgroundplayback.exe. Working on parenting this back to the correct application (we have a valid PFN but invalid PRAID), should be fixed in dev branch in a day or so.

Thanks for the report!
