### ISSUE TITLE
Cannot map apps to playback device

### ISSUE THREAD

**Issue by cone-egg** [File-New-Project/EarTrumpet#260]
When I right click on an app, nothing happens and so I cannot select which playback device to use with each app.
I can right click the EarTrumpet icon and change the default device, but not individually for apps.

The version I am running according to the store is 1.5.3.0 but I cant seem to update it.

Any help to either update if that is the issue, or map apps to devices will be much appreciated. Thanks.

**Comment by riverar** [comment]
Hi @cone-egg, 1.5.3.0 is our older client. 2.0 won't show up until you update to Windows 10 April 2018 Update. Check https://www.microsoft.com/en-us/software-download/windows10 for more information.
