### ISSUE TITLE
App requires admin privileges to work (on latest Windows Insider builds?)

### ISSUE THREAD

**Issue by Dinjoralo** [File-New-Project/EarTrumpet#261]
On my system, EarTrumpet needs to be run as admin for it to function at all. Running it normally still has the process running, but the icon doesn't appear in the notification area. I'm guessing this isn't intended, since it means the app can't start with Windows since there's no way to make UWP apps start in admin automatically. This might have to do with my being on the latest Insider build of Windows, but I'm not sure. Anything I can do to help debug this problem, I'll do.

**Comment by riverar** [comment]
What build of Windows 10 are we talking about here?

**Comment by Dinjoralo** [comment]
Right now, it's build 17711. This also happened on build 17704, the one prior.

**Comment by riverar** [comment]
Can you confirm you're using EarTrumpet 2.0 or higher? (Check the version on the executable in `C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.0.3.0_x86__1sdd7yawvg6ne\EarTrumpet`. You do **not** need to change permissions to open this location directly.)

**Comment by riverar** [comment]
Having a tough time reproducing this, hmm. Can you reproduce on any other machines or VM? Can you right-click the stuck EarTrumpet.exe, click `Create dump file`, zip up the dump and email it to `team @ eartrumpet.app`? Thanks!

**Comment by Dinjoralo** [comment]
...I'm now realizing, I should have tried this on my laptop that's also running the latest insider builds. Eartrumpet functions there. Sorry about that. Sending a dump file to you, now.
