### ISSUE TITLE
Request: Open in a Window

### ISSUE THREAD

**Issue by GOTROK** [File-New-Project/EarTrumpet#262]
Would be nice to be able to open the app inside a window that can stay open and not close when focus shifts away.

Example reason:  I shift between conference calls, music, and apps and it'd be a huge time savings to simply have the sound volume app always open to more quickly turn this app up or mute that app.

**Comment by riverar** [comment]
@GOTROK This is already supported in 2.0, are you using that version? (2.0 requires the latest Windows 10 update.)

**Comment by riverar** [comment]
Closing this issue; seems like you're on an old version of EarTrumpet. Feel free to re-open if incorrect.
