### ISSUE TITLE
MS Edge (Win 10 - 1803 Build) does not save volume adjustments

### ISSUE THREAD

**Issue by Dragonsteel1776** [File-New-Project/EarTrumpet#264]
As noted in the title, there seems to be an issue with Microsoft (MS) Edge browser.  Currently running on Win 10 - 1803 build.  The sound volume level that is set does not save in ear trumpet.  The volume level will reset when the computer is restarted.  It does seem to reset if the browser is closed down completely and then brought back up.  

Edge Build:  42.17134.1.0
Edge HTML: 17.17134

**Comment by davuxcom** [comment]
I don't believe this impacts Edge/Windows 10 anymore. Closing.
