### ISSUE TITLE
New Feature Request: Mute Microphone

### ISSUE THREAD

**Issue by ghost** [File-New-Project/EarTrumpet#269]
Hi,

I have to say I love this tool.  The one thing I wish it had is an easy way to mute the recording device at a layer so that I can be certain that the mic isn't picking up room sounds when I don't want it to.  To more or less disable audio from it.  Some headsets don't have a mute button on them, I unfortunately have one of them.

This also become a great security feature.

Keep up the great work! You Rock!

Regards,
CM

**Comment by iG8R** [comment]
Hi.
The same to me. Please, add this feature - it would be very convenient.

**Comment by kilbasar** [comment]
+1. More broadly, would be great to have default Microphone (and/or other recording devices) as a level you can adjust/mute and showing the current output, just like is done for output sources. Thanks!
