### ISSUE TITLE
Incompatibility with Beat Saber: with EarTrumpet running ingame sound doesn't work

### ISSUE THREAD

**Issue by MiniMeOSc** [File-New-Project/EarTrumpet#270]
I really like EarTrumpet as well as the VR game Beat Saber. However interestingly enough since the last update to the game an incompatibility with EarTrumpet appeared.
When I start the game with EarTrumpet running the game's sound doesn't work. If I open EarTrumpet's volume mixer I see no entry for the game on any sound device (so that I could maybe move it from the wrong device). Changing default audio devices doesn't help either.
I have to quit EarTrumpet and restart the game, then audio ingame suddenly works. If I then launch EarTrumpet audio disappears again...

One could argue now that I should ask the game's developers since their update broke things, but they might probably say to go here since it's this app causing the issue, so I gotta start somewhere ;-).

In [troubleshooting_data.txt](https://github.com/File-New-Project/EarTrumpet/files/2215092/troubleshooting_data.txt) I can see it's creating AudioSessions and such, but it then moves them, notes them inactive and removes them again all while the game is still running. Any ideas why?

**Comment by riverar** [comment]
@MiniMeOSc Interesting. Try this:
1. Close Beat Saber and EarTrumpet
2. Open Settings > System > Sound > App volume and device preferences and click the Reset button at the bottom
3. Retry Beat Saber and EarTrumpet

**Comment by MiniMeOSc** [comment]
Interesting. It's already a (probably new) Windows feature to specify a default audio device per app? Thought it was something specifically new in EarTrumpet. Before EarTrumpet got it I was using CheVolume btw.. You never stop learning new things :D. I was actually looking for a reset option, but not knowing it's a Windows feature I was looking in the wrong place.

That actually helped. Thanks!

**Comment by riverar** [comment]
@MiniMeOSc Hah! Did it resolve the issue or?

**Comment by MiniMeOSc** [comment]
Yes, game sound now works with EarTrumpet running :-). Gonna close the issue.

(Interestingly though I tried downgrading the game version earlier, it then also worked until I updated again. I guess it'll remain a mystery why it acted like that...)
