### ISSUE TITLE
EarTrumpet doesn't stay in notification area between sessions

### ISSUE THREAD

**Issue by equin0x80** [File-New-Project/EarTrumpet#272]
Windows 10 Pro 64-bit: I add EarTrumpet to the notification area, via Windows settings: "Notification Area > Select which icons appear on the taskbar".  A few login sessions later, I notice that it has disappeared to the hidden "extra icons" portion of the notification area.  I go and re-add it.  Again it disappears after a few sessions. I have had no such problem with any other tray application, e.g. OneDrive and CCleaner work fine.

**Comment by gustms** [comment]
This happens for me when the program updates, as the executable change folders.

**Comment by riverar** [comment]
@equin0x80 @gustms Yep, not much we can do here other than continue to let Microsoft know this impacts its customers.

**Comment by equin0x80** [comment]
This is still horribly frustrating: to change the volume (a frequent and common task), I have to hit the "^" overflow button, adjust my eyes to icon positions on the newly popped-up panel, and click the right one -- only then can I change the volume.

Workaround ideas:
1. A setting where EarTrumpet can be shown as a normal taskbar button (like any other program) instead of in the tray. It sounds stupid but it would be better than this.
2. A shortcut key that pops up EarTrumpet and allows keyboard navigation to change the volume.

**Comment by riverar** [comment]
@equin0x80 Am happy to respond to your latest reply, but it seems to have vanished. Remember, you can drag the EarTrumpet icon out of the overflow menu and into the notification area. Every update, however, it will pop back in there -- this is a Windows issue, I'll bug Microsoft about it again.

**Comment by elijahgagne** [comment]
You might also look at AutoHotKey to assist. There are numerous example where you can create hotkeys (some using the mouse wheel) that will let you adjust the volume.

**Comment by GoldenTao** [comment]
This one should now be working in the latest update of EarTrumpet (2.1.2.0).  Please reopen if you're still having this issue.

**Comment by equin0x80** [comment]
Thanks for your work on this. Can you please summarise what you actually changed? It might be useful for other apps that use the notification area.

**Comment by davuxcom** [comment]
See the documentation at https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/ns-shellapi-_notifyicondataa

If you are starting with a WPF app that uses System.Windows.Forms.NotifyIcon, you must do the following:
- Switch to Shell_NotifyIconW interop, using the NOTIFYICONDATAW structure which has the guidItem member available (not the earlier version of the struct that identifies icons only by hwnd+id).  The versiono in System.Windows.Forms is using the earlier version that will not work.
- Identify your icon using guidItem, not hwnd+id.
- Authenticode sign your exe file so that the shell can handle moving the location.

>  The path of the binary file is included in the registration of the icon's GUID and cannot be changed. Settings associated with the icon are preserved through an upgrade only if the file path and GUID are unchanged. If the path must be changed, the application should remove any GUID information that was added when the existing icon was registered. Once that information is removed, you can move the binary file to a new location and reregister it with a new GUID. Any settings associated with the original GUID registration will be lost.

> Note  The only exception to a moved file occurs when both the original and moved binary files are Authenticode-signed by the same company. In that case, settings are preserved through the move.

Here is the bulk of the logic: https://github.com/File-New-Project/EarTrumpet/blob/dev/EarTrumpet/UI/Helpers/ShellNotifyIcon.cs
