### ISSUE TITLE
Can I start Volume Mixer from command line?

### ISSUE THREAD

**Issue by mockroot** [File-New-Project/EarTrumpet#276]
Hi. Can I start this window from command line?
![screenshot_05-08-2018_06-14-33](https://user-images.githubusercontent.com/24863704/43682228-0242c6fa-9877-11e8-9e6a-998ba505456f.png)

I want to create shortcut for this window with AutoHotkey. If there is a command line option, it would be great. Thank you.

**Comment by riverar** [comment]
If you right-click the icon in the tray, you'll find Settings where a hotkey can be configured.
 
![image](https://user-images.githubusercontent.com/475132/43682277-f7b9d68a-9824-11e8-9cdc-59ccc243ad1e.png)

**Comment by MarcG2** [comment]
I would have also found this useful.  If your using AHK a simple work around would be to have AHK send the keyboard hotkey that eartrumpet is configured to use.  I had my AHK script using the default hotkey which was removed at some point.  

Anyway where are Eartrumpet settings saved at?  I would like to set my eartrumpet keyboard shortcuts using a script.  I own many computers and having to manually set the shortcut every time I do a fresh windows setup is annoying.

**Comment by NIronwolf** [comment]
I would also love this feature.
