### ISSUE TITLE
2.0.5.0 reverts to English en-us

### ISSUE THREAD

**Issue by duk6046** [File-New-Project/EarTrumpet#277]
v2.0.5.0 please fix it

**Comment by yinyue200** [comment]
My device has also encountered the issue.

**Comment by mdmk** [comment]
Same problem on 4 PCs.
All on latest 64 bit Windows 10 Build 1803.
I use French Windows, the app is in english.
I suggest adding an option to set language manually, for edge cases where you don't want the same language than in OS or face bugs.

**Comment by riverar** [comment]
An update for this issue has been submitted to the Store (2.0.6.0). You should see it soon, hopefully Friday. Thanks!

**Comment by mdmk** [comment]
I forced the update by clicking "Obtain new updates" button in the store app.
The fix is working, at least on one of my computers.
Thanks for the quick fix.

**Comment by riverar** [comment]
Wow, that was fast, for the Store team. Going to close this, please let us know if you run into any other problems. Thanks!
