### ISSUE TITLE
Feature:  Add support for MIDI controllers

### ISSUE THREAD

**Issue by GordonSmith** [File-New-Project/EarTrumpet#278]
Allow changing the volume of individual apps via midi controller!

**Comment by schmic** [comment]
Oh yes please!

**Comment by jacky4566** [comment]
+1

It would also be fantastic to pull the program icons through IAudioSessionControl::GetIconPath method.

I'm working on a midi controller with active display!

**Comment by flibble666** [comment]
Sorry to revive an old post but i found [this ](https://github.com/ho0ber/NK2Tray) it allows you to control Windows Audio Mixer with a Korg nanoKONTROL2 and other similar control surfaces.
and i would assume work with ear trumpet.
