### ISSUE TITLE
EarTrumpet opens up by itself

### ISSUE THREAD

**Issue by Raytar** [File-New-Project/EarTrumpet#280]
EarTrumpet opens up by itself sometimes. I have noticed that it can happen when I rearrange tiles in the start menu or drag and drop Edge tabs between windows.

Here is a gif of it happening: 
![2018-08-20_12-34-15](https://user-images.githubusercontent.com/10762082/44336432-b9cbba00-a477-11e8-93ee-e68e6d9287f2.gif)

I am not able to reproduce it consistently, but it seems to happen more often after a reboot.

Seems to be similar to what others have reported in the Feedback hub:
* https://aka.ms/AA23q6e
* https://aka.ms/AA23y3i

**Comment by riverar** [comment]
Interesting, can you open Settings and click `Collect troubleshooting data` at the bottom and mail that to `team@eartrumpet.app`? Thanks!

**Comment by riverar** [comment]
@Raytar Can you also try changing the hotkey to None (just hit Save) and see if you can reproduce?

**Comment by Raytar** [comment]
@riverar I've sendt the data. Also, I had already set the hotkey to None.

**Comment by Raytar** [comment]
I set the hotkey back to the default, and I can't reproduce it anymore by rebooting. I'll leave it like that and report back if it happens again later.
