### ISSUE TITLE
Layout issues on non-16:9-displays

### ISSUE THREAD

**Issue by o-l-a-v** [File-New-Project/EarTrumpet#281]
EarTrumpet usually misplaces it's popup/ dialog when I use it with the 1920x1200px screens at work. This makes me unable to reach the top content, in my example master volume for a connected bluetooth device. It has been like this months, restarting the application usually fixes it.

Before force close -> restart
![image](https://user-images.githubusercontent.com/6450056/44343038-19809000-a48d-11e8-8326-961326662d10.png)

After force close -> restart
![image](https://user-images.githubusercontent.com/6450056/44343113-52b90000-a48d-11e8-90eb-af808c016086.png)

**Comment by o-l-a-v** [comment]
I might also add that I'm running 125% scaling across all screens. Scaling seems to cause layout issues with multiple apps, might be the problem here too.

**Comment by riverar** [comment]
Hey @o-l-a-v, do you have any more information on when this starts to happen? Is it when you plug in a new device or just randomly at some point?

**Comment by o-l-a-v** [comment]
Not sure if I've seen a pattern yet. I usually boot up my Lenovo when I start at work. It's docked to two monitors á 1920x1200px. I then insert a USB DAC, and thats when I start arranging audio output, and see that the layout/ placement is off. Then I usually close EarTrumpet, the open it again. But I'll try to be more systematic in my testing, will report back to you when I got more info.

**Comment by ElvenSpellmaker** [comment]
I get a similar thing, which I assume is to do with multiple-DPI and resolution monitors, except my gap is even more pronounced:
![image](https://user-images.githubusercontent.com/2286713/46095681-07dd8700-c1b5-11e8-8d8e-1d5c843680fc.png)

**Comment by riverar** [comment]
Are you on EarTrumpet 2.0.7.0? We fixed a bunch of DPI related issues

**Comment by ElvenSpellmaker** [comment]
I'm on the latest Windows Store version which isn't that:
![image](https://user-images.githubusercontent.com/2286713/46095817-5d199880-c1b5-11e8-93a9-e4e0089cc01f.png)

**Comment by riverar** [comment]
Strange, can you check for updates in your Store app? Maybe it's stuck and needs a kick.

**Comment by ElvenSpellmaker** [comment]
I just updated it before posting my post, I'll try to have another look, but it's weird that it's got a different version for me. 🤔

**Comment by ElvenSpellmaker** [comment]
The store seems to be quite broken, it's now downloading another version. O.o
![image](https://user-images.githubusercontent.com/2286713/46096476-33fa0780-c1b7-11e8-9ece-cb9394cddd6e.png)

Seems to be a lot better now!

**Comment by riverar** [comment]
What OS version/build are you on? We have some packages that won't go out to older builds of Windows 10 but shouldn't be affecting you.
