### ISSUE TITLE
Ear Trumpet won't launch

### ISSUE THREAD

**Issue by SRChastain** [File-New-Project/EarTrumpet#282]
Ear Trumpet is installed on both my laptop and new RCA Cambio tablet.  It works beautifully on my  laptop but it won't launch on the tablet.  I have the April update on Windows10 and the tablet confirms it should support the app.  I don't  know what else to do.  It is a wonderful app and I want it to work on my tablet.

**Comment by SRChastain** [comment]
Thanks for getting back to me.   There are no error messages.   It is confirmed that the app is installed and shows a launch button.  I touch the launch or open button and nothing happens.

**Comment by SRChastain** [comment]
Mr. Rivera, one other observation.  The Ear Trumpet app can be configured when I log in.   On the
start-up page, it says this app is "not measured".

**Comment by GoldenTao** [comment]
Are you still having issues with getting EarTrumpet to run on your tablet?  When you launch it, does EarTrumpet show up in Task Manager?

**Comment by SRChastain** [comment]
David Golden

Yes, Ear Trumpet is running in Task Manager.  The elite technical squad at
Microsoft
helped to install and launch the app on my RCA Cambio 2 in 1
tablet/laptop.  But the
sound is still too low to stream old movies or for that matter, even newer
movies.  Ear
Trumpet works beautifully on another device.   Do you think the problem is
in the RCA
hardware?  I have just about given up on solving the problem and I so
wanted Ear
Trumpet to work on my tablet.

Sherry Chastain
