### ISSUE TITLE
"Incorrect Parameter" when launching EarTrumpet from Win Store

### ISSUE THREAD

**Issue by jeckyD** [File-New-Project/EarTrumpet#286]
I always keep getting this error when launching EarTrumpet from Windows Store. Quoted below (from error prompt):

[Window Title]
C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.0.6.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe

[Content]
C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.0.6.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe

The parameter is incorrect.

Any suggestions?

**Comment by riverar** [comment]
Hi @jeckyD what version/build of Windows 10 are you running? (Start > Run > Winver) Do you have all the latest updates installed?

**Comment by jeckyD** [comment]
Hello good sir. 
I'm running Version 1803 OS Build 17134.228.
All updates are intact as I've checked.

**Comment by GoldenTao** [comment]
Are you still having the same issue with the latest EarTrumpet version?

**Comment by jeckyD** [comment]
Apparently, yes.. I'm now thinking it might have been caused by my WindowApps folder permissions and ownership settings? I might have messed it up for some reason.

**Comment by GoldenTao** [comment]
It could, can you try it on another machine that hasn't had the permissions changed?

**Comment by jeckyD** [comment]
Tried uninstalling/installing and the wsrefresh.exe thingy. Still won't launch but the error has changed.. weird, sorry for this bugging. 

[Window Title]
C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.0.7.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe

[Content]
C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.0.7.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe

Cannot create a file when that file already exists.


[OK]

Anyways, tried this on other devices and it works fine. Folder Permission Owner is set to "SYSTEM".

**Comment by jeckyD** [comment]
Hello good sire riverar,

Performed your suggestion. Hopefully this problem is resolved. Thanks a bunch for watching this issue, EarTrumpet has been very useful for me, so I'm hoping for a good response from MS.

**Comment by AndreySeleznov** [comment]
@riverar thanks! 
I posted MS Feedback https://aka.ms/AA6i4p6, selected App Installation Issues category as there was no App launch issues category. 
Fingers crossed!

**Comment by riverar** [comment]
@AndreySeleznov Strange, sounds like they changed a few things. I'll email them about this now.

**Comment by CallMeVorex** [comment]
Posted some feedback aswell, having issue with loading up the program, unable to sue my headset as i am very reliant on eartrumpet and with it stopping working has done somethign to my headset ive tried troubleshooting alot and nothing can work. 
https://aka.ms/AA8cnhs

**Comment by riverar** [comment]
@CallMeVorex As a workaround, uninstall EarTrumpet and use chocolatey to reinstall. This will bypass appcontainer/appmodel and restore the app.

**Comment by CallMeVorex** [comment]
Ah okay than you got it, trying to figure out why when i have my headphones selected as an output it still plays through my main speakers, i have the default playback device set in ear trumpet aswell as settings so im not too sure, all worked before i restarted my pc earlier and eartrumpet didnt work so not too sure atm.

**Comment by David263** [comment]
I cannot use the Feedback Hub link above because I get the same error message (link to app not found) as I get for EarTrumpet. For me, these resulted from deleting some Windows files and persists even after running DISM and SFC. I'm not yet willing to reload (reset) Windows yet.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
