### ISSUE TITLE
Unable to Change Audio Output

### ISSUE THREAD

**Issue by Railang** [File-New-Project/EarTrumpet#288]
On any of the programs running, I can't swap the audio device it is outputting. This is one of the key features I tried this program out for, since I have been using Chevolume to do so for the past while, and that has become increasingly unstable.

I am not sure if I installed wrong (just installed from Windows Store) or if there is another issue going on.

**Comment by LoungeFlyZ** [comment]
I'm not seeing the ability to switch either.  Installed from the store.  Not 100% if i'm using it correctly.

![image](https://user-images.githubusercontent.com/1360936/46267434-c832da00-c4e9-11e8-913c-93c12e1fb7ec.png)

**Comment by LoungeFlyZ** [comment]
@riverar ah ok! yeah that will be it. This is a new build and I didnt realize I hadn't applied 1803. I'll try that. Thanks!
