### ISSUE TITLE
Icon shows muted with "x" when volume at "0"

### ISSUE THREAD

**Issue by ralfyguy** [File-New-Project/EarTrumpet#290]
The icon now shows as muted with an "x" when the volume is set to "0" instead of no bars like before. I know technically it is muted but it looks confusing next to the Windows stock icon

**Comment by GoldenTao** [comment]
Can you send us a screenshot? When you set the Windows Volume to 0, it also mutes/changes to an x on the system tray.

**Comment by ralfyguy** [comment]
This is a screenshot with the volumes at “0”.
Sent from Mail for Windows 10

**Comment by GoldenTao** [comment]
Sorry images don't come through in email replies.

**Comment by ralfyguy** [comment]
This is with volumes set at “0”. Before the update the icon looked like the right Windows icon. Volume is not “muted”. Ear Trumpet now always shows the “muted” icon when at “0”

Sent from Mail for Windows 10

**Comment by riverar** [comment]
Closing this issue. If you get an image, please re-open the issue / upload it via GitHub (cut/paste it right in). Thanks!
