### ISSUE TITLE
Resetting audio level

### ISSUE THREAD

**Issue by YWI** [File-New-Project/EarTrumpet#291]
EarTrumpet is resetting audio levels on Fortnite (game) & Spotify I have to adjust them all the time and it's becoming devastating. Is there any way to store my settings?

**Comment by GoldenTao** [comment]
Not at the moment sorry, we use the saved state from Windows, which for most desktop apps is saved, but for Modern apps this usually isn't saved, so they reset to full volume. We have a few other feature requests for a preset system which would be a workaround when we get to building that.

**Comment by YWI** [comment]
I understand. Ear trumpet is literally an essential to my everyday usage. Spotify and fortnite keep on restting. I really hope you can keep me updated with maybe an ETA for a resolution of this issue. Thanks for making my life simpler.

**Comment by YWI** [comment]
Although i would like to state that thry used to not reset about 3 months ago. I’m not sure honestly.

**Comment by GoldenTao** [comment]
When they say they keep resetting... Does that only reset after restarting the app or after you restart your PC or just randomly they will reset?

**Comment by YWI** [comment]
They both reset after app restart.

**Comment by YWI** [comment]
Is a fix going to be implemented?
