### ISSUE TITLE
Very difficult to manage Firefox/Firefox Dev tabs

### ISSUE THREAD

**Issue by Riajyuu** [File-New-Project/EarTrumpet#293]
You are  allowed to run Firefox & FDE by default since it is different profile. 
When you do that, EarTrumpet only recognize the first of them most probably because they have the same process name, `firefox.exe` .
I guess if can separate them by different file (aka installation) location so that we can control them both.

![image](https://user-images.githubusercontent.com/16912240/46050768-6b1fd880-c125-11e8-807b-db9043f7f0c4.png)

**Comment by GoldenTao** [comment]
You should also be able to right click on FireFox in EarTrumpet and it will give you a list of the individual sessions.  That should let you change the volume for either Firefox or FDE.

**Comment by riverar** [comment]
Hey @Riajyuu, can you hover over the icons and see tab names?

**Comment by Riajyuu** [comment]
@riverar No. None of them.
You can only see tab names when you your tab number is no more than content processes number, which will be increased to 8 at most soon. But I have dozens of tabs.

**Comment by Riajyuu** [comment]
@riverar 
Currently I suggest giving up per-tab management but control parent process of fx & fde respectively

**Comment by riverar** [comment]
Should be fixed in next release, see https://github.com/File-New-Project/EarTrumpet/issues/312

**Comment by riverar** [comment]
Hi @Riajyuu have you tried 2.1.1.0 yet? Should be much easier now, re-open if this is still a problem. Thanks.
