### ISSUE TITLE
Enhancements tab missing when opening playback devices dialog from EarTrumpet

### ISSUE THREAD

**Issue by berrnd** [File-New-Project/EarTrumpet#296]
Hi, and first thanks for this great little daily helper tool! :)

Noticed the following on different machines:
When I open the playback devices dialog from the context menu of the EarTrumpet tray icon, the Enhancements tab of any playback device is missing in the device properties dialog.
(I think what's in that tab is driver specific, at least not every device has such a tab.)

To make clear what I mean, here a short screencast:

Opened from EarTrumpet:
![2018-10-15_19-59-12](https://user-images.githubusercontent.com/2161815/46969104-4c25be00-d0b5-11e8-85b5-90676b866cf9.gif)

Opened from control panel / settings app:
![2018-10-15_20-00-04](https://user-images.githubusercontent.com/2161815/46969121-56e05300-d0b5-11e8-959f-93f4d226f398.gif)

Tried to investigate a little bit myself what that could cause, but found nothing so far...

**Comment by riverar** [comment]
Yikes, good catch.

**Comment by ToppestOfDogs** [comment]
I have the same issue. For the longest time, I thought it was a driver issue making it disappear.
