### ISSUE TITLE
EarTrumpet in a weird state after connecting remotely

### ISSUE THREAD

**Issue by drujd** [File-New-Project/EarTrumpet#298]
Windows 10 x64 17134.345

I have EarTrumpet installed on my work computer, to which I often connect remotely using RDP. Every time I connect locally after being connected over RDP, EarTrumpet is in a weird state:

- It shows disabled and nonexistent audio devices, twice
- It shows audio as muted/disabled, even though that is not true
- When I try to change volume or enable sound, EarTrumpet crashes

Restarting EarTrumpet fixes everything.

![image](https://user-images.githubusercontent.com/6545887/47018541-3ff13d80-d155-11e8-98ae-3f3161f90a47.png)

**Comment by hangy** [comment]
Maybe an option to refresh/reload available devices could be a solution? I noticed a similar problem when I enabled a monitor that's connected through HDMI and was not able to use the added HDMI audio device in EarTrumpet until I restarted the application.

**Comment by riverar** [comment]
Hey @hangy, am working on this. But if you can reproduce this again, would be helpful if you could right-click EarTrumpet, click EarTrumpet Settings > Collect troubleshooting data, then send that data to `team@eartrumpet.app`. Thanks!

**Comment by drujd** [comment]
[eartrumpet_after_rd_connection.txt](https://github.com/File-New-Project/EarTrumpet/files/2860408/eartrumpet_after_rd_connection.txt)

**Comment by davuxcom** [comment]
This should have been fixed in 2.0.8.0 - reactivate if you're still seeing the identical behavior please.
