### ISSUE TITLE
No fast mute support

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#3]

**Comment by oerpli** [comment]
I implemented this here:
https://github.com/oerpli/EarTrumpet/commit/a24e295d579ddfe56454083738ecdd5034fd201b

I'm not entirely sure wether it's a beatiful solution - I tried to mimic the default Windows behaviour:
* muting does not change the displayed volume 
* scrolling to change the volume afterwards changes the volume starting from where it was before
* reducing volume to 0 displays the muted state


Also the visual is maybe still lacking - this was the best I came up with:
![t28f00e 1](https://cloud.githubusercontent.com/assets/4408819/8788521/4f2e0d88-2f3b-11e5-91d5-ef06b90e7ad3.png)


Should I create a pull request for this?
