### ISSUE TITLE
Touch-friendly way to switch audio devices

### ISSUE THREAD

**Issue by rockfordlhotka** [File-New-Project/EarTrumpet#30]
This may be total scope creep, but it would be really nice to have a touch-friendly way to switch audio playback and recording devices.

I typically have multiple microphones and speakers (BT or wired), and often need to switch between them. The old-fashioned Windows dialog for this purpose is far from friendly even for a mouse user, much less touch.

**Comment by GoldenTao** [comment]
We don't at the moment have any plans to work with recording devices, but I'll reference this in the change device ticket we have, so we don't forget to chat about it.

Merged with #9
