### ISSUE TITLE
Diablo 2 / Diablo 2 Lord of Destruction do not appear in EarTrumpet

### ISSUE THREAD

**Issue by NitroFrost** [File-New-Project/EarTrumpet#304]
Diablo 2 lords of destruction is just not getting picked up at all by ear trumpet. I confirmed that I'm looking at the right input and that it's also being picked up in the normal volume mixer under the same input device and can have it's volume controlled that way. 

I have also tried adding the command for the shortcut to allow the sound to play when not focused on the game. this also didn't fix it.

**Comment by riverar** [comment]
Let me get Diablo 2 installed and check this out. Thanks for the report.

**Comment by riverar** [comment]
Can confirm missing in EarTrumpet -and- Windows 10 "App volume and device preferences" (modern mixer). App does appear in Legacy volume mixer, however.

**Comment by riverar** [comment]
Can confirm bug still exists in Windows 10 19H1 (18282). Reached out to Windows audio team.
![image](https://user-images.githubusercontent.com/475132/48509762-d3766680-e806-11e8-8b12-bc2900081fa3.png)

**Comment by riverar** [comment]
The Windows audio mixers now see Diablo 2 as of build 18309, we're investigating why EarTrumpet cannot however.

**Comment by riverar** [comment]
Additional information sent to Microsoft; few more bugs filed. Just keeping you up to date, we're actively working on this together! Who would've thought Diablo 2 would be such a pain in the butt.

**Comment by riverar** [comment]
@NitroFrost Closing this as fixed in the next Windows update. Thanks for the report!

**Comment by NitroFrost** [comment]
> @NitroFrost Closing this as fixed in the next Windows update. Thanks for the report!

Thank you for the hard work. Took awhile but the fact that you continued to work on such a small bug and old game shows dedication. Love it and thank you again.
