### ISSUE TITLE
EarTrumpet has white notification area icon in Windows Light Mode

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#305]
![image](https://user-images.githubusercontent.com/475132/48509507-31567e80-e806-11e8-953f-d976bc0fae09.png)

**Comment by ravn83** [comment]
It´s funny, i want open the same feature request.
It will be great, if the devs will inclunde the theme based icons :-)

greetz,
ravn

**Comment by Dinjoralo** [comment]
The option for a lightmode icon would be nice, and hopefully not overtly difficult to implement.

**Comment by riverar** [comment]
This is now supported in 2.1.1.0, thanks for the report!
