### ISSUE TITLE
How to build EarTrumpet

### ISSUE THREAD

**Issue by Onepamopa** [File-New-Project/EarTrumpet#307]
Where can we find a comprehensive guide on how to build EarTrumpet from source?

I've installed Visual Studio 2017 Community edition, however, it keeps spitting a ton of errors about missing stuff I don't know where to find.

**Comment by Onepamopa** [comment]
I'm not saying "do this immediately". I just need the basic requirements - what do I need to install along with Visual Studio, so I would be able to compile it.

**Comment by Onepamopa** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX3217	SDK folder containing 'UAP.props' for 'UAP 10.0.14393.0' cannot be located. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information.	EarTrumpet.Package	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets	852

**Comment by riverar** [comment]
@Onepamopa Here you go, try this https://github.com/File-New-Project/EarTrumpet/blob/dev/COMPILING.md

**Comment by Onepamopa** [comment]
I was using a newer SDK 10.0.17763.132, why the project requires an old one?

**Comment by jclaessens97** [comment]
@riverar  Hey, in June I cloned & got it working, but had a fresh install since then. Now I followed the doc linked above, but it keeps spitting an error about the Windows reference in the Eartrumpet project. Any chance you forgot to mention that in the doc? 😃  See screenshot below, this is the output when I try to build the Package project on x86.

![afbeelding](https://user-images.githubusercontent.com/10177148/49341288-77577300-f64b-11e8-8095-90bf36a4029d.png)

**Comment by Nytohan** [comment]
> @riverar Hey, in June I cloned & got it working, but had a fresh windows install since then. Now I followed the doc linked above, but it keeps spitting an error about the Windows reference in the Eartrumpet project. Any chance you forgot to mention that in the doc? 😃 See screenshot below, this is the output when I try to build the Package project on x86.
> 
> ![afbeelding](https://user-images.githubusercontent.com/10177148/49341288-77577300-f64b-11e8-8095-90bf36a4029d.png)
> 
> And the correct UWP SDK is installed:
> ![afbeelding](https://user-images.githubusercontent.com/10177148/49341302-a968d500-f64b-11e8-8bc2-272609f9cc00.png)

Also having this issue.

**Comment by riverar** [comment]
@jclaessens97 I was able to reproduce this; workaround in #320
