### ISSUE TITLE
Can someone please compile this for ARM architecture too please?

### ISSUE THREAD

**Issue by domcote** [File-New-Project/EarTrumpet#308]
Title says it all - currently this is only available for x86. Would someone mind compiling the next release for ARM too, please? I'd do it myself, but I'm not a dev. 😉

**Comment by riverar** [comment]
We run on ARM64 devices today. Whatcha trying to do?

**Comment by riverar** [comment]
Windows on ARM is missing the .NET CLR for ARM32 and ARM64 architectures. We can't target those platforms until .NET Core 3.0 gets released.

**Comment by james856** [comment]
Now that .NET Core 3.1 is released, is it possible to have ARM64 version of EarTrumpet?

**Comment by domcote** [comment]
+1, obviously. ;-) That being said, I must admit it runs fine with emulation too. In fact, all 32bit .net apps I tried to date run fantastically well on ARM, with excellent performance - rivalling Intel native performance IMHO.

**Comment by matze19999** [comment]
I tried to compile it for arm64 but had no access unfortunately :(
Really wan't to use it on  my Surface Pro X, I love this app on my PC

**Comment by domcote** [comment]
It works great on all Snapdragons (835, 850, 8cx and SQ1) as an x86 app – I use it all the time. Go ahead and install it. 👍

Dominique Côté | Account Technology Strategist
Global Product Solutions GPS | Device Partner Sales DPS
Mail, Teams: docote@microsoft.com<mailto:docote@microsoft.com> | Phone: +49 (1515) 895 6043
Sent from Outlook on my Snapdragon-based Surface Pro X

Microsoft Deutschland GmbH
Walter-Gropius-Straße 5, 80807 München
http://www.microsoft.com/germany<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.microsoft.com%2Fgermany&data=02%7C01%7CDominique.Cote%40microsoft.com%7Cf5bc01db9cb04e00d68f08d741bb9793%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637050146276722771&sdata=nusB8oyANNXgPsTagzn5vT%2FC%2FHz0cIkvLtdOT27WP5A%3D&reserved=0>
http://news.microsoft.com/de-de/<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fnews.microsoft.com%2Fde-de%2F&data=02%7C01%7CDominique.Cote%40microsoft.com%7Cf5bc01db9cb04e00d68f08d741bb9793%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637050146276722771&sdata=uD2QIVF4K2o3V99kyPMb6jpEF%2BAub%2BbPAk2%2FyKsVyOk%3D&reserved=0>

Amtsgericht München, HRB 70438

**Comment by riverar** [comment]
@matze19999 EarTrumpet works fine on ARM64 devices. You don't need to recompile it.

**Comment by xgdgsc** [comment]
Maybe time to reconsider providing native arm64 builds with https://www.microsoft.com/en-us/d/windows-dev-kit-2023/94K0P67W7581?activetab=pivot:overviewtab and https://www.notebookcheck.net/Huawei-MateBook-E-Go-is-unleashed-as-a-new-Windows-on-ARM-2-in-1-with-a-2-5K-display-starting-at-just-over-US-600.647400.0.html .

**Comment by riverar** [comment]
@xgdgsc EarTrumpet currently runs on .NET Framework, which has no ARM64 equivalent. Good news though, I already finished the port to .NET 6 which means native x86, x64, and arm64 builds. I just haven't merged it into `dev` yet. Stay tuned!

**Comment by xgdgsc** [comment]
Thanks. Any update? Snapdragon X Elite next year seems very promising.

**Comment by xgdgsc** [comment]
I compiled the arm version with rafael/dotnet branch at https://github.com/xgdgsc/EarTrumpet/releases/download/1/eartrumpet.7z
