### ISSUE TITLE
Audio levels reset on pc restart

### ISSUE THREAD

**Issue by YWI** [File-New-Project/EarTrumpet#309]
For games/discord/more apps the audio levels reset whenever I restart my PC how can I save them after a restart? They used to save.

**Comment by riverar** [comment]
In Windows 10, you can use `App volume and device preferences` to set default volume levels

![image](https://user-images.githubusercontent.com/475132/48972442-53f34f00-efdf-11e8-9de1-bc94b3254057.png)

**Comment by YWI** [comment]
So if I set them from there on startup they will be like that?

**Comment by riverar** [comment]
It should; try it.

**Comment by YWI** [comment]
It didn't.
Any advice, I'd really hope to fix this it's a lifechanger heh...

**Comment by riverar** [comment]
Closing this bug for same reason as https://github.com/File-New-Project/EarTrumpet/issues/291 tl;dr: Windows should remember this stuff. We'll have a future version that has additional controls too, stay tuned.

**Comment by YWI** [comment]
helloo
