### ISSUE TITLE
Xbox app constantly resetting volume

### ISSUE THREAD

**Issue by stamminator** [File-New-Project/EarTrumpet#31]
In the Windows 10 Xbox app, the volume control only appears once a video has already started playing (which means it'll blow your eardrums out for a split second before you can adjust it), but that's not the real issue. When you do adjust the volume, it resets to 100% in between every video. Even reopening the same video back to back, it resets the volume. I'm not having this issue for other apps, just the Xbox app. Running v1.2.0.0.

**Comment by Wuestengecko** [comment]
As it's a metro app, this might be related to #23 - also see the blog post: https://blogs.msdn.microsoft.com/windowsappdev/2012/08/23/media-playback-what-you-need-to-know-about-playing-media-to-make-your-app-shine-in-windows-8/ (it's the same i linked there)
