### ISSUE TITLE
Unnecessary association of sound streams in version 2.0.7.0

### ISSUE THREAD

**Issue by MDMAoverdose** [File-New-Project/EarTrumpet#312]
The last published version - "2.0.7.0", in difference from old - "1.3.2.0", unites similar programs in one sound stream. I start - "Tor Brouser" and "Firefox Quantium" in "Windows 10", and the latest version of your program, unites these browsers in one sound stream. The old version of EarTrumpet, shows them separately. Separately sound stream of Tor, and separately sound stream of Firifox. I ask to correct it whenever possible, to make that the new version divided these programs as well as old.

**Comment by GoldenTao** [comment]
We still let you work on them separately, just right click on any app and we'll popup a window with all the individual sessions.

We're looking into what other options there are when it comes to apps using the same browser for different purposes (like FireFox and the Firefox Dev version)
