### ISSUE TITLE
Feature Request: Hotkey to increase/decrease volume by % amount set in settings

### ISSUE THREAD

**Issue by datadragon00** [File-New-Project/EarTrumpet#322]
It would be good to have a user defined hotkey to increase or decrease the volume by a percentage amount you set in settings. For example ctrl-right arrow to increase volume by 5% or 10% at a time (as you set), or ctrl-left arrow to decrease volume by 5% or 10% at a time. Another one could be set to mute such as ctrl-down arrow puts the volume to 0% if you set to decrease by 100%. 
I think the hotkey should modify the volume of the currently used application rather then master. Currently you have to use the hotkey to open the panel, up or down arrow to the application being used, and then left and right arrows to modify.

**Comment by jupiter104** [comment]
I'd really like this as well. It would be great if you could assign hot keys for individual programs to increase and decrease their volumes.
