### ISSUE TITLE
New Windows 10 install, right click doesn't give option to move app to anouther output

### ISSUE THREAD

**Issue by Cur76** [File-New-Project/EarTrumpet#323]
Just finished a Windows 10 install and added EarTrumpet. Right clicking any applications in the app only shows the slider, the arrows I am used to are no longer available. I have tested with Firefox, Discord. Advice appreciated.

**Comment by Cur76** [comment]
I should also note I have tried running the app as administrator.

**Comment by riverar** [comment]
Hi there, can you provide a screenshot?

**Comment by Cur76** [comment]
https://imgur.com/a/L8Lx3I2

**Comment by riverar** [comment]
Hm, isn't clear what the issue is here. It seems you right-clicked a Firefox session group and we're showing you all the sessions (e.g. tabs) correctly.

**Comment by Cur76** [comment]
Sorry. Maybe I'm not understanding the app. Previous install I had on my old Windows 10 laptop had the option to send the app to another audio device with arrows stacked horizontally in the top tight hand corner when you right clicked the app. I do not see how to do this with this particular install, is there a manual or something I can reference?

**Comment by riverar** [comment]
Oh I see. Did you install EarTrumpet from the Windows store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)? Are you on the latest version of Windows 10? (e.g. Version 1809)

**Comment by Cur76** [comment]
Yes, installed from the store. I am running 2.0.7.0 according to the about section.

**Comment by Cur76** [comment]
Just tested on my old laptop it's the same version and some apps allow movement, while none of them do on this install. The audio devices are Nvidia ti1070 hdmi output and onboard realtek chip. I can provide more info if needed or debug info if that's available.

**Comment by riverar** [comment]
What version of Windows?

**Comment by riverar** [comment]
Sounds like you're on a version of Windows earlier than 17134 (aka April 2018 Update, or "Redstone 4") where moving audio sessions isn't supported.

**Comment by Cur76** [comment]
Windows 10 Pro, 1709/Build 16299.847

**Comment by Cur76** [comment]
Ahh I will update, it's a fresh install. I'll update this thread when I do, thanks.
