### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by MrLBX** [File-New-Project/EarTrumpet#33]
Hi guys, have installed on windows 10 pro  and am getting a Net framework unhandled exception error when left clicking the icon on tray. it only seems to be doing it on   my main account and works fine under a guest account. i suspect it is a potential conflict with another program. Heres the error log. it may as well be russian as i have no idea what it means. any ideas? 
Mucho Luvos

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at EarTrumpet.Services.UserSystemPreferencesService.get_UseAccentColor()
   at EarTrumpet.Services.ThemeService.GetWindowBackgroundColor()
   at EarTrumpet.Services.ThemeService.UpdateThemeResources(ResourceDictionary dictionary)
   at EarTrumpet.MainWindow.UpdateTheme()
   at EarTrumpet.MainWindow.TrayIcon_Invoked()
   at System.Action.Invoke()
   at EarTrumpet.TrayIcon.TrayIcon_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

EarTrumpet
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
##     CodeBase: file:///C:/Program%20Files%20(x86)/Ear%20Trumpet/EarTrumpet.exe

PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll

WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll

System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll

PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll

UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by riverar** [comment]
Can you open Regedit and navigate to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize and attach a screenshot? If a folder doesn't exist, send a shot at the lowest you can go.

**Comment by MrLBX** [comment]
here you go :D 
![reg](https://cloud.githubusercontent.com/assets/14791673/10026691/1f05fdbc-615b-11e5-8590-30071c92f3f0.jpg)

**Comment by MrLBX** [comment]
interesting. if i change to a high contrast theme it works

**Comment by riverar** [comment]
Yep, and now if you change back, it works again right? I presume this means you never previously changed your colors before.

**Comment by MrLBX** [comment]
no if i change it back it stops working again

**Comment by riverar** [comment]
Can you screenshot the Personalization control panel (with the color palette) and the Control Panel\All Control Panel Items\Personalization window? Appreciate it! Pretty sure how we'll fix this but was just curious.

**Comment by MrLBX** [comment]
you can pop in on teamviewer if you like. follow me on twitter and il dm you the login

**Comment by MrLBX** [comment]
![personalization](https://cloud.githubusercontent.com/assets/14791673/10027129/50ad95e4-615d-11e5-9160-8ddc42c7da29.png)

**Comment by MrLBX** [comment]
![palette](https://cloud.githubusercontent.com/assets/14791673/10027240/dced99e6-615d-11e5-9480-0ed2d2a3bb9e.png)

**Comment by MrLBX** [comment]
i think ive fixed it :D

**Comment by MrLBX** [comment]
well you pointed me there lol

**Comment by riverar** [comment]
Thanks we'll incorporate a fix too.

**Comment by MrLBX** [comment]
Legends. and thanks for the software. il be sure to point people in your direction

**Comment by riverar** [comment]
Can you reproduce the issue and screenshot HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize

**Comment by riverar** [comment]
Standing by for your reply.

**Comment by hashhar** [comment]
The error was due to the absence of an Accent Colour defined for the user account? How'd you fix this?

I am asking as I've started contributing to .NET projects to practice as I've recently started learning it and have started by fixing such simpler issues on the OpenLiveWriter project.
