### ISSUE TITLE
Move volume bars via arrow keys

### ISSUE THREAD

**Issue by homezonebenny** [File-New-Project/EarTrumpet#330]
In the normal Windows 10 mixer you can click on a bar, and after that you can move it 1 step up and down with the arrow keys.
That's not possible with EarTrumpet.

Means if you want exactly 46 volume, you have to hit this right with the left click and hold moving mouse.

**Comment by riverar** [comment]
@homezonebenny  EarTrumpet supports this today. Can you provide your EarTrumpet version number in Settings/About?

**Comment by homezonebenny** [comment]
1.3.2.0...
I can't move the bars via the arrow keys on my keyboard. I can hover it and scroll in 2er steps via scrollwheel. But not in 1er steps with they keyboard arrows itself :-\

**Comment by riverar** [comment]
@homezonebenny You're on a very old version of EarTrumpet. Please grab the latest from the Microsoft Store https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp

**Comment by Tonio78370** [comment]
Until the last update the adjustment through the arrow keys worked but with the last version, 2.1.1.0, this disappeared. Could you please re-activate this; Windows 2-step adjustment is a pain in the neck, it's either too loud or too soft... Thanks
