### ISSUE TITLE
Does not Launch - Win10 1809 

### ISSUE THREAD

**Issue by fursty** [File-New-Project/EarTrumpet#332]
Great idea, desperately needed but does not launch... running in task manager and does nothing

**Comment by riverar** [comment]
@fursty Yikes, not good. do you see any corresponding .NET events in the Application event log? Should give us more insight.

**Comment by riverar** [comment]
Hey @fursty, did you grab EarTrumpet from the overflow menu? See animation below:
![welcome](https://user-images.githubusercontent.com/475132/52973296-6ed12780-3372-11e9-9c11-b3f0c4b4bcd1.gif)

**Comment by riverar** [comment]
Haven't heard back, please re-open this issue as needed. Thanks!
