### ISSUE TITLE
Ghost window appears in task switcher after switching from tablet mode to non-tablet mode

### ISSUE THREAD

**Issue by dean1012** [File-New-Project/EarTrumpet#335]
Sorry to reopen but this issue is still present. Running version 2.0.8.0 on Windows 10 1809 17763.316. Reposting here as a new issue since commenting on the other one didn't reopen it.

Have EarTrumpet open. Activate tablet mode. Deactivate tablet mode. EarTrumpet now shows a phantom window in task switcher. Opening the flyout removes the phantom window until tablet mode is activated again.

#294 isn't fixed.

_Originally posted by @dean1012 in https://github.com/File-New-Project/EarTrumpet/issues/294#issuecomment-466055624_

**Comment by riverar** [comment]
Re-opened original issue, thanks @dean1012.
