### ISSUE TITLE
Question: Simultaneous Output to Multiple Playback Devices

### ISSUE THREAD

**Issue by davidshq** [File-New-Project/EarTrumpet#337]
Is there a way to send output to multiple playback devices simultaneously?

For example, to have a HDMI cable and an audio cable plugged in, the HDMI going into a TV and the audio cable going into a speaker system and both playing the same audio?

**Comment by majocha** [comment]
You would propably need something like [VOICEMEETER](https://www.vb-audio.com/Voicemeeter/index.htm) for that.

**Comment by davidshq** [comment]
Thanks!

**Comment by SerVB** [comment]
@majocha , such programs can output to up to two devices simultaneously. What if I want three devices?
