### ISSUE TITLE
EarTrumpet is another language? How to fix it?

### ISSUE THREAD

**Issue by NodoNorte** [File-New-Project/EarTrumpet#338]
![anotacao 2019-03-06 114438](https://user-images.githubusercontent.com/48289896/53893787-45b4c600-4005-11e9-87c6-b9f9b66ad032.jpg)
My Windows 10 is Portuguese Language but this app don't, how can I fix it? Help me please!

**Comment by riverar** [comment]
Hi @NodoNorte, that's weird. Did you change your system font?

Can you run these commands and provide the two text files? (Drag them into this issue.)
`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts" >fonts.txt`
`reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontSubstitutes" >substitutes.txt`

**Comment by NodoNorte** [comment]
I do this and nothing has changed. :/ 

And I dont change system font too.

**Comment by NodoNorte** [comment]
I wanna run these commands on CMD?

**Comment by NodoNorte** [comment]
![anotacao 2019-03-08 113744](https://user-images.githubusercontent.com/48289896/54038318-a0c9f280-4196-11e9-9231-f0b168e0282a.jpg)

**Comment by NodoNorte** [comment]
![anotacao 2019-03-08 114015](https://user-images.githubusercontent.com/48289896/54038471-01592f80-4197-11e9-919d-6df24587d997.jpg)

**Comment by tomverhoeff** [comment]
I was able to reproduce this issue by making the following change in the registry, which sets the default font for messageboxes to the symbol font. Changing it to a normal font (default included below) "fixes" the issue.
### Set MessageFont to Symbol
`[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
"MessageFont"=hex:eb,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
  00,00,00,01,00,00,00,00,53,00,79,00,6d,00,62,00,6f,00,6c,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00`

### MessageFont Default (on my machine)
`[HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics]
"MessageFont"=hex:eb,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,00,00,90,01,00,00,\
  00,00,00,01,00,00,05,00,53,00,65,00,67,00,6f,00,65,00,20,00,55,00,49,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00`

**Comment by riverar** [comment]
Thanks @tomverhoeff, @NodoNorte what's your `HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics` look like?

**Comment by GoldenTao** [comment]
Any update on this @tomverhoeff @NodoNorte or did it go back to the correct language?

**Comment by riverar** [comment]
Actually, going to close this. Please re-open if needed, thanks.
