### ISSUE TITLE
Windows 10 - Netflix App volume control works inconsistently

### ISSUE THREAD

**Issue by ghost** [File-New-Project/EarTrumpet#34]
Running version 1.2.0.0 on Windows 10 Professional, 64-bit.

This is difficult to reproduce consistently, but it is happening frequently enough that I imagine it wouldn't take more than a few attempts to do so.

When altering the volume of the Netflix app from the Windows Store the volume control sometimes has no effect. Moving the slider seems to do nothing. I can change the volume slider to no effect and then mouse away from the Ear Trumpet volume mixer, and when opening the Ear Trumpet volume mixer again the volume of the Netflix app is back at 100.

It takes exiting the Ear Trumpet application and restarting it. This is not consistent either, I may have to exit and restart Ear Trumpet a few times before the volume control for Netflix works properly.

Additionally, it appears that it will sometimes not recognise the Netflix app and requires the Netflix app to be restarted for the entry in Ear Trumpet to register.

**Comment by riverar** [comment]
Yep, have seen this. Our working theory is that a buffer deep in the core of Windows is filling up with invalid volume requests, which takes a bit to clear out. (You can force this by restarting the Windows Audio service.)

We'll need to dig deeper, thanks for the report.

**Comment by GShocked** [comment]
This fixed it for me: http://superuser.com/questions/1117267/win-10-netflix-app-bug-constant-100-volume

**Comment by riverar** [comment]
Closing this bug as it's old now.
