### ISSUE TITLE
Is it possible to limit all other applications' volume under specific level ?

### ISSUE THREAD

**Issue by GreatFireWall** [File-New-Project/EarTrumpet#340]
For example: 
Some game's audio is very slow, you must make the volume level upper.
Now, the trumpet volume level is 20, the system and the game volume are 20 too. 
If I slide up the volume of game to 50, the trumpet volume will auto up to 50, now, if a new application launch, it will also up to 50, **this is not expected**, is it possible to limit all other application volume level at 20 except the game ?

**Comment by GoldenTao** [comment]
Not sure I totally understand this one sorry, are you saying when you slide the Master Volume up to 50% that your game slider also goes up to 50%?  Or do you mean that your game is now a lot louder, but you want it to stay at the original volume?

If it's the second one, that's how the Windows sound system works, each app is a % volume of the master device volume, so 20% for you game is 20% of the master volume.  If you drag up the master volume, you'd have to decrease the game slider to keep it lower.

Let us know if you're still having this issue and reopen if needed.

**Comment by GreatFireWall** [comment]
Sorry, I described the problem too complicated.

As the follow image, 1, 2, 3 rows are 20, 4 is 100, that's my expected. 
Now, if a new application launch, it will also 100, I want any other new application limit to 20.

![image](https://user-images.githubusercontent.com/4510984/58867871-cb700c80-86ed-11e9-8ba0-6ba504aab922.png)

**Comment by GoldenTao** [comment]
Ah, that makes sense. We've got an add-on in the works for this kind of thing. See #51 where we'll update when the add-on is ready!

**Comment by GreatFireWall** [comment]
I think this is a bit different from "remember volume", I mean it will limit all any other new launch app even if they never set the volume. 😄

**Comment by GF-Huang** [comment]
After 2 years, I found out that I still need this feature. Is there any progress?

My idea, is it possible to monitor all new sound programs which never set the volume (maybe hook at new process start or the process first time appear in EatTrumpet control bar, sorry I don't how EatTrumpet implements this), when found, adjust its volume to 20, as described earlier.

**Comment by riverar** [comment]
@GF-Huang Try our [experimental dev build](https://eartrumpet.app/). It contains EarTrumpet Actions which should allow this. Give it a shot!

**Comment by GF-Huang** [comment]
Thanks your quick response!

**Comment by GF-Huang** [comment]
By the way, I guess you should be very familiar with the windows audio system. Don't know if you play games? Some games sound are much low than other games or the system sound even if I set their 100 in EarTrumpet. In other words, some games sounds like 20 even if you set it to 100. But if I wear headphones, there is no such problem. (Related games: Skyrim 5, Red Dead Redemption 2)

Every time I play these games, I need to turn up the volume of the entire system and this game, and then turn down the volume of all other programs, so that all sounds sound the same.

Do you have any clues on this? This problem has troubled me for many years. Thanks !!!

**Comment by GF-Huang** [comment]
@riverar Hey, is it possible to match all process by without enter a process name here?

![image](https://user-images.githubusercontent.com/4510984/119407641-1807e480-bd17-11eb-94e5-98b3e128289d.png)

**Comment by riverar** [comment]
> @riverar Hey, is it possible to match all process by without enter a process name here?
> 
> ![image](https://user-images.githubusercontent.com/4510984/119407641-1807e480-bd17-11eb-94e5-98b3e128289d.png)
> 

No, but I can look into adding that.

**Comment by riverar** [comment]
@GF-Huang The process start trigger is actually broken, so I'll need to fix that first.

**Comment by hlebushekhub** [comment]
Is it yet to be fixed? I have the same problem: when any new games launching they set the volume to 100% which is very loud for me. I really need that limit the launched any app option without setting any processes to the Actions
