### ISSUE TITLE
chrome is not showing in ear Trumpet

### ISSUE THREAD

**Issue by D1N35HV** [File-New-Project/EarTrumpet#341]
> 
> 
> @localizeteam Can you provide more details? What version of EarTrumpet? What version of Chrome? What version of Windows 10?

@riverar i am using EarTrumpet V.2.0.8.0 windows 10 1803 and chrome 73.0
this issue is coming from the day I reinstalled my Ear Trumpet.

**Comment by riverar** [comment]
@localizeteam Can you provide more details? What version of EarTrumpet? What version of Chrome? What version of Windows 10?

**Comment by riverar** [comment]
@D1N35HV Weird. Can you open EarTrumpet settings, click Collect troubleshooting data, and send that to `team @ eartrumpet.app`? Thanks.

**Comment by riverar** [comment]
@D1N35HV Got your email, doesn't appear Chrome is playing audio. Can you play a YouTube video and verify it does not appear in EarTrumpet? If so, can you gather data again and send it to the same email?

**Comment by riverar** [comment]
This was fixed offline via email. We reset the persisted endpoint for all the user's apps using Reset button in App Volume and Device Preferences.

**Comment by smirki** [comment]
+1 to this, it helped a ton!

**Comment by zibarbar1** [comment]
who have the same problem that eartrumpet not showing google chrome sound and sound not working i fix it by going to start/settings/system/sound/ app volume and device preferences down there you will find google chrome make sure is default for both output/input . like it helped 👍 hami

**Comment by appsss77** [comment]
Me too. Please tell me how to solve it.
