### ISSUE TITLE
Slovenian language needs plural resource option for tooltip

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#343]
Jernej points out that the resource `{1} percent volume - {0}` needs a plural form to read less awkward in the Slovenian language (https://twitter.com/jernej__s/status/1110990523014266886)

**Comment by jernejs** [comment]
Depending on the translation framework you use, this might be quite hard to implement (Slovenian needs different plural forms for 1, 2, 3-4 and everything else, and these repeat for every 100 items; other languages have different rules). gettext has full support for this, and there's a pure .NET implementation in [ngettext](https://github.com/neris/NGettext).

**Comment by riverar** [comment]
@jernejs We may consider removing "percent", and replace with `%`. (This text is used by screen readers.) That would alleviate this issue, right?

**Comment by jernejs** [comment]
That'd work.

**Comment by davuxcom** [comment]
Sorry for such a long delay here @jernejs, this issue is now fixed in 2.1.4.0, and Slovenian language is actually included now.  Thanks for your help localizing EarTrumpet!
