### ISSUE TITLE
Ear Trumpet won't work Windows 10 1809 

### ISSUE THREAD

**Issue by Zephmarie** [File-New-Project/EarTrumpet#345]
Installed EarTrumpet rom Microsoft store today and placed icons on start menu and taskbar. It won't launch. When I left click the icon on taskbar a window opens that says Welcome  to EarTrumpet but the only option is "Close." I just got my laptop back with newly installed Windows 10 1809. Audio volume is dismal so did some searching and found EarTrumpet, hoping it would help. No luck.  Hope you can help! Thanks.  p.s. won't even launch when I go back to Microsoft store and click "Launch" from there, although says it's installed.

**Comment by riverar** [comment]
Hi @Zephmarie, did you grab our icon out of the overflow area?

![](https://user-images.githubusercontent.com/475132/52973296-6ed12780-3372-11e9-9c11-b3f0c4b4bcd1.gif)

**Comment by Zephmarie** [comment]
Hi. Not sure what you mean, but the image you posted is what I get when I left click the icon.

**Comment by riverar** [comment]
@Zephmarie Yep, that's our one-time welcome window that instructs users to find our icon (it has the same icon as Windows does). Some more examples of what we look like:

https://github.com/File-New-Project/EarTrumpet/blob/master/README.md

**Comment by Zephmarie** [comment]
Hmmm. Well now I've restarted laptop, icon is no longer on taskbar, but is in Start menu. Repinned to taskbar and now it won't even allow me to left click. Nothing happens. It's just a little trumpet icon. If I right click icon one option is EarTrumpet, one option is Unpin from taskbar. I chose EarTrumpet, left click, nothing. Right click "Open" or "Run as administrator." Neither option does anything.

**Comment by riverar** [comment]
@Zephmarie I think there's some confusion about what our app is. EarTrumpet does not launch an app window and auto-starts with Windows. You don't need to launch it from the shortcut (nor will anything happen).

EarTrumpet adds an icon to the tray in the form of a speaker icon (see graphics above). You can left/right click that icon to interact with our app.

**Comment by Zephmarie** [comment]
Thank you. But I have not found any way to be able to interact with the app. Right or left click on little speaker icon does nothing. The only way I got the little speaker icon to appear on my Start menu and taskbar was by clicking the 3 little dots to the right of "Launch" on the Microsoft store page where I downloaded from. But even clicking "Launch" from there nothing happens.

**Comment by GoldenTao** [comment]
@Zephmarie EarTrumpet won't show any UI when it starts running (except the welcome screen that shows once when you first run EarTrumpet), it also won't appear on your Taskbar, it only shows up in your Tray icons (usually bottom right, next to the clock)

In EarTrumpet's case, it's icon is the same as the normal Windows Volume icon, but because of the way Windows works, you'll likely find it in the overflow area which you can access by clicking the up arrow button in the tray area.

It looks like you've been able to get to the EarTrumpet flyout, that window with the 4 volume bars at 100% is the EarTrumpet Flyout.

**Comment by riverar** [comment]
@Zephmarie Oh cool, EarTrumpet is working great then. EarTrumpet consists of the flyout you opened (icon on the right of the taskbar) and the EarTrumpet Volume Mixer window you opened earlier. That's everything our app offers. 👍

Were you expecting something different? I can try to point you in the right direction of other apps if we don't do what you need.

**Comment by Zephmarie** [comment]
Okay. Thanks. But shouldn't the volume increase when I have the EarTrumpet slider all the way to 100? It doesn't change the volume level one way or the other. When I right click the speaker icon, there is a check mark next to "Speaker/HP (Realtek High Definition Audio). When I open the Volume Mixer,  only *that* slider effects any change in audio volume. Even with all 3 sliders set to 100 the audio is very low. I do know that the version Windows 10 I got (1809) does have audio problems but was hoping this app would allow me to increase the volume. Wah.

**Comment by Zephmarie** [comment]
> 
> 
> @Zephmarie EarTrumpet won't show any UI when it starts running (except the welcome screen that shows once when you first run EarTrumpet), it also won't appear on your Taskbar, it only shows up in your Tray icons (usually bottom right, next to the clock)
> 
> In EarTrumpet's case, it's icon is the same as the normal Windows Volume icon, but because of the way Windows works, you'll likely find it in the overflow area which you can access by clicking the up arrow button in the tray area.
> 
> It looks like you've been able to get to the EarTrumpet flyout, that window with the 4 volume bars at 100% is the EarTrumpet Flyout.

Thank you G-Tao. As I explained to the kind Riverar, there is just no difference at all, either increasing or decreasing audio using the slider for EarTrumpet. ;(

And yes, it does appear in the overflow. Thanks a ton you guys.
