### ISSUE TITLE
Eartrumpet stopped working after updating to 2.1.0.0

### ISSUE THREAD

**Issue by Tonio78370** [File-New-Project/EarTrumpet#347]
Hello,

I received the update today on both of my computer, Windows 10 Home, and the program won't launch anymore. Uninstall and reinstall doesn't solve the problem, neither resetting the sound properties. Can you help?

Thanks

**Comment by SW1FT** [comment]
I'm having this issue as well.

**Comment by riverar** [comment]
Hey all, we found a problem after shipping 2.1.0.0, sorry about that. We fixed the problem and sent an update to the Store (2.1.1.0) but we're waiting for the Store to finish certification. This should get cleared soon (today)!

**Comment by Katoru** [comment]
Ok, thanks for the feedback, i am having the same problem too.

**Comment by riverar** [comment]
Update: EarTrumpet 2.1.1.0 is now being delivered to the Store. It should land on your machines momentarily, if it hasn't already.

**Comment by Katoru** [comment]
Update happened few seconds ago, as planned.
EarTrumpet is now functioning. Thank you !
