### ISSUE TITLE
Change default device and default communication device simultaneously

### ISSUE THREAD

**Issue by orenbullock** [File-New-Project/EarTrumpet#348]
This issue is sort of a continuation of issue #71.

My problem mostly pertains to using Discord, but it does happen in other applications as well.
I like to use/talk on Discord using both my headphones (USB/DAC) and speakers (analog input) depending on if I need good audio for games, my ears need a rest, etc.

EarTrumpet is typically great for moving between the two, however, since my headphones are the "default communications device" on the computer, Discord will always play through them regardless of what the "default device" is (which is what EarTrumpet changes). 

If you guys could implement a settings option to change either/or/both the "default communications device" and "default device" then I think this problem would be solved.

**Comment by Luckz** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/71#issuecomment-396823592 makes it sound like this was _resolved_ in version 2.0, but it isn't so?

**Comment by orenbullock** [comment]
> [#71 (comment)](https://github.com/File-New-Project/EarTrumpet/issues/71#issuecomment-396823592) makes it sound like this was _resolved_ in version 2.0, but it isn't so?

From what I've seen, there still isn't a solution. There is no option to manipulate the "default communication device" in addition to the "default device"

**Comment by davuxcom** [comment]
The comment in #71 refers to changing for Console AND Multimedia rendering, which isn't related to also changing the communication device at the same time.  We are aware of the request and this thread is tracking moving the comm device when moving the default device.

**Comment by VapidLinus** [comment]
**Example use case:** This is annoying in many games that use VOIP. A lot of them use the communication device for voice audio, while using the audio device for game audio. You generally want all sound to come from the audio device you're currently using - so whenever I want to switch between my audio devices, I still have to open the legacy sound menu to change both.

**Comment by Luckz** [comment]
> I still have to open the legacy sound menu to change both.

FWIW if you don't need the many other special features of EarTrumpet on a daily basis, both SoundSwitch and Audio Switcher can change devices for you much faster than the Sound Control Panel route. The latter way drove me crazy over time.
(Both can also be installed via scoop, the first tool from a third party bucket.)

**Comment by VapidLinus** [comment]
Thank you @Luckz. SoundSwitch was perfect for me. I will keep both installed.

**Comment by Aasikki** [comment]
This would be a nice thing to have. I play quite a bit in vr and having to go to discord or windows audio settings settings every time to change the output device is annoying. SoundSwitch works well but I still need EarTrumpet for the volume mixer, so having this option would eliminate having to use two applications.

**Comment by TIPConsulting** [comment]
Bump.  I would also really like this to set both (or all) default device outputs. Console, communication, and possibly media

**Comment by TIPConsulting** [comment]
Here is an implementation of a registry policy object that can change all 3 different audio device roles on windows 

https://github.com/frgnca/AudioDeviceCmdlets/blob/master/SOURCE/AudioDeviceCmdlets.cs#L412

I just integrated this code into a project, so I can confirm that this method works. It's fairly simple to extract the core functionality out of his commandlet implementation

**Comment by LukasDoubleU** [comment]
I implemented this and other features over at my fork.
There is a new setting to "change the default communication" device.
If enabled, EarTrumpet will change the comms device as well when changing the default output device.

If you want you can test the pre-release:
https://github.com/LukasDoubleU/EarTrumpet/releases
