### ISSUE TITLE
Setting a shortcut can stop keys from working globally

### ISSUE THREAD

**Issue by equin0x80** [File-New-Project/EarTrumpet#351]
Win10 Pro 64-bit. Apparent bug when setting up a shortcut key in Settings > Shortcuts.

Focus the Your Shortcut box and press a few keys, like say the letters F and G.

These keys then no longer work at all in other applications, such as Notepad or the Chrome browser! They just don't do anything. (However, if you press these keys with Shift at the same time, you can still get a capital letter. But pressed alone, they do nothing.)

It seems that EarTrumpet is somehow locking the key resource so other apps can't see it...? Exiting EarTrumpet allows the keys to work again.

**Comment by riverar** [comment]
I'm a bit confused. You want to assign a shortcut -- say to open the flyout -- and have that same combination also do something else in another app?

**Comment by equin0x80** [comment]
No, I mean after pressing the key in EarTrumpet's settings box, that key literally doesn't work if you switch to another window. You can't type that letter any more. It's like EarTrumpet has acquired a lock on the key and it can no longer send keystrokes to other windows.

**Comment by riverar** [comment]
Got it, thanks @equin0x80!

**Comment by GoldenTao** [comment]
Thanks for the bug report, we've got a fix ready for release soon.

**Comment by davuxcom** [comment]
Fixed in 2.1.2.0
