### ISSUE TITLE
Volume cannot be adjusted with arrow keys

### ISSUE THREAD

**Issue by Tonio78370** [File-New-Project/EarTrumpet#352]
Until the last update the volume adjustment through the arrow keys worked but with the last version, 2.1.1.0, this disappeared. Could you please re-activate this; Windows 2-step adjustment is a pain in the neck, it's either too loud or too soft... Thanks

**Comment by riverar** [comment]
Thanks @Tonio78370 we've reproduced this.

**Comment by davuxcom** [comment]
Fixed in 2.1.2.0
