### ISSUE TITLE
Can't run the vs project (The type or namespace name 'windows' could not be found)

### ISSUE THREAD

**Issue by Heacien** [File-New-Project/EarTrumpet#353]
The error occurs on a few rows, like `using Windows.ApplicationModel;`.

I can't find any missing references or dependencies.
*I should already have all needed Win 10 UWP packages installed.*

**Comment by riverar** [comment]
Hey @Heacien, are you using the compilation documentation?
https://github.com/File-New-Project/EarTrumpet/blob/master/COMPILING.md

**Comment by Heacien** [comment]
@riverar thanks, I couldn't find it - I'll give it later a try

**Comment by riverar** [comment]
@Heacien No problem, let us know if you run into any further problems!
