### ISSUE TITLE
Move Fluent design to a separate project and make a library out of it.

### ISSUE THREAD

**Issue by NickAcPT** [File-New-Project/EarTrumpet#354]
I've been using EarTrumpet for a long time and I now noticed that it uses WPF.
So, my suggestion is to make a separate and easy to use managed library for enabling the use of Acrylic materials (and possibly other elements of the Fluent Design system) for WPF.

Doing this would make it easy to fix anything if Microsoft decides down the line to change something regarding the API itself.

**Comment by riverar** [comment]
Thanks @NickAcPT, it's already pretty isolated from the rest of EarTrumpet and easy to reuse/support. We're not really interested in making a managed library; the code is there if anyone needs it though.
