### ISSUE TITLE
Icon should not show x when not muted and volume is at 0

### ISSUE THREAD

**Issue by DragoCubed** [File-New-Project/EarTrumpet#355]
I think this is related to #290. It was apparently intended behaviour. I hope that gets changed to be like the Windows icon.

**Comment by riverar** [comment]
@DragoCubed Hm, we're doing exactly what Windows is doing. Are you seeing different behavior?

![x](https://user-images.githubusercontent.com/475132/56755960-91523900-6745-11e9-8163-a9bdf7a26d26.gif)

**Comment by DragoCubed** [comment]
Try unmuting it when you hit 0.

When I lower my volume to 0 with my keyboard and then unmute it, the icon shows that it is muted even though it isn't.

**Comment by riverar** [comment]
@DragoCubed Oh wow, interesting. Thanks!
