### ISSUE TITLE
cannot uninstall

### ISSUE THREAD

**Issue by wghassen** [File-New-Project/EarTrumpet#356]
Ear Trumpet is not listed under Programs and Features, and when i try to uninstall it from the apps and features menu nothing happens after clicking the uninstall button.i am trying to reinstall the app not remove it completely because i like it better than the default windows volume slider, but the app doesn't run anymore and i can't even bring back the old volume slider.
it is still listed in the apps list and i can't even install again from the windows app store in order to rewrite the existing app.

Edit: i managed to bring the old volume slider with some tweaking in the registries but eartrumpet still wouldn't install or reinstall.

**Comment by githubbercat57** [comment]
It uninstalled off mine I'm running windows 10 home, 64 bit, build 17164, 400 ram, but it took several clicks on the mouse before it disappeared. The thing I see is that it doesn't show up on revo uninstaller.

The kitty

**Comment by runbei99** [comment]
Ditto. No Windows uninstall, no Revo uninstall. No folder in Programs or x86.

**Comment by davuxcom** [comment]
- Open Start menu
- Scroll down to EarTrumpet
- Right click, Uninstall

EarTrumpet should be uninstalled.
If EarTrumpet isn't in Start menu, it isn't installed.

Wait 2 minutes.

Win+X, start Powershell and run this command:
```get-appxpackage | ? Name -like *EarTrumpet*```

What's the output?

If it's empty, EarTrumpe isn't installed.

**Comment by davuxcom** [comment]
Closing this out.

- EarTrumpet is only distributed as a packaged app. Packaged apps can be uninstalled via Settings or powershell.
- If you installed some unofficial version, it won't have an uninstaller.
- Tools like Revo uninstaller will damage your system, don't use them.
- EarTrumpet will be installed in the WindowsApps folder, not %ProgramFiles% or other classic locations.

**Comment by eterror** [comment]
This is a WindowsApp! :)

Win+X, start Powershell and run this command:

to check (if is nstalled):
get-appxpackage | ? Name -like *EarTrumpet*

to uninstall:  
Get-AppxPackage *EarTrumpet* | Remove-AppxPackage
