### ISSUE TITLE
Microsoft Edge "Progressive Web App" Support

### ISSUE THREAD

**Issue by mortyobnoxious** [File-New-Project/EarTrumpet#359]
I installed Spotify as "Progressive Web App" through Microsoft Edge.

Here's the Windows Volume Mixer showing Spotify icon above the volume bar:
![image](https://user-images.githubusercontent.com/42044258/57568039-755bc200-73ea-11e9-9b16-a3024d63eb13.png)

Here's EarTrumpet showing Microsoft Edge icon instead of Spotify icon:
![image](https://user-images.githubusercontent.com/42044258/57568036-712fa480-73ea-11e9-8519-d0ae872d6166.png)

Could you please add support for this.

**Comment by riverar** [comment]
Closing this as Microsoft Edge (legacy) was discontinued and Microsoft Edge (Chromium) doesn't show any icons.
