### ISSUE TITLE
Notification overlaps autohide taskbar

### ISSUE THREAD

**Issue by mathijshenquet** [File-New-Project/EarTrumpet#36]
My taskbar is set to autohide on the left hand side. The EarTrumpet notifications overlap the taskbar while native windows 10 notifications dont. This is illustrated in the attached screenshots

Native notification
![native](https://cloud.githubusercontent.com/assets/242143/10362705/836586a4-6db0-11e5-8d18-652ce61a5009.jpg)

Trumpet's notification
![trumpet](https://cloud.githubusercontent.com/assets/242143/10362735/b4dd8dee-6db0-11e5-849a-94c5fc19219c.jpg)

**Comment by ckaotik** [comment]
Also happens on "regular" bottom task bar.
