### ISSUE TITLE
EarTrumpet publisher name is "File-New-Project" in Apps & Features

### ISSUE THREAD

**Issue by jnm2** [File-New-Project/EarTrumpet#361]
![image](https://user-images.githubusercontent.com/8040367/57819498-afb0c080-7756-11e9-8d66-485a18907675.png)

**Comment by jnm2** [comment]
I'm really dumb. That's your name. 😂

**Comment by riverar** [comment]
@jnm2 Haha! Totally understand where you're coming from.
