### ISSUE TITLE
EarTrumpet 没法用鼠标点击“Windows 旧版”

### ISSUE THREAD

**Issue by swilosir** [File-New-Project/EarTrumpet#362]
第一个问题是右键鼠标移动到“windows 旧版”选项后，进行子选项的时候选框会消失
第二个问题是EarTrumpet 好像没有与“百度输入法”兼容。经常会崩溃

**Comment by riverar** [comment]
Translated:
```
The first problem is that when the right mouse is moved to the "Windows Old" option, the candidate box will disappear when the sub-option is made.

The second problem is that EarTrumpet does not seem to be compatible with Baidu Input. Often crash
```

**Comment by davuxcom** [comment]
@swilosir I installed Chinese language and didn't see what you describe, but I don't know if the translation is correct and I am understanding.

Would it be possible for you to take a video (screen recording) of the problem?

**Comment by yinyue200** [comment]
@davuxcom I think "Windows Old" means "Windows Legacy"

**Comment by yinyue200** [comment]
The issue is can't be reproduced in my PC. Could you provide more infomation?
