### ISSUE TITLE
EarTrumpet not starting after log in on Windows 10 Pro for Workstations

### ISSUE THREAD

**Issue by Kaan88** [File-New-Project/EarTrumpet#368]
After the May 2019 update eartrumpet doesn't start at boot. 
The entry in the startup section of task manager keeps getting disabled by itself. 
I've tried reinstalling the app but it didn't help.

**Comment by davuxcom** [comment]
Does EarTrumpet work as expected once you start it manually?

Search for ***Startup Apps***

Is the checkbox selected for EarTrumpet?

![image](https://user-images.githubusercontent.com/1456216/58639301-8726db80-82ab-11e9-9cf1-6b267fa3bddf.png)

**Comment by Kaan88** [comment]
The app does work fine. 

I can't find that section in settings, it doesn't show up on search either.

This is how my apps section looks

![image](https://user-images.githubusercontent.com/1260152/58639715-1c939100-82e7-11e9-9321-6f1d02ca8a14.png)


![image](https://user-images.githubusercontent.com/1260152/58639635-ddfdd680-82e6-11e9-8c98-6b38e21039ae.png)

**Comment by GoldenTao** [comment]
In your Task Manager, you should be able to click EarTrumpet and click Enable (bottom right)

**Comment by Kaan88** [comment]
> 
> 
> In your Task Manager, you should be able to click EarTrumpet and click Enable (bottom right)

That's the thing, it get's disabled by itself.

**Comment by GoldenTao** [comment]
Does it get disabled as soon as you enable it or after rebooting? If its the second, could you checked your Event Viewer -> Windows Logs -> Application and see if there is a .NET Error related to EarTrumpet that happens on boot?

**Comment by Originalme** [comment]
You should be able to find the screen easily enough. Just search for it in the settings pane.

![image](https://user-images.githubusercontent.com/132492/58724302-1954df80-8391-11e9-9859-6a05c1ec503f.png)

**Comment by Kaan88** [comment]
> Does it get disabled as soon as you enable it or after rebooting? If its the second, could you checked your Event Viewer -> Windows Logs -> Application and see if there is a .NET Error related to EarTrumpet that happens on boot?

I don't think it's ever enabled, when I reopen the task manager it shows as disabled. That startup apps is knowhere to be found, I have searched for it.

**Comment by riverar** [comment]
@Kaan88 Start > Run > `ms-settings:startupapps` and click OK. What happens? 

Can you also use regedit to check `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System` and see if the following values exist?

* SupportFullTrustStartupTasks
* EnableFullTrustStartupTasks

Also, check `HKCU\Software\Policies\Microsoft\Windows\Explorer` for `EnableAllStartupApplications`.

**Comment by Kaan88** [comment]
@riverar I had to add all of those keys manually, after that the menu became available and the app started at boot. Thanks!

It's greyed out though, for some reason. ![image](https://user-images.githubusercontent.com/1260152/58749693-8b542400-8478-11e9-9f6f-d1856198ffc6.png)

Workstation pro seems to have some weird defauşts.

**Comment by riverar** [comment]
@Kaan88 Strange indeed. We're going to install this now and see what's going on. Might be a Windows bug. Are you on a domain that's pushing out group policy?

**Comment by Kaan88** [comment]
I am not on a domain. It was an upgrade on october edition of workstation pro. 
It was fine until I upgraded to this May version. 

After the upgrade Windows also disabled "Receive Window Auto-Tuning Level" which limited my download speed to 10 mbits for no reason. 

After these seemingly random problems I went back to home edition. Everything is fine now. Thanks for all the help.

**Comment by Allavaz** [comment]
It's happening to me too on Windows 10 Education 1909. I tried reinstalling the app and the issue still persists.

**Comment by riverar** [comment]
We can't reproduce this, and several releases of Windows have passed, so may already be fixed. Please open a new issue to let us know if you hit this problem again.
