### ISSUE TITLE
Not showing streams from the Microsoft Edge Content Process

### ISSUE THREAD

**Issue by Cptbirdseye** [File-New-Project/EarTrumpet#37]
Both me and my husband are trying it out but it doesn't work.  It reckons we're not running any apps but we're running Microsoft Edge.

**Comment by riverar** [comment]
It only shows apps that have active sound sessions -- does it show up when you visit YouTube for example?

**Comment by riverar** [comment]
MicrosoftEdgeCP isn't being properly detected. Example: https://student.testmasters.com/portal/online/Test.aspx

Will investigate

**Comment by riverar** [comment]
Can't reproduce today with 1.2.0.0. Can you?
