### ISSUE TITLE
Battery Procent APP ?

### ISSUE THREAD

**Issue by opelit** [File-New-Project/EarTrumpet#370]
Hey , I don't know how to ask by DM so I wonder if we can see in the future an similar app which shows battery icon with battery %, by the current windows battery icon I can never guess what can be battery : half , 3/4 ? maybe less? The icon suck . Could love if I was able to switch between my power plans, enable battery saver and the rest of info while clicking the icon .

Loving EarTrumpet and using it since first beta !

**Comment by riverar** [comment]
You're in luck. My friend @petrroll did just that. Check out https://github.com/petrroll/PowerSwitcher

**Comment by opelit** [comment]
That's great ! Do you know if he will update it for 1903? I mean Light theme

**Comment by riverar** [comment]
Closing this, but @petrroll can help you out on that repository.
