### ISSUE TITLE
After Updating EarTrumpet, It doesn't work sometimes.

### ISSUE THREAD

**Issue by mortyobnoxious** [File-New-Project/EarTrumpet#372]
After Updating EarTrumpet through Microsoft Store, It doesn't work sometimes.

Disappears from taskbar. Opening it again doesn't work.

I have to end the task through Task Manager and open it again for it to work.

**Comment by davuxcom** [comment]
Interesting behavior - you are saying EarTrumpet isn't crashing, but it's stuck running while not giving you a tray icon to do anything.

Next time this happens, could you go into Task manager on the details page, find EarTrumpet.exe, right click and select ```Create Dump File``` and then share the .DMP file that it generates?

**Comment by mortyobnoxious** [comment]
File size is too big. 300+MB.

**Comment by riverar** [comment]
Hey there, please email team@eartrumpet.app and we'll set you up with private storage to send this file securely. Thanks!

**Comment by Stuke00** [comment]
Same thing is happening to me too on both my home PC and Work PC.  Both are on 1903.

**Comment by Kaedin** [comment]
Same issue here. W10 version 1903.

**Comment by davuxcom** [comment]
Can you guys estimate how many hours EarTrumpet runs before getting stuck?

**Comment by mortyobnoxious** [comment]
Hi, I send a .dmp file to the email provided above.

**Comment by davuxcom** [comment]
This bug should have been fixed in 2.1.4.0 by this commit: 91da1e5
