### ISSUE TITLE
Installing EarTrumpet without the Microsoft Store (sideloaded)

### ISSUE THREAD

**Issue by GoldenTao** [File-New-Project/EarTrumpet#374]
We're in the process of setting up a side loading version of EarTrumpet that will allow you to continue to receive updates even if you can't install EarTrumpet from the Store.

Please follow this issue for updates and we'll post here as soon as we launch it.

**Comment by Nonononoki** [comment]
Should the title be "Installing EarTrumpet with**out** the Windows Store (Side load version)"?

**Comment by rivman** [comment]
When Windows Store worked ? Please free us from such abominations :)
[https://imgshare.io/image/applicationframehost-qsljthgttk.2fdPX]

**Comment by ScyllaHide** [comment]
same problem here. gotta hate windows store ...

**Comment by rayman3003** [comment]
Thank u. I'm waiting for non-store version too.

**Comment by ScyllaHide** [comment]
i found this here and it works for me: https://github.com/Nonononoki/EarTrumpet/releases

w/o using the M$-Store.

**Comment by iPollox** [comment]
That's what I'm using, @ScyllaHide I got Windows 10 LTSC (Enterprise) and it does NOT have Windows Store, and I like to have a stripped OS without everything Microsoft/Google/any other big company.

**Comment by kort3x** [comment]
Still: chocolatey would be my prefered way of installing.

**Comment by Katoru** [comment]
Since the Windows store is a source of many problems like : 

- Microsoft store not starting
- Download not starting
- Download freezing
- Installation not completing
- Installed app is not launching

It would be usefull if EarTrumpet could be installed without any microsoft store thingy.

I'm subscribing to this topic.

**Comment by beppe9000** [comment]
Can there be a portable release as a regular WPF exe ?

**Comment by Nonononoki** [comment]
@beppe9000 For the time being you can download a portable exe here: https://github.com/Nonononoki/EarTrumpet/releases

**Comment by saanuregh** [comment]
i made a chocolatey package for it, https://chocolatey.org/packages/eartrumpet/

**Comment by riverar** [comment]
Hi @saanuregh appreciate your efforts. Is there a way we can take control of that chocolate package to ensure it's kept updated? We'd like to control and make MSIX, choco and Store packages available. Thanks!

**Comment by saanuregh** [comment]
sure, i can either delete it or add you guys as the maintainer to transfer control. FYI it uses @Nonononoki 's portable build.

**Comment by beppe9000** [comment]
great!

**Comment by riverar** [comment]
@saanuregh Thanks! Let's add [rafael@filenewproject.onmicrosoft.com].

**Comment by saanuregh** [comment]
@rivman I need your chocolatey username to add you as maintainer.

**Comment by riverar** [comment]
@saanuregh RafaelAtFnp it appears.

**Comment by saanuregh** [comment]
@rivman It says maintainer not found.

**Comment by riverar** [comment]
@saanuregh Yeah my mistake, that was a NuGet account. For Chocolately, let's use: EarTrumpet

**Comment by saanuregh** [comment]
@riverar Added you, its on pending approval.

**Comment by riverar** [comment]
@saanuregh Thanks got it. Going to work on getting our msix/appinstaller packages in place so we can wire it into chocolately. Standby.

**Comment by saanuregh** [comment]
Great! My currently implemented way to install is not ideal way, an MSIX package would be the ideal.

**Comment by riverar** [comment]
nuspec checked in (https://github.com/File-New-Project/EarTrumpet/commit/d4007f9d0bd21dbcf748e6c91ffaf5360d75039d) and a `eartrumpet` chocolatey package is in review / should be out shortly. We'll wire it up to GitHub Actions next.

Will close this issue (finally), thanks everyone for your patience.

**Comment by ZurMaD** [comment]
https://chocolatey.org/packages/eartrumpet
