### ISSUE TITLE
cant change the output device of a particular app 

### ISSUE THREAD

**Issue by qasatecas** [File-New-Project/EarTrumpet#377]
![123](https://user-images.githubusercontent.com/51379428/58899883-a340d780-8706-11e9-8afd-7a2fa075274a.png)
cant change the output device of a particular app
the icon disapears it happens then i reinstall windows and the app 
version 2.1.2.0

**Comment by riverar** [comment]
Hi @qasatecas, that feature is only available in Windows 10 17134 or higher to move sessions around. You are missing some Windows 10 updates. Hope that helps!
