### ISSUE TITLE
Audio Output changed to another device but after disconnect no way to change back

### ISSUE THREAD

**Issue by DaStivi** [File-New-Project/EarTrumpet#378]
hi,
as described in title, when ah audio output (for example from browser) is change to another output device, and after this device  is disconneced (headphones or dockingstation on notebooks) the browser dont playback audio.. and no change to change the output device as i dont see the app in the eartrumped flyout anymore as it is in an unpluged device list thats not displayed anmore

**Comment by davuxcom** [comment]
Settings -> System -> Sound -> App volume and device preferences. Hit the reset button at the bottom.

![image](https://user-images.githubusercontent.com/1456216/59082527-5eed3d00-88a8-11e9-990a-3cb1750eb964.png)

**Comment by riverar** [comment]
@DaStivi Did this resolve the issue for you? Suspect it will.

**Comment by DaStivi** [comment]
Hi, @riverar @davuxcom "Problem" fixed yes thank you!
sorry for dumb question, i did looked into the windows settings dialog, but apprently didn't scroll down completley to the advanced settings...

propably it is possible to make such a reset button in the eartumpet settings too?
