### ISSUE TITLE
Overlay not positioned correctly with task bar on auto-hide

### ISSUE THREAD

**Issue by ckaotik** [File-New-Project/EarTrumpet#38]
When the Windows task bar is set to auto-hide, the Eartrumpet popup does not positiion itself correctly..
![eartrumpet](https://cloud.githubusercontent.com/assets/151904/10751307/5ac71f54-7c7f-11e5-979c-9e4d91c7e49a.png)

**Comment by riverar** [comment]
Duplicate of #36

**Comment by ckaotik** [comment]
Ooopsie. Must have missed that one ... Let's keep this all tidy and in one place :)
