### ISSUE TITLE
EarTrumpet Causes Bluetooth Feedback / Disconnects

### ISSUE THREAD

**Issue by zkhcohen** [File-New-Project/EarTrumpet#381]
Environment:

Windows 10 Home 1809
Ear Trumpet 2.1.2.0

Symptoms:

Bluetooth crackles and disconnects frequently. This affects Airpods most consistently.

Diagnosis:

Open EarTrumpet. Notice that adjusting the volume for individual programs is laggy (the volume sliders jitter and lag as you drag them).

Solution:

Restart EarTrumpet.

**Comment by davuxcom** [comment]
Can you check the CPU usage of EarTrumpet prior to closing it? Is it high?

**Comment by zkhcohen** [comment]
Surprisingly, it's low. Maybe 2%?

**Comment by davuxcom** [comment]
Any other patterns (e.g. it happens after a few hours usage, never a problem after a reboot)?
