### ISSUE TITLE
Slider should not be "disabled" when muted

### ISSUE THREAD

**Issue by Poopooracoocoo** [File-New-Project/EarTrumpet#382]
This is to match the Windows volume flyout behaviour. 

#290 #355 #383

**Comment by davuxcom** [comment]
We intentionally dim the app slider (but don't change interaction behavior) to make it more clear in the list which items are muted.

**Comment by davuxcom** [comment]
Scratch that - I think I regressed this. It should do this for the app slider, but not necessarily the main slider.

**Comment by davuxcom** [comment]
![image](https://user-images.githubusercontent.com/1456216/59149267-47a57100-89c8-11e9-8901-612991a542bb.png)
