### ISSUE TITLE
Mute icon does not have a hover state, a pressed state or a tooltip

### ISSUE THREAD

**Issue by Poopooracoocoo** [File-New-Project/EarTrumpet#383]
#290 #355 #382

**Comment by davuxcom** [comment]
Mute icon on the system flyout doesn't have any of that, and the tooltip is in use for apps for their title, so we picked this design.

**Comment by Poopooracoocoo** [comment]
Nah I'm not really that technical. I just know my issues will actually be seen compared to the Feedback Hub. 

I just tested it myself. The mute icon on the system flyout **does** have all of it. I think a tooltip would be good on the main slider. I can't take a screenshot of the tooltip for some reason.

**Comment by davuxcom** [comment]
Yep you're right. On 1903 there is now "Toggle mute" on the mute button.  I see the hover/pressed state now, it's very subtle but that isn't new.
