### ISSUE TITLE
1 Game/Application Always starts at 90%

### ISSUE THREAD

**Issue by Jayshua83** [File-New-Project/EarTrumpet#387]
Any idea why this could be happening?

I have 1 Game/Application that always starts at 90% volume in EarTrumpet...

So very odd! Did NOT use to do this.

**Comment by riverar** [comment]
Try going to Settings > System > Sound > App volume and device preferences. Hit the reset button at the bottom.

**Comment by riverar** [comment]
@Jayshua83 Any updates?
