### ISSUE TITLE
Flyout show animation is not always smooth

### ISSUE THREAD

**Issue by davuxcom** [File-New-Project/EarTrumpet#391]
The flyout animation is achieved by:
- Fading in Window.Opacity
- Translating vertically to the final position by animation Window.Top

This has the following problems:
- Sometimes the animation isn't smooth
- Sometimes the animation finishes in the wrong location
- The animation lacks the acrylic background (it is 100% opaque from the first frame, even though the window content fades in)

Both of these animation issues are thought to occur more under CPU stress.

The right fix may be to use DirectComposition to compose an animation and not move the window, however this is anticipated to be expensive.

**Comment by davuxcom** [comment]
I observed that on 1903 over remote desktop, with animations `on`, the flyout show animation reliably stops ~10px prior to the correct end position.

**Comment by ufolud** [comment]
I'm facing not-smooth flyout animation at  any time I'm opening menu from taskbar.

**Comment by davuxcom** [comment]
@ufolud Do you also see it fail to achieve the final position?

This is what I'm seeing on 1903 over remote desktop, recorded with [Screen2Gif](https://www.screentogif.com/downloads.html):

![animationFail1](https://user-images.githubusercontent.com/1456216/59965476-6117e400-94c3-11e9-9581-673d5cdd2174.gif)

Perhaps you could take a video or confirm if yours looks similar?

**Comment by ufolud** [comment]
@davuxcom 
As you can see, I don't have problems with position after animation, but still it's really not smooth
![image](https://i.imgur.com/r3EhaGr.gif)
Compared to network popup built in by default
![image](https://i.imgur.com/K9M673D.gif)
Both gifs were recorded in 60fps

**Comment by DrQwarck** [comment]
I have this problem too. The UI suddenly become sluggish, even after i restart my PC. Both gifs in 60 fps using Screen2Gif.
![github1r](https://user-images.githubusercontent.com/52542970/60681643-4463af00-9eba-11e9-9c3b-fd7b6b40fbc0.gif)
![github3r](https://user-images.githubusercontent.com/52542970/60681869-07e48300-9ebb-11e9-853f-efb3675ad275.gif)

**Comment by FeBe95** [comment]
I am experiencing the lagging volume mixer too, only far more extreme. I have recorded a video moving my mouse, showing how the mixer window responds to it (note that the playback is in real-time!). I've also put a YouTube in the background that shows a timer. The mouse movement lasts half a second while the whole Windows UI freezes completely for about 8 seconds. What is going on here?
![drag6](https://user-images.githubusercontent.com/7470739/81740024-95f6a600-949c-11ea-8275-4b89b4b82564.gif)

**Comment by mnguyen36** [comment]
Wanted to pop in and say I was excited to upgrade from v1.3 and that this is being continually supported! However I immediately noticed the jiggery animation and for whatever reason it is killing the experience for me :\ @riverar

**Comment by mnguyen36** [comment]
https://github.com/File-New-Project/EarTrumpet/pull/473 Looks like there's already a PR out for this! How do you link PRs?

**Comment by riverar** [comment]
@mnguyen36 You linked it correctly 👍 This won't be fixed any time soon, due to constraints imposed by acrylic, wpf, and dwm.

**Comment by thebigsmileXD** [comment]
It seems to not respect performance settings at all. All my UI animations are turned off, and this app ui comes up slow and stuttering. Please make it respect the Windows settings for a more integrated feel

**Comment by qaisjp** [comment]
Having a setting to turn off the animation entirely would be nice in the meantime.

**Comment by roschlau** [comment]
Would like to add my voice to this - smooth animations would be nice, but completely disabling them would still be much preferable for me to the stutter that's occurring for me!

**Comment by riverar** [comment]
Cleaning up the issues list. There's no work to be completed here--this is a well known limitation--so am closing this issue for now. We'll revisit this if/when the UI framework is moved over to something more modern.

**Comment by qaisjp** [comment]
@riverar does that include the capability to turn off the animation altogether?
