### ISSUE TITLE
Volume Mixer opens a very wide window across multiple displays

### ISSUE THREAD

**Issue by TheBaronJJ** [File-New-Project/EarTrumpet#392]
When right clicking the menu and clicking volume mixer the mixer stretches across both of my screens, along with this when i move the window around the pc freezes and will not respond but the volume mixer window keeps moving.

https://prnt.sc/o57rqi 

-Info: Win 10 1903 / 9 playback devices / 1# screen = 1920x1080 / 2# screen = 1680x1050

if there is any other bits of info you need please say

**Comment by davuxcom** [comment]
The slow window dragging is #349.

This issue can track the window UX being awkward with lots of devices.

You can mitigate this issue by disabling devices if they are not necessary, but of course this doesn't help if you are using the devices (even passively).

**Comment by harakiwi** [comment]
can confirm OPs issue. 
Having multiple monitors (btw GPU vendors removing DVI, instead adding HDMI doesn't help...)
![EarTrumpet_borked](https://user-images.githubusercontent.com/1221504/60555982-7ef50c80-9d3f-11e9-93c6-8a4581772abe.png)
With driver updates, windows updates, the PC suddenly thinking "This is a brand new device! Let's enable it"

Would love to have either: 

the volume mixer window **resize**able (starting at a max width of my desktop)
or
the volume mixer window set to the max width of my desktop and make it **scroll**able
or
an option to show devices in a **tiled** style

![EarTrumpet_tile-fix](https://user-images.githubusercontent.com/1221504/60555983-7f8da300-9d3f-11e9-9052-580c25b0959c.png)

**Comment by davuxcom** [comment]
If you look above your post I checked in a fix to add ScrollBars, it'll be in the next major update.

**Comment by wooziwoozi** [comment]
sorry to necro, but i am having a similar issue. right now its not too big, but over time it gets bigger and bigger randomly??? once it was going across both my monitors.

i have two 4k monitors if thats whats causing it? it worked fine for years though. 

here is an image:
![Image 004 - 2021-02-26](https://user-images.githubusercontent.com/13823693/109335971-bd9edb00-7830-11eb-800e-110845f56142.png)
