### ISSUE TITLE
Opening the windows legacy menu disappears when going to select an option

### ISSUE THREAD

**Issue by RogueX00** [File-New-Project/EarTrumpet#399]
![ET Legacy Menu](https://user-images.githubusercontent.com/53188021/61647221-b6314c00-ac61-11e9-8fcf-2490d3811a07.gif)

**Comment by davuxcom** [comment]
Thanks for reporting - we received a report of this in Chinese but weren't sure about exactly what was going on, and it's exactly as described.

Can you please go to Settings / General / About / Collecting troubleshooting data, and share everything at the top, above the timestamped lines?

**Comment by RogueX00** [comment]
https://pastebin.com/CALhjRh2

**Comment by davuxcom** [comment]
I'm guessing you see this 100% of the time?

If you drag your Taskbar over to the left side of the screen (causing the submenu to open the to the right of the menu) is it also broken?

**Comment by RogueX00** [comment]
It is fixed if the taskbar is on the left

**Comment by RogueX00** [comment]
If you're quick enough you can keep it open:

**Comment by Lego9182** [comment]
This is really annoying!! https://i.imgur.com/LlpfWOs.gifv
It happens to me and I can only access Windows Legacy with the arrow keys or by being lucky, it seems.
 The problem is that the selection area for the pop-out to appear isn't big enough, so when moving the cursor over, it disappears.
The reason it works when on the left is because the pop-out overlaps the selection box. https://i.imgur.com/JdF1Cwx.gifv

**Comment by Lego9182** [comment]
@riverar it used to work fine but now it pretty much never works, I think. I can't test right now but I'll check later.

**Comment by Lego9182** [comment]
@riverar I tried restarting Windows 3 times, all times it hasn't worked.

**Comment by riverar** [comment]
Thanks @Lego9182 (and others), I've fixed this and it's going through review now. Should be in the next release.

**Comment by RogueX00** [comment]
Thank you. Not too big of a problem but I thought I should bring it up.

**Comment by Lego9182** [comment]
Cool, thanks!!On 29 Aug 2019 12:45 am, Rafael Rivera <notifications@github.com> wrote:Thanks @Lego9182 (and others), I've fixed this and it's going through review now. Should be in the next release.
