### ISSUE TITLE
No Windows 8.1 support

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#4]

**Comment by riverar** [comment]
Closing, Windows 10 is a free upgrade; no need to support Windows 8.1.

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/41

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/12

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/190
