### ISSUE TITLE
Hide SpeechRuntime.exe ?

### ISSUE THREAD

**Issue by Sotuma** [File-New-Project/EarTrumpet#40]
SpeechRuntime.exe is a Windows file but I'm not entirely sure what it does on Windows. Do you think it could just be hidden from the list entirely? It doesn't have an icon so it looks funny to see.

![zyptk5x](https://cloud.githubusercontent.com/assets/13699813/11013622/9845d850-84e2-11e5-851b-1bd63011cd0c.png)

**Comment by riverar** [comment]
Are you using text-to-voice or voice-to-text features in Windows 10? Or any other accessibility features?
