### ISSUE TITLE
Incorrect Battle.net client icon displayed

### ISSUE THREAD

**Issue by Sugz** [File-New-Project/EarTrumpet#401]
I notice an issue with a app icon, the app being Battle.net.
![ear_trumpet_battle_net_icon_issue](https://user-images.githubusercontent.com/15956915/62330582-5c2e5300-b4b9-11e9-88ef-c77e3574c5aa.png)

I had a similar issue, I was fetching the same icon (temp file icon) from Battle.net process, using QueryFullProcessImageName with PROCESS_QUERY_LIMITED_INFORMATION, and i was retreiving a temp file instead of the exe (hence the temp file icon).
I solve that issue by using Windows Management Instrumentation (WMI) to extract the executable path from the process, but it's definitely slower.
If by chance you find a better solution...

**Comment by riverar** [comment]
@Sugz Thanks, will look into this now!

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/62389779-90376180-b515-11e9-9268-8f44757ea125.png)

Not seeing the same behavior. Do you have repro steps? What version of EarTrumpet are you using? Can you collect troubleshooting data via Settings?

Thanks!

**Comment by Sugz** [comment]
I'm using the version from the microsoft store. 
In terms of repro, I just open the flyout window (I guess, from the System Tray), and there is the temp icon instead of the correct one.

Here are the data for Battle.net:

  Battle.net
    [Inactive]: 7% Desktop pid:27832 
    AppId: C:\Program Files (x86)\Battle.net\.Battle.net.exe.739.29660.temp  id={0.0.0.00000000}.{7d1861c7-fedf-402e-98d1-6e7ead40922d}|\Device\HarddiskVolume3\Program Files (x86)\Battle.net\Battle.net.exe%b{00000000-0000-0000-0000-000000000000}|1%b27832
    IconPath: C:\Program Files (x86)\Battle.net\.Battle.net.exe.739.29660.temp
    GroupingParam: 2e058005-8d1f-43f4-912c-cede2ebe7404

**Comment by riverar** [comment]
@Sugz The EarTrumpet version number is in Settings > General > About.

**Comment by riverar** [comment]
@Sugz The entire log would be helpful, as it contains a bunch of data we need to diagnose this. (You can email it to `team@eartrumpet.app`.) If that isn't possible, let us know.

**Comment by Sugz** [comment]
@riverar The version i'm using is the 2.1.3.0. I've sent you the full log by mail.

**Comment by riverar** [comment]
@Sugz Can you reinstall Battle.net? It seems to be in a weird state, perhaps via an incomplete upgrade or other issue.

**Comment by Sugz** [comment]
@riverar Well I updated Windows and the bug is gone, the Battle.net client icon is the correct one now.

**Comment by riverar** [comment]
@Sugz Interesting. Is there still a .temp file on disk for Battle.net?

**Comment by Sugz** [comment]
@riverar Yes there is still one, which seems to be a copy of Battle.net.exe (same size)

**Comment by riverar** [comment]
@Sugz OK, I think for now we're going to close this. If it pops up again, please let us know!
