### ISSUE TITLE
High CPU and RAM usage

### ISSUE THREAD

**Issue by thegamerx1** [File-New-Project/EarTrumpet#402]
I was running a malware scan but thats no reason for eartrumpet to take 40% of cpu and 1,5Gb of ram
Edit: I'm also using a memory booster which may have inflicted in something [Link](https://www.rizonesoft.com/downloads/memory-booster/)
https://youtu.be/jc7FxJDMgyg

**Comment by davuxcom** [comment]
Yes that kind of cpu and memory usage is extremely high. Could you please collect and share the log from `Settings / General / About / Collect troubleshooting data` while this is happening?

**Comment by thegamerx1** [comment]
Eartrumpet crashed after some time of making the video but the right click menu was not appearing when i released the right click it dissapeared not sure if that could help in anyway the high cpu and ram usage doesnt seem to appear again will check the process regurlarly to see if happens again.

**Comment by riverar** [comment]
What's the Explorer Hook shown in the video?

**Comment by thegamerx1** [comment]
Its a program that when you press space in the explorer it shows a preview or info of the file or folder
http://1218.io/

**Comment by thegamerx1** [comment]
Going to close the issue because its probably not going to happen again and because i wasnt able to get the troubleshooting data

**Comment by qb20nh** [comment]
Just experienced this, I panicked and I immediately tried to kill it and uninstalled the app.
![6c5bce5](https://user-images.githubusercontent.com/1734074/114276840-6614a180-9a63-11eb-9f8e-c9c62b91528d.png)
