### ISSUE TITLE
Arrow icons to switch output device is missing

### ISSUE THREAD

**Issue by LazyLama** [File-New-Project/EarTrumpet#405]
Hi There, 
  I just installed this app and do not see the arrows to switch the output device. Any help would be much appreciated.

I'm running version 2.1.4.0 on Windows 10

![image](https://user-images.githubusercontent.com/12070127/62908325-797ae100-bd45-11e9-8b2b-e53601c12c57.png)

![image](https://user-images.githubusercontent.com/12070127/62908328-7c75d180-bd45-11e9-82d4-f68ee17f375d.png)

[tmp717.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/3494885/tmp717.tmp.txt)

**Comment by riverar** [comment]
Hi @LazyLama, you're using an old version of Windows 10. You must be using Windows 10 build 17134 or higher to get audio redirection capabilities. You can upgrade via the upgrade assistant https://www.microsoft.com/en-us/software-download/windows10

Hope that helps!

**Comment by LazyLama** [comment]
ah, i see. ok i'll update and let you know. TY

![image](https://user-images.githubusercontent.com/12070127/63025027-5c91fb00-be76-11e9-86a0-daa7551ddfcc.png)
