### ISSUE TITLE
Task "EarTrumpet" is killed and not auto-restarted when restarting explorer.exe

### ISSUE THREAD

**Issue by xeepress** [File-New-Project/EarTrumpet#406]
When I restart explorer.exe (because I need to flush it's memory cache occupancy often), EarTrumpet is killed but not restarted automatically. It's a WindowApp, so I cannot restart it by running a *.bat file which does:

```
taskkill /f /im explorer.exe
taskkill /f /im EarTrumpet.exe
del iconcache_*.db
start explorer.exe
start /D "C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.4.0_x86__1sdd7yawvg6ne\EarTrumpet\" EarTrumpet.exe
```

It always returns an access authority error.
I wish it would not only killed but also be restarted automatically whenever I restart "explorer.exe'.

**Comment by davuxcom** [comment]
Whether or not EarTrumpet is automatically restarted by the shell is out of our hands, but you can launch Windows Store apps from the command line, just not by path.

You can use this command to start EarTrumpet:
`explorer.exe Shell:AppsFolder\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne!EarTrumpet`

**Comment by xeepress** [comment]
> Whether or not EarTrumpet is automatically restarted by the shell is out of our hands, but you can launch Windows Store apps from the command line, just not by path.
> 
> You can use this command to start EarTrumpet:
> `explorer.exe Shell:AppsFolder\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne!EarTrumpet`

Thanks very much! Your command works!
