### ISSUE TITLE
EarTrumpet tray icon forgets it's position on the taskbar

### ISSUE THREAD

**Issue by MahdiGhiasi** [File-New-Project/EarTrumpet#407]
Since the last update, the icon keeps going to the "Show hidden icons" although I drag it back to the main tray.

This used to happen once for each update a while back, and stopped happening altogether after an update as you guys found a way for that. But now this happens too often even without updating the app. (I see that it's missing from the taskbar and then I find it in the hidden icons often)

**Comment by davuxcom** [comment]
We're looking into this issue. So far what we understand is that this would occur when EarTrumpet requests updating the icon, and the shell is busy due to a spike in system events preventing timely servicing of the request. Things like changing the theme, hibernation (#404) or other high-workload scenarios may exacerbate this.

**Comment by MahdiGhiasi** [comment]
My device is Surface Book 2, and is connected to a second monitor with lower DPI set as its primary monitor. When I detach the tablet, there is a few seconds where shell is busy changing the primary monitor, resizing all the shell elements to the new dpi, processing device connect/disconnects, and other things related to the attach/detach event. And I do detach the tablet multiple times a day.

So I guess my use case fits your explanation as to what can be the cause of this.

If there's anything I can do to help you (collecting logs, maybe?) the next time this happens on my machine, feel free to tell me.

**Comment by davuxcom** [comment]
Yes, if you could pull logs right after that second icon appears, it'd help us have confidence that we fix it correctly.

**Comment by spikespaz** [comment]
I also have this problem.

![image](https://user-images.githubusercontent.com/12502988/63197453-ade3eb00-c02c-11e9-8e26-0b3b7ccb1b0f.png)

**Comment by riverar** [comment]
Closing this bug as we reverted our notification area icon behavior in 2.1.6.0. Please open a new issue if you run into any issues, thanks!
