### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by svnpenn** [File-New-Project/EarTrumpet#41]
I get that [Windows 10 is a free upgrade][1], but I do not want Windows 10. I
want to continue using Windows 7.

Please do not follow Microsoft with the forced upgrade mentality.

[1]:
http://github.com/File-New-Project/EarTrumpet/issues/4#issuecomment-126995849

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/12

**Comment by GoldenTao** [comment]
Sorry the main feature of Ear Trumpet has no use on Windows 7 as you can't use Modern apps on Windows 7.

**Comment by riverar** [comment]
Upgrade to Windows 10 you Luddite.

**Comment by svnpenn** [comment]
@riverar no thanks

http://reddit.com/r/technology/comments/3keoau/microsoft_has_confirmed_that_they_are_downloading

**Comment by svnpenn** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/190
