### ISSUE TITLE
Flyout blocks browser buttons and won't move.

### ISSUE THREAD

**Issue by mwestport** [File-New-Project/EarTrumpet#410]
Flyout blocks the browser buttons and it cannot be moved.  Have to wait for it to close.  Great otherwise.
![Annotation 2019-08-29 204614](https://user-images.githubusercontent.com/33640384/63985854-8155b780-ca9f-11e9-8bdf-5a3ad4894d1e.png)

**Comment by riverar** [comment]
@mwestport That on-screen display is built into Windows and not a part of EarTrumpet.
