### ISSUE TITLE
[Question] Bluetooth menu

### ISSUE THREAD

**Issue by thegamerx1** [File-New-Project/EarTrumpet#411]
I know this doesn't have much to do with EarTrumpet but having a bluetooth menu like EarTrumpet to manage bluetooth devices would be very cool instead of opening the configuration then devices and bluetooth. I'm sure some people would even pay for it.

Got the idea from here: https://www.reddit.com/r/Windows10/comments/aoblnb/a_system_tray_menu_for_connectingdisconnecting/

**Comment by GoldenTao** [comment]
Thanks for the idea, it's probably not something we're looking to build but someone could take some of the EarTrumpet code and build something like that pretty easily.  I couldn't quickly find it, but someone has created a power plan changer using some of our window/flyout code.
