### ISSUE TITLE
Tray icon tooltip doesn't update when changing volume with scroll wheel

### ISSUE THREAD

**Issue by thegamerx1** [File-New-Project/EarTrumpet#416]
![FyD7c3xEdX](https://user-images.githubusercontent.com/34986564/64987512-a16fde00-d8c9-11e9-9bc1-bc1882d37120.gif)

**Comment by davuxcom** [comment]
There's nothing (reasonable) we can do here, the shell is getting updated but isn't expiring an active tooltip to replace it with an updated one.

**Comment by thegamerx1** [comment]
The program next to the volume icon the "12" number one changes the brightness with the scroll wheel and the tooltip gets changed but i sometimes can see that it moves the mouse somewhere else and then brings it back to update the tooltip
![DolJIwZ2L3](https://user-images.githubusercontent.com/34986564/65066224-46e78800-d984-11e9-8cc3-15e4c2e1d019.gif)
