### ISSUE TITLE
not starting up with windows

### ISSUE THREAD

**Issue by Elias8477** [File-New-Project/EarTrumpet#417]
Since this is a windows 10 store program I can't find a .exe so I can't place it in shell:startup to autorun it, same goes with task scheduler, not possible since I don't know the file locations. Looked in settings and didn't find it anywhere in there.

This worked all the time and stopped working a few months ago.

**Comment by davuxcom** [comment]
You can use this command to start EarTrumpet:
`explorer.exe Shell:AppsFolder\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne!EarTrumpet`

**Comment by riverar** [comment]
EarTrumpet already registers a startup task. You should see EarTrumpet in Settings > Apps > Startup.

**Comment by Elias8477** [comment]
> You can use this command to start EarTrumpet:
> `explorer.exe Shell:AppsFolder\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne!EarTrumpet`

Thanks!

**Comment by tophattwaffle** [comment]
I have the same issue. For started Settings > Apps > Startup does not exist on any of my Windows 10 1903 installs. I know this isn't a EarTrumpet issue, but I saw you mention it in a previous response.
![image](https://user-images.githubusercontent.com/6774125/66082391-acfd0f00-e52f-11e9-9a85-4139c96a37ea.png)

In Task Manager > Startup there is an EarTrumpet entry, however it always reverts back to "Disabled" as soon as I close Task Manager. This happens 2 of the W10 1903 installs I have.
![2019-10-02_16-15-27](https://user-images.githubusercontent.com/6774125/66082490-df0e7100-e52f-11e9-9879-5f2137c3285c.gif)

For now I am launching EarTrumpet using the previously mentioned command in a startup script.

**Comment by riverar** [comment]
Strange, can you open the Registry Editor, navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion` and cut/paste the `BuildLabEx` value here?

**Comment by Snaacky** [comment]
I'm also having the Task Manger close disabled issue on 1903. 

My `BuildLabEx` value is `18362.1.amd64fre.19h1_release.190318-1202`

**Comment by riverar** [comment]
Thanks @Snaacky; And you're on Windows 10 Pro? Can you take a look at `HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\EarTrumpet` for us? State should change to 1 when disabled via Task Manager (and 2 when enabled). Can you confirm?

**Comment by Snaacky** [comment]
![XRCCh9OFnS](https://user-images.githubusercontent.com/4893775/66099988-24a25c80-e577-11e9-9a6a-c7707f19d750.gif)

Windows 10 Pro Version 1903 (OS Build 18362.356)

`State` is set to `2` regardless of whether or not the application is listed as Enabled or Disabled under Task Manager > Startup and will always revert back to Disabled after closing Task Manager as shown in the GIF above.

**Comment by tophattwaffle** [comment]
The state is the same for me as well. Always "2" no matter what.

**Comment by riverar** [comment]
@Snaacky Are you still seeing this issue? Some steps we can try:

1. Run https://live.sysinternals.com/procmon.exe
2. In the filter window, add a filter for [Path] [contains] [40459File-New-Project.EarTrumpet_1sdd7yawvg6ne] then click the Add button
3. Open Task Manager and enable EarTrumpet to run at startup
4. Click the magnifying glass 🔍 (or type <kbd>CTRL</kbd>+<kbd>E</kbd>) to stop monitoring
5. Click File > Save and in the Save To File dialog, ensure All Events is selected. Change the path for the output PML as needed.
6. Comrpess the PML (zip, 7zip, rar, etc.) and email us a copy (team@eartrumpet.app). If it's too large, we can provide a OneDrive upload location. Let us know in the email.

**Comment by riverar** [comment]
@Snaacky @tophattwaffle Any updates?

**Comment by bacitoto** [comment]
> Thanks @Snaacky; And you're on Windows 10 Pro? Can you take a look at `HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\40459File-New-Project.EarTrumpet_1sdd7yawvg6ne\EarTrumpet` for us? State should change to 1 when disabled via Task Manager (and 2 when enabled). Can you confirm?

Yes the state changes to 1
![image](https://user-images.githubusercontent.com/1870197/70683276-ab6f6600-1c99-11ea-8c90-32ff777eeadc.png)
I close task manager, and it reverts back to disable and still has a 2 on the STATE value of reg

**Comment by TheAresjej** [comment]
Same here: Windows 10 1909 (build 18363.535) (latest release) 🙁 @riverar

**Comment by riverar** [comment]
@TheAresjej @bacitoto Hey, can you perform the steps listed above https://github.com/File-New-Project/EarTrumpet/issues/417#issuecomment-549112253? Haven't received anything yet, should help shed some light on this!

**Comment by bacitoto** [comment]
@riverar Just did, I jsut didn't have the time before to do so.
Hope it's helpful

**Comment by riverar** [comment]
@bacitoto Haven't received anything yet.

**Comment by TheAresjej** [comment]
Hmm... I have a guess... In older versions of windows we have a startup options in settings (settings/apps/startup) but for some reason it was removed so maybe there is something left in the settings application and overwrites the selected settings? 😄

**Comment by TheAresjej** [comment]
Done (I sent the logs by e-mail) @riverar

**Comment by bacitoto** [comment]
> @bacitoto Haven't received anything yet.
Weird I just double-checked and I did send the email to the correct address...can I just post the link here s oyo ucan download the log? Or the .log as info I shouldn't display publicly or not

**Comment by riverar** [comment]
@TheAresjej Thanks, taking a look now!

@bacitoto Weird, send an email to the above address and I'll reply with a OneDrive area you can upload to. Sorry for the headache.

**Comment by riverar** [comment]
@TheAresjej @bacitoto Can you open Registry Editor, navigate to `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System` and provide a screenshot or export?

**Comment by bacitoto** [comment]
> @bacitoto Weird, send an email to the above address and I'll reply with a OneDrive area you can upload to. Sorry for the headache.
I guess my emails aren't being received, weird stuff, anyway here's [my log](https://mega.nz/#!McdgHQIC!AZtROxyzaAPaSpQ7Mrcx6Bl4-2Ynuc5lUmaqrbVHcok)

> @TheAresjej @bacitoto Can you open Registry Editor, navigate to `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System` and provide a screenshot or export?
![image](https://user-images.githubusercontent.com/1870197/70929040-1a4a1780-202a-11ea-8e92-38ca19a047f8.png)

> Also, question from Microsoft -- are these work machines or machines on an Active Directory that could be receiving policies to block startup apps?
This is my personal computer....I might have (a long time ago) blocked some w10 features such as store, xbox app and etc, BUT, everything was working fine untill the latest w10 update 18362.1.amd64fre.19h1_release.190318-1202

**Comment by TheAresjej** [comment]
I use [WPD](https://wpd.app) but the only similar option to block "startup apps" is "background apps" setting... 🤔 As for the registry screen, unfortunately I don't have access to this system anymore because there were still problems with it so I switched to Windows 8.1 😜

**Comment by riverar** [comment]
@bacitoto Yikes, that's not correct. Sounds like whatever you used to "block" those features wiped out important system policies. Can you share the software/guides you used?

In the meantime, try re-adding the startup policies via this script (save as .reg and double-click):

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableFullTrustStartupTasks"=dword:00000002
"EnableUwpStartupTasks"=dword:00000002
"SupportFullTrustStartupTasks"=dword:00000001
"SupportUwpStartupTasks"=dword:00000001
```

Then try your Task Manager actions again.

**Comment by riverar** [comment]
Closing as we don't have a stable repro. There were Windows bugs in this area that have been resolved over the last few releases. Please open a new issue to let us know if you hit this problem again. Thanks!
