### ISSUE TITLE
Main volume slider on hover, not just after clicking on eartrumpet icon

### ISSUE THREAD

**Issue by martonx** [File-New-Project/EarTrumpet#420]
I suggest a new feature:

Current working flow: you have to go to eartrumpet icon in the notification area, click on it, then flyout displays where you can change the volume.

I suggest to eliminate that click. If I go to notification area, and just hovering on eartrumpet icon, the flyout should be visible.

I don't know this could be a windows feature (notification area hover instead of clicking) of Eartrumpet feature.

**Comment by davuxcom** [comment]
Have you tried using your mouse scroll wheel on the icon instead of (clicking) opening it? For only changing the master volume, you can use scroll or middle click without opening EarTrumpet.

**Comment by SweetyVolty** [comment]
use this to change volume; https://rammichael.com/7-taskbar-tweaker

**Comment by riverar** [comment]
@martonx We support adjustment via mouse scroll wheel without opening EarTrumpet. Going to close this issue. Feel free to re-open if you don't feel like that's good enough.
