### ISSUE TITLE
Crashes on startup - Win 10 Home N x64

### ISSUE THREAD

**Issue by eastpaw** [File-New-Project/EarTrumpet#43]
Hi, thanks for creating such a useful program!

My installation on a new Win 10 upgrade crashes repeatedly during startup. I typically have to run it 5-10 times before it will start properly. Any idea what's going on here? I've reinstalled it a few times but the problem is still here.

**Comment by riverar** [comment]
Can you provide any messages or stack traces you're seeing? Perhaps a snip of whatever is in the event log?

**Comment by eastpaw** [comment]
I just get the generic

"A problem caused the program to stop working correctly. Windows will close
the program and notify you if a solution is available."

Running as administrator doesn't help.

I don't have WinDbg installed... is there a way native to a basic Win 10
installation to get a stack trace?

**Comment by riverar** [comment]
There should be more detail in the Event Viewer > Windows Logs > Application.

**Comment by eastpaw** [comment]
Ah, I see. I just reproduced the crash and 5 error logs were created. I have saved them into 5 text files named in order of occurrence and attached them here.

[Crashes on startup - Win 10 Home N x64.zip](https://github.com/File-New-Project/EarTrumpet/files/67443/Crashes.on.startup.-.Win.10.Home.N.x64.zip)

**Comment by GoldenTao** [comment]
We haven't been able to reproduce this one. Please reopen this issue if you still have this issue.
