### ISSUE TITLE
Feature Request: Option to make switching audio device also change the communication device

### ISSUE THREAD

**Issue by VapidLinus** [File-New-Project/EarTrumpet#430]
The right-click tray menu has a quick way to change the audio device. https://i.imgur.com/E96kA44.png

However, changing the audio device here does not change the "communication device" in Windows. If I change my audio device from my headphones to my speakers, the "communication device" is still the headphones. https://i.imgur.com/50TZpX6.png

This is annoying in many games that use VOIP. A lot of them use the communication device for voice audio, while using the audio device for game audio. So whenever I want to switch between audio devices, I still have to open the legacy sound menu to change both.

**My request** is to add an option so that when you change the audio device in EarTrumpet's tray-menu, it will change _both the audio device and the communication device._

**Comment by davuxcom** [comment]
duplicate of #348
