### ISSUE TITLE
No sound New Chrome update

### ISSUE THREAD

**Issue by flibble666** [File-New-Project/EarTrumpet#434]
ET Version : 2.1.5.0 
Chrome Version: 78.0.3904.70
Windows 10 Updated as of 10/28/19 (28/10/19)

 Open a new tab in chrome or refreshing (includes login refresh)  and all additional tabs opened will have no sound.
The only way to fix the issue is to restart Chrome. refreshing or reloading the tab has no effect.

*Update defiantly an issue with Ear trumpet removing ET is the only fix i can find but constantly relaunching chrome.

**Comment by riverar** [comment]
@flibble666 Can you provide repro steps? I tried Chrome 78.0.3904.70, opened two YouTube tabs and each video played. EarTrumpet shows Chrome volume correctly.

![image](https://user-images.githubusercontent.com/475132/67710724-b9815580-f97d-11e9-9c3a-a6cd9e1da797.png)

**Comment by flibble666** [comment]
No After removing and reinstalling issue seems resolved.
