### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by AndreySeleznov** [File-New-Project/EarTrumpet#435]
Trumpet crashes on start, latest version from 9/9. Win 10 Pro 1903
![image](https://user-images.githubusercontent.com/43615582/67838695-8b755000-fafa-11e9-8f6a-ddfc0a9084a3.png)

**Comment by riverar** [comment]
Hey @AndreySeleznov can you please perform the following steps and update issue #286? Thanks. I'll forward it to Microsoft as soon as you let us know you're done.

https://github.com/File-New-Project/EarTrumpet/issues/286#issuecomment-453363095

Closing as duplicate.
