### ISSUE TITLE
Forgets Netflix app volume setting - Win 10 Home N x64

### ISSUE THREAD

**Issue by eastpaw** [File-New-Project/EarTrumpet#44]
My Ear Trumpet remembers settings just fine... except for the Netflix app. That one resets to 100% every time I start up Netflix, even during the same logon session.

**Comment by riverar** [comment]
This is a limitation of non-Win32 apps, incl. Netflix. :(

**Comment by eastpaw** [comment]
Ah, I see. Thank you for the reply!
