### ISSUE TITLE
Add support for OSC control surfaces like TouchOSC

### ISSUE THREAD

**Issue by ChGGse** [File-New-Project/EarTrumpet#440]
Would be awesome to see support for OSC since it's becoming the new standard for control surfaces.

MIDI support would also be nice, however it limits you to having 16 channels whereas OSC is limitless.

**Comment by riverar** [comment]
Hey @CheesePwn, is your thinking here that a hardware product would implement OSC communication and talk to EarTrumpet to control app volumes?

**Comment by CheesePwn** [comment]
> Hey @CheesePwn, is your thinking here that a hardware product would implement OSC communication and talk to EarTrumpet to control app volumes?

This is correct yes.

**Comment by riverar** [comment]
@CheesePwn Cool, thanks. Will read up on this!

**Comment by flibble666** [comment]
If NK2Tray supported more device it would save alot of work.
https://github.com/ho0ber/NK2Tray

Also what about adding rtpMIDI this would allow apps like TouchDAW.
https://www.tobias-erichsen.de/software/rtpmidi.html
http://www.humatic.de/htools/touchdaw/

**Comment by flibble666** [comment]
Thankyou i am alredy running TouchDAW & rtpMIDI  i will check out Power Mixer  thx for the info.
