### ISSUE TITLE
Slider does not properly move relatively to mouse when dragging.

### ISSUE THREAD

**Issue by TheV360** [File-New-Project/EarTrumpet#441]
Whenever I change the volume in EarTrumpet, I have to be careful to click the left side of the slider head. If I don't, the slider head will jump to exactly where I'm clicking. This should only be the case if my cursor is not over the slider head. This does not happen in the vanilla volume slider.

[Here's a recording of the issue in question.](https://github.com/File-New-Project/EarTrumpet/files/3884183/2019-11-24_16-46-53.zip)

This may be a DPI issue, because my screen's DPI is set to 225%. Also note that my cursor's hotspot is slightly lower than the actual top-left corner of my cursor.

**Comment by riverar** [comment]
Thanks. Reposting as gif for convenience.
![issue](https://user-images.githubusercontent.com/475132/69502752-b53a5080-0ec7-11ea-97cc-d2ac862cd39c.gif)

**Comment by riverar** [comment]
Hey @TheV360 fix is in, will get this into the next update. If you're interested in trying a dev build to verify, let me know.
