### ISSUE TITLE
Multiple Notification Area registrations

### ISSUE THREAD

**Issue by pingzing** [File-New-Project/EarTrumpet#442]
Hi! It looks like EarTrumpet doesn't unregister old entries from the Notification Area when upgraded or (re)installed. I've upgraded several times via the Windows store, and have six entries total, most of which are (I think) for no-longer valid installations: 

![image](https://user-images.githubusercontent.com/5133649/69552375-08370500-0fa7-11ea-8def-f2958ecb8d09.png)

(This is in the Settings app, Personalization -> Taskbar -> Notification area subheader -> Click on `Select which icons appear on the taskbar`)

I'd like to remove these by hand, but have no idea where the registry stores them. It probably makes sense for EarTrumpet to clear old entries itself, too.

**Comment by riverar** [comment]
Thanks @pingzing, we're tracking this issue via #404. Going to close this one. Working on it right now! https://github.com/File-New-Project/EarTrumpet/issues/404#issuecomment-552290070

**Comment by pingzing** [comment]
Ah, saw that but didn't realize it was the same issue! Sorry for the dupe!
