### ISSUE TITLE
Changing volume via slider causes 100% CPU

### ISSUE THREAD

**Issue by makedir** [File-New-Project/EarTrumpet#443]
Changing volume via slider causes 100% CPU and freeze the entire tablet. This just happens on a tablet of mine, not on my desktop.

**Comment by riverar** [comment]
@makedir Can you provide details on the tablet? Make/model/etc.

**Comment by makedir** [comment]
It is a Dell 7140 tablet. It kinda just happens, when Chrome is open and plays a audio, for example on twitcht.tv, when I then try to change the slider of Chrome in EarTrumpet, it creates 100% cpu load and everything freezes, including EarTrumpet. Restarting EarTrumpet resolves sthe issue, and it works normally for a while, until it happens again.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
