### ISSUE TITLE
Feature: splitting the code into not-dispatcher dependant library and GUI

### ISSUE THREAD

**Issue by YoSarin** [File-New-Project/EarTrumpet#445]
**Back story**
I like the way EarTrumpet handles audio volume changing and I would like to have possibility of using that part of it in other applications. Ideally as dll/NuGet package.
Also I would like to be able to use it in CLI application. Which is not possible because of Dispatcher not working properly in CLI (at least that is my understanding).

**Things I do plan to do for my own needs**
- Splitting "library" part of EarTrumpet into separate project
- Removing dependancy on Dispatcher from library (make Dispatcher "provider" injectable)

**Question**
Is there any broader need for this? As i would like to be able to eventually keep my applications up to date with latest EarTrumpet code, is there any will to accept changes of this kind?

**Comment by riverar** [comment]
@YoSarin What problems are you running into exactly? I had a quick discussion with @davuxcom and @GoldenTao and they provided a working sample (targeting .NET 4.6.2, x86):

```csharp
using EarTrumpet.DataModel.WindowsAudio;
using System;
using System.Windows.Threading;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var dm = WindowsAudioFactory.Create(AudioDeviceKind.Playback);
            dm.Loaded += (s, e) =>
            {
                foreach (var device in dm.Devices)
                {
                    Console.WriteLine(device.DisplayName);
                    device.Volume = 0.99f;
                }

                Console.ReadKey();
            };

            Dispatcher.Run();
        }
    }
}
```

**Comment by YoSarin** [comment]
Ah, thats interresting. I have created very similar sample when i was playing with it and it didn't work at all... o.O

Will investigate it a bit further, probably i just have forgotten something...
