### ISSUE TITLE
After undocking laptop, EarTrumpet UI is stretched and icon gets duplicated

### ISSUE THREAD

**Issue by Kaedin** [File-New-Project/EarTrumpet#447]
Hi Dev,

I've recently run into following issue that after undocking laptop from USB docking station, EarTrumpet's UI is stretched and its notification bar icon get duplicated as in below screenshot.

![image](https://user-images.githubusercontent.com/26382655/70437620-aa211c00-1a94-11ea-8057-8a135a801c89.png)

The restart of application is required to end the incorrect appearance and behavior. Any idea what's behind this?

My SW/HW setup (attached GPU details in case there's something to do with those):

Windows 10 Version 1909 Build 18363.476
Intel(R) UHD Graphics 630 (Driver Version 26.20.100.7463)
NVIDIA Quadro P2000 (Driver Version 26.21.14.4128)

Best regards,
Kaedin

**Comment by AlexWayfer** [comment]
The similar on PC, not notebook, with latest Windows 10 and external ASUS Xonar MK2.

**Comment by riverar** [comment]
Related #439

**Comment by riverar** [comment]
@Kaedin Thanks for the report, we're still trying to reproduce this on our end!

**Comment by jessehouwing** [comment]
Seeing this too. It seems to occur when my laptop switches between the Intel graphics card and the nvidia graphics card as soon as I plug in the power chord of the laptop. The version I have installed is the one from the Windows Store.

![image](https://user-images.githubusercontent.com/4173387/71546420-edd1bc00-2996-11ea-9a95-5cf6ca8cb078.png)

I do have only one EarTrumpet instance running:
![image](https://user-images.githubusercontent.com/4173387/71546429-09d55d80-2997-11ea-8984-976aedae01e3.png)


Lenovo X1 Extreme gen2
Windows 10 2004

![image](https://user-images.githubusercontent.com/4173387/71546441-207bb480-2997-11ea-92d0-9d456b535c59.png)

**Comment by Troikster** [comment]
getting icon duplication as well, each time the machine comes back from hibernation
![image](https://user-images.githubusercontent.com/53865512/72891340-52710400-3d14-11ea-865c-c5da0ac0e99e.png)

Only one entry in Task Manager as well
![image](https://user-images.githubusercontent.com/53865512/72891443-8d733780-3d14-11ea-9bf2-17507a15ce4a.png)

**Comment by LazerFX** [comment]
I'm also getting duplication.  It seems to be when I have a USB audio device (Jabra 20) plugged into the Thunderbolt 3 docking station.  When I hibernate or dock-and-undock, the system appears to generate a new EarTrumpet icon in the status area.  Each one has a different 'device' identified in the tool-tip, but they all bring up the same UI.  It also happens when plugging in Monitors that have HDMI-aware audio outputs, as the nVidia graphics card supports audio-out via HDMI.

**Comment by LazerFX** [comment]
Further to previous comments, I can show this happening in a screenshot:
![image](https://user-images.githubusercontent.com/17338491/74533542-beb4e100-4f29-11ea-9d07-f7740a0e0991.png)
As you can see, I have a number of duplicated eartrumpet icons after a few days of docking/undocking and changing monitors.  It appears to be triggered by anything that adds/removes monitors from the environment - plugging in an HDMI cable, connecting to a dock, adding a new virtual desktop, etc.

**Comment by riverar** [comment]
Closing. We can't reproduce the stretching. (The icon duplication was already fixed.) Several releases of Windows have now passed so the problem may no longer exist. Please open a new issue to let us know if you hit this problem again. Thanks!
