### ISSUE TITLE
Can't move apps between playback devices

### ISSUE THREAD

**Issue by lebeanshoe** [File-New-Project/EarTrumpet#451]
Running Windows 10 Pro on a 2017 Macbook Air with Bootcamp.

When I right click apps in eartrumpet, I get the little popup, but I don't get the option to move the app between playback devices. 

![vIkIbGberg](https://user-images.githubusercontent.com/58503045/71451709-24f26400-2730-11ea-8c1e-4e0b91d4a7e5.gif)

**Comment by riverar** [comment]
Hi @lebeanshoe, you're using an old version of Windows 10. You must be using Windows 10 build 17134 or higher to get audio redirection capabilities. You can upgrade via the upgrade assistant https://www.microsoft.com/en-us/software-download/windows10

Hope that helps!

**Comment by riverar** [comment]
@lebeanshoe Any updates?

**Comment by lebeanshoe** [comment]
@riverar Sorry about the late reply. I got everything working properly thanks to you. Happy new year!
