### ISSUE TITLE
Test sound not playing when clicking slider heads

### ISSUE THREAD

**Issue by beppe9000** [File-New-Project/EarTrumpet#456]
I think this should be replicated from windows behavior

**Comment by riverar** [comment]
Thanks, closing as this is a duplicate of #425

**Comment by beppe9000** [comment]
Wow... lack of test sound everywhere had me thinking the feature was missing

**Comment by riverar** [comment]
@beppe9000 It shouldn't be gone everywhere, it will play on the default device only. Which could be, say, Steam Streaming.

**Comment by beppe9000** [comment]
That is what I was reporting
