### ISSUE TITLE
Sound level of program back to 100% after a restart of that program

### ISSUE THREAD

**Issue by Waterboy1602** [File-New-Project/EarTrumpet#458]
The audiovolume of 100% is too loud, so I always change the volume of every app to 20%. It happens now that if I close an app and restart it, the volume goes back to 100%. Is there a way to fix this that the adjusted volume will be saved even after a restart of the app?

![Eartrumpet Issue](https://user-images.githubusercontent.com/24163882/73075970-6d32ac80-3ebd-11ea-8551-7e53cf90a46c.gif)

Edit: Changed the title for clarification and added a GIF to show what I mean.

**Comment by Waterboy1602** [comment]
This is fixed now. Must been a Windows related problem. I'm now on Windows Insider Preview Build 19559.

**Comment by CosimoMatassini** [comment]
The same in Windows version 2004 since I updated in June.

**Comment by riverar** [comment]
@CosimoMatassini Which app?

**Comment by CosimoMatassini** [comment]
Every app that has no inbuilt preset volume  saver. I also commented on an open issue but maybe you didn't see it. I really hope that it can be fixed asap because i really need this app to work properly.

**Comment by riverar** [comment]
@CosimoMatassini EarTrumpet doesn't provide this functionality. I asked for the app because I'm trying to determine if this is a desktop (win32) application or a modern ("uwp") application. Windows is responsible for remembering volume levels for desktop apps. Windows does not, however, remember volume levels for modern apps.

**Comment by CosimoMatassini** [comment]
For example Google Chrome (which is the one that I use the most) 64bit that I downloaded from the web and not from the Microsoft Store

**Comment by CosimoMatassini** [comment]
Can I do something myself (maybe see what's wrong with the files or something where windows stores the volume levels)? I' ve tried to unistall and reinstall the app but nothing solved.

**Comment by CosimoMatassini** [comment]
https://user-images.githubusercontent.com/24163882/73075970-6d32ac80-3ebd-11ea-8551-7e53cf90a46c.gif it's the same as this.

**Comment by CosimoMatassini** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/512 there's an issue already open about this where I commented 2 weeks ago
