### ISSUE TITLE
Ear Trumpet Volume Mixer off Screen

### ISSUE THREAD

**Issue by cpwegener** [File-New-Project/EarTrumpet#459]
When I open ear trumpet from the Windows 10 version 1909 OS build 18363.592 Tray the volume mixer is half off the monitor.
<img width="110" alt="Eartrumpet off screen" src="https://user-images.githubusercontent.com/2767793/73021642-cd055680-3ddc-11ea-9bc3-590dc6dabbfa.png">

**Comment by cpwegener** [comment]
You can close this issue. It seemed to last one day and now ear trumpet's behavior is correct

<img width="275" alt="Eartrumpet correct behaivor" src="https://user-images.githubusercontent.com/2767793/73099285-094dbb00-3ea0-11ea-9028-015c7fd9260a.png">

**Comment by riverar** [comment]
Thanks @cpwegener if it happens again, please reach out!
