### ISSUE TITLE
Shell_NotifyIcon issues

### ISSUE THREAD

**Issue by dremin** [File-New-Project/EarTrumpet#460]
While debugging an issue in my app, I discovered a few problems with the current `Shell_NotifyIcon` implementation in EarTrumpet. In `NOTIFYICONDATA`, EarTrumpet is setting `uVersion` to `NOTIFYICON_VERSION_4` to attempt to opt in to new shell behavior. However, because the size of the `NOTIFYICONDATAW` struct is incorrect, the shell (in this case, Windows Explorer) is treating the notify icon as having `uVersion` set to 0.

This can be validated while debugging: `WM_CONTEXTMENU` and `NIN_SELECT` messages are not being sent to the notify icon on right-click and left-click, respectively. These messages are sent to notify icons that opt in to `NOTIFYICON_VERSION_4`.

Fixing the struct causes the shell to then use the `NOTIFYICON_VERSION_4` behavior that EarTrumpet is intending to opt in to. However, fixing this exposes a few issues with how EarTrumpet is behaving when opting in to `NOTIFYICON_VERSION_4`:

1. The `uFlags` member is not specifying `NIF_SHOWTIP`, so the tooltip is hidden (this enum value is used when opting in to `NOTIFYICON_VERSION_4` to indicate that a standard tooltip should be used)
2. When the shell sends right mouse clicks to the notify icon, it sends both `WM_RBUTTONUP` and `WM_CONTEXTMENU` messages at the same time when opting in to the new behavior. However, EarTrumpet does not handle this correctly, causing the context menu to appear and then immediately disappear. Keeping track of the context menu state fixes this.

Documentation regarding `NOTIFYICONDATA` behavior is available here: https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataw

I can help correct these issues with a PR, let me know if that would be OK. Thanks!

**Comment by riverar** [comment]
@dremin Good catch, oops. If you have changes ready to review, feel free to submit a PR. Otherwise we'll get it cleaned up asap.

**Comment by dremin** [comment]
@riverar I submitted a PR, do you need anything else from me at this point?

**Comment by riverar** [comment]
@dremin No, thanks again though! Haven't had a chance to review it yet fully. Have a backlog of loc and some updates to kick out the door first.

**Comment by riverar** [comment]
Closing issue. EarTrumpet 2.1.8.0 is now available in the Store with a fix for this issue. Thanks for your patience!
