### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by fernamp** [File-New-Project/EarTrumpet#462]
After updated to the a windows update request (windows-10-update-kb4532695 and kb4534132-cumulative-update-for-net-framework), I get a notification at start that states:
- C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.5.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
The filename, directory name, or volume label syntax is incorrect.

I don't know if this is an error from windows or something else.
I'll try a fix an update this accordingly.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
