### ISSUE TITLE
App-Store disabled, can't use eartrumpet

### ISSUE THREAD

**Issue by Tennessee-Timmy** [File-New-Project/EarTrumpet#463]

**Comment by Tennessee-Timmy** [comment]
https://i.imgur.com/mWH280t.jpg

**Comment by riverar** [comment]
Why is your Store disabled?

**Comment by Tennessee-Timmy** [comment]
President Trump gonna steal my interwebs :(
I'm on a old computer and disabled for more giggahertz

**Comment by riverar** [comment]
We're available via Chocolatey now, so closing this issue. I'll also have a chat with President Trump about your interwebs.
