### ISSUE TITLE
Korean language doesn't apply since a long time ago

### ISSUE THREAD

**Issue by duk6046** [File-New-Project/EarTrumpet#467]
It was not fixed at last version, so suggest a manual selection option.

**Comment by riverar** [comment]
@duk6046 Will fix this right now and push a release out. I might ask you for a few extra translations in a few minutes, if you don't mind.

**Comment by duk6046** [comment]
ok, i'm fine

**Comment by riverar** [comment]
@duk6046 Can you help complete missing Korean translations? https://crowdin.com/translate/eartrumpet/32/en-ko

**Comment by duk6046** [comment]
OK, i finished translations.

**Comment by riverar** [comment]
@duk6046 Great, thanks!
