### ISSUE TITLE
Bluetooth control

### ISSUE THREAD

**Issue by IDANKANFI** [File-New-Project/EarTrumpet#47]
Hi guys, cool app.
I have a Jabra REVO Wireless headset. back at last year when I installed windows 10, i could control the wireless volume. Then there was a Windows updte and changed this.
It's a bit difficult to explain but I'll try.

Good status: I press Vol+ or Vol- on the headset, and windows kindly views a status bar on screen - volume increasing or decreasing accordingly.
Bad status: I have to use headset Vol+ to max (of course no input on the screen) AND amplify the windows mixer to max. The duality is troubling.

Hope you guys can sort it out!

**Comment by riverar** [comment]
Have you narrowed down which update? Sounds like you just need to get Windows to see this headset properly. Be sure to also report it through the Feedback app.

**Comment by GoldenTao** [comment]
Not applicable to Ear Trumpet. If you do find this causes an issue with the app, please reopen this issue.
