### ISSUE TITLE
Does not work with "Select which icons appear on the taskbar"

### ISSUE THREAD

**Issue by dopoto2** [File-New-Project/EarTrumpet#470]
I chose to always show the EarTrumpet icon in my taskbar. However, as soon as I changed the volume level, the icon was gone. I now see two entries for EarTrumpet in Windows Settings > "Select which icons appear on the taskbar". See screenshot below:

![image](https://user-images.githubusercontent.com/47202328/75884879-36da3c80-5e2e-11ea-82f8-f85cb512ed19.png)

**Comment by samkatakouzinos** [comment]
My method to choose which icons show in Taskbar is to use the mouse and drag the icon away from the notification pop-up down to the Taskbar area. If I want to hide the icon I drag it from the Taskbar to the pop-up area. 

I don't use the menu shown in your image.

Does doing the above resolve the issue?

**Comment by riverar** [comment]
Thanks @dopoto2, what version of EarTrumpet are you using?

**Comment by dopoto2** [comment]
It's 2.1.7.0

**Comment by davuxcom** [comment]
Let's see if this isn't a dupe of https://github.com/File-New-Project/EarTrumpet/issues/460 - which is now fixed. There could possibly be stale versions of EarTrumpet in the settings page even once it's fixed. We've gone through a few iterations with Shell_NotifyIcon and our unique app type.
