### ISSUE TITLE
Doesn't change Output Device for all software

### ISSUE THREAD

**Issue by Alucard2112** [File-New-Project/EarTrumpet#472]
I have tried to get the game Sekiro to use another sound device than the standard one which worked. Somewhere along the way, something broke. Might be on your part, might be on Microsofts.
Long story short: The game sound gets sent to the standard device instead of the selected device.

**Comment by Dojh342** [comment]
I have the same problem but with a variety of apps and games.

**Comment by riverar** [comment]
@Alucard2112 @Dojh342 Yep, this feature doesn't work 100% of the time. A few questions:

* Can you redirect the audio via Windows Settings > System > Sound > App volume and device preferences? (screenshot below)
* Can you specify which apps/games you're having issues with?

![image](https://user-images.githubusercontent.com/475132/81276302-ad024780-9007-11ea-886e-3ad0f01dc555.png)

**Comment by Alucard2112** [comment]
Sadly, it also does not work with the internal windows settings (I've tried).
I have so far only come across certain games that won't work that way, namely "Sekiro: Shadows die twice" and "Ori and the Blind Forest".
I'll be keeping my eyes peeled for further software that doesn't work with that feature :)

**Comment by riverar** [comment]
Thanks @Alucard2112 will start tracking these titles. Ori is interesting, might get some traction there with Microsoft. I'll send an email.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it. (Microsoft was unresponsive.)
