### ISSUE TITLE
On startup, volume displays as 100% but is lower

### ISSUE THREAD

**Issue by red9350** [File-New-Project/EarTrumpet#476]
As per title, when windows starts, volume is displayed as 100% in both the system volume bar and in EarTrumpet's volume bars, yet the sound is quieter than 100%. Manually lowering and rising the volume of each EarTrumpet volume bar fixes the issue.

**Comment by riverar** [comment]
@red9350 Interesting, do you still see this behavior? Is it affecting all apps? Navigate to Settings > General > About and click Collect troubleshooting data. Attach the log to this issue or email it to team@eartrumpet.app (reference this issue). Thanks!

**Comment by red9350** [comment]
It seems to be fixed... Now i don't know if it actually was an EarTrumpet bug or a windows/driver one... You can close this for now

**Comment by dst27** [comment]
@red9350 please close this issue if it's fixed as you said.
