### ISSUE TITLE
Slider half off-screen when switching from 4K to 1080p resolution

### ISSUE THREAD

**Issue by mbloch94** [File-New-Project/EarTrumpet#477]
As described in the title.
A reboot fixes the issue
![image](https://user-images.githubusercontent.com/62449626/77210406-3a91e280-6b01-11ea-9a5d-c97d6f1c6f58.png)

**Comment by mbloch94** [comment]
Hmmm it seems like om not able to reproduce the error, after a reboot.
But this error occurred to me more than one time, and in connection with watching 4k movies.

I will keep you updated if i notice anything that might be relevant :)

**Comment by riverar** [comment]
Thanks @mbloch94!

**Comment by Hamzehn** [comment]
I'm seeing this exact thing every time I come back to use my computer in the morning after having left it on overnight.

- Main display: External 4k monitor at 200% scaling
- Laptop screen: 1440 screen at 175% scaling
- Displays used in extended mode
- Power settings (always plugged in): never sleep , but turn off display after 10 mins

**Comment by riverar** [comment]
@Hamzehn Every time or most of the time? If it's all the time, that's very useful! Can you also Collect Diagnostics (in EarTrumpet Settings > About) and email it to team@eartrumpet.app? Be sure to put this issue number in the subject somewhere.

**Comment by Hamzehn** [comment]
> @Hamzehn Every time or most of the time? If it's all the time, that's very useful! Can you also Collect Diagnostics (in EarTrumpet Settings > About) and email it to [team@eartrumpet.app](mailto:team@eartrumpet.app)? Be sure to put this issue number in the subject somewhere.

@riverar very sorry not sure how I missed your comment!

Ok, truth be told it doesn't happen every single time when I come back to use the computer in the morning, but I have to say there have only been a day or two where I did NOT run into this. Also, recently the distance by which ET is off screen has also increased so it's no longer half of it off screen, but more like 3/4 of it is off screen.

I'm on version 2.1.8.0

I hope this helps.

**Comment by Hamzehn** [comment]
@riverar sure enough it happened again today and I sent a diagnostics dump to team@eartrumpet.app

**Comment by Hamzehn** [comment]
@riverar just sent another diagnostics dump today. Hope these are helpful. Maybe this issue can be re-opened?

![image](https://user-images.githubusercontent.com/27373978/125797102-7731c60b-31b1-44a8-b879-d9725bdcc419.png)

**Comment by Oregoncat** [comment]
> As described in the title. A reboot fixes the issue ![image](https://user-images.githubusercontent.com/62449626/77210406-3a91e280-6b01-11ea-9a5d-c97d6f1c6f58.png)

I cure it by ending the Eartrumpet task then restarting it.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue 1304, thanks!
