### ISSUE TITLE
When volume is 0 and unmuted, icon shows one white "soundwave"

### ISSUE THREAD

**Issue by Poopooracoocoo** [File-New-Project/EarTrumpet#478]
There should be no white "soundwaves". The built in volume control in Windows 10 has the correct behaviour in the taskbar but not in the flyout. EarTrumpet doesn't have the right behaviour in both the taskbar and in its flyout.

**Comment by riverar** [comment]
@Poopooracoocoo Thanks. We're aware of this one; we suspect there was a change in behavior in Windows.
