### ISSUE TITLE
no animation when in-app animations are turned off (from control panel)

### ISSUE THREAD

**Issue by Poopooracoocoo** [File-New-Project/EarTrumpet#479]

**Comment by riverar** [comment]
@Poopooracoocoo Can you provide more detail?

**Comment by Poopooracoocoo** [comment]
![image](https://user-images.githubusercontent.com/51363864/77281631-a059b680-6d1b-11ea-9344-c3434cc41b29.png)
When "Animate controls and elements inside windows" is disabled, the Eartrumpet flyout doesn't animate whereas Windows 10's one does. It's different to "Animate windows when minimising and maximising".

**Comment by riverar** [comment]
We check the `SPI_GETMENUANIMATION` system parameter (via `SystemParameters.MenuAnimation`) to drive whether or not we animate the flyout. On my system (19041), it appears this is completely broken. Will investigate, thanks!

**Comment by riverar** [comment]
Actually, this works as designed. We act as a menu and follow the menu animation toggle (screenshot 1). You can also use the overall animation toggle in Settings (screenshot 2).

![image](https://user-images.githubusercontent.com/475132/77407387-4d135280-6d73-11ea-9424-55c3271d541d.png)

![image](https://user-images.githubusercontent.com/475132/77407557-8ba90d00-6d73-11ea-98b7-6faa3cda77fd.png)

Going to close this. Feel free to comment/re-open as needed!

**Comment by Poopooracoocoo** [comment]
@riverar ahhhh thanks. I wasn't sure which one caused it. I had turned off slide or fade menus on my other system because I wanted consistency between UWP and win32 apps. Sorry about that! I thought of the wrong setting.
