### ISSUE TITLE
EarTrumpet process is killed immediately when trying to mute the sound of the monitor connected with HDMI 

### ISSUE THREAD

**Issue by amseager** [File-New-Project/EarTrumpet#483]
Seems like after updating Windows 10 from 1809 to 1909 it's not possible to mute the sound of my monitor (HP 27ea) connected with HDMI. When I'm trying to click on the "sound" sign (see screenshot), the app just exits immediately. Now it's only possible to decrease the sound level to 0 by moving the volume slider. 
At the same time, clicking on the "sound" sign of my notebook ("Speakers/headphones" on the screenshot) works as intended.
Also, I use 3RVX for operating the sound from the keyboard, and muting by keyboard key stopped working too (but EarTrumpet is not closed in this case). But the main problem can be reproduced even without 3RVX launched, just with EarTrumpet.

![image](https://user-images.githubusercontent.com/13808248/78508829-8647bb80-7792-11ea-8d03-1b9312957f88.png)

**Comment by amseager** [comment]
[AppCrash_EarTrumpet.exe_4f7880d2fe3153f5381799925fbb4e0d9f7caf3_cda850cc_5f5be11e-4e47-47ca-a230-bbb576a289ab.zip](https://github.com/File-New-Project/EarTrumpet/files/4434769/AppCrash_EarTrumpet.exe_4f7880d2fe3153f5381799925fbb4e0d9f7caf3_cda850cc_5f5be11e-4e47-47ca-a230-bbb576a289ab.zip)

Attached the (probably) related report from C:\ProgramData\Microsoft\Windows\WER\ReportArchive

**Comment by riverar** [comment]
Thanks @amseager, do you have an EarTrumpet related entry in Event Viewer > Windows Logs > Application?

**Comment by amseager** [comment]
@riverar yes, I do. It's in Russian though, but I think the XML part is understandable.

```
Имя журнала:   Application
Источник:      Application Error
Дата:          05.04.2020 23:08:04
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     DESKTOP-TLPGCFM
Описание:
Имя сбойного приложения: EarTrumpet.exe, версия: 2.1.7.0, метка времени: 0x5e54326e
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.18362.719, метка времени: 0x4061c730
Код исключения: 0xe0434352
Смещение ошибки: 0x00114192
Идентификатор сбойного процесса: 0x984
Время запуска сбойного приложения: 0x01d60b85a6374bd3
Путь сбойного приложения: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 7cd0ec59-55f2-489e-945e-46f7d197e57f
Полное имя сбойного пакета: 40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne
Код приложения, связанного со сбойным пакетом: EarTrumpet
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-04-05T20:08:04.464489800Z" />
    <EventRecordID>3116</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-TLPGCFM</Computer>
    <Security />
  </System>
  <EventData>
    <Data>EarTrumpet.exe</Data>
    <Data>2.1.7.0</Data>
    <Data>5e54326e</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.18362.719</Data>
    <Data>4061c730</Data>
    <Data>e0434352</Data>
    <Data>00114192</Data>
    <Data>984</Data>
    <Data>01d60b85a6374bd3</Data>
    <Data>C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>7cd0ec59-55f2-489e-945e-46f7d197e57f</Data>
    <Data>40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne</Data>
    <Data>EarTrumpet</Data>
  </EventData>
</Event>
```

**Comment by servetoz** [comment]
Hi,
I have same issue. if you didnt fix it yet, I can share my error log but it is in Turkish and at least readable.

`Uygulama: EarTrumpet.exe
Framework Sürümü: v4.0.30319
Açıklama: İşlenmeyen bir özel durum nedeniyle işlem sonlandırıldı.
Özel Durum Bilgisi: System.Runtime.InteropServices.COMException
   konum: EarTrumpet.Interop.MMDeviceAPI.IAudioEndpointVolume.SetMute(Int32, System.Guid ByRef)
   konum: EarTrumpet.DataModel.WindowsAudio.Internal.AudioDevice.set_IsMuted(Boolean)
   konum: EarTrumpet.UI.ViewModels.AudioSessionViewModel.<.ctor>b__1_0()
   konum: EarTrumpet.UI.Helpers.RelayCommand.Execute(System.Object)
   konum: MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   konum: System.Windows.Controls.Primitives.ButtonBase.OnClick()
   konum: System.Windows.Controls.Button.OnClick()
   konum: System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   konum: System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   konum: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   konum: System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   konum: System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   konum: System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   konum: System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   konum: System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   konum: System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   konum: System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   konum: System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   konum: System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   konum: System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   konum: System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   konum: System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   konum: System.Windows.Input.InputManager.ProcessStagingArea()
   konum: System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   konum: System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   konum: System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   konum: System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   konum: System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   konum: MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   konum: MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   konum: System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   konum: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   konum: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   konum: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   konum: MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   konum: System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   konum: System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   konum: System.Windows.Application.RunDispatcher(System.Object)
   konum: System.Windows.Application.RunInternal(System.Windows.Window)
   konum: System.Windows.Application.Run(System.Windows.Window)
   konum: EarTrumpet.App.Main()

`

**Comment by riverar** [comment]
Thanks, will close for now. But will link to master issue #1305 as well.
