### ISSUE TITLE
New fluent design icon suggestion for EarTrumpet. 

### ISSUE THREAD

**Issue by Donnnno** [File-New-Project/EarTrumpet#484]
Hi, As you may have noticed all the microsoft icons are getting updated. So I tought why not update some of my favorite open source apps as well. I've updated the icon for Quicklook a couple of days ago.
This is my first suggestion for Eartrumpet, to give it more depth and a modern look. Let me know what you think and I'm open to other suggestions :) 

![earhorn4x](https://user-images.githubusercontent.com/31142286/78547520-84681180-77ff-11ea-94a2-6785034a9ca4.png)

**Comment by riverar** [comment]
Nice work, @Donnnno. Will review with the team and get back to you soon!

**Comment by riverar** [comment]
@Donnnno We'd like to move forward with this, do you have this in vector format? There's also some concerns around contrast against light backgrounds, thoughts?

**Comment by Donnnno** [comment]
Cool! here's the vector file, it looks kinda messy inside because it was quite tricky to do the fake 3d effect right in combination with shadows and gradients. :s
I don't think light backgrounds shouldn't be a huge problem (but I could be wrong), the colors I used are from the new windows weather icon.
Here's a zip with the an svg file and my whole work file (made in Illustrator). 
[eartrumpet.zip](https://github.com/File-New-Project/EarTrumpet/files/4671844/eartrumpet.zip)

**Comment by riverar** [comment]
@Donnnno so my good friend @niels9001 gave it a spin, just a few minor things:

* icon is a bit too large
* shadows need a bit of tweaking to match Microsoft's icon (darker shadow?)

**Comment by riverar** [comment]
![20200523_153614](https://user-images.githubusercontent.com/475132/82741854-8df3fd00-9d0b-11ea-81fd-84a323214af6.jpg)

**Comment by Donnnno** [comment]
Completely agree with the two points, it looks really out of place now. I'll try to fix those things :-)

**Comment by Donnnno** [comment]
I hope this one has better sizing & shadows:
[eartrumpet v2.zip](https://github.com/File-New-Project/EarTrumpet/files/4673601/eartrumpet.v2.zip)

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/83936407-409a7580-a778-11ea-9ecf-c3001d09e411.png)

Going to make some tweaks to the shadow.

**Comment by riverar** [comment]
![image](https://user-images.githubusercontent.com/475132/83936528-55c3d400-a779-11ea-851f-c87d628a09e7.png)

Just added 0.05% to the opacity and switched mix-blend-mode to normal.

**Comment by riverar** [comment]
Thanks @Donnnno looks pretty good to move forward.

Can you submit a PR to replace our tile assets in [EarTrumpet/EarTrumpet.Package/Assets/](https://github.com/File-New-Project/EarTrumpet/tree/master/EarTrumpet.Package/Assets)?

**Comment by riverar** [comment]
@Donnnno How's it going?

**Comment by Donnnno** [comment]
@riverar Hey! Sorry had a couple of busy weeks so I totally forgot this oops. 
I'm not entirely sure witch ones to replace here :s 
![afbeelding](https://user-images.githubusercontent.com/31142286/84604762-88b44900-ae98-11ea-9508-11381cdaee74.png)

**Comment by niels9001** [comment]
@Donnnno You'd need to replace all of them. These assets are used for e.g. the different tile sizes, splashscreen, taskbar and for the icon that is shown in the Store.

@riverar The vector file is probably important to have, for all the assets you'd need for the Store?

**Comment by riverar** [comment]
Yeah, I'm going to take that newfangled "Visual Asset Generator" for a spin right now. If that doesn't pan out, will build some Adobe Photoshop macros.

**Comment by riverar** [comment]
Thanks @Donnnno @niels9001, after a lot of frustration, I got this done. Will be in the next update.

**Comment by Donnnno** [comment]
@riverar oof, sorry I didn't had the time to do it yesterday. Thanks for replacing the icons (:

**Comment by riverar** [comment]
@Donnnno No problem, I realized it was quite a difficult task and used it as an opportunity to provide some feedback to Microsoft. Thanks again for the icon!

**Comment by tomzorz** [comment]
@riverar I made this a looong time ago, but might still work better than what they implemented inside VS https://github.com/tomzorz/UwpBetterTileGen
