### ISSUE TITLE
FR: Apps routing to multiple output devices

### ISSUE THREAD

**Issue by tomber42** [File-New-Project/EarTrumpet#486]
Hi, dont know if that is possible but it would be nice to routing an app to more than one output devices and can adjust it seperate.

**Comment by HaArD2000** [comment]
This would be great, I have several monitors and a soundbar and would love it if I could direct sound from VLC/Plex to all of them at the same time and tweak the volume of each device independently to get the right mix.

**Comment by SirNahka** [comment]
Thirded. Any idea when this might potentially be added? Is this in progress or anything like that?
