### ISSUE TITLE
Can you provide .exe pre-compile release?

### ISSUE THREAD

**Issue by p1r473** [File-New-Project/EarTrumpet#489]
My Windows Store is busted on my Win10 installation, and Chocolatey says the eartrumpet package can't be found

**Comment by riverar** [comment]
@p1r473 Chocolatey is still reviewing the package, but you can install using `choco install eartrumpet --version=2.1.7.0`. Pushing to get that resolved soon, thanks!

**Comment by riverar** [comment]
Update: Chocolatey package is now generally available. No need to use the --version argument now.
