### ISSUE TITLE
System Notifications no longer are being able to be able to lower the volume.

### ISSUE THREAD

**Issue by dragons4life** [File-New-Project/EarTrumpet#49]
Is there a trick somewhere were I can just make the windows system notification sound REALLY low, it used to work with this program and now it does't makes me so sad.

**Comment by riverar** [comment]
Do you have Show Desktop Apps enabled? Should be able to lower those sounds by lowering the System Sounds item.

**Comment by GoldenTao** [comment]
Closed due to lack of repro. If you get this one again, please reopen this issue.
