### ISSUE TITLE
Microphone chooser like the headphone chooser

### ISSUE THREAD

**Issue by dc-grimm** [File-New-Project/EarTrumpet#490]
Like the dropdown for Speakers / headphones as well as the options on the right click, can we have the same for Recording devices / microphones?

**Comment by angelopampalone** [comment]
Seconded, I would also like to have a bar for mic volume.

**Comment by Be77amy** [comment]
Came here looking for this, Thirded. Have more than one recording device so would be nice to route different mics to different programs like the output

**Comment by riverar** [comment]
Closing in favor of #99  #269 #302 but we hear you loud and clear.
