### ISSUE TITLE
Can't set "Alt Shift S" for shortcuts

### ISSUE THREAD

**Issue by Dr-KerbalMD** [File-New-Project/EarTrumpet#491]
I tend to use Alt Shift for global hotkeys I want to add, but EarTrumpet won't let me use it. The window records the Alt Shift part, but won't let me put in a letter.

![image](https://user-images.githubusercontent.com/20614697/79781693-dc2c6f80-830b-11ea-9cc7-e73577eb6032.png)

Works fine with Ctrl Shift, though:

![image](https://user-images.githubusercontent.com/20614697/79781815-15fd7600-830c-11ea-8859-635fff754388.png)

**Comment by riverar** [comment]
@kraetos Good catch, thanks!
