### ISSUE TITLE
Is application audio routing/output switching between devices only available on 1803+?

### ISSUE THREAD

**Issue by JsphBstwck** [File-New-Project/EarTrumpet#497]
I'm on 1709, and have installed via chocolatey, however, the button for moving an application's output to another device is missing.

https://imgur.com/a/D2lggrd

**Comment by riverar** [comment]
@JsphBstwck Yep, requires 1803 or higher as that's when it was added to Windows 10. 1709 is EOL across all sectors, so you should upgrade ASAP.
