### ISSUE TITLE
FR: Monitor(s) brightness control

### ISSUE THREAD

**Issue by Onepamopa** [File-New-Project/EarTrumpet#499]
It would be very cool if something like this: https://github.com/blackholeearth/Win10_BrightnessSlider can be integrated into EarTrumpet.

Use case - at least for me - I'm running multiple Windows 10 VMs with direct hardware pass-through, and brightness control in the notification area is not available.

You could reach out to "blackholeearth" and see if this can be done directly using his ready code.

**Comment by riverar** [comment]
Thanks @Onepamopa but this is out of scope for EarTrumpet. @blackholeearth's slider looks pretty good too.
