### ISSUE TITLE
Moving any ear trumpet window is very strange

### ISSUE THREAD

**Issue by ramonsmits** [File-New-Project/EarTrumpet#500]
Moving any ear trumpet window is very strange. The dragging is very slow and after letting go the window drags on for a short while. Resizing has the same problem

Version: 2.1.7.0
Environment: Windows 10 version 1909

**Comment by riverar** [comment]
Thanks @ramonsmits this is a known issue (#349) with Windows 10. We'll yank out the acrylic soon.

**Comment by thasmo** [comment]
@riverar I'm encountering this too on Windows 10 21H1 (Build 19043).
