### ISSUE TITLE
The parameter is incorrect - EarTrumpet launch problem

### ISSUE THREAD

**Issue by CallMeVorex** [File-New-Project/EarTrumpet#501]
![image](https://user-images.githubusercontent.com/42901035/81443191-e0121b80-916c-11ea-8a22-6f3feed8b8e9.png)
Getting this error when loading up eartrumpted (as well as on startup)

Windows Version:
![image](https://user-images.githubusercontent.com/42901035/81443271-0b950600-916d-11ea-9901-f85ea95b44f3.png)

**Comment by riverar** [comment]
Tracking this via #286 already. Can you follow the steps here? https://github.com/File-New-Project/EarTrumpet/issues/286#issuecomment-453363095
