### ISSUE TITLE
EarTrumpet doesn't launch at startup in Manganese builds of Windows 10

### ISSUE THREAD

**Issue by piell0** [File-New-Project/EarTrumpet#503]
On Windows 10 2004 it doesn't launch on startup anymore, even though it's enabled in the task manager

**Comment by riverar** [comment]
@piell0 Not seeing that here on Windows build 19041.207, what build are you using? If you're comfortable with regedit, can you screenshot the contents of the key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System`? (You should see values named EnableFullTrustStartupTasks, EnableUwpStartupTasks, etc.

**Comment by piell0** [comment]
I'm on Windows 10 Insider Preview 19624.1000, but I'm having this problem for a couple of months. I'm not sure from what built it has started.

![immagine](https://user-images.githubusercontent.com/65291764/81846756-e2042200-9552-11ea-83d5-288c8424a8d9.png)

**Comment by riverar** [comment]
@piell0 Registry looks good, hmm, anything in Event Viewer that could provide a hint? I'll install 19624 now and take a look, to make sure Microsoft didn't break anything.

**Comment by riverar** [comment]
@piell0 I can confirm, EarTrumpet is not starting up in 19628. Just a heads up, these aren't 20H1 builds (20H1 went GA recently, build 19041). You're on Fast ring which is far future stuff. But I'll start sending some emails now.

**Comment by riverar** [comment]
@piell0 If you upgrade to 19628, you should be able to enable EarTrumpet via Task Manager and everything will work correctly. Can you confirm?

**Comment by riverar** [comment]
Microsoft has confirmed there was a bug in this area in recent builds. It's fixed. If you run into this issue in builds > 19628, please re-open this bug.
