### ISSUE TITLE
Program that used a divice that isn't connected anymore cant be rerouted

### ISSUE THREAD

**Issue by Lightningblade** [File-New-Project/EarTrumpet#508]
Hello,
I had Firefox on a play over an audio device that no longer exists and now Firefox doesn't exist in any of the remaining audio devices. I can rename the firefox.exe to e.g.: firefox2.exe and it works fine for audio but everything else that relies on that exe doesn't work. In Firefox there isn't even a speaker symbol on the tabs anymore when trying to play sound (Probably because Firefox doesn't find the audio device itself that it is mapped to). 

Is there a way to reset all program bindings or reset the config (Because reinstalling eartrumpet doesn't work, and I can't find any file that resembles a datastore for the bindings in the folder). And to look through the source code to find where in the registry or appdata it is saved is a bit much for me.

**Comment by Lightningblade** [comment]
https://www.reddit.com/r/firefox/comments/ba471o/no_sound_from_firefox/f0y8z9j/ had a similar problem I think. And I tried deleting everything in %appdata%/.. that contains the string "eartrumpet". It didn't fix anything

**Comment by Lightningblade** [comment]
Temp fix, open regedit and search for Eartrumpet. Delete all entries that have a data field that looks like bytes (hex).

**Comment by riverar** [comment]
That's not necessary. Type Win+X, select Settings and then System > Sound > App volume and device preferences. At the bottom, click the <kbd>Reset</kbd> button.
