### ISSUE TITLE
"TuneIn Radio" mute changing output

### ISSUE THREAD

**Issue by angelopampalone** [File-New-Project/EarTrumpet#509]
Goodmorning.
The windows store app "TuneIn Radio" goes mute when I change audio output.

Starting up with headphone output (and sound):
![image](https://user-images.githubusercontent.com/6606447/83239190-d0985800-a197-11ea-987c-b01d8b388d4a.png)
![image](https://user-images.githubusercontent.com/6606447/83239210-da21c000-a197-11ea-9886-d3da3c34f41b.png)

Switching to monitor output (no sound)
![image](https://user-images.githubusercontent.com/6606447/83239312-ff163300-a197-11ea-990f-50e02f7ee37d.png)
![image](https://user-images.githubusercontent.com/6606447/83239327-03dae700-a198-11ea-8a7e-8cc9ff805bed.png)

And this is the app:
![image](https://user-images.githubusercontent.com/6606447/83239544-5916f880-a198-11ea-88a5-63eb8c103afe.png)
https://www.microsoft.com/it-it/p/tunein-radio/9wzdncrfj3sf?activetab=pivot:overviewtab

Thank you!

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.
