### ISSUE TITLE
FR: API accessible from windows desktop apps.

### ISSUE THREAD

**Issue by ryantheleach** [File-New-Project/EarTrumpet#511]
EarTrumpet is amazing, ~I've paid for the upgrade~ I'd be willing to donate to the project, and it's perfect for twitch streamers trying to organize their audio.

However, occasionally we need to automate some actions, including swapping / routing applications to different audio devices.

Exposing an API for EarTrumpet, would make this a ton easier.

**Comment by riverar** [comment]
@ryantheleach Paid for an upgrade? Can you share more information?

**Comment by ryantheleach** [comment]
I'm struggling to find evidence of it but I have memories of 'buying' Ear Trumpet on the store in some fashion.  Think it was a 'do nothing' donation like payment, that was listed as an in-app purchase.
