### ISSUE TITLE
FR: Drag and Drop Applications Between Output Devices

### ISSUE THREAD

**Issue by HumanizerDroid** [File-New-Project/EarTrumpet#513]
This is likely way more complicated than it sounds.

Im not a developer, but I would assume the best way to achieve this is to set Windows to use a Virtual Audio Device (EarTrumpet) for all apps, then EarTrumpet can manage the flow of audio from each source to destination. Allowing a drag and drop interface.

Use Case: Im listening to music via speakers, friend calls via Discord, I pause the music or he can hear it over my headphones. If I want to continue to listen to music and talk to my friend, i now how to open Spotify settings and change output device. The same in reverse. The potential Time savings are unlimited.

I would be happy for this to be a pro version! Up to £10 for a perpetual license.

Cheers, Jake.

**Comment by HumanizerDroid** [comment]
I revert, you already have the functionality of changing audio device :0 You have to right click 👍 

This is amazing haha! Will save me loads of time.

I would still like drag and drop, but I'm a happy man now.

**Comment by mirddes** [comment]
no i dont want to right click I ASKED FOR DRAG AND DROP

**Comment by ilkekaratas** [comment]
yes! Why not drag and drop?
