### ISSUE TITLE
Doesn't start when windows starts on version 2004

### ISSUE THREAD

**Issue by treypop** [File-New-Project/EarTrumpet#514]
On on Windows version 2004 EarTrumpet doesn't start at start up. I have to click the program in my start menu to run it.

**Comment by riverar** [comment]
Probably related #368

@treypop Navigate to Start > Run > type `ms-settings:startupapps` and click OK. What happens?

Can you also use regedit to check `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System` and see if the following values exist?
* `SupportFullTrustStartupTasks`
* `EnableFullTrustStartupTasks`

Also, check `HKCU\Software\Policies\Microsoft\Windows\Explorer` for `EnableAllStartupApplications`.

**Comment by riverar** [comment]
@treypop Did something change?
