### ISSUE TITLE
Microsoft Store displays error 0x80070520 (ERROR_NO_SUCH_LOGON_SESSION) when attempting to install EarTrumpet

### ISSUE THREAD

**Issue by heikoglaeske** [File-New-Project/EarTrumpet#517]
I'm not able to install from MS Store.
installing further apps is possible from MS store

I'll get the following code
Code: 0x80070520

**Comment by riverar** [comment]
@heikoglaeske This is a general Microsoft Store error (ERROR_NO_SUCH_LOGON_SESSION). Are you logged into the Store? Have you tried rebooting?

If all else fails, close the Store app, navigate to Start > Run, typing `wsreset`, then click OK. Wait a minute or so, then try again.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
