### ISSUE TITLE
EarTrumpet loses applications

### ISSUE THREAD

**Issue by HeviSevi** [File-New-Project/EarTrumpet#529]
Not sure if this started today, but at least I noticed it today.

EarTrumpet suddenly loses all individual applications/programs and leaves only my headsets volume there.
Speakers don't have this problem at all.

Windows volume mixer is working fine, but of course I'd rather use EarTrumpet since it's much more functional.

I use Logitechs G933 headset if that helps.

**Comment by riverar** [comment]
@HeviSevi Strange, can you reproduce this issue? When you do, collect troubleshooting data (via Settings) and attach here (or email it to team@eartrumpet.app). Thanks!

**Comment by HeviSevi** [comment]
Oh damn, I forgot to give an update on the issue. I completely forgot that it's an app that I can simply close and launch again. Relaunching it fixes the issue. 

It has happened only a few times and I'm unable to reproduce it, it just happens when it happens. I'll try to remember collect troubleshooting data next time.

**Comment by jfgodin** [comment]
I've had the same problem. I've discovered that it will happen when I change audio hardware settings (such as default playback device) in Windows. Restarting the app will fix it until the next change.

**Comment by Aniel** [comment]
> I've had the same problem. I've discovered that it will happen when I change audio hardware settings (such as default playback device) in Windows. Restarting the app will fix it until the next change.

I observe the same behavior, when switching devices. A restart of EarTrumpet fixes the problem

**Comment by Squeeky** [comment]
I periodically have this problem.  Annoying!  Yes, exit and restart fixes it, but I wish the EarTrumpet team could fix it.

**Comment by M-Ryba** [comment]
I can also reproduce this issue, it happens when switching modes on my Creative X G6 DAC and when switching between Dolby Atmos surround in windows settings

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
