### ISSUE TITLE
Ear Trumpet doesnt show any apps being opened.

### ISSUE THREAD

**Issue by mfavlutters** [File-New-Project/EarTrumpet#53]
so i opened skype and Dirt Rally and i wanted to try Ear Trumpet by lowering the volume of Dirt Rally so i could normally talk using Skype, but there arent any apps showing. it just says "it looks like you dont have any apps open.

**Comment by Rhedox** [comment]
https://github.com/File-New-Project/EarTrumpet/issues/52 Maybe same reason? Do you have "Show desktop apps" enabled?

**Comment by riverar** [comment]
@mfavlutters Can you confirm this is working now and close the issue if so?
