### ISSUE TITLE
Remove Feedback Hub link for feedback and replace it with GitHub

### ISSUE THREAD

**Issue by MarcAnt01** [File-New-Project/EarTrumpet#531]
![image](https://user-images.githubusercontent.com/43090263/88651289-d17f3480-d0c9-11ea-9c0e-9aa4c3275659.png)

**Comment by Cyberdroid1** [comment]
I also support the idea. Feedback Hub might be good for Windows apps, but not for 3rd-party apps. Its easier to look at issues on Github rather than Feedback Hub. Comment with 👍 or 👎 .
