### ISSUE TITLE
Eartrumpet won't open after windows update KB4568831.

### ISSUE THREAD

**Issue by Dojh342** [File-New-Project/EarTrumpet#536]
Eartrumpet (and several other apps such as 1password) won't open after windows update KB4568831. Confirmed by uninstalling the update which returns behaviour to normal.

**Comment by riverar** [comment]
I updated my machine and am not seeing any issues. Can you share the error you're seeing?

**Comment by Dojh342** [comment]
Just dived into event viewer - looks like the cause is my (out of date) rivatuner!

Faulting application name: EarTrumpet.exe, version: 2.1.7.0, time stamp: 0x5e54326e
Faulting module name: RTSSHooks.dll, version: 0.0.0.0, time stamp: 0x5c837072
Exception code: 0xc0000005
Fault offset: 0x00015d98
Faulting process ID: 0x40f0
Faulting application start time: 0x01d66d5f48643485
Faulting application path: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Faulting module path: C:\Program Files (x86)\RivaTuner Statistics Server\RTSSHooks.dll
Report ID: f1aa263e-a2a1-4962-bed5-10e79ecfcff5
Faulting package full name: 40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne
Faulting package-relative application ID: EarTrumpet

**Comment by WhiteLionATX** [comment]
Same for me. EarTrumpet crashes silently after starting it and after windows update. Same for Deepl. Before the update I had the same behavour after restoring my windows from hibernate.Name der fehlerhaften Anwendung: EarTrumpet.exe, Version: 2.1.7.0, Zeitstempel: 0x5e54326e
Name des fehlerhaften Moduls: d3d9.dll, Version: 10.0.19041.546, Zeitstempel: 0xc44e6fb3
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0004f5bb
ID des fehlerhaften Prozesses: 0x2268
Startzeit der fehlerhaften Anwendung: 0x01d6cb042c4dfe90
Pfad der fehlerhaften Anwendung: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\d3d9.dll
Berichtskennung: 2ec444a1-bf9f-45b6-9ba8-0e85fe589405
Vollständiger Name des fehlerhaften Pakets: 40459File-New-Project.EarTrumpet_2.1.7.0_x86__1sdd7yawvg6ne
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: EarTrumpet

Anwendung: EarTrumpet.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 6D55F5BB

**Comment by riverar** [comment]
Closing. Looks like this was an external issue and is fixed! Please open a new issue to let us know if you hit this problem again. Thanks!
