### ISSUE TITLE
Czech translations

### ISSUE THREAD

**Issue by bramborman** [File-New-Project/EarTrumpet#538]
Hi, I see there is no czech localization. I found the Crowdin project so I started working on the czech localization.
Is there anything else I should do beside translating the resources there?

**Comment by riverar** [comment]
@bramborman That's it, I can then export a snapshot and merge it in. Thanks very much!

**Comment by bramborman** [comment]
@riverar I just finished the localization so you can merge it in. I'd open a pull request with that but unfortunately I'm unable to compile the app so I'm unable to test it and so :/

**Comment by riverar** [comment]
@bramborman Will grab it in a moment; do also file any issues you're having with compilation, as it may indicate our compilation steps need to be revised. https://github.com/File-New-Project/EarTrumpet/blob/master/COMPILING.md
