### ISSUE TITLE
Missing slider control with touchpad/trackpad

### ISSUE THREAD

**Issue by Pivilio** [File-New-Project/EarTrumpet#542]
In the standard Windows volume slider, you can use two finger swipe to scroll to change volume. This is useful as it doesn't play the Windows volume change sound. Device is a Surface Laptop 1769 with precision touchpad.

**Comment by Cyberdroid1** [comment]
Actually there is slider control. Slide the 2 fingers up with the cursor on the bar. The volume will decrease. Do the opposite for increasing.

**Comment by Pivilio** [comment]
> Actually there is slider control. Slide the 2 fingers up with the cursor on the bar. The volume will decrease. Do the opposite for increasing.

Oh thanks, that's good to know. I was trying to swipe left and right since that's what the Windows slider uses. It's confusing to have them only work on different axes 😅

**Comment by Cyberdroid1** [comment]
Yeah, i agree it was strange to see that happen. 

I suggest that you please close this issue now. Thanks!
