### ISSUE TITLE
Dragging the settings box has a slow-motion animation

### ISSUE THREAD

**Issue by Cyberdroid1** [File-New-Project/EarTrumpet#543]
Steps to reproduce - 

1)Open the settings for EarTrumpet by rightclicking on its icon in windows notification area, and choosing settings.
2)Click and hold the title bar and drag it.

Expected result - 
The box should move smoothly with cursor and quickly.

Actual result - 
The box moves slowly and seems vague.

**Comment by riverar** [comment]
Thanks, this is a dupe of #349.
