### ISSUE TITLE
devs in need of help

### ISSUE THREAD

**Issue by horusra** [File-New-Project/EarTrumpet#545]
I'm sorry for posting this here, but the devs of Unigram seem to claim that having a tray icon for UWP requires magic of some sort. 
Can you guys please help them out?

https://github.com/UnigramDev/Unigram/issues/1905
https://github.com/UnigramDev/Unigram/issues/1955

**Comment by riverar** [comment]
@horusra Will reach out to Filippo and Unigram devs. Unigram is not a _runFullTrust_ app so they have no official access to the notification area.

**Comment by horusra** [comment]
> @horusra Will reach out to Filippo and Unigram devs. Unigram is not a _runFullTrust_ app so they have no official access to the notification area.

Thank you so much!

**Comment by FrayxRulez** [comment]
I don't need help, but thanks.

**Comment by FrayxRulez** [comment]
EarTrumpet is a Win32 software and it has classic access to the system tray.
Unigram is a UWP app and UWP apps don't support it. 
I'm not going to write some dumb hacky code just for this, I'll likely migrate Unigram to Win32 as soon as WinUI 3 will be stable enough for this.
