### ISSUE TITLE
Add audio source switching

### ISSUE THREAD

**Issue by Nuzza** [File-New-Project/EarTrumpet#547]
It would be great if EarTrumpet could allow the user to switch the audio source you're listening to when clicking on the icon. Ways this could be implemented/presented is in the dropdown when you expand the list of all audio sources, an option to switch to that source would be a great enhancement for EarTrumpet. Currently, I still keep Windows 10 default volume tray icon in the taskbar along with EarTrumpet as I use EarTrumpet for the easy access volume mixer (great job btw), but use the default Windows 10 volume to switch audio sources like when I connect my Bluetooth headphones to my computer. This would also bring more use to the expanded view of all the audio sources, having the option to switch to that audio source.

**Comment by riverar** [comment]
@Nuzza Right-clicking the notification area icon presents a list of devices to switch to. Is that what you were looking for?

**Comment by Nuzza** [comment]
That was fast, oh wow, somehow I completely missed that, thanks a tone!

**Comment by Nuzza** [comment]
@riverar Thanks again! Amazing app btw, one of my favs on the Microsoft Store, cheers!
