### ISSUE TITLE
Missing localization string

### ISSUE THREAD

**Issue by bramborman** [File-New-Project/EarTrumpet#548]
I'm testing the czech localization I made and noticed there's a string that's not localized and is not just a _dev thing_:

![screenshot](https://user-images.githubusercontent.com/20975774/90963963-ccd95080-e4bc-11ea-9608-b95072257b13.png)

**Comment by riverar** [comment]
Testing on a Czech (cs-CZ, 1029) system.

```powershell
[Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms") | Out-Null
$Converter = New-Object Windows.Forms.KeysConverter
$Converter.ConvertToString($Null, [System.Globalization.CultureInfo]::CurrentUICulture, [Windows.Forms.Keys]::None)

None
```

**Comment by riverar** [comment]
Doesn't look like keys are localized in Windows
![image](https://user-images.githubusercontent.com/475132/90990128-b16d5480-e553-11ea-8564-cca2c3d246e9.png)

Perhaps `None` should be treated as a special case. Will consider that, though adding new strings to the app requires a round of tedious localization.

**Comment by bramborman** [comment]
@riverar Wouldn't think it's not localized in Windows itself 😮 It's just minor issue so maybe the special case for `None` can be added when new strings are added later?

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I filed an issue over at https://github.com/dotnet/winforms/issues/8527 to continue tracking this issue.
