### ISSUE TITLE
Put EarTrumpet in the Store

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#55]
Wrap using "Project Centennial" for UWP access

**Comment by riverar** [comment]
Update: Should be available next month

**Comment by riverar** [comment]
@jssshashi What's wrong with it?

**Comment by jssshashi** [comment]
Company Name field says File-New-Project

**Comment by GoldenTao** [comment]
The org name for this project is File-New-Project.

**Comment by jssshashi** [comment]
:) did not see that one !!

**Comment by riverar** [comment]
Done with https://github.com/File-New-Project/EarTrumpet/commit/87c2a8090e9598489fae657c893d91789eb894df
