### ISSUE TITLE
Action to switch and toggle spatial sound

### ISSUE THREAD

**Issue by ThiruGS** [File-New-Project/EarTrumpet#550]
Windows 10 as of version 2004 has the option to change or turn on/off the spatial sound option by right-clicking on the volume icon. The spatial sound may work great for games and movies but gives a poor output for songs so It's really handy to have a switch to toggle them on and off.
Currently, there is no way to get that same functionality in Ear Trumpet and because of that, I need to have the Windows volume controller pinned to my taskbar.
It'll be great to have an option in Ear Trumpet to have the ability to switch and toggle the spatial sound on or off.

Thanks!

**Comment by riverar** [comment]
Thanks, we're already tracking this via #212.
