### ISSUE TITLE
'Audio settings' entry in context menu opens the 'Playback devices' tab instead of actual audio settings

### ISSUE THREAD

**Issue by paolo257428** [File-New-Project/EarTrumpet#554]
When clicking the **_Old Windows Menu > Audio Settings_** (may not be the exact english string cause I'm using the italian locale) entry in the tray icon's context menu, the '_Playback devices_' tab of the old control panel is opened. I think this is an oversight and that the correct behaviour would be to open the Audio page of the Windows Settings app (as the corresponding entry of the actual Windows volume tray icon does).

Attaching an image to show what I'm talking about (again pardon the italian locale):
![immagine](https://user-images.githubusercontent.com/45040214/91342655-a3ca0000-e7db-11ea-8511-c82d7088a763.png)

I could take on this small change by myself and file a PR for it later on, but I don't have much time to look into it right now (just installed EarTrumpet yesterday so I didn't have the chance to familiarize with the code yet) so maybe someone else will be able to fix it quicker than I would.

**Comment by riverar** [comment]
Thanks @paolo257428, good bug.

**Comment by paolo257428** [comment]
Good job fixing it this quick! Should I just close the issue or wait for the update to do so ?

**Comment by riverar** [comment]
@paolo257428 When we merge to main and release, it'll close automagically!
