### ISSUE TITLE
EarTrumpet sometimes does not correctly open

### ISSUE THREAD

**Issue by prakharb5** [File-New-Project/EarTrumpet#560]
EarTrumpet sometimes opens partly covering the taskbar.

![image](https://user-images.githubusercontent.com/51435948/91938479-b4b1ce80-ed11-11ea-8360-7c1d02dfa345.png)

**Comment by riverar** [comment]
Thanks, we see this from time to time but cannot reproduce it reliably enough to fix at this time. If you figure out repro steps, let us know!

**Comment by Cyberdroid1** [comment]
Maybe just summon the window repetitive types? That's all I can say for it.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
