### ISSUE TITLE
App does not appear to be DPI aware.

### ISSUE THREAD

**Issue by Drexl** [File-New-Project/EarTrumpet#562]
Right-clicking on the Ear Trumpet icon results in a very small menu on my 4k monitor at 150% scaling. Overriding DPI scaling (using any setting) doesn't have any effect.

**Comment by Drexl** [comment]
This appears to only be effecting the root context menu. Application windows (such as the mixer), and child context menus (windows legacy settings) are larger.

**Comment by riverar** [comment]
@Drexl Can you collect Troubleshooting data (Settings > About) and paste the file here? EarTrumpet has extensive high DPI support.

**Comment by Drexl** [comment]
[tmpC74E.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/5294160/tmpC74E.tmp.txt)

**Comment by riverar** [comment]
```
systemDpi: 96
taskbarDpi: 144
```

Have you logged out/in since changing the DPI?

**Comment by Drexl** [comment]
> ```
> systemDpi: 96
> taskbarDpi: 144
> ```
> 
> Have you logged out/in since changing the DPI?

Yes, many times. I've not changed DPI settings for over a year. Although this isn't the only application that suffers from this issue now that I think about it. I've fixed it with other applications by overriding DPI scaling. It's often just the system tray icon context menu that has an issue when it happens, which is only a handful of apps.

**Comment by riverar** [comment]
In Advanced scaling settings, is this feature on or off?

![image](https://user-images.githubusercontent.com/475132/94470707-e38a5b80-017c-11eb-84bf-f651f7fc2547.png)

**Comment by Drexl** [comment]
On. I'm in a meeting so can't turn it off and restart, but I'll try that later.

**Comment by riverar** [comment]
No need to change it, mine is on too and the taskbar/system DPIs match. Will investigate this further, thanks!

Just a heads up, the version of Windows you're using is near EOL (December 2020).

**Comment by Drexl** [comment]
Windows 10 Pro 1909? 0_o

**Comment by riverar** [comment]
The log you sent shows `osVersionBuild: 18362.1.amd64fre.19h1_release.190318-1202`, which is Windows 10 May 2019 Update (1903).

**Comment by Drexl** [comment]
![image](https://user-images.githubusercontent.com/2714403/94473409-028aec80-0181-11eb-8ae0-83fa95bebd6e.png)
I opened the log, and yea that's what it says. Idk what to tell you. Here is a screenshot from my settings. I update frequently. I replaced my motherboard a few days ago because the old one died. *shrug*

Also, idk if this helps at all, but I'm using dual monitors. The top monitor is my 4k display at 150% scaling, the  bottom monitor is 1440p with no scaling adjustments. The taskbar sits on the top monitor. I use Display Fusion, but I'm not aware of anything it's doing that should touch scaling in any way. I'm not using it's taskbar.

**Comment by riverar** [comment]
Can you open Registry Editor, navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`, and paste the values for `BuildLab` and `BuildLabEx`?

**Comment by Drexl** [comment]
BuildLab: 18362.19h1_release.190318-1202
BuildLabEx: 18362.1.amd64fre.19h1_release.190318-1202

**Comment by riverar** [comment]
Maybe something overwrote those values on your machine. (Or Windows didn't update them after upgrading.)

Can you navigate to `C:\Windows\`, right-click Explorer.exe > Properties > Details tab and paste/verify the `File version`?

**Comment by Drexl** [comment]
10.0.18362.997

**Comment by riverar** [comment]
Hey @Drexl are you still seeing this issue with the 19042 (20H2) release of Windows?

**Comment by Drexl** [comment]
I'm unable to verify as I've changed displays to a single ultrawide. I think perhaps some combination of multiple monitors, differing resolutions, and differing DPI scaling between displays could have been causing the issue. Granted, the issue was sometimes resolved in other apps exhibiting the same odd behavior by overriding DPI scaling (Share X is an example where this worked), but it's plausible this might be a weird edge case resulting from an OS bug. I've yet to experience this issue now that I've adopted a more sensible display configuration. :)

**Comment by riverar** [comment]
@Drexl Thanks for following up. I switched to an ultrawide as well (Samsung 49" CHG90 monster) for the first time. Definitely pros and cons to this approach. I kind of miss my separate monitors at times.

At any rate, will close this for now. But holler if it happens again.
