### ISSUE TITLE
EarTrumpet prevents screen from being turned off after set time

### ISSUE THREAD

**Issue by Reonu** [File-New-Project/EarTrumpet#563]
Long story short: Windows 10 was never turning off my screens after the time I set in the power options. I ran powercfg /requests and saw this: https://i.imgur.com/Vc9Glta.png

I closed EarTrumpet and it was inmediately fixed. The USB Audio device thing dissapeared from there and Windows was once again able to turn off the screens after the set time passes.

**Comment by riverar** [comment]
Hi @Reonu, does it happen if you restart EarTrumpet and try to reproduce this behavior? Can you provide troubleshooting data? (Settings > About > Collect troubleshooting data)
