### ISSUE TITLE
UI Tweak for Overall Volume

### ISSUE THREAD

**Issue by cleslie577** [File-New-Project/EarTrumpet#564]
Have an option to switch the position of the main volume closer to the original volume mixer.  And then have the additional applications above the main volume.  More simple and similar to the original volume mixer.  I feel like I change overall volume much more often than separate app volumes so it should be easier to move your mouse to.

![Screenshot-2020-09-29-120531](https://user-images.githubusercontent.com/24420048/94604764-ff5d3280-024c-11eb-98b8-0c2a340b26d3.jpg)

**Comment by riverar** [comment]
Thanks for submitting this. We discussed this as a team long ago and decided it wasn't something we want to support in EarTrumpet.
