### ISSUE TITLE
EarTrumpet not responding to anything

### ISSUE THREAD

**Issue by guyman70718** [File-New-Project/EarTrumpet#566]
For some reason, a few days ago eartrumpet started randomly ignoring clicks, but eventually, it would open. It became more and more common, and now it won't open at all. I tried reinstalling it from the MS Store and it made no difference. I can't left click to open it, or right click to open the context menu. If I hover over it, it does update the default device and the volume, but I can't get it to open up at all. I am running windows 10 1909.

**Comment by guyman70718** [comment]
huh, so right now while I was watching a video, the context menu for ear trumpet popped up on my screen and it won't go away now, and all the buttons won't respond.

**Comment by nguyentvan7** [comment]
I notice a similar issue, but restarting EarTrumpet seems to fix it for me, so it seems like over time the performance degrades.

**Comment by guyman70718** [comment]
Yes, it seems like it just takes incredibly long for things to happen sometimes. A few hours after I commented that the context menu popped up like half an hour late, eartrumpet decided to open itself and do the first time wizard/demo/tutorial, even though I hadn't clicked the icon since.

**Comment by guyman70718** [comment]
It seems that the problem starts after waking from sleep

**Comment by Matterhorn56** [comment]
I ended up uninstalling permanently; even reinstalling solved the problem for only half a day before the taskbar icon became unresponsive again.

**Comment by Matterhorn56** [comment]
For me, this works: "A quick fix is to install EarTrumpet, copy C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_1.4.3.0_x86__1sdd7yawvg6ne into another folder and run EarTrumpet.exe there (outside the Store)."

mentioned here as a temporary fix for a different issue
https://www.reddit.com/r/forza/comments/558vfc/eartrumpet_alternative/

**Comment by riverar** [comment]
@Matterhorn56 Strange, haven't seen this before. If you're still willing to dig into this, please start EarTrumpet fresh, get it into the funky state, then open EarTrumpet Settings, navigate to General > About, and click Collect troubleshooting data. Shoot that output to `team@eartrumpet.app` and referencing this issue. Thanks!

**Comment by Matterhorn56** [comment]
Alright, so I've started using the app normally after a fresh windows install and all is going well! If I encounter it again I'll send the troubleshooting data.
