### ISSUE TITLE
Displaying Battery Level of Bluetooth Headphones

### ISSUE THREAD

**Issue by mortyobnoxious** [File-New-Project/EarTrumpet#567]
I don't know if this is out of range of your project but if implemented, this would be really great.

Directly seeing battery level of Bluetooth headphones something like this:
![image](https://user-images.githubusercontent.com/42044258/95461420-e2c4a700-097e-11eb-82e4-0ad4b70d38d7.png)

**Comment by riverar** [comment]
Neat idea, thanks!
