### ISSUE TITLE
Setup.exe - Trojan Found by Windows Defender

### ISSUE THREAD

**Issue by myty** [File-New-Project/EarTrumpet#57]
Windows Defender found a trojan type malware in the setup.exe.

Unfortunately, I removed the file from quarantine before I thought of reporting it here, hence I don't really have any further info.  I'm assuming it's a false positive, but figured I'd report it just in case it isn't.

**Comment by Stephanvs** [comment]
Got the same notification..

![image](https://cloud.githubusercontent.com/assets/375631/14504040/47a92728-01b3-11e6-80b1-e5092a8bce3d.png)

The link redirects to: https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fFathale.B!plock&threatid=2147709273&enterprise=0

**Comment by myty** [comment]
Yup.  That's the one.

**Comment by GoldenTao** [comment]
Microsoft released an update of the definitions, this should now be working correctly.  Thanks for reporting.
