### ISSUE TITLE
Audio Switches Back to Previous Playback Device

### ISSUE THREAD

**Issue by Blootrix** [File-New-Project/EarTrumpet#571]
I'm using a music player called MusicBee

I changed MusicBee to play music from - "VoiceMeeter VAIO3"
(Originally MusicBee played music from - "VoiceMeeter Input")

When double checking, audio now plays from - "VoiceMeeter VAIO3"

If I close MusicBee and reopen it, music now incorrectly plays from - "VoiceMeeter Input"

When I go to change the line back to "VoiceMeeter VAIO3", it is already checked, BUT MusicBee is in the "VoiceMeeter Input" section and I need to check "VoiceMeeter VAIO3" again, even thought it's already checked.

Any idea what I can do to fix this bug?
Thanks.

**Comment by lesyriad** [comment]
MusicBee has a built in setting that is overriding both EarTrumpet and Windows settings.  Within MusicBee Click on the MusicBee menu at the top control bar.  Select Edit/Edit Preferences.  Under Player select there is an option called Sound Device: select what output you want there and it will be saved across quitting MusicBee.

**Comment by Blootrix** [comment]
> MusicBee has a built in setting that is overriding both EarTrumpet and Windows settings. Within MusicBee Click on the MusicBee menu at the top control bar. Select Edit/Edit Preferences. Under Player there is an option called Sound Device: select what output you want there and it will be saved across quitting MusicBee.

Thank you very much, I really appreciate the help in fixing my issue.
