### ISSUE TITLE
Audio redirection for popular game Fall Guys not possible

### ISSUE THREAD

**Issue by popposoft** [File-New-Project/EarTrumpet#572]
Hello

I installed EarTrumpet in order to solve audio redirection for one particular stubborn executable: Fall Guys

![Immagine](https://user-images.githubusercontent.com/554770/97280361-77af1780-183c-11eb-951d-ad81d356adde.png)

As you can see in the screenshot attached I tried to redirect this app inside Aux-2 channel 
I own an Elgato Wave-1 microphone as you can see

App shows audio channel inside win10 control panel as well but as you can see from the elgato wave link mixer app (aux-2 is behind EarTrumpet panel but its level shows no audio) and EarTrumpet panel, audio comes off default (which is System channel in my case).
Strange thing is in Aux2 channel icon of the app is present but it does not output audio as you can tell from the meter.

I tried many times, with all the different channels, same outcome. I tried to reroute and then close the app and reopen it, same outcome. This won't work for some reason.

What can be done to fix this?

Thanks in advance

**Comment by riverar** [comment]
Hey @popposoft, let's rule out EarTrumpet here. Open Start > type "sound mixer options" and hit Enter. In the [App volume and device preferences] window that appears, try changing the output device for Fall Guys. Does it work?

**Comment by popposoft** [comment]
It never worked this way for this particular application, and that's the main reason I installed EarTrumpet.

BTW I updated the game today from Steam, I just repeated this process a dozen times.
Closed the app and reopened every time I changed the output to anything else than the default I have set (control panel does not apply the change instantaneously) but no, sound always goes to default output every time.

**Comment by riverar** [comment]
@popposoft Ah ok. I'm going to mark this as a Windows bug.

To assist the audio stack engineers at Microsoft, please file a bug in Feedback Hub under `Devices and Drivers` - `Audio and sound`. You can cut and paste this template (but verify the steps apply to you). Please also check ☑ Save a local copy of diagnostics and attachments created when giving feedback. Send a copy of that data to team@eartrumpet.app and reference issue 572.

```
Summary: Windows 10 does not redirect Fall Guys audio to my chosen output device

Explain in more detail:
When I start Fall Guys and attempt to redirect the output to another device, via [App volume and device preferences], nothing happens. The audio continues to output via the wrong device.

Repro steps:
  1. Start Fall Guys
  2. Open [App volume and device preferences] and change the output device from [Default] to another non-default device
  3. Observe Fall Guys audio continues to play through the default device

See also: EarTrumpet/issues/572
```

Then paste a link here and I'll forward it directly to the audio team.

**Comment by mikjo243** [comment]
Got the samer problem. Eartrumpet doesn't help. It shows fall guys under Game channel. But every time I start Fall Guys a new instance of it appears under System sound channel. Haha. Shit game. ;)

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
