### ISSUE TITLE
Mute no longer saved on Microsoft Solitaire Collection after Windows update

### ISSUE THREAD

**Issue by bigfoott** [File-New-Project/EarTrumpet#578]
This appears to be a similar issue to #88, which worked for me until a few days ago.

Prior to using EarTrumpet, the program would unmute itself every time it ran an ad. Once I started using EarTrumpet the mute was saved. Now, it unmutes once I reopen it, but it doesn't unmute when ads play.

Win 10 OS version 19041.572

**Comment by riverar** [comment]
@bigfoott Sorry, not following you here. Can you provide repro steps? Are you saying when you mute Solitaire you still hear ad audio?

**Comment by riverar** [comment]
I can reproduce this. Solitaire has a long history here of being ... problematic.

1. Start Microsoft Solitaire Collection
2. Set the app volume to 42% then mute the app
3. Close Solitaire and re-open it
4. Observe volume and mute state are reset

**Comment by bigfoott** [comment]
Yeah, I originally found EarTrumpet because I wanted a way to keep Solitaire muted lol. Your repro steps work for me as well.

**Comment by carlosvsilva** [comment]
I'm trying EarTrumpet to keep one noisy game app (Cold Space) at a lower volume than the rest of the system, but when I relaunch it the volume for it is reset like in Windows native volume mixer. Can you look into it please? Thanks

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. (We will, however, make sure EarTrumpet Actions can mute this at launch properly.) Feel free to keep the discussion going. Thanks!
