### ISSUE TITLE
Fast-switch default playback device

### ISSUE THREAD

**Issue by longzheng** [File-New-Project/EarTrumpet#58]
There are many apps which don't allow you to specify output device. I usually have to manually go to Sound properties to set the default device when using specific apps.

It would be a very handy feature of EarTrumpet to allow switching playback devices quickly.

Mockup (default state)
- Show name of current default device
- Show dropdown toggle

![image](https://cloud.githubusercontent.com/assets/484912/14586235/fcdc3814-04d4-11e6-8de6-26210e67c7b3.png)

Mockup (switch state)
- Show speaker name and device name of all ready and available speakers (hide disconnected and disabled speakers)
- Indicate currently default device
- Click to switch to new device

![image](https://cloud.githubusercontent.com/assets/484912/14586240/358fe4f8-04d5-11e6-98dc-192bff8b3dd0.png)

**Comment by longzheng** [comment]
I've just learned this feature is in the context menu. I would suggest
- Updating readme to include more features
- Still implement a design like this to imply it is doable without right-clicking the icon (less discoverable)

**Comment by longzheng** [comment]
I guess this dupes and relates to #54 #9 

Specifically for #30 I think this is a more touch friendly solution

**Comment by Rhedox** [comment]
Heres how Microsoft did this:
![image](https://cloud.githubusercontent.com/assets/1131720/14761291/53f5d7e6-095c-11e6-8f27-bd314154b171.png)

I'd suggest implementing it in a similiar fashion.

**Comment by riverar** [comment]
Check out EarTrumpet 2.0. https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp
