### ISSUE TITLE
Swedish translations

### ISSUE THREAD

**Issue by leonlarsson** [File-New-Project/EarTrumpet#584]
Hello! I just wanted to inform you that I have contributed the Swedish translations over on Crowdin.

Not fully up-to-speed on what happens after, but I'm happy to help. Thanks for the awesome and extremely helpful application!

Cheers!

**Comment by riverar** [comment]
Thanks @leonlarsson, got it!

**Comment by riverar** [comment]
Closing issue. EarTrumpet 2.1.8.0 is now available in the Store with a fix for this issue. Thanks for your patience!
