### ISSUE TITLE
Dragging the volume mixer window produces mouse lag

### ISSUE THREAD

**Issue by Robzyy** [File-New-Project/EarTrumpet#585]
Dragging Eartrumpet's volume mixer window makes my mouse lag, making the process very slow.  

Right as I was writing this, I have tried to record it to give you an idea but it looks like it also makes Gyazo lag behind. When Gyazo was done processing, the recording was looking just fine, like there was nothing unusual...

Intel Graphics Driver version: 27.20.100.8935 
NVidia Driver version: 457.30
Windows version: 20H2
Let me know if you need more info!

**Comment by riverar** [comment]
Yep, it's a Windows bug. We're tracking this one already via #349 thanks.
