### ISSUE TITLE
EarTrumpet only shows main volume after switching Spatial Sound

### ISSUE THREAD

**Issue by avansteenbruggen** [File-New-Project/EarTrumpet#587]
EarTrumpet only shows main volume after switching Spatial Sound in the windows settings
I switch my spatial sound in sound properties and the i only see the main volume in EarTrompet, have to restart it to see all volumes again.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
