### ISSUE TITLE
Moving Window?

### ISSUE THREAD

**Issue by boxcatx3** [File-New-Project/EarTrumpet#59]
Is there a way to move the window?

**Comment by GoldenTao** [comment]
Is there a reason you want to move it?  Currently no, it's locked to the task bar to show up like the network pane.

**Comment by boxcatx3** [comment]
It shows up in the middle of my screen and I want it to  stay  locked to my second screen

**Comment by GoldenTao** [comment]
Can you grab a screenshot?

**Comment by boxcatx3** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/18585309/14695774/66114f66-0743-11e6-8ad2-f6f1f34e81fc.png)

**Comment by riverar** [comment]
Can you also provide a screenshot of Display Settings (right-click the desktop)?
