### ISSUE TITLE
[Bug] Some audio stream does not show up when using hands-free devices

### ISSUE THREAD

**Issue by IAmNotAJerk** [File-New-Project/EarTrumpet#590]
Zoom meeting audio does not appear as a separate audio channel when using hands-free devices. In windows legacy mixer, it appears no problem. 

![image](https://user-images.githubusercontent.com/23354246/101559205-9ee03380-39fb-11eb-8fbb-b8a664c985fa.png)
![image](https://user-images.githubusercontent.com/23354246/101559242-b0294000-39fb-11eb-9572-923970b05d25.png)

Zoom is shown on other devices, but not in the hands-free device I'm using. As shown in the first image, in the legacy mixer, when the same hands-free device is selected, the audio stream appears as expected.

**Comment by riverar** [comment]
Interesting, I'll check this out. Can you also grab the troubleshooting data in EarTrumpet > Settings > About and email it to team@eartrumpet.app? Thanks!

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.
