### ISSUE TITLE
Cant install the app

### ISSUE THREAD

**Issue by Chrinsieboy** [File-New-Project/EarTrumpet#596]
I cant install the app on windows.
I am on windows 10 home edition
V10.0.19042 Build 19042

**Comment by riverar** [comment]
@Chrinsieboy Can you provide more info? What happens, how are you trying to install it, etc.?

**Comment by Chrinsieboy** [comment]
Im installing it on my windows 10 computer by the microsoft store.
It just says Error with code 0x80072F8F.
I couldnt find anything with that code by microsoft, so yea

**Comment by Cyberdroid1** [comment]
Looked online. Seems like a windows bug. 
Try a media creation upgrade. Can help in fixing it.

**Comment by riverar** [comment]
Closing. We can't reproduce this. Several releases of Windows have now passed so the problem may no longer exist. Please open a new issue to let us know if you hit this problem again. Thanks!
