### ISSUE TITLE
Add command line control

### ISSUE THREAD

**Issue by engelby** [File-New-Project/EarTrumpet#602]
I frequently switch between 2 different output sound devices.  Could there be a way to use Powershell to programmatically change between outputs?

**Comment by firewaran** [comment]
until this is considered or implemented i can recommend the option setdefaultsounddevice from [NirCmd](https://nircmd.nirsoft.net/setdefaultsounddevice.html)
I use that to switch between three setups: VR, Normal, Headphones

**Comment by engelby** [comment]
Thanks!  Somehow my google-fu didn't find that utility.   For those who may be wondering, I can confirm this works under Windows 10.
