### ISSUE TITLE
Window automatically resizes when closing and opening

### ISSUE THREAD

**Issue by Dani3lNL** [File-New-Project/EarTrumpet#603]
When opening, it looks like this:

![grafik](https://user-images.githubusercontent.com/20766261/103290079-fcf3ab80-49e8-11eb-96c8-b378402a587b.png)

Then I manually resize it to this:

![grafik](https://user-images.githubusercontent.com/20766261/103290103-0bda5e00-49e9-11eb-8840-1ac434ff59c5.png)

When then closing the window and opening again, it's reset back to what it looks like in the first image.

**Comment by davuxcom** [comment]
This is the intended behavior. Spanning across screens creates a different set of problems, so this was the solution. This window does not remember size/position across open/close either.

**Comment by MikeyMike22** [comment]
Why would that be intended? I did not mention spanning across screens, why would we want it to span across screens? @davuxcom

**Comment by davuxcom** [comment]
> Why would that be intended? I did not mention spanning across screens, why would we want it to span across screens? @davuxcom

This is why it doesn't just open up and show all your devices. It makes a cut-off at some point because we didn't want it crossing screen boundaries.  Are think we pick something like no wider than 70% of the screen it'll open on, as the max width.
