### ISSUE TITLE
Ear Trumpet does not start

### ISSUE THREAD

**Issue by bhujelaayushgc** [File-New-Project/EarTrumpet#604]
I think after the recent windows update, ear trumpet just does not start. Here is the Windows Log for `.NET Runtime`

Application: EarTrumpet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 65BF65AD

**Comment by bhujelaayushgc** [comment]
Never mind! Found a hint.

https://github.com/File-New-Project/EarTrumpet/issues/268#issuecomment-405086088

**Comment by riverar** [comment]
So was this another case of MSI Afterburner?
