### ISSUE TITLE
Please provide ZIP Archive to download at Github

### ISSUE THREAD

**Issue by lunainvictum** [File-New-Project/EarTrumpet#606]
Happy new year together!

Could it be possible to provide a simple ZIP Archive to download here at Github?

I dont have MS Store. I removed the complete "App Support" from my Windows so it isnt possible to use and install any "Apps" anymore. Like i want it.

And i dont want to use Chocolatey either. 

So i look at the Page from Chocolatey and searched the package. There i looked in the Script where chocolatey download eartrumpet and found out that it simply provides a Release.zip. So i download the nupkg. Decompressed it with 7zip. Searched for Release.zip, decompressed this too and found eartrumpet. 

This is to complicated for normal peoples, who wants to use eartrumpet, without to sell their Soul to Microsoft or Chocolatey. 

Sry for my bad english. Im native German Speaker.

**Comment by riverar** [comment]
How do you plan on receiving updates?

**Comment by lunainvictum** [comment]
So long everything works like needed, no Updates are necessary.

And if a Problem occurs, i could simply Check here at github if a new Release is released.

To write a Option or Function into eartrumpet to Check at github if a new Version is released and update it by simply download it from github and decompressing the archive on the installation path is possible too.

I wrote a powershell Script for a another program that i found at github and dont have a Update function (only to Check if a new Release is released and to open the webpage for the User). 

Am 2. Januar 2021 01:45:21 MEZ schrieb Rafael Rivera <notifications@github.com>:
>How do you plan on receiving updates?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/File-New-Project/EarTrumpet/issues/606#issuecomment-753410788

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Trouffman** [comment]
The main reason for the release would be to not be tied to the Windows Store.
