### ISSUE TITLE
Rename the "Windows Legacy" menu to "Windows"

### ISSUE THREAD

**Issue by xmha97** [File-New-Project/EarTrumpet#608]
Hi,
Please rename the "Windows Legacy" menu to "Windows" and remove legacy items.
![Windows 10](https://user-images.githubusercontent.com/23485114/103614291-83564300-4f3d-11eb-842f-8bae337da528.png)

You can use the UWP settings, for example:

# Volume Mixer
```
ms-settings:apps-volume
```

# Playback devices
```
ms-settings:sound-devices
```

# Sound settings
```
ms-settings:sound
```

Also, see:
https://4sysops.com/wiki/list-of-ms-settings-uri-commands-to-open-specific-settings-in-windows-10/

**Comment by riverar** [comment]
There's no reason to do that.

**Comment by xmha97** [comment]
> 
> 
> There's no reason to do that.

You will do this because the Windows legacy settings (Control Panel) are being removed.

**Comment by riverar** [comment]
@xmha97 If the applets disappear, we'll hide the entries on that version of Windows. But current development builds of Windows 10 show these settings are not gone yet.
