### ISSUE TITLE
Can i get a how 2?

### ISSUE THREAD

**Issue by te11enbach** [File-New-Project/EarTrumpet#609]
I don't really use things like this so if anyone could give me a process tree cus i dont know where to go after extracting the zip.

**Comment by Cyberdroid1** [comment]
Install the app from the MS store.

**Comment by riverar** [comment]
@te11enbach Hi there, check out the README https://github.com/File-New-Project/EarTrumpet#install. Let us know if need more help via Discussions tab above. Thanks! Closing this issue.
