### ISSUE TITLE
Split audio streams to different playback devices

### ISSUE THREAD

**Issue by MortenManden** [File-New-Project/EarTrumpet#61]
If windows allows it splitting the audio to different devices would be a great improvement.
I would like to be able to:
- Play e.g. the radio from Microsoft Edge browser on Bluetooth speaker
- Play a video from youtube on chrome with the internal browser
- Run a Skype voice call on the jack-stick head phones

All at once of course

**Comment by MortenManden** [comment]
Is possible in indievolume.com and chevolume.com

**Comment by riverar** [comment]
I've played with these apps and none of them work reliably, which speaks to general app compat. We'll keep looking into this though.

**Comment by mdb17** [comment]
This is something I would be interested in this as well

**Comment by vandepoelm** [comment]
I would pay for this function, 

CheVolume is bulky and not practical, all the rest is useless.

i really like eartrumpet, its a real lifesaver for me.

**Comment by MortenManden** [comment]
Hi friend! 


We are planning  a short trip this summer and wanted to  share  some routes  with you, what do  you think? More  info here <http://about.fowlervilletoday.com/e4bqfkkf>

Yours faithfully, morten

**Comment by Droyk** [comment]
if anyone seeing @MortenManden  link don't touch it, this link is a trojan so beware  
![screenshot_20161003151751](https://cloud.githubusercontent.com/assets/15848350/19035498/644c3918-8987-11e6-9892-d9cb7ad5cf81.png)

**Comment by MortenManden** [comment]
Seems I've been hacked - have just updated my password - and deleted the spam-post!

**Comment by frango9000** [comment]
https://github.com/audiorouterdev/audio-router

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
