### ISSUE TITLE
Translated: After updating to 20H2, when mute switching, the sound is abnormally

### ISSUE THREAD

**Issue by yyt666666** [File-New-Project/EarTrumpet#610]
操作步骤
1.暂停音乐播放器
2.静音音频输出
3.重新开始播放音乐播放器
4.取消音频输出的静音
5.此时依然没有声音
6.进入设置-声音，此时声音就出现了
使用系统自带的音量控制静音，是正常的
我的系统当前版本是
版本	Windows 10 专业版
版本号	20H2
安装日期	‎2020/‎9/‎7
操作系统版本	19042.685
体验	Windows Feature Experience Pack 120.2212.551.0
使用的软件版本是Microsoft Store 下载的最新版

**Comment by riverar** [comment]
Translated repro steps:

1. Pause‎ music player
2. ‎Mute audio output ‎
3. Restart playing ‎music player
4. Un mute the audio output ‎
5. There is still no sound
6. Enter Settings-Sound, ‎at which point the sound appears Using the volume control that comes with the system Mute, is normal 

My ‎‎ system the current ‎version is version Windows 10 ‎Pro version number 20H2‎
‎ installation date 2020/9/7‎
‎ operating system version 19042.685‎

Experience Windows Feature Experience Pack 120.2212.551.0‎
The software version used is the latest version downloaded by the Microsoft Store‎

**Comment by riverar** [comment]
@yyt517863742 I can't reproduce this. Can you provide more information on which music player you're using?

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
