### ISSUE TITLE
Ear Trumpet will not switch program's volume when changing the active device

### ISSUE THREAD

**Issue by suctionDunk** [File-New-Project/EarTrumpet#617]
When I right-click the icon and choose a new device,
![image](https://user-images.githubusercontent.com/77592246/104858152-439f3c00-58eb-11eb-8dc0-89016390b334.png)

NONE of my programs switch over. I now have to switch each program individually. I have tried resetting the default playback and comm devices and nothing changed. Several full restarts also did nothing. Anyone know the reason for this?

**Comment by 0lm** [comment]
Im using EarTrumpe 2.1.7.0 and for me everything works properly. Switching between the Main Device, Audios also switch. (except a few unique certain Programs which wont play a sound on the new devie when switching, but this is an issue with these certain softwares/games, not with Eartrumpet).
So, this is probably an issue only you (or only a few people?) have. Would be hard to reproduce then.
