### ISSUE TITLE
Suggestion: System Volume should be near taskbar

### ISSUE THREAD

**Issue by oerpli** [File-New-Project/EarTrumpet#62]
I think that the system volume should be near the taskbar because it's the most important item. 

I looked into the XAML and saw that it's realized with a HeaderedItemControl currently - I think that there is no built in support for displaying the header item at the bottom.

Also the background of the header item is a little too similar to the slider knob.

**Comment by StashCat** [comment]
At first I thought you were hallucinating, but then I remembered I have my taskbar at the top.

**Comment by GoldenTao** [comment]
We're open to feedback on this, our idea with the design was that using Ear Trumpet was to first adjust the volume of that rogue app that started blaring sound (ie the Xbox app) and a secondary action would be adjusting the master volume.

**Comment by oerpli** [comment]
I thought the main use case would be a replacement for the default (master volume) volume control. 

Sometimes I want to change some specific programs but more often I change the system volume. 

ymmv.

**Comment by GoldenTao** [comment]
We discussed this one a bit further and with some of the features we're looking to add in the next version, it won't make sense to have the master volume at the bottom of the window.

Thanks for the feedback on this.
