### ISSUE TITLE
Ear Trumpet crash randomly on youtube videos

### ISSUE THREAD

**Issue by Kaislink** [File-New-Project/EarTrumpet#621]
Hi, i had a problem since mid December 2020. on games, windows, twitch etc i have no problem, but with youtube the program crash randomly. It happens for no season, maybe i watch an 1h video and nothing happens and the next time it crashes 3 times on a 10 min video.

Also not only the program crashes, the screen turns black and i have to wat 10-15 secs to the pc works again, it seems the graphic driver crashes too, but on the log nothing appears. 
Here are the logs, i hope it helps:

Aplicación: EarTrumpet.exe
Versión de Framework: v4.0.30319
Descripción: el proceso terminó debido a una excepción no controlada.
Información de la excepción: System.OutOfMemoryException
   en System.Windows.Media.Composition.DUCE+Channel.SyncFlush()
   en System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean, System.Nullable`1<ChannelSet>)
   en System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   en System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   en MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by davuxcom** [comment]
Check for an updated video graphics driver for your PC. EarTrumpet is a victim here as well.

**Comment by riverar** [comment]
There's more technical information here, if you're interested https://docs.microsoft.com/en-us/troubleshoot/dotnet/framework/wpf-render-thread-failures. Not much we can do here so closing.
