### ISSUE TITLE
how to customize

### ISSUE THREAD

**Issue by Cyturk** [File-New-Project/EarTrumpet#623]
this isnt really a issue more of a question but how do i customize the eartrumpet box? like how do i change the size and the color.

![image](https://user-images.githubusercontent.com/78085420/105991722-39342d80-60b5-11eb-8e7c-b20a4439bc65.png)

**Comment by MadafakinRio** [comment]
From what I know you can't, it uses your accent color. The point is the functionality, not customization.

**Comment by davuxcom** [comment]
The width of the flyout is designed to match the system flyouts.

The height of the flyout is determined by how many sessions are on the default device, or (if expanded), how many devices and their sessions are enabled on the PC.

The color follows the system colors. You can use `Win+X` -> `Settings` -> `Personalization` -> `Colors` to change the color options.  EarTrumpet flyout will follow `Windows mode` when on the Taskbar flyout, and `app mode` when the full mixer is opened.
