### ISSUE TITLE
Suggestion : Add Publisher to your app

### ISSUE THREAD

**Issue by MIGMLG** [File-New-Project/EarTrumpet#63]
Add Publisher to your app
![eartrumpet](https://cloud.githubusercontent.com/assets/13486024/15341748/83ddde60-1c88-11e6-8fad-24d1d834a4e2.png)

**Comment by riverar** [comment]
Good catch, we should definitely add this.

**Comment by MIGMLG** [comment]
Thanks man for the quick response.
