### ISSUE TITLE
VMware Workstation machines only have a single entry

### ISSUE THREAD

**Issue by Zoxc** [File-New-Project/EarTrumpet#64]
Ear Thrumpet can only control only one of the running VMware Workstation virtual machines.

**Comment by riverar** [comment]
Do multiple machines show up in the classic sound mixer? VMware might be piping all audio through a single broker process

**Comment by Zoxc** [comment]
It did show up as multiple entries on Windows 7. I don't control the volume of all machines either, just one of them.

**Comment by riverar** [comment]
Can you repro this on Windows 10 with the classic sound mixer?

**Comment by Zoxc** [comment]
No, they are separate entries there.
