### ISSUE TITLE
Suggestion:Complete replacement of standard windows tray icon

### ISSUE THREAD

**Issue by ioannis-e** [File-New-Project/EarTrumpet#66]
In order to completely replace the standard windows volume control tray icon:
- [ ] 1. Include the `standard right-click popup menu` items, to EarTrumpet right-click menu (possibly as a submenu) like `Open Volume Mixer` and `Recording devices` and `Playback devices` dialog boxes
- [x] 2. Use a dynamic icon to indicate
  - [x] a) `mute level`
  - [x] b) `volume level`

**Comment by GoldenTao** [comment]
2 is in 1.5.0.0 and the others are coming shortly.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
