### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by santosch** [File-New-Project/EarTrumpet#68]
It would be awesome if you could add the possibility to define some shortcuts,
at least to define one for opening the panel (I don't like searching for the icon in my tray).
Would be really great though when after opening i could use my keyboard e.g. arrow-keys to select an entry in the list and increase/decrease the volume.

(For example: I Press Ctrl+Alt+V to bring up the panel, press two times arrow down to select the second entry end decrease it's volume by holding the left arrow key)

If you do #51 it also would be awesome if you could switch profiles with shortcuts.

thanks for the great work!

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
