### ISSUE TITLE
Suggestion: Change icon when master volume is muted

### ISSUE THREAD

**Issue by Ryoken0D** [File-New-Project/EarTrumpet#69]
This has in essence has replaced the Windows Volume icon on my computers, the only thing I find myself missing is the visual indication on the system tray when the volume is muted. It would be great if we could get that, or an option for it.

Other than that I love the program. It's replaced but my Windows Volume, and AudioSwitch (which I had been using to change the active audio device).  Thanks for making it :)

**Comment by riverar** [comment]
Good idea!

**Comment by crumpetcrusher** [comment]
I'll move this to a separate issue if it's not really related.  When the main UI is open and you adjust the volume via another means (hardware buttons/jogwheel), the volume slider does not update until reopening the UI.

Same as OP though, this is a great program and I'm looking forward to seeing some of the enhancements already brought up in other issues. 😄  Thanks!

**Comment by GoldenTao** [comment]
Updates on this one will be in #66.
