### ISSUE TITLE
Respect the OS animation settings

### ISSUE THREAD

**Issue by equin0x80** [File-New-Project/EarTrumpet#70]
Ear Trumpet gradually appears with a sliding animation when it is opened. This should not happen if the Windows OS-level setting "Animate windows when minimizing and maximizing" has been disabled. (Compare the Start menu behaviour.) In that case, the window should appear immediately, with no sliding animation.

**Comment by riverar** [comment]
Good catch, likely just need to call SystemParametersInfo with SPI_MENUANIMATION.

**Comment by mkruselj** [comment]
I just came here to report this. Glad somebody did it before me. Hoping to see this fixed soon!


Great, GREAT program, guys!

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
