### ISSUE TITLE
Bug: Changing active audio device doesn't change it for all programs

### ISSUE THREAD

**Issue by Ryoken0D** [File-New-Project/EarTrumpet#71]
So this one drove me nuts but I finally figured out that EarTrumpet was the issue.
I have my normal Speakers, and a USB Headset. If I change the default device to the headset, some programs, most notably TeamSpeak, will continue to use the speakers for their audio out.

Now if I use a program like AudioSwitch, or manually go into the Playback Devices, and set the headset as default, it works fine for everything.

**Comment by Wuestengecko** [comment]
Just reproduced this when switching from Laptop speakers to USB headphones. Issue is that windows actually knows two default devices (for both audio input and output), one "default device" and one "default communications device". EarTrumpet only changes the former, VoIP programs (like TeamSpeak and Skype) use the latter, thus they don't switch over.

**Comment by riverar** [comment]
This is not a bug but rather a design decision we made. We felt it was less useful to move both the default multimedia and communication devices, given typically communication devices remain static -- usually assigned permanently to a headset.

Are you constantly changing your default communication device? If so, why?

**Comment by Wuestengecko** [comment]
On my Laptop, i often plug the headset in and out as i change locations or just generally want to listen via speakers, and as I plugged it into a different USB port now than the last time, it didn't assign the default devices correctly. This got me a bit confused, as I already had my music on the headset but TeamSpeak insisted on the speakers still being default.
This shouldn't happen often though, I mainly commented to share my observations.

**Comment by Ryoken0D** [comment]
I have a USB Headset I use for games/teamspeak, when I'm using it I want everything to go through it. The rest of the time I use my speakers (or HDMI) for audio, and the mic on my Webcam.
Since this is working as intended, could we get an option to toggle it from applying as it does now, to applying to everything? Or even have a list for multimedia, and one for communication, so we can change them each as needed.

**Comment by riverar** [comment]
Give this another shot in EarTrumpet 2.0. Let us know if you continue to have issues (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

**Comment by Luckz** [comment]
> 
> 
> Give this another shot in EarTrumpet 2.0. Let us know if you continue to have issues (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)

It still only changes the Default Device, not the Default Communications Device.

**Comment by TheRealNoob** [comment]
@Luckz is correct.  I've reinstalled EarTrumpet several times today until i found this issue.

This is particularly frustrating for me because i don't have a communications device.  So I didn't care which device was my default.  Until now I guess.

**Comment by alexbobp** [comment]
@riverar This issue was never resolved and shouldn't be closed
