### ISSUE TITLE
Can not change output device

### ISSUE THREAD

**Issue by Royal-Slevin** [File-New-Project/EarTrumpet#72]
Since the new windows update I am not able to change the output device.

**Comment by riverar** [comment]
Does restarting the Windows Audio service resolve the issue?

**Comment by Royal-Slevin** [comment]
No it does not.

**Comment by riverar** [comment]
Are you on the latest EarTrumpet? 1.3.2.0? (right-click the tray icon)

**Comment by Royal-Slevin** [comment]
My bad, I was not. It does work after the update. Thanks for this awesome program and your help!
