### ISSUE TITLE
Feature Request: Hide Devices from EarTrumpet

### ISSUE THREAD

**Issue by c-dot-gonz** [File-New-Project/EarTrumpet#727]
This was a discussion in the comments of Issue #558 but was not addressed in the release that led to that request being closed. Please add the functionality to hide devices from EarTrumpet. I have 9 hardware audio devices that I cannot turn off but I do not route program audio to them, so they are cluttering up the EarTrumpet menu.

I'd also be happy with having the ability to "pin" certain devices so that they appear in the minimized EarTrumpet menu, especially if I can order the devices how I want. Right now, there's no real way to organize the devices in EarTrumpet that I know of, and they don't seem to be sorted by any method I can figure out.

**Comment by riverar** [comment]
Hi @c-dot-gonz. That issue was moved to discussion #713, in the new Ideas area, along with the rest of the feature requests. We'd like to keep the issues area reserved for actionable issues. Sorry for the confusion!
