### ISSUE TITLE
Have an Idea before

### ISSUE THREAD

**Issue by nightwind93** [File-New-Project/EarTrumpet#73]
Have an idea before:

https://dribbble.com/shots/2346729-Windows-10-Volume-Control

You can use the design if you want~

**Comment by riverar** [comment]
I don't think this design makes sense. And it certainly does not fit in with the look and feel of Windows.

![doesnotfit](https://cloud.githubusercontent.com/assets/475132/17661383/9f2198fa-6293-11e6-9914-fa9625050857.jpg)

Some things that came to mind immediately:
- Why are there two different volume metaphors? (bars and ticks) Or are those showing audio currently playing?
- Why are there two different slider styles?
- Lots of horizontal mouse movement
- Your app icons aren't aligned with the speaker in the master volume area
- Why are there no numbers? Precision is gone.

**Comment by GoldenTao** [comment]
Thanks for the feedback and the design, however, it doesn't quite fit in with where we are trying to head with Ear Trumpet.
