### ISSUE TITLE
Feature Request: Add a reset button & Let user choose if they want to too see icons or text.  

### ISSUE THREAD

**Issue by Droyk** [File-New-Project/EarTrumpet#74]
Hey Developer thanx for making a good app with a good UI 
but can you plz add some features too 

Add a reset Button and Let user choose if they want to too see icons or text for example see the below screenshot 
![image](https://cloud.githubusercontent.com/assets/15848350/18099608/fad69a42-6f04-11e6-97ff-476321e2e75e.png)

If you want a demo here it is https://marvelapp.com/explore/881275/windows-volume-control-ui-redesign/

**Comment by riverar** [comment]
Hm, some interesting ideas. Some questions:
- What does the Reset button do? Reset to 100%? 0%? 50%? And why is a user clicking this button?
- Why do users want to remove the icons and replace it with text? We believe parsing the text every time is much harder than remembering an app icon.

**Comment by Droyk** [comment]
You are about to read some bad English and I am really sorry about it I am not a native English speaker.
> What does the Reset button do? Reset to 100%? 0%? 50%? And why is a user clicking this button?

Well Reset button reset's the volume mixer setting to it's default values user can actually configure the default values for example I configured 70 is a default sound value so whenever I am gonna hit reset sound value in a volume mixer will become 70.

> Why do users want to remove the icons and replace it with text? We believe parsing the text every time is much harder than remembering an app icon.

Well it's really simple I have many software that really have ugly icons it doesn't really look that nice on a good background so instead of using icons simply just use text that will be a eye saver.

So will you add these features I hope you does

**Comment by Droyk** [comment]
You are about to read some bad English and I am really sorry about it I am not a native English speaker.
> What does the Reset button do? Reset to 100%? 0%? 50%? And why is a user clicking this button?

Well Reset button reset's the volume mixer setting to it's default values user can actually configure the default values for example I configured 70 is a default sound value so whenever I am gonna hit reset sound value in a volume mixer will become 70.

> Why do users want to remove the icons and replace it with text? We believe parsing the text every time is much harder than remembering an app icon.

Well it's really simple I have many software that really have ugly icons it doesn't really look that nice on a good background so instead of using icons simply just use text that will be a eye saver.

and it seems like app needs some minor improvements for example [font size is really bold and big](https://i.imgur.com/AyrOqS2.png) 

[Font size should be like this](https://i.imgur.com/k73NwzO.png)   

I really hope you make these improvements.

**Comment by riverar** [comment]
Your English is great.

I still don't understand why anyone would use a "Reset" button. Resetting all audio sliders to, say 70%, doesn't make a lot of sense to me. Why do you need this? How does it improve your life?

I understand apps have ugly icons but text is hard to read. Imagine you had 30 apps in that list and had to find Skype. (Sorting would make things worse as app entries would move around.)

**Comment by Droyk** [comment]
Well Reset button is only for those people who don't usually like loud sound for example I have many speakers and if the volume is high enough they can crush my ears up so I usually lower my sound level to make things work. and I get your meaning  it not for the usual peoples but only for those people like their loudness remains to user configured level not go full.

Well I really don't work with 30 apps open but ya I get your meaning so let's do this give the user choice to choose from icons or text it will the user only choice. by doing this every user will be happy 
you already have icons now you just have too add a choice to see text or icons.

**Comment by riverar** [comment]
Sounds like a "default level" (when you first start an app, for example) is more appropriate than a reset button. Or would you use a reset button more than once for an app?

We'll think about the text toggle.

**Comment by Droyk** [comment]
yup a default level but I couldn't be able to understood your example So guess I would use a reset button more than once for an app i think 

and even if you don't want add an reset button plz do everything you can to add a text toggle because I would really love too see an text toggle. text toggle is the most important GUI enhancement right now

Important Enhancements
- [ ] Let the user choose if they want to too see icons or text 
- [ ] numerical font size should be smaller 

Not that important Enhancement
- [ ] add a reset button 
- [ ] let the user select a playback device like windows default volume mixer does.
- [ ] [leave the default volume slider in the lowest](https://cloud.githubusercontent.com/assets/15848350/18947711/d19416fa-8651-11e6-9527-53a861f79a34.png)

**Comment by GoldenTao** [comment]
Not sure about the font size change, we're trying to emulate the Windows design as close as possible which is why it's the size it currently is.

**Comment by Droyk** [comment]
Well even if you guys are imitating window's default font design then font looks a bit jaggy and a little bit bigger comparing to the default one.

**Comment by GoldenTao** [comment]
I think that might have been a WPF text rendering thing. I've added a small change to that in the next feature version.

**Comment by Droyk** [comment]
okay let's see will it fix the font issue or not in the next release but wait a minute when you are gonna release the next update.

**Comment by GoldenTao** [comment]
That won't be for a while yet, we've got a few things planned for the next big release.

**Comment by Droyk** [comment]
okay what about other requested features
- [ ] [leave the default volume slider in the lowest](https://cloud.githubusercontent.com/assets/15848350/18947711/d19416fa-8651-11e6-9527-53a861f79a34.png)

like in this image https://cloud.githubusercontent.com/assets/15848350/18099608/fad69a42-6f04-11e6-97ff-476321e2e75e.png

see the default speaker volume slider is on first and then remaining goes on on the other hand your's gives the reverse effect.

**Comment by GoldenTao** [comment]
We're still going over the design for some other features, so I don't have an answer for that one yet.

We did have a big discussion while working on version 1.4 about the master volume being at the bottom and decided that was the wrong move design wise. Especially with some of the other plans we have in regards to multiple devices.  That said, we'll go over it all again for this next version.

**Comment by Droyk** [comment]
> We did have a big discussion while working on version 1.4 about the master volume being at the bottom and decided that was the wrong move design wise.

what do you mean by "about the master volume being at the bottom and decided that was the wrong move design wise"?  why the master volume being at bottom is wrong move design wise?

**Comment by Droyk** [comment]
> @riverar  I understand apps have ugly icons but text is hard to read. Imagine you had 30 apps in that list and had to find Skype. (Sorting would make things worse as app entries would move around.)

Then you can just add a search bar on your UWP app if you think it would look ugly then I will make a good UI to make a appeal to you how about it. it would only take me a 20 to 30 minutes.

**@GoldenTao & @riverar it's been 6 months guys where are you? when the next version is going to come? 
plz do something!!**
