### ISSUE TITLE
Forza horizon 4 not remembering its volume setting (from ear trumpet)

### ISSUE THREAD

**Issue by Akxe** [File-New-Project/EarTrumpet#741]
## Description
A clear and concise description of what the bug is

## Steps to reproduce
1. Open "Forza Horizon 4"
2. Change volume
3. Close it down
4. Relaunch "Forza Horizon 4"
5. Check volume (it is back at 100%)

## Meta
* EarTrumpet version: 2.1.7.0
* Windows 10 version: 20H2 - 19042.804

**Comment by riverar** [comment]
@akxe Thanks, this is a Windows bug sadly.

To assist the audio stack engineers at Microsoft, please file a bug in Feedback Hub under `Devices and Drivers` - `Audio and sound`. You can cut and paste this template (but verify the steps apply to you). Please also check ☑ Save a local copy of diagnostics and attachments created when giving feedback. Send a copy of that data to team@eartrumpet.app and reference issue 741.

```
Summary: Windows 10 does not remember audio levels for Forza Horizon 4

Explain in more detail:
When I start Forza Horizon 4, it starts at 100% volume level each time.

Repro steps:
  1. Start Forza Horizon 4
  2. Set volume level to 50% via Windows
  3. Close Forza Horizon 4
  4. Start Forza Horizon 4
  5. Observe Forza Horizon 4 is back to 100% volume level

See also: EarTrumpet/issues/741
```

Then paste a link here and I'll forward it directly to the audio team.

**Comment by Slegnor** [comment]
@riverar I am having a similar issue with another program and I have submited feedback to MS as suggetsed above but where can I locate the local copy of diagnostics and attachments to forward to the Audio team?
Thanks

**Comment by riverar** [comment]
Saved diagnostics/etc. go to `C:\ProgramData\Microsoft\Diagnosis\FeedbackArchive` at this time of writing.

While I'm here, I'm cleaning up the issues list. There's no work to be completed here so am closing this issue for now. Feel free to keep the discussion going. Thanks!
