### ISSUE TITLE
Include Audio Device(s) name in the pull up menu

### ISSUE THREAD

**Issue by jssshashi** [File-New-Project/EarTrumpet#75]
It would be good it the pop up titled with **Speakers (2-High definition audio device )**.
just like the regular windows Sound icon says.

**Comment by riverar** [comment]
We show exactly that, are you seeing something different? Got a screenshot?

**Comment by riverar** [comment]
Oh you mean the main UI, got it.

**Comment by jssshashi** [comment]
screenshot http://imgur.com/a/rQ34q

**Comment by GoldenTao** [comment]
Thanks for this one, updates/fixed will be in #58.
