### ISSUE TITLE
Volume mixer window drag issue

### ISSUE THREAD

**Issue by CalbertAmu** [File-New-Project/EarTrumpet#754]
## Description
The volume mixer window has problems when being dragged to another place

## Steps to reproduce
1. right click the tray icon 
2. Click on 'volume mixer'
3. Drag the new mixer window
4. See error: The window animation is very slow to move

## Meta
* EarTrumpet version: (latest MS store update)
* Windows 10 version: 19042.804

**Comment by riverar** [comment]
Dupe of #349 (pinned issue), thanks though.
