### ISSUE TITLE
Bug and Suggestions for the context menu

### ISSUE THREAD

**Issue by Geeyun-JY3** [File-New-Project/EarTrumpet#758]
Kinda bug? Logically?
## Description
1. Now Sound settings open the Sound page of the Windows Settings app, it is not an entry that open the older Sound control panel (as mentioned in [Crowdin](https://crowdin.com/translate/eartrumpet/32/en-zhcn?filter=basic&value=3#1746)). So I think it should not be an entry under the Windows Legacy. It should be directly in context menu of the tray icon, just like the native volume icon of Windows 10.
Related: #554
2. Suggestions: 
	1. Add an entry in Windows Legacy context menu that open the Playback tab of the older Sound control panel.
	2. Add underline access keys for options in context menu of the tray icon, <u>E</u> for Sound setting (after 1. implemented), <u>M</u> for Volume mixer (follow the native volume icon of Windows 10), <u>S</u> for Settings. 
	I would even go further and suggest that add them for the options in the Windows Legacy context menu (I do hope that🙈)? It depends on you.
4. Change the Microsoft Store link in README to: https://www.microsoft.com/store/apps/9NBLGGH516XP
It is locale natural.
Reference: [Microsoft Docs](https://docs.microsoft.com/windows/uwp/publish/link-to-your-app)

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.804

## Screenshots
Context menu of the native volume icon of Windows 10
![image](https://user-images.githubusercontent.com/49396421/108581877-f2abb900-736a-11eb-9b26-50d5095d0689.png)

**Comment by riverar** [comment]
> Now Sound settings open the Sound page of the Windows Settings app, it is not an entry that open the older Sound control panel (as mentioned in Crowdin). So I think it should not be an entry under the Windows Legacy. It should be directly in context menu of the tray icon, just like the native volume icon of Windows 10.

Here's what each menu item opens:

![Screenshot of various windows showing audio configuration elements](https://user-images.githubusercontent.com/475132/108583217-d1a48300-72ec-11eb-96d8-3983fdafba89.png)

   We understand the last item (Sound settings) isn't exactly a _legacy_ feature, but we needed a place to put it. We can't put this in the top-level menu because it would confuse users looking for EarTrumpet specific settings.

2.
  i. We already have a Playback tab menu item (see screenshot). Is it not working for you?
  ii. Good idea. Can you add a separate idea for "Add access keys to EarTrumpet context menu"?
3. Yep, good catch. Can you create a new separate bug for this so I can link it properly on commit? Thanks!

**Comment by Geeyun-JY3** [comment]
> We already have a Playback tab menu item (see screenshot). Is it not working for you?

Oh I didn't notice that🤣. My bad. Just ignore the suggestion 2. ii.

> Can you add a separate idea for "Add access keys to EarTrumpet context menu"?

You mean open another discussion?

> Yep, good catch. Can you create a new separate bug for this so I can link it properly on commit? Thanks!

And here is it: #759

Then should I close this issue?

**Comment by Geeyun-JY3** [comment]
> We already have a Playback tab menu item (see screenshot). Is it not working for you?

Oh I didn't notice that🤣. My bad. Just ignore the suggestion 2. ii.

> Can you add a separate idea for "Add access keys to EarTrumpet context menu"?

You mean open another discussion?

> Yep, good catch. Can you create a new separate bug for this so I can link it properly on commit? Thanks!

And here is it: #759

Then should I close this issue?

**Comment by riverar** [comment]
@Geeyun-JY3 Yep, another Discussion under category Ideas. Thanks!

**Comment by Geeyun-JY3** [comment]
got it
