### ISSUE TITLE
Change the Microsoft Store link in README to a locale natural link

### ISSUE THREAD

**Issue by Geeyun-JY3** [File-New-Project/EarTrumpet#759]
## Description
Change the Microsoft Store link in README to: https://www.microsoft.com/store/apps/9NBLGGH516XP
It is locale natural.
Reference: [Microsoft Docs](https://docs.microsoft.com/windows/uwp/publish/link-to-your-app)

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.804

_Originally posted by @Geeyun-JY3 in https://github.com/File-New-Project/EarTrumpet/issues/758#issue-812496759_

**Comment by riverar** [comment]
Thanks!
