### ISSUE TITLE
Messed up position on volume panel

### ISSUE THREAD

**Issue by prakharb5** [File-New-Project/EarTrumpet#767]
## Description
Sometimes opening the volume panel by clicking the tray icon messes up the panel position

## Steps to reproduce
Just click on tray icon of Eartrumpet

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.804

## Screenshots

![image](https://user-images.githubusercontent.com/51435948/109343473-6ed65d00-7893-11eb-9dff-d44ebaf9871e.png)

**Comment by riverar** [comment]
@Cyberdroid1 Any more information you can provide? Maybe collect diagnostics via Settings > About and email that to us? (team@eartrumpet.app)

Some questions:
* Is this a laptop or desktop?
* Did you just wake up from suspend/hibernation?
* If you dismiss the flyout and re-open it, does it continue to be in the wrong position? Or is it only on the first time you open the flyout?

**Comment by Cyberdroid1** [comment]
Well, this issue has happened rarely, but it does happen.

Some answers:

- It is a laptop.
- Yes I woke the PC up from sleep
- If I reopen it, it continues to stay on wrong position. 
  - No, it is not necessary that I open the flyout first time after boot. The position is actually fine after every reboot.
  
  To fix this problem, I have to either restart the app, or just wait for some time and retrigger the flyout.

**Comment by tadly** [comment]
Same happens over here on my Desktop after asuspend/resume cycle.

Windows 10 (20H2)
Eartrumpet 2.1.8.0

As mentioned by Cyberdroid1, the flyout keeps opening in the wrong position and the app needs to be restarted.
For me, waiting doesn't fix anything though.

Here are my troubleshoothing data: https://paste.ubuntu.com/p/kRmV3dPjWw/

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue 1304, thanks!
