### ISSUE TITLE
Volume Mixer opens too wide

### ISSUE THREAD

**Issue by riverar** [File-New-Project/EarTrumpet#768]
[Split from #392]

sorry to necro, but i am having a similar issue. right now its not too big, but over time it gets bigger and bigger randomly??? once it was going across both my monitors.

i have two 4k monitors if thats whats causing it? it worked fine for years though. 

here is an image:
![Image 004 - 2021-02-26](https://user-images.githubusercontent.com/13823693/109335971-bd9edb00-7830-11eb-800e-110845f56142.png)

_Originally posted by @wooziwoozi in https://github.com/File-New-Project/EarTrumpet/issues/392#issuecomment-786795995_

**Comment by tech189** [comment]
Having a similar issue with my laptop connected to an external display, can't tell why it happens...
![image](https://user-images.githubusercontent.com/10728085/111996392-e35a8f80-8b11-11eb-9ee9-5e2813287928.png)

**Comment by SpacEagle17** [comment]
happening to me too, I've noticed that it only starts to happen after the pc is turned on for a longer period of time, so you don't notice this bug if the pc is only turned on for a couple of hours (but maybe it happens only to me like that).
![msedge_FPeIgd4XhW](https://user-images.githubusercontent.com/46494907/114940087-97191b80-9e41-11eb-8090-aa2ad709e59f.png)

**Comment by SpacEagle17** [comment]
Testing it right now. I will update here if I encounter the issue again or if it is fixed for me

**Comment by SpacEagle17** [comment]
It seems to be working correctly now. At least I haven't encountered the bug again. Thanks for fixing it!

**Comment by jesstech** [comment]
Just noticed it has grown arbitrarily wide again:

![image](https://user-images.githubusercontent.com/607359/136876453-2a4138a0-613e-40a4-82a7-5767ba4d722b.png)
![image](https://user-images.githubusercontent.com/607359/136876618-9abba5d0-6bcf-4de7-8184-4f0375838867.png)

Pretty sure I'm on the latest My best guess is that this has to do with DPI scaling differences between multiple monitors (I have a 4K TV hooked up as a secondary that I enable just for gaming and movies)

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue 1304, thanks!
