### ISSUE TITLE
Volumn level reset after system reboot

### ISSUE THREAD

**Issue by HappyJoo** [File-New-Project/EarTrumpet#779]
## Description
I like to turn the **System Sounds** down to 20%. But it reset to 100% every time I **restart** my computer. Don't really know why.

Ehhh, just when I was checking EarTrumpet version, I found another bug. When I try to drag its setting menu, It becomes very wierd and slowly moving. Don't know how to describe.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.804
*

**Comment by davuxcom** [comment]
Your second issue is https://github.com/File-New-Project/EarTrumpet/issues/349, a fix is in the works.

Your first issue.. Windows not remembering settings, is also around here somewhere too.

**Comment by Alok-S-Sharma** [comment]
I am also experiencing similar problem.

Every time I reboot my laptop, all the volumes except the main volume gets reset to 100.

**Comment by riverar** [comment]
First item is tracked via #349 / closed. Remembering volume levels is a platform issue tracked via #315.
