### ISSUE TITLE
New update came and... Came a bug?

### ISSUE THREAD

**Issue by Norimaro** [File-New-Project/EarTrumpet#78]
So, came a new udpate for EarTrumpet APP for Windows 10 Pro Anniversary and appeared this when I try to use it:

![capturar](https://cloud.githubusercontent.com/assets/22265311/18611378/4a65868e-7d0d-11e6-9e61-7e8c36735051.PNG)

> Consulte o final desta mensagem para obter detalhes sobre como chamar a 
> depuração just-in-time (JIT) em vez desta caixa de diálogo.
> 
> ************** Texto de Exceção **************
> System.DllNotFoundException: Não é possível carregar a DLL 'EarTrumpet.Interop.dll': Não foi possível encontrar o módulo especificado. (Exceção de HRESULT: 0x8007007E)
>    em EarTrumpet.Services.EarTrumpetAudioDeviceService.Interop.RefreshAudioDevices()
>    em EarTrumpet.Services.EarTrumpetAudioDeviceService.GetAudioDevices()
>    em EarTrumpet.ViewModels.AudioMixerViewModel.Refresh()
>    em EarTrumpet.MainWindow.TrayIcon_Invoked()
>    em System.Action.Invoke()
>    em EarTrumpet.TrayIcon.TrayIcon_MouseClick(Object sender, MouseEventArgs e)
>    em System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
>    em System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
>    em System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
>    em System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
>    em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Assemblies Carregados **************
> mscorlib
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> EarTrumpet
>     Versão do Assembly: 1.4.1.0
>     Versão do Win32: 1.4.1.0
>     Base de Código: file:///C:/Program%20Files/WindowsApps/40459File-New-Project.EarTrumpet_1.4.1.0_x86__1sdd7yawvg6ne/EarTrumpet.exe
> ----------------------------------------
> PresentationFramework
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
> ----------------------------------------
> WindowsBase
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
> ----------------------------------------
> System.Core
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> PresentationCore
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
> ----------------------------------------
> System.Xaml
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
> ----------------------------------------
> PresentationFramework.Aero2
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
> ----------------------------------------
> System.Windows.Forms
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> PresentationCore.resources
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_pt-BR_31bf3856ad364e35/PresentationCore.resources.dll
> ----------------------------------------
> UIAutomationTypes
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
> ----------------------------------------
> mscorlib.resources
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
> ----------------------------------------
> System.Windows.Forms.resources
>     Versão do Assembly: 4.0.0.0
>     Versão do Win32: 4.6.1586.0 built by: NETFXREL2
>     Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
> ----------------------------------------
> 
> ************** Depuração JIT **************
> Para habilitar a depuração just-in-time (JIT), o arquivo .config deste
> aplicativo ou computador (machine.config) deve ter o valor
> jitDebugging definido na seção system.windows.forms.
> O aplicativo também deve ser compilado com a depuração
> habilitada.
> 
> Por exemplo:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>

**Comment by MIGMLG** [comment]
New update already subbmited. Close this issue please. And check for store updates.

**Comment by Norimaro** [comment]
Mega thank you! I will wait.
