### ISSUE TITLE
Acrylic flickers when moving window first time

### ISSUE THREAD

**Issue by Cyberdroid1** [File-New-Project/EarTrumpet#782]
## Description
When moving the settings window, the acrylic flickers before getting disabled. I understand that acrylic is disabled to prevent the window moving lag. But the flicker seems like a bug

## Steps to reproduce
1. Go to the settings window
2. Drag the window title bar and move around
3. Notice the acrylic when you clikc 

## Meta
* EarTrumpet version: 2.1.8.17 (dev)
* Windows 10 version: 19043.844

## Screenshots

https://user-images.githubusercontent.com/51435948/110344184-400a7480-8053-11eb-86b8-18dcfca5cc5e.mp4

**Comment by riverar** [comment]
Thanks @Cyberdroid1, this is part of a workaround we created for the slow dragging issue. It's impossible to completely fix this issue at this time due to Windows bugs. Going to close this for now but we'll cover it in our upcoming known issues documentation.
