### ISSUE TITLE
Forza Horizon doesn't show in EarTrumpet

### ISSUE THREAD

**Issue by GoldenTao** [File-New-Project/EarTrumpet#79]
Interop fails to get Icon path correctly due to this app not including a PRI and a full icon path instead of relative to package path being returned.

**Comment by exts** [comment]
Same problem lol

**Comment by riverar** [comment]
Received reports this doesn't show in the classic mixer either.

To properly debug this, we need to fund (at least partially) the purchase of a Forza Horizon 3 download code.

<hr>
Item: [Forza Horizon 3](http://www.amazon.com/Forza-Horizon-DEMO-Xbox-Digital/dp/B01GW3PAYE) (download code for Xbox/PC)
Total donations received this far: **$0.00**
Minimum goal: **25%** ($14.99)
Preferred goal: **100%** ($59.99)
<hr>


Willing to help? Please send what you can to `rafael@withinwindows.com` -- Amazon GC, PayPal, and/or codes are accepted. I'll update this issue when funding is received/no longer needed.

(If folks are more interested in a Gittip/Gratipay-type system, let me know. I'm measuring interest for that sort of thing.)

**Comment by exts** [comment]
> You've sent $14.99 to rafael@withinwindows.com

**Comment by riverar** [comment]
Appreciate it **Lamonte**, **Damon**, **Brandon**. We'll keep this for EarTrumpet use of course. Will work on this right now.

**Comment by ImTheSloth** [comment]
You will most likely want to get the ultimate edition as it is the only playable version atm as the actual release isnt till the 27th depending on how much you got

**Comment by exts** [comment]
@ImTheSloth oh yeah, forgot about that. I do have the ultimate edition, game doesn't officially release for the 59.99 price point until tuesday/monday night?

**Comment by riverar** [comment]
So we're talking about this version, correct? https://www.amazon.com/Forza-Horizon-3-Ultimate-Xbox-One/dp/B01GW3LREG

**Comment by ImTheSloth** [comment]
Yes

**Comment by exts** [comment]
yeah that's the version me and @GoldenTao has currently - you can either wait until monday night/tuesday morning or get more funding support

**Comment by exts** [comment]
> Total donations received this far: $134.97 (whoa!)

nvm about the more funding comment xD

**Comment by ImTheSloth** [comment]
If you go on the winoews 10 store and search forza horizon 3 ultimate it should be the first result

**Comment by exts** [comment]
https://www.microsoft.com/en-us/store/p/forza-horizon-3-ultimate-edition/9nblggh4rq2x direct link if you don't have it yet

**Comment by riverar** [comment]
Fired up a Slack for us to chat on (https://file-new-project.slack.com)

**Comment by riverar** [comment]
We should have this fix in the Store pipeline tonight

**Comment by exts** [comment]
nice

**Comment by ImTheSloth** [comment]
@riverar how long does it take to go into the store and am i able to just update it straight off of github

**Comment by GoldenTao** [comment]
You would have to rebuild the code as we are no longer putting releases on GitHub. The store is unfortunately not that easy to predict, sometimes within 24 hours the new version is available, sometimes days.

**Comment by wicksy101** [comment]
Is this fix finished? If so how do i go about getting it?

**Comment by exts** [comment]
according to a few posts up @wicksy101 it'll display on the windows store when the update goes live since they don't post releases here anymore :(
