### ISSUE TITLE
EarTrumpet unable to show playback devices

### ISSUE THREAD

**Issue by Xnehaxixh** [File-New-Project/EarTrumpet#791]
## Description
EarTrumpet is not showing the playback devices, even though they are present and it is able to detect them. Rather it shows a strange behavior.  Upon right clicking on the body, it is showing the applications and their volume levels.

If there is any log file present somewhere, let me know since it can help you.

## Steps to reproduce
1. Go to the taskbar.
2. Click on 'EarTrumpet Icon'
3. It doesn't show any playback devices.
4. Have some applications open and right click on the body and it shows the application volume level.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.867

## Screenshots
![ezgif-6-ec95e957e16b](https://user-images.githubusercontent.com/33873170/111384986-29f25900-86d0-11eb-9e04-e47a41634719.gif)

**Comment by riverar** [comment]
@Xnehaxixh What customization software are you using here? This looks very different than normal Windows 10.

**Comment by Xnehaxixh** [comment]
> @Xnehaxixh What customization software are you using here? This looks very different than normal Windows 10.

For the Taskbar it's TaskBarX and for the windows UxThemePatcher. And some more minor stuff that I think shouldn't affect TaskBarX.

Do you want me to test by turning all of them off and check?

**Comment by riverar** [comment]
Yes please.

**Comment by Xnehaxixh** [comment]
I tested all of the customization software, turns out the culprit was Actual Transparent Windows. I have whitelisted EarTrumpet and did a reboot, now its working fine.

Thanks for your help!

Closing the issue.
