### ISSUE TITLE
EarTrumpet doesn't show all BlueStacks instances, it is grouped into 1 process

### ISSUE THREAD

**Issue by pnthach95** [File-New-Project/EarTrumpet#792]
## Description
I'm running 2 BlueStacks instances and want to control 1 of them. EarTrumpet shows 2 BlueStacks processes, BlueStacks and HD-Player, only HD-Player has sound. If I change HD-Player's volume, it changes all instances' volume. I right click HD-Player, I see 2 instances inside. It's more convenient to control if EarTrumpet shows all instances.

## Steps to reproduce
1. Open 2 BlueStacks instances and make them play sound
2. Control HD-Player's volume
3. Right click HD-Player
4. Control 1 of HD-Player children's volume.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.867

## Screenshots

![Screenshot 2021-03-18 093439](https://user-images.githubusercontent.com/31266357/111565203-91da9980-87cd-11eb-9890-0370e08831ad.png)

![image](https://user-images.githubusercontent.com/31266357/111564902-17aa1500-87cd-11eb-82f7-8781a7620126.png)

**Comment by pnthach95** [comment]
I'm using Bluestacks 4 (v4.280.0.1022, 32-bit Android) and no Hyper-V (not available on Windows 10 Home)

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.
