### ISSUE TITLE
No app's audio channels are switched over when changing audio devices

### ISSUE THREAD

**Issue by lividhen** [File-New-Project/EarTrumpet#793]
## Description
When I right click and select a new audio device, it doesn't switch any of my app's audio channels to it. But I can still switch apps over manually (right clicking on them).

## Steps to reproduce
1. Right click eartrumpet tray icon
2. Select a new audio device
3. Left click on the eartrumpet icon
4. Stare in confusion as the new audio device is now selected but no apps switch to it and no sound can be heard out of it.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 10.0.19042

## Screenshots

![image](https://user-images.githubusercontent.com/42221797/111712994-57481f80-8814-11eb-8c2c-b0b34483569c.png)
![image](https://user-images.githubusercontent.com/42221797/111712788-f6204c00-8813-11eb-8f6a-1866d53ad9aa.png)
![image](https://user-images.githubusercontent.com/42221797/111712794-fe788700-8813-11eb-9160-488a4db171a3.png)
![image](https://user-images.githubusercontent.com/42221797/111713194-b3ab3f00-8814-11eb-90a5-71e10a8a49fa.png)

**Comment by G3NSVRV** [comment]
same here, this just stop working.

**Comment by riverar** [comment]
@lividhen Is this still happening? If so, can you repeat those steps then navigate to Settings > General > About and click Collect troubleshooting data? That might contain some personal info so feel free to email that to us at team@eartrumpet.app (reference issue 793 please).

**Comment by lividhen** [comment]
Oh! I ran windows update, and it fixed its self. I wish i could tell you which specific update, but if i go to update history it says the latest one that was installed was 2 months ago...

**Comment by G3NSVRV** [comment]
> Oh! I ran windows update, and it fixed its self. I wish i could tell you which specific update, but if i go to update history it says the latest one that was installed was 2 months ago... Which is blatantly wrong.

same happens to me, same version but "refreshed" xd

thanks microsoft

**Comment by riverar** [comment]
Concerning this hit both of you. I'll try to retrace a few updates and reproduce. Glad it's working though!

Going to close this for now. If it returns, please re-open or ping the team.
