### ISSUE TITLE
Microsoft Store Displays Error Code: 0x80073D05 During Installation

### ISSUE THREAD

**Issue by PSiebertACETech** [File-New-Project/EarTrumpet#794]
## Description
Error occurs during installation from the Microsoft Store

## Steps to reproduce
1. Start installation from Microsoft Store
2. Download will complete
3. Installation will fail

## Meta
* EarTrumpet version: Microsoft Store does not display version, only release date 9/9/2016
* Windows 10 version: 19042.867

## Screenshots
![Screenshot 2021-03-22 162844](https://user-images.githubusercontent.com/81190439/112054245-b4511780-8b2b-11eb-8e55-e1c0a71fa519.png)

**Comment by riverar** [comment]
This is a Windows (appmodel) issue. That error resolves to `ERROR_DELETING_EXISTING_APPLICATIONDATA_STORE_FAILED`, which sounds like you have a pending delete operation. (Was EarTrumpet recently uninstalled?) Does a reboot clear this up?

**Comment by PSiebertACETech** [comment]
The app stopped working after a windows update, so I 'attempted' to uninstall and reinstall from the store, and sounds like the re-install was not completely successful. I have rebooted multiple times since the uninstall.

**Comment by riverar** [comment]
@PSiebertACETech Ah ok. Sorry for the trouble, Windows is... fragile in this area.

Try navigating to `%LocalAppData%\Packages` (you can paste that into File Explorer) and delete `40459File-New-Project.EarTrumpet_1sdd7yawvg6ne`

**Comment by PSiebertACETech** [comment]
@riverar Thanks so much, this folder was the culprit, although I still haven't been able to delete it. It keeps saying I don't have sufficient permissions, despite being an Admin, trying to open explorer with Admin Rights, and even third party file/folder unlocker tools. However I was able to move the folder to another location which allowed the installation to complete successfully.

Thanks so much for the help.
