### ISSUE TITLE
Last updated just messed the output sound per app feature

### ISSUE THREAD

**Issue by G3NSVRV** [File-New-Project/EarTrumpet#802]
## Description
Last updated just messed the output sound per app feature, I cannot switch audio devices per app like before; e.g. if I want Spotify sounds only in one output device.

It happens mostly on the card that is not windows default.

## Steps to reproduce
1. Open Eartrumpet with the left click on the taskbar for the mixer
2. Right click on the app
3. Switch sound card
4. Doesn't switch at all.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 1909 (18363.1379)

## Screenshots
https://user-images.githubusercontent.com/11720535/112524241-5e27e280-8d7e-11eb-8ee8-da23e057abc4.mp4

**Comment by G3NSVRV** [comment]
I tested resetting the app to the original state but nothing works.

**Comment by wardseward** [comment]
Same issue.

**Comment by riverar** [comment]
@G3NSVRV Nice video, can you repeat those steps then navigate to Settings > General > About and click Collect troubleshooting data? That might contain some personal info so feel free to email that to us at team@eartrumpet.app (reference issue 802 please).

**Comment by riverar** [comment]
Might be related #793, investigating.

**Comment by G3NSVRV** [comment]
> @G3NSVRV Nice video, can you repeat those steps then navigate to Settings > General > About and click Collect troubleshooting data? That might contain some personal info so feel free to email that to us at [team@eartrumpet.app](mailto:team@eartrumpet.app) (reference issue 802 please).

sure, but for some reason, all my apps from windows store has been updated and now works as expected 0.0...

Idk man, microsoft ...

**Comment by riverar** [comment]
Can't reproduce this but feel free to re-open if it happens again. Will be on the lookout for any diagnostic dumps via email and will keep trying to reproduce this on several other machines.
