### ISSUE TITLE
Cannot use EarTrumpet with a tablet.

### ISSUE THREAD

**Issue by absolutewitch** [File-New-Project/EarTrumpet#807]
After opening the EarTrumpet window you cannot do anything to it, clicking or anything will not do anything to it with a tablet, it just appears stuck. For refference I have a Wacom Intuos S. Here's a gyazo replay:
https://gyazo.com/fa8662a75b5a90995d8aac4be06d617c

**Comment by davuxcom** [comment]
That's kind of strange, I made it work with Windows touchscreen input. Do you often find that apps don't work? It seems like you would find this very commonly if it doesn't fall back to either mouse or pointer events.

**Comment by yumigod0** [comment]
> That's kind of strange, I made it work with Windows touchscreen input. Do you often find that apps don't work? It seems like you would find this very commonly if it doesn't fall back to either mouse or pointer events.

This does not happen often.

**Comment by riverar** [comment]
Is that Lively wallpaper in the background? If this happens again, try closing Lively.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.
