### ISSUE TITLE
EarTrumpet broke Bluetooth

### ISSUE THREAD

**Issue by Ventvo** [File-New-Project/EarTrumpet#812]
Hi,
after i installed EarTrumpet, it broke bluetooth on my laptop.
I installed it using powershell (don't have microsoft store on my windows) and the computer just stop seeing bluetooth module.
I tried reinstalling drivers, but its not that. I don't see bluetooth module at all.
I rebooted to linux and it work just fine. I reinstall whole system and it started working again. I installed EarTrumpet and it broke again.
Some screenshots:
![1](https://user-images.githubusercontent.com/22612951/114311590-ad487400-9aef-11eb-9fb5-60c80c54c3ba.png)
![2](https://user-images.githubusercontent.com/22612951/114311591-ade10a80-9aef-11eb-98e0-5ccad92b9458.png)
![3](https://user-images.githubusercontent.com/22612951/114311592-ade10a80-9aef-11eb-8e2b-01d2cbbb7633.png)
![4](https://user-images.githubusercontent.com/22612951/114311593-ae79a100-9aef-11eb-9b28-2258c321e3a5.png)

**Comment by riverar** [comment]
Hi @Ventvo, EarTrumpet doesn't make any changes to the OS or Bluetooth. Looks like this is a hardware or driver issue and we can't help with that here. Perhaps try [Microsoft support](https://support.microsoft.com/en-us/windows/fix-bluetooth-problems-in-windows-10-723e092f-03fa-858b-5c80-131ec3fba75c) or [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html).
