### ISSUE TITLE
Almost all apps randomly missing from volume list

### ISSUE THREAD

**Issue by Greyze** [File-New-Project/EarTrumpet#814]
## Description
EDIT:
_Discovered how the problem occurs. Editing ticket..._

When changing audio device, All apps disappear from the volume list so I cannot change an apps volume. I have to restart the program for it to display everything again. I don't know if this is normal behavior but with my particular setup it's not ideal.

I use a Creative Soundblaster ZxR. In the Creative software it has a Toggle to flip audio output between Headphones and Desktop Speakers. This is a hardware toggle, there isn't two separate audio devices in Sound Control Panel, just Speakers (Sound Blaster ZxR).

## Meta
* EarTrumpet version: 2.1.8.0
* Installed from App Store
* Windows 10 version: 20H2 (19042.928)

## Screenshots

Toggling audio device in Creative Sound Control Panel
![et1](https://user-images.githubusercontent.com/1690930/115057324-d1cf9200-9edb-11eb-9e53-61bcc3e9560f.png)

Immediately after closing and re-opening ear-trumpet
![image](https://user-images.githubusercontent.com/1690930/115057451-fd527c80-9edb-11eb-9c1e-a6f59a3398f9.png)

**Comment by GorlikItsMe** [comment]
I have similar problem. It happens everytime when i switch profiles on windows

**Comment by riverar** [comment]
@GorlikItsMe When you say switch profiles, what do you mean?

**Comment by Alok-S-Sharma** [comment]
A few days ago, I also faced a similar experience.

Other than the main volume, none of the other volumes were displaying.

I don't know what I did, but they returned, I guess I rebooted the laptop.

**Comment by scrable** [comment]
I was having this same issue. Many applications and other sound sources would not appear in the taskbar flyout. The solution for me was to restart EarTrumpet every boot after the Sound Blaster Command was done starting. To avoid manually doing this, I used [Startup Delayer](https://www.r2.com.au/page/products/show/startup-delayer/) to postpone launching EarTrumpet until the Sound Blaster Command is done launching.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
