### ISSUE TITLE
Addon support broken

### ISSUE THREAD

**Issue by skief** [File-New-Project/EarTrumpet#820]
Hey,
it seems like commit c7b6790fe8b31d3957e9d24d273783236e308d72 in the dev branch broke the addon support. Neither the plugins from your addons repo nor our hardware support addon is loaded after this commit.

**Comment by riverar** [comment]
Hey @skief, yep I did. Sorry about that. The [very next work item](https://github.com/File-New-Project/EarTrumpet/projects/6) is to load from the Documents location, will get that in ASAP.

In the meantime, you should be able to load add-ons via the `Addons` folder in the EarTrumpet installation directory (or just tweak the [AddonResolver ](https://github.com/File-New-Project/EarTrumpet/blob/c7b6790fe8b31d3957e9d24d273783236e308d72/EarTrumpet/Extensibility/Hosting/AddonResolver.cs) as needed).

I'll leave this bug open until I get that change in, standby.

**Comment by riverar** [comment]
@skief Should load as usual now, thanks for your patience. Re-open if you run into any issues. (I tested with the Addons repository workflow.)

**Comment by svenwml** [comment]
@riverar Is the support for loading addons from the documents location still on the ToDo-list?
