### ISSUE TITLE
Eartrumpet crashes when interacted with.

### ISSUE THREAD

**Issue by Spirit-chan** [File-New-Project/EarTrumpet#823]
When I boot my computer, and I try to interact with Eartrumpet, it crashes and refuses to launch.

**Comment by riverar** [comment]
Hi @Spirit-chan, can you open Event Viewer > Windows Logs > Application and see if there's an EarTrumpet related entry in there?

**Comment by Spirit-chan** [comment]
These are the entries.

First Error:
Log Name:      Application
Source:        Application Error
Date:          5/9/2021 2:18:01 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      SpiritLab
Description:
Faulting application name: EarTrumpet.exe, version: 2.1.8.0, time stamp: 0x602cd00d
Faulting module name: d3d9.dll, version: 10.0.19041.928, time stamp: 0x9e604254
Exception code: 0xc0000005
Fault offset: 0x000e544d
Faulting process id: 0x2724
Faulting application start time: 0x01d745077b8d686b
Faulting application path: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.8.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 5d066d2c-95aa-4fb4-81aa-8ac4785b5daa
Faulting package full name: 40459File-New-Project.EarTrumpet_2.1.8.0_x86__1sdd7yawvg6ne
Faulting package-relative application ID: EarTrumpet
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-09T19:18:01.5969872Z" />
    <EventRecordID>39015</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>SpiritLab</Computer>
    <Security />
  </System>
  <EventData>
    <Data>EarTrumpet.exe</Data>
    <Data>2.1.8.0</Data>
    <Data>602cd00d</Data>
    <Data>d3d9.dll</Data>
    <Data>10.0.19041.928</Data>
    <Data>9e604254</Data>
    <Data>c0000005</Data>
    <Data>000e544d</Data>
    <Data>2724</Data>
    <Data>01d745077b8d686b</Data>
    <Data>C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.8.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\d3d9.dll</Data>
    <Data>5d066d2c-95aa-4fb4-81aa-8ac4785b5daa</Data>
    <Data>40459File-New-Project.EarTrumpet_2.1.8.0_x86__1sdd7yawvg6ne</Data>
    <Data>EarTrumpet</Data>
  </EventData>
</Event>


Error Two: 
Application: EarTrumpet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 658A544D

**Comment by riverar** [comment]
@Spirit-chan Hm. Looks like a third-party issue (display drivers? customization software?) but can you do the following so we can be sure?

1. Open Regedit, navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`
2. Create a REG_DWORD value named `DumpType` and give it a value of 2
3. Reproduce the crash
4. Find the EarTrumpet.exe.dmp in %LOCALAPPDATA%\CrashDumps, zip it up and upload it to OneDrive/send a copy to team@eartrumpet.app. (Do not attach it here!)
5. Repeat step 1 above then delete `DumpType` to clean up

**Comment by Spirit-chan** [comment]
Sent it

**Comment by Spirit-chan** [comment]
Also, same issue has been happening, but yesterday, I was able to use EarTrumpet normally. Now today it doesn't work again.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.
