### ISSUE TITLE
Moving app to another device no longer works on Windows 10 dev builds

### ISSUE THREAD

**Issue by valipod** [File-New-Project/EarTrumpet#835]
## Description
When trying to move an app (say Chrome on youtube) from the default to another playback device, the app appears as a clone on the new device, the playback continues on the old one. No way to change it other than the regular windows interface Settings/System/Sound/App volume and device preferences (which works).

In less words, Ear Trumpet is no longer doing its main task :)

## Steps to reproduce
1. Open an app (Chrome) playback with some sound (a Youtube video)
2. Click on the EarTrumpet Icon
3. Right click on Chrome
4. Click on the double arrow icon
5. Select another playback device
6. Playback continues on the old device, an inactive clone of Chrome has been created on the new device

## Meta
* EarTrumpet version: 2.1.8.181 (first tried with the official store 2.1.8.0 version, same behavior)
* Windows 10 version: 21382.1, Windows 10 Feature Experience Pack 321.12100.0.3

The issue happened after the upgrade to version 21382.1 (or it might have been the very last build before this one), but it also happens on a clean install of build 21390.1. I cannot tell if this is a Windows bug, or a lasting change in the OS's behavior that might need updates on the Ear Trumpet side.

## Screenshots
![EarTrumpet](https://user-images.githubusercontent.com/1492705/118526145-9cbb9700-b748-11eb-9eec-c6c021a7cb82.jpg)

**Comment by im3or** [comment]
I have a speaker & a headphone. EarTrumpet is useless. Why do i need this piece of software when i can't switch my devices. Default windows sound in much better. Thanks a lot. Uninstalled!!

**Comment by riverar** [comment]
Thanks, will check this out tomorrow. Chrome is a bit of a bad test case because of the sandboxed tab processes, brokered audio, etc. complexities. That said, if it works on current production builds of Windows 10 then this is certainly alarming.

**Comment by valipod** [comment]
@riverar thanks for the reply. It just happened that I used Chrome as an example, it no longer works with any app (and yes, it works like a charm in prod builds, it's what made EarTrumpet a must). :)

**Comment by valipod** [comment]
@im3or EarTrumpet has worked for a long time, making switching between audio devices easy as pie. It just doesn't work now on some new builds of Windows 10, and this is why you open issues, to help fixing such problems. Not to wine-cry-shout.

**Comment by im3or** [comment]
> @im3or Ear Trumpet has worked for a long time, making switching between audio devices easy as pie. It just doesn't work now on some new builds of Windows 10, and this is why you open issues, to help fixing such problems, at least by letting the maintainers know about them. Not to wine-cry-shout.

Thanks for the reply. Sorry if my post sounded like i was whining. I have used Ear Trumpet for months but when it doesn't work (On my system) the way it is supposed to work, i have to move on. My apologies if by uninstalling it i am not giving the maintainers time to fix the problem i am having. So I've bookmarked this & check from time to time that this thread is fixed or not then i will install it again.

**Comment by riverar** [comment]
Can confirm, IAudioPolicyConfigFactory was changed. Working on a fix now, thanks for your patience all!

**Comment by riverar** [comment]
Fixed in latest dev builds.
