### ISSUE TITLE
Does not show programs opened, only works when closing app and opening again.

### ISSUE THREAD

**Issue by tazhel** [File-New-Project/EarTrumpet#846]
## Description
Sometimes when clicking on the EarTrumpet icon it does not siaply any of the apps open. So I can only control the master volume, not individually

## Steps to reproduce
1. Click on EarTrumpet Icon in the system tray.
2. No software is showing, only the master volume(not sure why)
3. By closing the EarTrumpet and opening it again, it now shows all programs.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 Pro version: 20H2

## Screenshots
This is how it looks when it happens
![image](https://user-images.githubusercontent.com/18552030/120480775-b0553780-c3af-11eb-994c-4c81cd596408.png)

This is how it should look, and how it is when closing and opening the application again.
![image](https://user-images.githubusercontent.com/18552030/120480401-48065600-c3af-11eb-8b7f-6ec86e6e4307.png)

**Comment by michaelchany** [comment]
It seems to reliably happen when switching users and logging to another profile.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
