### ISSUE TITLE
Microsoft Teams always resets to 100% volume

### ISSUE THREAD

**Issue by joloujo** [File-New-Project/EarTrumpet#847]
## Description
When using Microsoft Teams, every time you enter a new meeting, the app's volume is reset to 100%.

## Steps to reproduce
1. Enter a meeting in Teams

## Meta
* EarTrumpet version: 1.2.3.4
* Windows 10 version: 19042.746

## Screenshots
![image](https://user-images.githubusercontent.com/45150192/120837329-6a1ce700-c51b-11eb-9239-f903b991a021.png)

**Comment by i3asm** [comment]
I think this is because with every meeting teams starts new audio track, and it will be automatically start at 100%

I think this is related to this issue:  [#98](https://github.com/File-New-Project/EarTrumpet/issues/98)  where the user suggested saving the volume setting for every app.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. There's no work to be completed here at the moment so am closing this issue for now. Feel free to keep the discussion going. Thanks!
