### ISSUE TITLE
EarTrumpet only shows main volume when FxSound used while switching playback device.

### ISSUE THREAD

**Issue by ripslayer** [File-New-Project/EarTrumpet#848]
## Description
EarTrumpet only shows main volume when FxSound used while switching playback device.

## Steps to reproduce
1. Change From Headphone to Speakers or vice-versa
2. Will only show main volume after that.
3. Restart app to fix.

## Note
(App is working fine in 1909 with FxSound but after 1909 updates it is broken.)

## Meta
* EarTrumpet version: 2.1.8.181 (Dev)
* Windows 10 version: 21H1

**Comment by riverar** [comment]
After switching my output device a few times in FxSound, even Windows got confused. Suspect FxSound is hitting issues with their calls to SetDefaultEndPoint. Can you open a bug with them? Feel free to point them to this issue or have them reach out to us (team@eartrumpet.app).

**Comment by ripslayer** [comment]
Well, I had a chat with them and they can't fix it at least at the current moment that is. So it's a rip off for now I guess. If you can do something from your side will be glad tho. But at least thanks for figuring out the issue.

**Comment by batashahh** [comment]
Did you ever find out a way to make fxsound work with eartrumpet ?

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1305, thanks!
