### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by xmha97** [File-New-Project/EarTrumpet#850]
Hi, 
Windows 10 Enterprise LTSC doesn't have "Microsoft Store" and "App Installer" and people who use this edition of Windows can not use EarTrumpet.
I recently found out that these people can install EarTrumpet using Chocolatey.
Chocolatey is a package manager for Windows.
Just type the following command in PowerShell:
```
choco install eartrumpet
```
Please mention this in the README.md file.
Thanks.

**Comment by riverar** [comment]
It already does, thanks.
