### ISSUE TITLE
Adding VisualElementsManifest to the Chocolatey package

### ISSUE THREAD

**Issue by xmha97** [File-New-Project/EarTrumpet#851]
Hi, please add a VisualElements to the Chocolatey package:
![Start menu](https://user-images.githubusercontent.com/23485114/121803319-29794800-cc56-11eb-96de-9e45c2c585ec.png)
Download and use this file: [Additive.zip](https://github.com/File-New-Project/EarTrumpet/files/6643689/Additive.zip)

**Comment by riverar** [comment]
@xmha97 Thanks! Would you like to submit a PR and get credit for the change?

**Comment by xmha97** [comment]
> 
> 
> @xmha97 Thanks! Would you like to submit a PR and get credit for the change?

I can not.

**Comment by riverar** [comment]
@xmha97 OK, no problem. Will get it in soon.

**Comment by xmha97** [comment]
Thanks.

**Comment by riverar** [comment]
Closing as you're working on a PR.
