### ISSUE TITLE
On Windows 11 (21H2 22000.51) Insider Dev apps dont change between outputs

### ISSUE THREAD

**Issue by garridinsi** [File-New-Project/EarTrumpet#867]
## Description
A clear and concise description of what the bug is

When you right click an app to change the output device and you select an app, it doesnt change. Seems broken by the update.

## Steps to reproduce
1. Open from taskbar
2. Right click the app
3. Press the change button
4. Select device
5. Nothing happens

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 11 version: 22000.51 Insider Dev

**Comment by riverar** [comment]
Thanks @garridinsi, good timing. I actually fixed this last night. I'll push it out to the dev branch soon!

**Comment by garridinsi** [comment]
Perfect! I'll test it! Thanks for your work

**Comment by suntizzl** [comment]
How can get this update for EarTrumpet?

**Comment by primeminister91** [comment]
Any movement on this issue?  Really love the project.

**Comment by riverar** [comment]
Fixed with https://github.com/File-New-Project/EarTrumpet/commit/575de23e96ee962d810e31ec805c5a7a6395755e, should be rolling out to the dev channel shortly.
