### ISSUE TITLE
Rsod Error

### ISSUE THREAD

**Issue by UberboneZ** [File-New-Project/EarTrumpet#87]
I downloaded version 1.4.3.0 from the app store and instead of getting a Bsod i got a Rsod so i cold restarted my computer and before i could uninstall ear trumpet i got a Bsod just throwing this info out there because i didnt see any Rsod threads.

**Comment by riverar** [comment]
Don't know what RSOD means but sounds like it's a dupe of #84

**Comment by UberboneZ** [comment]
No its called a red screen of death its a graphical bug, I'm pretty sure it involves drivers it could be just a fluke of an issue due to the BSOD error i'm not sure.

**Comment by GoldenTao** [comment]
If you're still having this problem, please reopen this issue.
