### ISSUE TITLE
Can't install EarTrumpet developer build, Azure storage down

### ISSUE THREAD

**Issue by jordanyoong1** [File-New-Project/EarTrumpet#876]
## Description
It says "Error in parsing the app package." in App Installer

## Steps to reproduce
1. Go to EarTrumpet website
2. Click on the dev install button
3. See error

## Meta
* Windows 10 version: 19042.1083

## Screenshots
![image](https://user-images.githubusercontent.com/40160073/125472902-2a1090df-31f1-4dcf-b40e-3164d6828516.png)

**Comment by riverar** [comment]
Yep, sorry about that. My Azure subscription is suspended, waiting for Microsoft to fix it. 😥

**Comment by Delta18-Git** [comment]
Seems to be fixed now.
![image](https://user-images.githubusercontent.com/64347927/128030158-53eb272c-524f-40fc-81f3-127e719b80d0.png)
It hasn't installed but I think that is because I have the store version of EarTrumpet installed.

**Comment by riverar** [comment]
Azure storage is up now, thanks for your patience!
