### ISSUE TITLE
eartrumpet does not start

### ISSUE THREAD

**Issue by decentfam** [File-New-Project/EarTrumpet#886]
I have been using eartrumpet for some time, but when I restarted my computer one time the icon wasn't there and I could not launch the program nothing happened I tried to re-install it but had a lot of trouble with it. it's still not showing and it's not in the task manager either. when I restarted my computer recently it suddenly worked but it was a bit buggy so when I tried to restart my computer again it wasn't working again

**Comment by riverar** [comment]
@decentfam Please provide all the information in the bug report form.

**Comment by decentfam** [comment]
how do i do that
