### ISSUE TITLE
No applicable app licenses found

### ISSUE THREAD

**Issue by ryanmholmes** [File-New-Project/EarTrumpet#887]
![Screenshot 2021-07-30 104835](https://user-images.githubusercontent.com/86068175/127678619-2f5a6fb6-8b58-4bda-81b9-722dae667d0b.png)

I've been using EarTrumpet for years with no problems. Today, I woke my PC from hybrid sleep and was greeted by this dialogue. EarTrumpet would not launch. I repaired the install in the Windows program menu, which eliminated this dialogue, but EarTrumpet then would not start. I uninstalled and reinstalled from MS Store and was greeted again by the same dialogue on launch (and program fails to launch). So it currently can't be run on my system. Have not tried Chocolatey install or another PC. I was not experiencing this on the other as of last night, but have not checked today (in the case that an update may have caused it?).

Windows 10 Pro 21H1 OS build 19043.1110

EarTrumpet is a main app in my kit! Hope we can find the culprit.

**Comment by ryanmholmes** [comment]
This is now resolved after reinstalling following a reboot. Will reopen if recurs.

**Comment by riverar** [comment]
Thanks @ryanmholmes and sorry this is a pain. The Store is finicky. Next time it happens, also file a Feedback Hub item under [Microsoft Store] [Other issues or suggestions] and paste a link here.
