### ISSUE TITLE
Flyout sometimes hides&immediately shows when CPU frequency is lower (e.g. battery mode)

### ISSUE THREAD

**Issue by petrroll** [File-New-Project/EarTrumpet#89]
Click on tray-icon when fly-out is visible sometimes causes it to hide and reappear immediately when CPU frequency is low (e.g. on battery mode, reproduced on Haswell mobile CPU@800MHz). Flickering (fast sequential show&hide&show) happens from time to time when invoking hidden fly-out on low CPU as well (thought that is sometimes a to certain degree observable even on high-power).

It's probably caused by the fact that the hide animation invoked in `Window_Deactivated` (lost focus) by `HideWithAnimation` finishes before the message for `TrayIcon_Invoked` gets processed by WPF lop and therefore `TrayIcon_Invoked` sees current window in hidden state and re-invokes it.

As for the cause of flickering, I haven't investigated that further but suppose it's similar.

**Comment by petrroll** [comment]
And honestly, I can't really come up with a good way to fix it. An option would be to create a do-not-invoke-show&hide-animations window after each show/hide (e.g. 1.5 times the animation length), e.g. with a static variable animationInProgress (there're already two of those, just unify them) that would get reset by a Task not when animation finishes but a bit after that. 

That could, however, create a bit of unresponsiveness for the user which I don't particularly like. Also, it doesn't really solve the root of the issue, just heals the symptoms.

**Comment by riverar** [comment]
Interesting. If I understand this correctly, to repro this all I need to do install throw this on a tablet/laptop and lower its CPU frequency (by twiddling with the power plan). Will check it out.

**Comment by petrroll** [comment]
Yep, you understand that correctly, default "Power saver" plan should work just fine. 

(or use something like Intel XTU for down clocking)

**Comment by petrroll** [comment]
I've tried the hotfix I proposed in OP and it eliminates the hiding & reappearing quite well. https://github.com/petrroll/PowerSwitcher/commit/b4961b89c11814737038e27442a075bcc0e6565c

It still doesn't make showing and hiding on slow CPU fluid, though. The flickering problem still seems to happen though my debugging showed that it's not because the flyout would get shown&hidden&shown but (most probably) just due to insufficient recourses to maintain 60 FPS for the animation (which is quite surprising, TBH).

**Comment by petrroll** [comment]
Just to help with repro, It seems that only battery mode isn't throttling the system enough (on higher end laptops). What worked quite well for me was to start the program with debugging from visual studio while being unplugged (in addition to being on battery saver).

**Comment by riverar** [comment]
@petrroll Can you try this in EarTrumpet 2.0 when you get a chance? Re-open if needed.
