### ISSUE TITLE
Some progamms doesn't get switched

### ISSUE THREAD

**Issue by TheDanniCraft** [File-New-Project/EarTrumpet#891]
## Description
Some programms(like Crome) works, but other programms(Games like Minecraft) does't switch the audiolines. They stay in the same line, but in the selector is another line selected

## Steps to reproduce
1. Go to 'Taskbar'
2. Click on 'Eartrumpet Icon'
3. Scroll down to 'Speaker USB PnP Headest'
4. Click on 'Minecraft.exe'
5. Click on 'the double Arrow'
6. Select 'my own private Virtual Line '
The audio plays over the Speaker not over the virtual audio, but selected is the private Line 

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19043.1110

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1307, thanks!
