### ISSUE TITLE
Trumpet icon missing/replaced in task bar

### ISSUE THREAD

**Issue by Slippity** [File-New-Project/EarTrumpet#892]
## Description
The "Trumpet" icon is no longer in the system tray. It is now 2 speaker icons.

## Steps to reproduce
1. Installed EarTrumpet from within Windows 
2. After installation the correct taskbar icon is not there, it is now another speaker icon.
3. Tried reinstalling. Tried windows format/reinstall. Issue remains.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19043.1151

## Screenshots
![aaaaaaaaaa](https://user-images.githubusercontent.com/73107018/128648031-f7a096fd-b4ec-450f-a9c8-51e3be494177.PNG)

**Comment by riverar** [comment]
@Slippity You can turn the old icon behavior back on via Settings. (Right-click the EarTrumpet icon in the notification area.)
![image](https://user-images.githubusercontent.com/475132/128661852-4ef811e7-8288-4995-ae91-1ad95cdf4cfe.png)
