### ISSUE TITLE
Audio Device Switching

### ISSUE THREAD

**Issue by Ryoken0D** [File-New-Project/EarTrumpet#9]
First, this is a great little app. Love it. 
This is one other feature I'd love to see be a part of this, that is a way to quickly change the currently active audio device. For example to alternate between the soundcard, HDMI, USB Headset, etc.

**Comment by Eric2XU** [comment]
I second this, I would actually be willing to pay for it too. Windows makes it far to many clicks to swtich between my headset and my main auto output. In my case I have a soundbar and a set of earphones. When its late at night I switch to earphones. Always a pain, one click then switch (perhaps with a sub menu). Keep up the great work!

**Comment by Eric2XU** [comment]
Ryoken0D, I did find a solution for now for easy input switching using RainMeter and CircuitousTwo skin which has a great volume/input widget. Also kicked it up with Fountain of Colors which gives a live eq on the desktop too. Still hoping they add it to ET but at least its something.

**Comment by Rhedox** [comment]
Not exactly what you wanted but I added "Show playback devices" to the context menu similiar to what Windows' native volume tool has. 

https://github.com/File-New-Project/EarTrumpet/pull/35

**Comment by riverar** [comment]
Will discuss this with others and figure out what direction we want to go. Stay tuned!

**Comment by rockfordlhotka** [comment]
I am now running both Ear Trumpet and a project called [Audio Switcher](https://github.com/davkean/audio-switcher) to get most of the functionality I want.

If Audio Switcher supported in/out profiles it would be even better (I almost always use either my headset or my PC speaker/mic combo - so have pre-defined combos would make Audio Switcher pretty much perfect).

**Comment by riverar** [comment]
We're implementing this, stay tuned :smile:
