### ISSUE TITLE
Ear Trumpet is keeping my second GPU awake

### ISSUE THREAD

**Issue by lavacano201014** [File-New-Project/EarTrumpet#90]
Steps to reproduce:
1. Have two AMD GPUs in CrossFire (mine are R9 270Xs)
2. Run Ear Trumpet on an empty Windows desktop

Expected result: Only one GPU is active.
Actual result: Both GPUs are active.

**Comment by lavacano201014** [comment]
After some poking about, this is probably related to the program's ability to select a default audio device. Could we get an option to disable that particular functionality? I don't tend to use it anyway.

**Comment by riverar** [comment]
Does closing EarTrumpet free up one GPU immediately? This is certainly not related to the default audio device feature. This is likely some issue with WPF -- perhaps our upgrade to .NET 4.6.2 will resolve this.

**Comment by lavacano201014** [comment]
Yes, closing Ear Trumpet immediately powers off the other card.

A bug in AMD drivers wouldn't surprise me either, but so far out of all the programs that I have checked, only Ear Trumpet and f.lux have this problem,so I'm not sure we can blame them (yet)

**Comment by riverar** [comment]
Hm, perhaps we'll add a little reg flag you can set that will force our WPF app to set RenderOptions.ProcessRenderMode to Software only.

**Comment by riverar** [comment]
Do you still have this issue? If so, we can get you some test code with the above change.

**Comment by lavacano201014** [comment]
Unfortunately, yes, with Ear Trumpet 1.4.3.0.

**Comment by riverar** [comment]
Try replacing your executable with this version.
[EarTrumpet.zip](https://github.com/File-New-Project/EarTrumpet/files/689026/EarTrumpet.zip)

**Comment by lavacano201014** [comment]
I can't. Windows won't let me alter anything in the app's directory, even after changing file permissions as the built-in "Administrator" account. Apparently, altering store apps is verboten.

Can I get a full non-store build please?

**Comment by riverar** [comment]
[1.4.3.1_softwarerendering.zip](https://github.com/File-New-Project/EarTrumpet/files/690540/1.4.3.1_softwarerendering.zip)

**Comment by riverar** [comment]
That working better for you?

**Comment by lavacano201014** [comment]
Sorry I'm late, but yeah, that's solved it.

**Comment by ArsenicBismuth** [comment]
Hi, I'm having this issue too, as it's very visible EarTrumpet is using my dedicated GPU (instead of integrated). I tried forcing it in my dGPU control panel & windows graphic selector, both fail (despite flawlessly working on others).

Is there a new version for the software rendering executable? Or is it implemented in the newer version (5 years later).

**Comment by leopatik** [comment]
> Hi, I'm having this issue too, as it's very visible EarTrumpet is using my dedicated GPU (instead of integrated). I tried forcing it in my dGPU control panel & windows graphic selector, both fail (despite flawlessly working on others).
> 
> Is there a new version for the software rendering executable? Or is it implemented in the newer version (5 years later).

Hey! I have this issue too, did you found any fix?

**Comment by ArsenicBismuth** [comment]
@leopatik I don't know what happened, prob new version. But I don't see EarTrumpet using ANY GPU process now when closed. It'll resume using my dGPU when I open it, but otherwise it has been been idle most of the time.

**Comment by riverar** [comment]
@ArsenicBismuth Are you on a dev build perhaps?
