### ISSUE TITLE
EarTrumpet does only open a couple of times when clicked

### ISSUE THREAD

**Issue by TheRealDadbeard** [File-New-Project/EarTrumpet#900]
## Description
A clear and concise description of what the bug is

## Steps to reproduce
Leftclick the icon
Nothing happens

I have to click the default one then EarTrumpet will show itself for one time. Then after some time I will be able to have it popup again.

## Meta
* EarTrumpet version: 2.1.8.187
* Windows 10 version: 19043.1165

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it. (Some flyout unresponsive issues were fixed in newer versions.)
