### ISSUE TITLE
Blank App Icons

### ISSUE THREAD

**Issue by Xeizell** [File-New-Project/EarTrumpet#91]
My EarTrompet 1.4.3.0 doesn't show proper icons for some apps (in this case, Discord and Spotify). I tried reinstall and restart but didn't work. Thanks.

http://i.imgur.com/owbPJOV.png

**Comment by riverar** [comment]
- Can you hover over the default icons? Are those actually Spotify/Discord?
- What version of Windows are you using? Are you on an Insider build?
- Are Discord/Spotify installed in default locations? Or something special?

**Comment by Xeizell** [comment]
Thanks for replying.
1. Sure. http://i.imgur.com/bWrUMsV.png And also, what app is on the bottom? Sometime it's showing sometimes not.
2. No. Normal Win 10 anniversary w/ latest update.
3. Yeah, both in default locations.

**Comment by riverar** [comment]
- Can you visit %AppData%\Spotify in File Explorer and see if it shows a proper Spotify icon?
- Is this machine on a domain, perhaps with profile redirection or anything fancy?

**Comment by Xeizell** [comment]
1. Sure. http://i.imgur.com/yyz7eiW.png
2. No. It's in standard workgroup with local profile.

The 1.3.2.0 version is showing the app icon just fine tho.

**Comment by riverar** [comment]
Hey there @Xeizell, are you still having this issue?

**Comment by ioannis-e** [comment]
Windows 10 Pro - EarTrumpet 1.4.3.0 from windows store
2nd Spotify Free ???
4th Windows Shell Experience Host ???

![image](https://cloud.githubusercontent.com/assets/5904989/21905955/0148cf22-d912-11e6-839f-e6b6509efeac.png)

**Comment by GoldenTao** [comment]
Please reopen this issue if you're still seeing the same problem.
