### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by exhuma** [File-New-Project/EarTrumpet#910]
## Description

Clicking on the "Install" button in the Windows Store does absolutely nothing. No progress, no error, no install.

## Steps to reproduce
1. Open the Windows Store
2. Search for EarTrumpet
3. Click on "Install"

I was searching for a really simple download with an installer but could not find anything. I saw the "choco" alternative, but I prefer to keep my Windows environment as clean as possible so I would like to avoid installing choco *just* for this one app. A simple installer would be a really nice-to-have as alternative.

**Comment by riverar** [comment]
We have an experimental feed on https://eartrumpet.app if you don't mind using dev builds. Otherwise, you'll have to use choco (or [download the package manually and extract the zip](https://community.chocolatey.org/api/v2/package/eartrumpet/2.1.8.0)).

**Comment by exhuma** [comment]
That's pretty bad user-experience. I *really* love EarTrumpet. But this is the second PC I am unable to install it.

I tried to download the package as you mentioned, unzipped it and now I have a set of folders and I don't know what to do with them.

I really don't mind the installation via the MS-Store at all. But at least it should *work*.

On my last PC I assumed it was just something borked with my install. But now I'm sitting on a brand-new PC with a 100% fresh Windows installation and it just doesn't want to install 😢

**Comment by riverar** [comment]
@exhuma The Microsoft Store is an endless source of frustration, agree. What build/version of Windows are you using, btw?

**Comment by exhuma** [comment]
Version 21H1 (Build 19043.1237)

![image](https://user-images.githubusercontent.com/65717/134218803-90b255a5-5a1c-4426-99f9-5c77975420d5.png)
