### ISSUE TITLE
Question: How do I use EarTrumpet with Win11?

### ISSUE THREAD

**Issue by Corbinator333** [File-New-Project/EarTrumpet#914]
I just recently upgraded to Windows 11, and when I go to click the volume button (like I did in Win10) it just brings up the default Windows sound settings. How do I interact with EarTrumpet now that I'm using Win11?

**Comment by riverar** [comment]
Hi @Corbinator333, you can continue using EarTrumpet via its notification area icon. We unfortunately can't remove/override the system provided controls.

![image](https://user-images.githubusercontent.com/475132/136245360-ae23397a-b90a-40a8-a974-f002356276ec.png)

Going to close this as there's no action needed, but feel free to continue here if needed.
