### ISSUE TITLE
a couple of minor UI points

### ISSUE THREAD

**Issue by equin0x80** [File-New-Project/EarTrumpet#92]
Minor UI stuff: 1. The app tooltip says "Ear Trumpet - Volume Control for Windows". The user knows they are running Windows so that last part seems like unhelpful clutter. 2. The About menu item has an ellipsis (3 dots), but the ellipsis should not be used just because you are opening a new window -- only when the command is going to prompt the user for further parameters.

**Comment by Dany-R** [comment]
I'd like to second the second point (no pun intended ;) )
My proposal would be to remove the 3 dots and display a Web icon for the menu item (e.g. a globe).
Cheers, Dany

**Comment by riverar** [comment]
Volume Control for Windows is the product's tag line. But will consider the ellipses removal, a pull request would be welcome/appreciated.

**Comment by equin0x80** [comment]
Additional inconsistency in the latest version (1.4.4.0): "About Ear Trumpet" has a space before the ellipsis, but "Send Feedback" does not.  I would also remove the version number from the menu item: this belongs in the About box and not on the menu.  I've never seen any other app include the version number in the menu caption.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
