### ISSUE TITLE
Fortnite hangs / not responding when EarTrumpet open

### ISSUE THREAD

**Issue by Cam9731** [File-New-Project/EarTrumpet#927]
Basically the title, fortnite will open normally when eartrumpet is closed, but if open, the game will hang on the connecting screen for me after the recent update to fortnite. This issue had never occurred before then.

This occurs on every launch regardless of other open applications.

Easy fix is to just close it when launching the game, but still curious that it happens now after a update to the game came out just today.

**Comment by taradinoc** [comment]
This is happening for me too. I got here from [this Reddit post](https://www.reddit.com/r/FortNiteBR/comments/q7lcdx/fortnite_stuck_on_connecting_screen/).

I use EarTrumpet to force Fortnite to use a certain device (VoiceMeeter Aux Input), and it hangs on the "connecting..." screen when my default audio device is set to something else (VoiceMeeter Input). I can get Fortnite to run successfully by changing the default device back to VoiceMeeter Aux Input before I start it.

VoiceMeeter also hangs while Fortnite is in this state, so I had assumed it was a problem with VoiceMeeter, and I actually hadn't tried closing EarTrumpet. I'll try that next time.

**Comment by lummux** [comment]
Same issue.  Sending report.  Posting video another user having the same issue.
https://www.youtube.com/watch?v=lajykQfXVg0

**Comment by Convoy20** [comment]
Just confirming that I was having this issue, windows 10 - very very odd.

**Comment by sarsticus** [comment]
Windows 10 - I have this issue as well, it started happening yesterday. I opened it with no issue, and then a couple hours later it got stuck on "connecting" and Fortnite becomes non-responsive. 

Like others have said, this issue stops as soon as I change Fortnite to output to my default audio device. However it if I change Fortnites output again, the issue reappears the next time I try to open Fortnite.

I have attached troubleshooting data from EarTrumpet while the app is running

[tmpB9C2.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/7532910/tmpB9C2.tmp.txt)

**Comment by KevC117** [comment]
Just popping in here to say that I too have now encountered this issue. I have been running EarTrumpet with Fortnite for over a year now and this problem just popped up today for me.

Windows 10 - Build 21H2 19044.1348

When launching Fortnite with EarTrumpet open, Fortnite will hang on the "Connecting..." screen forever. The workaround for this is to close Fortnite, Close EarTrumpet, then re-launch Fortnite, followed by EarTrumpet.

I am not using EarTrumpet to force a different sound device for Fortnite, I am using Windows itself to do that. Fortnite launches fine with my audio device preference via windows as long as EarTrumpet is not running. From what I've noticed, it seems like Fortnite cannot hook into an audio device while EarTrumpet is running at startup.

Attached is the requested troubleshooting data:
[tmp4FEA.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/7543486/tmp4FEA.tmp.txt)

**Comment by gkatsaros16** [comment]
yea me to

**Comment by gkatsaros16** [comment]
any updates @riverar

**Comment by riverar** [comment]
Nothing yet, been tied up sorry. Annoyingly I can't reproduce this here. Maybe I'll put out a hotfix that just ignores Fortnite launches for now.

**Comment by boulderhead** [comment]
This is no longer an issue for me with the latest Fortnite update (Chapter3, Season 1).

**Comment by gkatsaros16** [comment]
yea me to

**Comment by Richkan1** [comment]
same here. not an issue anymore after the latest FN update

**Comment by Cam9731** [comment]
Can confirm, no longer an issue for me either!

**Comment by riverar** [comment]
Wow, thanks all for the update! Sounds like Epic is on top of things over there.
