### ISSUE TITLE
Feature Request: Add a persistent window mode

### ISSUE THREAD

**Issue by qoncept96** [File-New-Project/EarTrumpet#93]
I would very much like to see a persistent window mode, that opens and remains opened until you close it. This is a much simpler for people whose workflow has them using the volume mixer regularly - you can simply move your mouse to the appropriate slider and use the scroll wheel to adjust without a click, and without losing focus in the app you're actively using.

**Comment by qoncept96** [comment]
FYI, I was planning on just doing this myself but I haven't been able to get the project to build. I assume since I'm using VS 2015 I should be opening the vs15 solution? I've tried opening both and keep getting the error below. I've been fighting with it for hours and thought it would be prudent to ask.. :)


1>C:\Users\jared\source\repos\EarTrumpet\EarTrumpet\TrayIcon.cs(9,15,9,31): error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?)

...etc, all references to Windows.*

**Comment by riverar** [comment]
The VS15 solutions is for Visual Studio "15" Preview (required for AppX project). You can use the EarTrumpet.sln for Visual Studio 2015.

**Comment by abgrac** [comment]
**Bump!** This is, for a long time in Windows OSes,  a **must**.

**Comment by riverar** [comment]
Any progress @qoncept96?

Will investigate undockable UI.

**Comment by qoncept96** [comment]
@riverar Unfortunately no, I haven't had access to VS much since those comments.

**Comment by riverar** [comment]
Now available in EarTrumpet 2.0. Grab it from the Microsoft Store (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp)
