### ISSUE TITLE
Flyout on W11 should set a right margin

### ISSUE THREAD

**Issue by ZhaoMJ** [File-New-Project/EarTrumpet#933]
## Description
Flyouts on Windows 11 not only have a bottom margin but also a right/left margin (see the screenshots). It'd be great if EarTrumpet can do the same to match the style of W11. 

## Meta
* EarTrumpet version: 2.1.9.0
* Windows 11 version: 22000.258

## Screenshots
![image](https://user-images.githubusercontent.com/48666391/137367012-9c1bc42d-3d71-4bf1-8d53-7fa8a060951a.png)

![image](https://user-images.githubusercontent.com/48666391/137367109-d87136c3-e90b-487d-9548-1f81a15ae479.png)

**Comment by duk6046** [comment]
very agree

**Comment by loboly-19** [comment]
can confirm

**Comment by riverar** [comment]
This should be fixed in EarTrumpet 2.1.10 now available in the Microsoft Store, chocolatey, and other sources!
