### ISSUE TITLE
Volume doesn't saved in some games.

### ISSUE THREAD

**Issue by ahopjn** [File-New-Project/EarTrumpet#934]
After the next launch of the game, the volume changes to 100 (or another standard value).
Games:
- Battlefield V
- Call of Duty Warzone
- Call of Duty Cold War
- Counter-Strike Global Offencive

**Steps to reproduce**
1. Launch the game.
2. Change volume.
3. Exit from the game.
4. Again launch the game.
5. The volume has been reset.

EarTrumpet version: 2.1.9.0
Windows 10 version: 19043.1237

**Comment by riverar** [comment]
This isn't a feature of EarTrumpet (although EarTrumpet Actions, [in dev builds](https://eartrumpet.app), may help). This is _supposed_ to be handled by Windows.

_Please_ follow the steps here (change the template as needed) https://github.com/File-New-Project/EarTrumpet/issues/512#issuecomment-683485012 to get Microsoft feedback with log data.

Closing this for now as there's nothing to fix/do here but I keep this on top of mind. Thanks!
