### ISSUE TITLE
EarTrumpet opening animation lags

### ISSUE THREAD

**Issue by DanRotaru** [File-New-Project/EarTrumpet#936]
## Description
When I'm opening app from taskbar I have big animation lags (feels like 20-25 fps), I have Ryzen 7 4700U. I recorded video how smoothly opens default windows volume bar and EarTrumpet.

## Steps to reproduce
1. Just open app

## Meta
* EarTrumpet version: 2.1.9.0
* Windows 10 version: 19043.1288
* Windows 10 Pro 21H1

## Video
Check video (for best experience open in fullscreen mode)

https://user-images.githubusercontent.com/7759507/137783485-359e0398-ca0e-47e8-8615-aa08bc6c430f.mp4

**Comment by DanRotaru** [comment]
😞

**Comment by riverar** [comment]
@DanRotaru I'll take another look at moving to WinUI 3 XAML when the Windows App SDK is available in a few months.

**Comment by DanRotaru** [comment]
Maybe just add possibility to turn off this animation in settings, just show/hide without any anymation
