### ISSUE TITLE
Xbox App not showing up

### ISSUE THREAD

**Issue by FlxtLine** [File-New-Project/EarTrumpet#94]
The volume slider for the xbox app is not showing up. All my other programs have sliders. How can I fix this? Tried restarting/shutting down my pc, and reinstalling the program. Even different versions of it. No luck. Please help.

**Comment by timo103** [comment]
I've been having the same problem with the Xbox app and with Halo Wars on said app.

Neither show up on eartrumpet or the default audio mixer. Even if there's sound in game or a video playing on the app.

**Comment by SHaMROCK73** [comment]
This is an issue for me too.  The Xbox App does not display even when streaming.  It did work before, it is the main reason I use Eartrumpet.  The Xbox (beta) App seems to work though...

**Comment by riverar** [comment]
@SHaMROCK73 Does it appear in the Windows mixer?

**Comment by GoldenTao** [comment]
Please reopen this issue if you're still seeing the same problem.

**Comment by CCF100** [comment]
I believe this was an issue on Microsoft's part. I no longer experience this after Windows updated it.
