### ISSUE TITLE
EarTrumpet keeps disabling itself in the Startup Items menu

### ISSUE THREAD

**Issue by Proaxel** [File-New-Project/EarTrumpet#941]
## Description
I noticed at one point, EarTrumpet no longer opens on its own when Windows boots up and logs in, I have to manually launch it every time. I open Task Manager and check the Startup tab, and it says it's Disabled. Weird, I don't remember disabling it at all. I enable it, but then the next day when I start up my computer the same thing happens, and in the Task Manager set back to Disabled again. I set it to Enabled, and immediately rebooted. Once back into Windows I checked the Task Manager Startup tab again and it's set to Disabled. Something keeps disabling it and I have no idea why or what could it possibly be.

It only started doing this recently, in the 1-2 years I've had it installed. (It's as awesome as ever)

## Steps to reproduce
I don't really have a means of reproducing it as I am completely unsure as to what could possibly be the cause.

But for the sake of just having a summary of what is wrong:
1. Open Task Manager
2. Go to Startup Tab and set EarTrumpet to Enabled
3. Reboot
4. Check Task Manager Startup tab and see it's Disabled

## Meta
* EarTrumpet version: 2.1.9.0
* Windows 10 version: 19042.1288

**Comment by riverar** [comment]
Can you perform the steps listed here https://github.com/File-New-Project/EarTrumpet/issues/417#issuecomment-565943575?

**Comment by Proaxel** [comment]
> Can you perform the steps listed here [#417 (comment)](https://github.com/File-New-Project/EarTrumpet/issues/417#issuecomment-565943575)?


![image](https://user-images.githubusercontent.com/9545347/144768265-28a4ccb1-e2cd-40ae-a846-e99827990bc4.png)

Apologizes for taking so long

**Comment by Proaxel** [comment]
Ok, that seemed to fix it! But I still am not entirely sure why it happened... 

It's tied to those registry values apparently. I did get a new laptop recently and this is how it looks: 
![image](https://user-images.githubusercontent.com/9545347/144768865-8f298267-6400-44fb-aaaf-622645697c95.png)

I don't recall deleting registry values in this particular area... could it be some program that is doing it and I have yet to use it on my new laptop?

**Comment by adavier** [comment]
Apologies for the hijack, but incase someone else ends up here via a search (like me) and the regedit fix doesn't work here is something else to check:

In my case it was after upgrading to Win11 Pro (HDR forced my hand). The above would happen, and then if I added the aforementioned registry keys, after a reboot they would be gone again.

The upgrade broke the Group Policies, which promptly nuked the registry key every startup, so the fix for me was:

- Fix gpedit by:
    - Navigating to c:\Windows\System32\GroupPolicy
    - Renaming Machine to Machine.old
    - Restarting
- Then apply the above registry entries.
- Restart
- Now you should be able to enable Eartrumpet (and others such as Monitarian) and it should stay enabled.

**Comment by jakoinc134** [comment]
same issue was happening to me, the bug still lives but the script for regedit fixed it.

**Comment by riverar** [comment]
Will close this as there's nothing actionable for us here. (This is a Windows bug.) Feel free to keep the discussion going and re-open if there's something we can do.

**Comment by Mohamed5956** [comment]
i've that issue for windows 11 any ideas about how to fix it ?

**Comment by riverar** [comment]
@Mohamed5956 Follow the steps here https://github.com/File-New-Project/EarTrumpet/issues/417#issuecomment-566869108
