### ISSUE TITLE
App generally unresponsive from taskbar shortcut

### ISSUE THREAD

**Issue by RainbowElliot** [File-New-Project/EarTrumpet#945]
## Description
Pretty simple, I click the speaker icon and it only shows the mixer sometimes. It's very sticky and unresponsive to being turned on and off repeatedly. Windows native volume icon is very snappy though

## Steps to reproduce
1. Go to the little speaker icon, click it, click away from it, click it again OR click the little speaker repeatedly
2. The mixers will stop showing up, unless you leave it alone for 15-30 seconds and try again

## Meta
* EarTrumpet version: 2.1.9.0
* Windows 10 version: 19042

## Screenshots
If applicable, add screenshots to help explain your problem
![jGWl2tXeGR](https://user-images.githubusercontent.com/39570503/140005117-965369b7-19d4-45b1-95c2-b0cb89beab24.gif)
.

**Comment by Xaero252** [comment]
I can also replicate this. Easiest way to replicate:

Open Chrome. Click to call the flyout menu. Click the content pane of the chrome window. Try clicking the volume icon again.

Chrome is just an example, but seems very reliable to reproduce this problem. Spam-clicking seems to bring the flyout back up.

**Comment by riverar** [comment]
Great video, unfortunately it's proving difficult to reproduce. Does this behavior persist if you restart EarTrumpet? Does it persist if apps emitting audio are closed/stopped?

**Comment by The-MAZZTer** [comment]
Seeing this in 2.1.9.12. I'm using Windows 11 if it matters. Didn't see this in Windows 10 but I also upgraded to a new version of Ear Trumpet around the same time (I was using a really old version). It happens all the time, restarting doesn't help.

It feels like the dialog is slow to open sometimes. It might depend on applications running or perhaps some weird bug with tracking the dialog open state (so it thinks it should close it when I click the icon when it's already closed). This is just speculation.

If I repeatedly left click on the trumpet icon it's a lot easier to trigger for me. But it can also happen on the first click.

Interestingly if I right click on the icon followed by a left click the floating dialog shows up more consistently.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it. (There was some flyout responsiveness work done in 2.1.10+ so this may be fixed.)

**Comment by The-MAZZTer** [comment]
Haven't noticed any issues with this for a while so let's say it's fixed, I'll reopen if I run into it again.
