### ISSUE TITLE
Applications stay on system default after swapping them to new audio channel

### ISSUE THREAD

**Issue by S3RRATED** [File-New-Project/EarTrumpet#952]
## Description
Please note Im also using a GOXlr Mini 
This happens with multiple games ( The ones Ive tried are DST - Dont Starve Together and Terraria ) 
when first loading the game it binds itself to your default ( System ) then when you change the application to be streamed through another channel ( Game ) it likes to stay in the system stream and not move even though it says its currently in 'game'

Idk if Im just being dumb or what. In the first screenshot you can see that DST is making sound through System and in the second screenshot you can see that its meant to be in game but its actually in both Game and System but the Game one isn't making any sound?

## Meta
* EarTrumpet version: 2.1.9.0
* Win10Pro Build 19041.vb_release.191206-1406

## Screenshots
![test1](https://user-images.githubusercontent.com/94322547/141981935-4e9d3ea2-f9e6-4900-8dde-b1afb8381050.png)
![test2](https://user-images.githubusercontent.com/94322547/141981939-fb795e32-8ea3-43cf-89ff-64533f68ec7a.png)

**Comment by riverar** [comment]
Unfortunately, this is almost always a third-party or Windows bug. To test that, close EarTrumpet completely and try setting the defaults via Windows directly.  (Start > search for "sound mixer options" > change the default output/input devices for your apps. Does anything happen?

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. I'm going to tie this to master issue #1307, thanks!
