### ISSUE TITLE
panel doesn't show itself properly when I back from sleep

### ISSUE THREAD

**Issue by Jensenese1** [File-New-Project/EarTrumpet#958]
## Description
A clear and concise description of what the bug is panel doesn't show itself when I back from sleep.

## Steps to reproduce
1.go system sleep
2. See error

## Meta
* EarTrumpet version: 1.2.3.4
* Windows 10 version: 19042.746

**Comment by riverar** [comment]
Isn't clear what's happening here due to the lack of details. Feel free to file another issue with more detail. Thanks!
