### ISSUE TITLE
Option to control volume per app with shortcuts or something

### ISSUE THREAD

**Issue by Navroza** [File-New-Project/EarTrumpet#96]
It would be great to add hotkeys for example I'd bind volume up/down and mute button of chrome on keyboard keys which I wont use so I could control music volume while gaming and I dont have to minimize and its time saver.

**Comment by clndwhr** [comment]
Has there been any movement with hotkeys for this?

**Comment by GoldenTao** [comment]
We're looking at a hotkey to have EarTrumpet appear for a future version, but we haven't really discussed specific app hotkeys, that could become quite problematic, but we'll look into it.

**Comment by tjcornish** [comment]
Thanks for a great and useful app.  I wanted to +1 this idea.  We are currently using PowerMixer which supports per-app keyboard shortcuts especially for muting/unmuting an app.  PowerMixer is not currently being developed and is problematic under Windows 10, so we're looking for a replacement.  Our use case is using shortcut keys to mute/unmute a TV stream when the user's phone rings or when someone walks into their office for a conversation.

Thanks

**Comment by yfmacit** [comment]
Please we need shortcut keys. Sometimes alt+tab can be a problem. Thanks to developers for this app.

**Comment by riverar** [comment]
We have a hotkey for opening the fly-out in EarTrumpet 2.0 (https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp) but sounds like you want a few more. Will keep this open, bear with us.

**Comment by ProH8R** [comment]
I would like to +1 this too. It would be especially useful when gaming.

For example when playing games, being able to quickly mute Chrome, Spotify, Music App etc without having to Alt Tab via F1-F12 or any other hotkey combination would be amazing. 

The Fly-Out menu is really great for games that support Full-Screen Windowed mode, but for games like Counter Strike Global Offensive, it causes a lengthy Alt-Tab.

Would love this to be added to the to-do list 👍

**Comment by Lordinio** [comment]
would love to be able to toggle between the audio devices or sources to change the volume with keyboard volume controls. If you could just choose between audio devices you wouldn't need to create new shortcuts for new programs

**Comment by infini667** [comment]
please guys, I beg you, make this possible! I'm suffering with this for a long time!! I want to control the spotify volume in game. these idiots could add this simple feature to spotify, but no... having to minimize the game everytime to control the volume is a pain. specially when I'm streaming. your software is great, just need this. thank you very much!
