### ISSUE TITLE
"System Sounds" trackbar change does not play a system sound

### ISSUE THREAD

**Issue by hl2guide** [File-New-Project/EarTrumpet#961]
## Description
"System Sounds" trackbar change does not play a system sound.

## Steps to reproduce
1. open main pane
2. slide the "System Sounds" trackbar

## Meta
* EarTrumpet version: 2.1.9.0
* Windows 10 version: 19044.1348

## Screenshots
N/A

**Comment by riverar** [comment]
Thanks for the idea @hl2guide. We don't have any plans to support this; we do beep, however, on master volume change.
