### ISSUE TITLE
Install EarTrumpet without Windows Store

### ISSUE THREAD

**Issue by creativrss** [File-New-Project/EarTrumpet#967]
How to install EarTrumpet on Windows 11 without Windows store in the easiest way, by which I also get the latest updates.

**Comment by riverar** [comment]
We have Chocolatey packages (as the README points out). You can also use AppInstaller (https://install.eartrumpet.app/master/EarTrumpet.Package.appinstaller). Or use our dev builds (see https://eartrumpet.app). Hope that helps!

**Comment by mitr0n4ik** [comment]
спасибо, работает
