### ISSUE TITLE
Volume control freezes, app crashes with a memory access error, can't relaunch.

### ISSUE THREAD

**Issue by niktr** [File-New-Project/EarTrumpet#969]
EventViewer Log:
```
Faulting application name: EarTrumpet.exe, version: 2.1.8.0, time stamp: 0x602cd00d
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0xcbf6f7d1
Exception code: 0xe0434352
Fault offset: 0x0012a6f2
Faulting process id: 0x26b4
Faulting application start time: 0x01d7d960f33ad6db
Faulting application path: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.8.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 2cec6bc7-2e78-485f-be40-93d66c52c3fb
Faulting package full name: 40459File-New-Project.EarTrumpet_2.1.8.0_x86__1sdd7yawvg6ne
Faulting package-relative application ID: EarTrumpet
```
when i try to start it manually from EarTrumpet.exe it gives me "access denied". I will run some Windows diagnostics to make sure this isn't another Microsoft spaghetti code issue.
Will update this post if i have new info.

**Comment by riverar** [comment]
Your EarTrumpet is outdated (2.1.8.0), can you try updating?

**Comment by niktr** [comment]
my windows store was borked so it wouldn't update. I downloaded the dev build.

**Comment by riverar** [comment]
And how did it go?

**Comment by niktr** [comment]
no crashes so far, but i'm having huge lag spikes while sliding the volume bar left and right on individual programs.
CPU usage goes up to 40% and doesn't drop until the slider stops moving.
![image](https://user-images.githubusercontent.com/19730922/146421019-c67ac45e-1c52-4f74-8d7a-88b9ef3f1dd7.png)

**Comment by riverar** [comment]
All apps or just one?

**Comment by niktr** [comment]
just the ones currently playing multimedia. Youtube videos, mp4, webp, etc. Maybe an update tick issue? 
(as in it could be solved by intentionally adding tick delay between volume updates instead of it being realtime)

then again... if this is an isolated issue, it could just be my crappy PC.

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.

**Comment by niktr** [comment]
I think it's fixed. Can't reproduce.

**Comment by riverar** [comment]
@niktr Thanks for following up! Please feel free to reach out if it does creep up again
