### ISSUE TITLE
软件在win11下。出现声音控制的面板叠加在一块，导致智能控制电脑的主声道，其他的程序的都被盖住了

### ISSUE THREAD

**Issue by 15156517753** [File-New-Project/EarTrumpet#970]
## Description
A clear and concise description of what the bug is

## Meta
* EarTrumpet version: 1.2.3.4
* Windows 10 version: 19042.746

## Screenshots
![重启后](https://user-images.githubusercontent.com/63525702/145373897-0a1ed6ec-ea7b-4a99-8c2e-191f17210bcf.png)
![窗口都叠在一块](https://user-images.githubusercontent.com/63525702/145373907-2104ac8b-6467-44d3-9ab7-c83b8f87a8c7.png)

**Comment by Geeyun-JY3** [comment]
我建议你重新组织一下语言，然后用英文按模板填写相关信息。

**Comment by riverar** [comment]
Please complete the issue form properly. Thanks!
请正确填写问题表格。谢谢！
