### ISSUE TITLE
Excessive resource consumption

### ISSUE THREAD

**Issue by wp231** [File-New-Project/EarTrumpet#981]
## Description
I opened Work Manager and found that the CPU resource usage reached 15%

## Meta
* EarTrumpet version: 2.1.9.0
* Windows 11 version: 21H2

## Screenshots
![2021-12-25_21-19-48](https://user-images.githubusercontent.com/56443833/147385814-8ae89d22-a122-4a1e-839e-63f04289a8de.png)

**Comment by riverar** [comment]
Dupe of #956, #515, and #402.

![image](https://user-images.githubusercontent.com/475132/147867491-4ebd8841-380a-49a5-902c-bf03794a6a0d.png)


Please right-click EarTrumpet.exe and _Create dump file_, then send that to team@eartrumpet.app. Thanks!

**Comment by riverar** [comment]
Hi there. I'm cleaning up the issues list. This issue is a bit stale. Please try reproducing this issue with current version of EarTrumpet and ping me if you can still reproduce it.
