### ISSUE TITLE
Firefox (Microsoft Store) icon

### ISSUE THREAD

**Issue by xmha97** [File-New-Project/EarTrumpet#986]
# Issue
I installed Firefox from Microsoft Store.
https://www.microsoft.com/store/productId/9NZVDKPMR9RD
![ EarTrumpet](https://user-images.githubusercontent.com/23485114/147680826-393dfc3e-9d41-41cd-835e-c6636cf644e4.png)
As you see in the image above, the Firefox (Microsoft Store) icon is not displayed correctly. ![Firefox Icon](https://user-images.githubusercontent.com/23485114/147681514-736f1800-a16e-4573-81c5-0656e496df92.png)
But the icon of Firefox (non-Microsoft Store) is displayed correctly. ![Firefox Icon](https://user-images.githubusercontent.com/23485114/147682040-934b5e07-114f-4e64-a269-f8649eef048b.png)
# Troubleshooting Data
See [tmpA978.tmp.txt](https://github.com/File-New-Project/EarTrumpet/files/7789733/tmpA978.tmp.txt)

**Comment by riverar** [comment]
Thanks, can reproduce.

**Comment by xmha97** [comment]
> can reproduce.

Sorry, I did not understand what you mean.

**Comment by riverar** [comment]
@xmha97 I was able to see the issue once, but cannot anymore. Are you still seeing this issue? What version of Firefox?

**Comment by riverar** [comment]
OK I have a stable repro. I'll investigate and fix this.
![image](https://user-images.githubusercontent.com/475132/148166013-f416c058-e751-4729-87d2-5ad8703a4ec8.png)

**Comment by xmha97** [comment]
> @xmha97 I was able to see the issue once, but cannot anymore. Are you still seeing this issue? What version of Firefox?

Yes, please install the Firefox from the following link:
https://www.microsoft.com/store/productId/9NZVDKPMR9RD

**Comment by xmha97** [comment]
> OK I have a stable repro. I'll investigate and fix this.
> ![image](https://user-images.githubusercontent.com/475132/148166013-f416c058-e751-4729-87d2-5ad8703a4ec8.png)
> 

Thanks.

**Comment by riverar** [comment]
This should be fixed in EarTrumpet 2.1.10 now available in the Microsoft Store, chocolatey, and other sources!
