### ISSUE TITLE
Add option to change default microphone device

### ISSUE THREAD

**Issue by sergeybruh** [File-New-Project/EarTrumpet#99]
Guys could you please add function of changing default microphone ?
Only one reason don't give me turn-off sound icon, I can't gent quick access to 
sound configuration form you app, to change microphone I would love you to add
there button to go to sonud devices setup or if is possible just add function of adding default device 
![image](https://cloud.githubusercontent.com/assets/13604069/21404475/0cc50810-c7ca-11e6-99b7-c9255b64e953.png)

![image](https://cloud.githubusercontent.com/assets/13604069/21404464/feff5e6a-c7c9-11e6-802c-d81475c12162.png)

Kind regards,
Sergey.

**Comment by Droyk** [comment]
+1 and plz add keyboard shortcut for them so that user can easily switch b/w them.

**Comment by riverar** [comment]
Changing the default mic device is interesting, will investigate that! Thanks.

**Comment by Kramins** [comment]
I would also request for Voice Gating support similar to VoiceMeeter.

**Comment by ghostlyghastly** [comment]
It would be nice to have microphone with volume slider in there
my problem is that my microphone's volume setting gets changed - no idea by which software - and getting to the ui where i can check/reset this requires a lot of clicks and brain-processing of cluttered ui (window's sound settings)
