### ISSUE TITLE
Not working after change sound source (speakers/headphones) 

### ISSUE THREAD

**Issue by PertR** [File-New-Project/EarTrumpet#995]
Hi

little feedback

i have Sound Blaster Z
win 10 homo 21H1

 When i change sound source from spekears to headphones, Eartrumpet stops working and does not showing applications which are currently playing. Restarting Eartrumpet problem solves.

**Comment by riverar** [comment]
Thanks for reporting this. We are currently tracking SoundBlaster related issues with #574.
